-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Top] [Rarity.Rare] (146 items)
    { item="Base.Bandeau_Burlap", basePrice=39, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Denim", basePrice=39, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_FaunHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Garbage", basePrice=46, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Hide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Rag", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Tarp", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_Black", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_Blue", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_White", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ghillie_Top", basePrice=69, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_Hide_DOWN", basePrice=62, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_DOWN", basePrice=50, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.HoodieDOWN_WhiteTINT", basePrice=50, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_Black", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_BlueUni", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_Red", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_White", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_DiamondPatternTINT", basePrice=176, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=8} },
    { item="Base.Jumper_PoloNeck", basePrice=53, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_RoundNeck", basePrice=49, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_TankTopDiamondTINT", basePrice=168, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Jumper_TankTopTINT", basePrice=47, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_VNeck", basePrice=47, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_KY", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_Rangers", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_Z", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Blue", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Brown", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Green", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_LimeGreen", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Pink", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_White", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoDesert", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoDesertNew", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoGreen", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoMilius", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoTigerStripe", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoUrban", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Burlap", basePrice=42, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Cotton", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Denim", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimBlack", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimLight", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimRandom", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CropTopNoArmTINT", basePrice=35, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CropTopTINT", basePrice=35, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Denim", basePrice=58, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalTINT", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite_ShortSleeve", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite_ShortSleeveTINT", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_HawaiianRed", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_HawaiianTINT", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey01", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey02", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey03", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey04", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey05", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey06", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack", basePrice=52, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack_Green", basePrice=52, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack_TINT", basePrice=52, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Burlap", basePrice=39, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Cotton", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Denim", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimBlack", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimLight", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_OfficerWhite", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_OliveDrab", basePrice=40, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_PoliceBlue", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_PoliceGrey", basePrice=94, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_Priest", basePrice=39, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_PrisonGuard", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Ranger", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Scrubs", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Sheriff", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_Workman", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ArmyGreen", basePrice=111, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_BluesCountry", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_BusinessSpiffo", basePrice=39, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoDesert", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoDesertNew", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoGreen", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoMilius", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoTigerStripe", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoUrban", basePrice=42, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultDECAL", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultDECAL_TINT", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultTEXTURE", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultTEXTURE_TINT", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_EMD", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Fossoil", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Gas2Go", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_HipHop", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_HuntingCamo", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Indie", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_IndieStoneDECAL", basePrice=42, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_LongSleeve_HuntingCamo", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_LongSleeve_SuperColor", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_McCoys", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Metal", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_OliveDrab", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PileOCrepe", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PizzaWhirled", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PoliceBlue", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_PoliceGrey", basePrice=94, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_PoloStripedTINT", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PoloTINT", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanBlue", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanRed", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanRed02", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanWhite", basePrice=45, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_PoliceBlue", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_Profession_PoliceWhite", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_Profession_RangerBrown", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_RangerGreen", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_VeterenGreen", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_VeterenRed", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Punk", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Ranger", basePrice=43, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Rock", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Rock2", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Scrubs", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Sheriff", basePrice=93, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_SpiffoDECAL", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Sport", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_SportDECAL", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_SuperColor", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ThunderGas", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_TieDye", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Tuxedo", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ValleyStation", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteLongSleeve", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteLongSleeveTINT", basePrice=41, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteTINT", basePrice=38, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_AngusHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DeerHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DefaultTEXTURE", basePrice=44, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DefaultTEXTURE_TINT", basePrice=44, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_FawnHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Garbage", basePrice=46, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_HolsteinHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_SimmentalHide", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Tarp", basePrice=48, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
})

print("[DynamicTrading] Top Registry Complete")
