require "DT/Common/Config"

DynamicTrading.RegisterDialogue("Player", "Tracking", {
    EN = {
        Request = {
            "This is {player}. {npc}, send me your current coordinates.",
            "{npc}, I have your signal. Give me a location fix.",
            "{npc}, this is {player.firstname}. Need your exact position, over.",
            "I'm locking onto your channel, {npc}. Call out where you are.",
            "{npc}, radio check. Send your grid and surroundings.",
            "Come in, {npc}. I need a bearing on your position.",
            "{npc}, I'm tracking your frequency. What's your twenty?",
            "Picking up your signal, {npc}. Can you confirm your location?",
            "This is {player.firstname} reaching out. {npc}, where are you set up?",
            "{npc}, I'm coming to find you. Send coordinates when you can.",
            "Got your frequency locked in, {npc}. Drop me a position marker.",
            "{npc}, do you read me? I need your current grid reference.",
            "I need to pin you down, {npc}. What's your location?",
            "{npc}, this is {player.firstname}. Squawk your position, over.",
            "Trying to find you out there, {npc}. Light up the channel with a fix.",
            "{npc}, signal is holding. Give me something to walk toward.",
            "Looking for you, {npc}. Send me your grid so I can start moving.",
            "I've got your channel open, {npc}. Where should I be heading?",
            "{npc}, {player.firstname} here. Paint me a picture of where you're at.",
            "Keying up on your frequency, {npc}. Ready to copy your position.",
        },
        Approach3000 = {
            "Three klicks out, {npc}. That's going to be a long walk. I'm on my way.",
            "{npc}, I'm well over two klicks away still. Don't hold your breath.",
            "Copy your position, {npc}. I've got about three thousand meters between us.",
            "That's a hike, {npc}. Three klicks. I'll start heading your direction now.",
            "{npc}, this is going to take a while. Three thousand meters on the tracker.",
            "I can see the heading on the signal, {npc}. Three klicks though. Long road.",
            "Three thousand meters, {npc}. I'll keep the channel open while I walk.",
            "{npc}, the signal's barely registering at this distance. But I have a vector.",
            "Starting the approach from three klicks out, {npc}. Keep the signal alive.",
            "You're practically on the other side of the map, {npc}. Three thousand meters.",
            "{npc}, I'm three klicks away. I'll check in when I'm closer.",
            "Three thousand meters of who-knows-what between us, {npc}. Heading out now.",
            "Long trip ahead, {npc}. Three klicks. I'll try to make it in one piece.",
            "{npc}, reading your signal from three thousand out. Locking in the bearing.",
            "That's serious distance, {npc}. Three klicks. I'm starting the march.",
            "Three thousand meters, {npc}. I hope there's a clear path between here and there.",
            "{npc}, I just plotted the heading. Three klicks. Wish me luck.",
            "Setting out toward your signal now, {npc}. Three thousand meters to cover.",
            "Well, {npc}, three thousand meters isn't going to walk itself. Here I go.",
            "Copy, {npc}. Three klicks between us. Beginning approach, will update en route.",
        },
        Approach2000 = {
            "Two klicks now, {npc}. I've made some progress at least.",
            "{npc}, I'm at about two thousand meters out. Halfway through the worst of it.",
            "Two klicks, {npc}. The signal's sounding better from here.",
            "I've covered a good chunk, {npc}. Two thousand meters left.",
            "{npc}, two klicks on the tracker. Heading is still true.",
            "Getting there, {npc}. Two thousand meters. Feels like I've been walking for hours.",
            "Two klicks, {npc}. Not close, but closer than I was.",
            "{npc}, the distance is shrinking. Two thousand meters and moving.",
            "Two thousand meters, {npc}. I can feel the signal pulling me in.",
            "Moving steady, {npc}. Two klicks left. The ground's been manageable so far.",
            "{npc}, two klicks out. I haven't run into anything too nasty yet.",
            "Two thousand meters, {npc}. I'll pick up the pace where I can.",
            "The trek's about half done by my count, {npc}. Two klicks.",
            "{npc}, signal's getting clearer at two thousand. I'm on the right track.",
            "Two klicks away, {npc}. Starting to feel like this might actually work.",
            "Two thousand meters and the road's been mostly clear, {npc}.",
            "{npc}, I'm inside two klicks now. The second half should be easier.",
            "Two thousand meters to go, {npc}. I'll radio again when I'm closer.",
            "Still marching, {npc}. Two klicks. Your signal's my compass.",
            "Two klicks out, {npc}. My legs are questioning my life choices, but I'm coming.",
        },
        Approach1500 = {
            "Fifteen hundred meters, {npc}. We're getting somewhere now.",
            "{npc}, I'm at a klick and a half. Signal is solid from here.",
            "One and a half klicks, {npc}. The worst part of the hike is behind me.",
            "Fifteen hundred meters, {npc}. I'm past the midpoint for sure.",
            "{npc}, a klick and a half out. I should start seeing your area soon.",
            "Getting into your territory, {npc}. Fifteen hundred meters by the tracker.",
            "Fifteen hundred, {npc}. I can tell the landscape is changing. Getting closer.",
            "{npc}, one and a half klicks. The signal's been guiding me true so far.",
            "Klick and a half, {npc}. Starting to feel less like a voyage and more like a visit.",
            "Fifteen hundred meters, {npc}. Confident I'm on the right path now.",
            "{npc}, I'm tightening the distance. Fifteen hundred left.",
            "One five hundred meters, {npc}. Moving well and keeping alert.",
            "A klick and a half, {npc}. I'll keep my eyes open as the area changes.",
            "{npc}, fifteen hundred meters to go. Not bad considering where I started.",
            "Klick and a half out, {npc}. The receiver's humming nicely at this range.",
            "Fifteen hundred meters, {npc}. Are there any landmarks I should watch for?",
            "{npc}, still pushing forward. Fifteen hundred meters on the approach.",
            "Getting closer by the minute, {npc}. Fifteen hundred and shrinking.",
            "One point five klicks, {npc}. The end is starting to feel achievable.",
            "Fifteen hundred meters, {npc}. Keep the light on, I'm almost in your orbit.",
        },
        Approach1000 = {
            "One klick, {npc}. Single digits. The finish line's in sight, kind of.",
            "{npc}, a thousand meters out. I'm inside your kilometer.",
            "One klick even, {npc}. Does the area start looking familiar?",
            "Thousand meters, {npc}. I'm close enough to start worrying about being seen.",
            "{npc}, I'm at one klick. Signal's strong and steady.",
            "Under a klick now, {npc}. I'm in the home stretch.",
            "One thousand meters, {npc}. I can tell the terrain matches what you described.",
            "{npc}, a klick out. Almost time to start looking instead of just walking.",
            "One klick, {npc}. If anything goes loud, you might hear it from here.",
            "Thousand meters, {npc}. The signal is painting a clear line right to you.",
            "{npc}, I'm inside a thousand. It's getting real now.",
            "One klick even, {npc}. I'll start slowing down and paying more attention.",
            "A thousand meters and closing, {npc}. Are you still in the same spot?",
            "{npc}, one klick. I can practically smell civilization. Or what's left of it.",
            "Thousand meters out, {npc}. Going to start approaching more cautiously.",
            "One klick, {npc}. Close enough that I'm switching from navigator to hunter.",
            "{npc}, I've got a thousand meters of ground left. Closing in.",
            "Under one klick, {npc}. The signal says I'm coming in straight.",
            "A thousand meters, {npc}. I'm going to tighten up the approach from here.",
            "One klick, {npc}. See you soon. Keep the channel open.",
        },
        Approach750 = {
            "Seven fifty, {npc}. Three quarters of a klick and tightening.",
            "{npc}, seven hundred fifty meters. I'm well inside your area now.",
            "Three quarters of a klick, {npc}. The signal's pulling strong.",
            "Seven fifty meters, {npc}. Getting into the final approach phase.",
            "{npc}, I'm at seven fifty. Starting to look around more carefully.",
            "Seven hundred fifty meters, {npc}. I might start seeing signs of your camp soon.",
            "Three quarters out, {npc}. The tracker is really locked in now.",
            "{npc}, seven fifty meters. What should I be looking for at this range?",
            "Seven fifty, {npc}. Close enough that I'm watching every shadow.",
            "Seven hundred fifty meters and the signal is crystal, {npc}.",
            "{npc}, three quarters of a klick. I'm switching to careful mode.",
            "Seven fifty meters, {npc}. The terrain looks like it could be yours.",
            "Under a klick by a good margin now, {npc}. Seven fifty.",
            "{npc}, I'm getting close. Seven fifty meters. Any hazards I should know about?",
            "Seven hundred fifty meters, {npc}. I'll start scanning for your position.",
            "Three quarters of a klick, {npc}. Almost at the point where I use eyes over signal.",
            "Seven fifty, {npc}. If you can see movement out your way, that might be me.",
            "{npc}, seven fifty meters. I'm tightening the search radius.",
            "Seven hundred fifty and counting down, {npc}. We're in the endgame.",
            "Three quarters out, {npc}. Let me know if you spot me before I spot you.",
        },
        Approach500 = {
            "Half a klick, {npc}. We're getting into tight territory now.",
            "{npc}, five hundred meters. I should start seeing your area.",
            "Five hundred meters, {npc}. The signal is strong enough I could follow it blindfolded.",
            "Half a klick out, {npc}. This is close. Real close.",
            "{npc}, I'm at five hundred. What does your setup look like from outside?",
            "Five hundred meters, {npc}. My eyes are doing more work than the radio now.",
            "Half a klick, {npc}. I'm slowing down and being careful.",
            "{npc}, five hundred meters out. Should I approach from any particular direction?",
            "Five hundred and closing, {npc}. The tracker says I'm dead on.",
            "Half a kilometer, {npc}. I think I can see the kind of area you described.",
            "{npc}, five hundred meters. Switching to visual scanning.",
            "Five hundred, {npc}. The gap between us is almost small enough to shout across.",
            "Half a klick, {npc}. If you're watching, you might see me moving in.",
            "{npc}, I'm inside five hundred meters. Getting into the final zone.",
            "Five hundred meters, {npc}. Everything from here is careful footwork.",
            "Half a klick, {npc}. The hard traveling is done. Now it's just finding you.",
            "{npc}, five hundred out. I'll radio once more before I go visual-only.",
            "Five hundred meters and I can feel it, {npc}. We're close.",
            "Half a klick, {npc}. My gut says we'll be face to face soon.",
            "Five hundred meters, {npc}. Last stretch before the real search begins.",
        },
        Approach300 = {
            "Three hundred meters, {npc}. I'm in your neighborhood for real now.",
            "{npc}, three hundred out. The signal is locked and the area looks right.",
            "Three hundred, {npc}. I'm scanning every building and corner.",
            "Three hundred meters, {npc}. If you look outside, you might see me approaching.",
            "{npc}, I'm at three hundred. What side of the area are you on?",
            "Three hundred meters and the tracker's humming, {npc}. I'm right here.",
            "Under three hundred now, {npc}. I can feel how close we are.",
            "{npc}, three hundred meters. I'm threading through your area carefully.",
            "Three hundred, {npc}. If I'm being quiet, it's because I don't want guests.",
            "Three hundred meters out, {npc}. Everything matches your description.",
            "{npc}, we're inside three hundred. Almost time to ditch the radio.",
            "Three hundred meters, {npc}. I'm practically on top of your signal.",
            "Three hundred and shrinking, {npc}. Keep talking, it helps me zero in.",
            "{npc}, three hundred out. Are there any dead I should be worried about?",
            "Three hundred meters, {npc}. I'm close enough to start feeling exposed.",
            "Inside three hundred now, {npc}. The precision of the tracker matters here.",
            "{npc}, three hundred meters. I can smell the difference. You're close.",
            "Three hundred, {npc}. This is the part where the searching gets serious.",
            "Three hundred meters, {npc}. I'm going to tighten up and come in careful.",
            "Under three hundred and closing, {npc}. Almost done with this trek.",
        },
        Approach200 = {
            "I think I've got your general area, {npc}. Two hundred meters out, maybe.",
            "Starting to pick up a stronger signal. I'm still far out, {npc}.",
            "I'm on the move toward you, {npc}. Probably about two hundred meters still.",
            "{npc}, I've got a rough bearing. Heading your way but I've got ground to cover.",
            "Two hundred meters or so, {npc}. The signal's faint but it's there.",
            "Long walk ahead still, {npc}, but I'm pointed in the right direction.",
            "Getting something on the tracker, {npc}. I think I'm about two hundred out.",
            "{npc}, I'm closing in but it'll be a minute. Two hundred meters by my count.",
            "Heading your way, {npc}. The frequency is starting to level out.",
            "I can feel the signal pulling me in the right direction. Still distant, {npc}.",
            "Moving to your position, {npc}. Couple hundred meters to go, looks like.",
            "The tracker says I'm getting warmer, {npc}. Two hundred meters, roughly.",
            "I've got a long stretch of ground between us still, {npc}. Pushing through.",
            "{npc}, I've broken into your range. Faint, but I can read you better now.",
            "Two hundred meters. Doesn't feel close, but at least I know where I'm going, {npc}.",
            "Signal firmed up a notch. I'm on approach, {npc}. Far side still though.",
            "I'm out here somewhere in your periphery, {npc}. Working my way closer.",
            "The needle swung your way, {npc}. Two hundred meters, give or take.",
            "{npc}, I just hit what I think is your outer range. Heading straight in.",
            "Starting the long walk in, {npc}. Hold tight.",
        },
        Approach150 = {
            "Closing the gap, {npc}. A hundred fifty meters, maybe less.",
            "Signal's cleaning up nicely, {npc}. I'm getting there.",
            "Hundred and fifty meters by my reckoning, {npc}. Shouldn't be too long now.",
            "{npc}, the tracker's smoothing out. I'm well within your area now.",
            "I can tell I'm getting closer, {npc}. The signal doesn't lie.",
            "Hundred fifty meters, {npc}. I'm past the halfway point for sure.",
            "{npc}, things are looking familiar to what you described. Making progress.",
            "The frequency's getting tighter, {npc}. I'm narrowing it down.",
            "Still walking but the signal says I'm doing well, {npc}. Maybe a hundred fifty out.",
            "Getting into your neighborhood, {npc}. Or what passes for one out here.",
            "{npc}, I've covered a lot of ground. The tracker's pulling strong now.",
            "Hundred fifty meters. I should be seeing signs of your area soon, {npc}.",
            "Keep talking, {npc}. Your voice helps me gauge the distance.",
            "Coming in steady, {npc}. The signal's a lot cleaner at this range.",
            "I think I can see the kind of area you described. Getting closer, {npc}.",
            "{npc}, we're cooking. Hundred fifty meters and shrinking.",
            "Not far now by the tracker's read. Hundred fifty, maybe a bit less, {npc}.",
            "The gap's closing fast, {npc}. I've got a good pace going.",
            "Hundred fifty meters out. I'll start scanning for visual soon, {npc}.",
            "Almost there in spirit, {npc}. The body's catching up.",
        },
        Approach100 = {
            "I'm getting closer, {npc}. Should be within a hundred meters now.",
            "Your signal is tightening up. I'm around a hundred meters out, {npc}.",
            "I'm nearly on your block, {npc}. Call anything out if you need to.",
            "Hundred meters, {npc}. This feels close. I should see you soon.",
            "I can feel the signal locking in, {npc}. Hundred meters.",
            "Almost in visual range, {npc}. Hundred meters by my count.",
            "{npc}, I think I can make out the area you're in. Hundred meters.",
            "Getting tight now, {npc}. A hundred meters feels like nothing.",
            "Right in the zone, {npc}. I'm scanning as I walk. Hundred meters.",
            "Hundred meters, {npc}. I'll start looking for you specifically now.",
            "{npc}, the home stretch. I'm about a hundred meters from your position.",
            "Close enough to start getting excited, {npc}. Or nervous. Maybe both.",
            "I can almost taste the rendezvous point, {npc}. Hundred meters.",
            "The tracker is strong and steady. Hundred meters, {npc}. Eyes peeled.",
            "{npc}, I'm in your orbit now. Hundred meters and closing.",
            "Not much left between us, {npc}. Maybe a hundred meters of pavement.",
            "A block away, maybe less, {npc}. I'm keeping my eyes wide open.",
            "The signal's humming, {npc}. I'm right there. Hundred meters out.",
            "Hundred meters, {npc}. If you hear footsteps, that's me. Hopefully.",
            "I'm close, {npc}. Real close. Let me know if you spot me first.",
        },
        Approach75 = {
            "Seventy-five meters, {npc}. I should be seeing you any moment.",
            "Real close now, {npc}. Seventy-five meters. I'm scanning everything.",
            "{npc}, I'm tightening the search. Seventy-five meters out.",
            "The signal is almost buzzing at this range, {npc}. Seventy-five meters.",
            "Getting into the final approach, {npc}. Seventy-five meters.",
            "If I squint, I might already see you. Seventy-five meters, {npc}.",
            "Seventy-five meters, {npc}. What should I be looking for exactly?",
            "I'm right in your pocket, {npc}. Seventy-five meters or so.",
            "{npc}, I can practically hear you without the radio. Almost there.",
            "Closing in, {npc}. Seventy-five meters. Things are getting real.",
            "The tracker is practically screaming at me. Seventy-five meters, {npc}.",
            "{npc}, seventy-five meters. I'm looking for anything that looks alive.",
            "I'm so close I almost don't need the radio anymore, {npc}.",
            "Seventy-five meters and counting down, {npc}. Stay put.",
            "Nearly there, {npc}. Can you do anything to make yourself visible?",
            "I'm sweeping the area, {npc}. Seventy-five meters. Should be any second.",
            "Tight range now, {npc}. I'm watching every corner.",
            "{npc}, I'm in the thick of it. Seventy-five meters by the signal.",
            "Give me a sign, {npc}. I'm at seventy-five meters and counting.",
            "The last stretch, {npc}. Seventy-five meters. Keep the channel hot.",
        },
        Approach50 = {
            "I'm within fifty meters now, {npc}. Keep talking.",
            "Fifty meters or less. I should be close enough to spot you soon, {npc}.",
            "I'm right on top of the signal now, {npc}. Give me a visual cue.",
            "Fifty meters, {npc}. I'm scanning everything that moves.",
            "Close enough to hear a cough, {npc}. Fifty meters.",
            "{npc}, fifty meters. Are you somewhere I can see from ground level?",
            "I'm practically on you, {npc}. Fifty meters. Look for me too.",
            "Fifty meters and the signal is maxed out. You're right here, {npc}.",
            "We should be looking at each other any moment, {npc}. Fifty meters.",
            "{npc}, I'm threading through your area now. Fifty meters on the tracker.",
            "Fifty meters. If you wave, I'll see it, {npc}.",
            "The frequency is rock solid. Fifty meters, {npc}. We're almost done.",
            "I'm looking for anything out of the ordinary, {npc}. Fifty meters.",
            "Half a block at most, {npc}. I should see you any second.",
            "{npc}, the search is almost over. Fifty meters by my read.",
            "Can practically feel your presence, {npc}. Fifty meters out.",
            "Fifty meters, {npc}. This is it. Point me in if you can see me.",
            "I'm right here in the thick of it, {npc}. Fifty meters.",
            "{npc}, we're close enough to shout. But let's not attract attention.",
            "The tracker says fifty. My gut says closer. Looking for you now, {npc}.",
        },
        Approach25 = {
            "Twenty-five meters, {npc}. I can almost see you. I think.",
            "{npc}, twenty-five meters. If you're looking out, you might spot me.",
            "I'm right on your doorstep, {npc}. Twenty-five meters.",
            "We're practically in the same room, {npc}. Twenty-five meters.",
            "Twenty-five meters. One of us should see the other any second, {npc}.",
            "{npc}, stop me if you spot me. I'm at twenty-five meters.",
            "This is close enough to feel silly using a radio, {npc}. Twenty-five meters.",
            "I'm right here, {npc}. Twenty-five meters. Where should I look?",
            "Twenty-five meters, {npc}. I'm going to start looking in windows.",
            "{npc}, the signal is off the charts. You're right here with me.",
            "If I turn around, I might be staring at you, {npc}. Twenty-five meters.",
            "Twenty-five meters. I'm going to holster the radio and use my eyes, {npc}.",
            "Almost face to face, {npc}. Twenty-five meters on the dot.",
            "{npc}, I'm stepping carefully. Twenty-five meters. Almost there.",
            "I feel like I should be able to reach out and touch you, {npc}.",
            "The signal can't get any stronger, {npc}. Twenty-five meters.",
            "Twenty-five meters, {npc}. Last stretch. Let me know you see me.",
            "We're so close it's almost funny, {npc}. Where are you exactly?",
            "{npc}, twenty-five meters. I'm about to walk right into you.",
            "Just a few more steps, {npc}. This is it. Twenty-five meters.",
        },
        Approach10 = {
            "I'm within ten meters, {npc}. I think I can see you.",
            "Ten meters. Visual contact should be any second now, {npc}.",
            "I'm basically on you now, {npc}. Looking up from the radio.",
            "There you are, {npc}. I've got eyes on you.",
            "Ten meters, {npc}. I'm looking right at you.",
            "Found you, {npc}. Putting the radio down.",
            "Visual confirmed, {npc}. Ten meters. Coming right to you.",
            "That's you, yeah? Ten meters. I'm walking over now, {npc}.",
            "{npc}, I see you. We're done with the radio part. Ten meters.",
            "Got you, {npc}. Ten meters. No need to keep broadcasting.",
            "I can see your face from here, {npc}. Walking over now.",
            "Ten meters and closing, {npc}. This is it. We made it.",
            "Contact, {npc}. Visual. I'm right here.",
            "I'm waving at you right now, {npc}. Can you see me? Ten meters.",
            "{npc}, lowering the handset. I can see you plain as day.",
            "Ten meters. I think we can have this conversation in person now, {npc}.",
            "There's the person behind the signal. Ten meters, {npc}. Coming in.",
            "Eyes up, {npc}. That's me walking toward you. Ten meters out.",
            "{npc}, we did it. Visual contact. Closing the last ten meters now.",
            "Finally. I can see you, {npc}. Radio's done its job. Coming over.",
        },
        Away = {
            "Wait... I think I'm losing the signal. Am I going the wrong way?",
            "Static's getting heavy. Did I miss a turn?",
            "The ping's fading out. I must be heading away from the source.",
            "Hold on, the tracker's dropping. Wrong way.",
            "Dammit, the signal's getting weaker. I need to re-center.",
            "I think I'm losing you, {npc}. Heading might be off.",
            "The relay's getting spotty. I'm drifting too far.",
            "Wrong direction. The signal just tanked.",
            "If I keep this up, I'll lose the lock entirely. Backtrack.",
            "The noise is drowning you out, {npc}. I'm heading the wrong way.",
        }
    }
})