-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material.Metal] [Rarity.Common] (4 items)
    { item="Base.Badge", basePrice=42, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=35, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.DogTag_Pet", basePrice=42, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },
    { item="Base.DogTag_Pet_Blank", basePrice=42, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },

    -- [Resource.Material.Metal] [Rarity.Rare] (89 items)
    { item="Base.Aluminum", basePrice=90, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumFragments", basePrice=90, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumScrap", basePrice=20, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.BenchAnvil", basePrice=64, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BenchAnvilUntreated", basePrice=64, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvil", basePrice=59, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=59, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvil", basePrice=82, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvilUntreated", basePrice=82, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BrassIngot", basePrice=118, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Brass", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BrassScrap", basePrice=22, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Brass", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Bullhorn", basePrice=69, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.Calipers", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.CopperIngot", basePrice=123, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.CopperScrap", basePrice=24, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CopperSheet", basePrice=223, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBenchVise", basePrice=68, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBenchViseParts", basePrice=68, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBlade", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.DrawPlate", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.GoldBar", basePrice=369, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.GoldCoin", basePrice=353, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Coin", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.GoldScrap", basePrice=322, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.GoldSheet", basePrice=441, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.HeadingTool", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBand", basePrice=94, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Band", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBandSmall", basePrice=94, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Band", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBarMold", basePrice=65, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronBarQuarter", basePrice=104, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBlock", basePrice=107, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBloom", basePrice=79, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Bloom", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronChunk", basePrice=98, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronIngot", basePrice=109, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronIngotMold", basePrice=65, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronPiece", basePrice=86, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Piece", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.IronScrap", basePrice=21, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.JarLid", basePrice=87, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Katana_Blade", basePrice=89, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Katana_Blade_Broken", basePrice=27, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.KeyPadlock", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=28} },
    { item="Base.LargeMeteorite", basePrice=59, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Leash", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Lighter", basePrice=97, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LighterBBQ", basePrice=96, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.LighterDisposable", basePrice=96, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LongCrudeBlade", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.Loupe", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.MeatCleaverBlade", basePrice=90, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.Oxygen_Tank", basePrice=94, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrame", basePrice=69, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrameLarge", basePrice=69, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronBlock", basePrice=107, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronChunk", basePrice=98, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.PiercedIronIngot", basePrice=114, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.PiercedSteelBlock", basePrice=130, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.PiercedSteelChunk", basePrice=122, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.PiercedSteelIngot", basePrice=117, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Pocketwatch", basePrice=71, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.ScrapMetal", basePrice=28, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SheepShears", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheepShearsForged", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheetMetal", basePrice=217, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SilverBar", basePrice=137, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SilverCoin", basePrice=125, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Coin", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SilverScrap", basePrice=32, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=13} },
    { item="Base.SilverSheet", basePrice=180, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.SmallCopperSheet", basePrice=154, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SmallGoldBar", basePrice=375, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SmallSheetMetal", basePrice=148, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SmallSilverBar", basePrice=139, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SpadeHead_Forged", basePrice=75, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.SpearLongHead", basePrice=90, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.Stapler", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Staples", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelBarMold", basePrice=74, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelBarQuarter", basePrice=127, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelBlock", basePrice=130, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelChunk", basePrice=122, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelIngot", basePrice=117, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelIngotMold", basePrice=74, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelPiece", basePrice=94, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Piece", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelRodQuarter", basePrice=96, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Rod", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SteelScrap", basePrice=28, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SteelSlug", basePrice=96, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Slug", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Thimble", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Tsquare", basePrice=69, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.TuningFork", basePrice=70, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=55, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.WoodenIngotCastMold", basePrice=55, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=8} },
})

print("[DynamicTrading] Metal Registry Complete")
