-- ============================================================================
-- Literature Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Literature.Book] [Rarity.Common] (4 items)
    { item="Base.LetterHandwritten", basePrice=50, tags={"Literature.Book", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Note", basePrice=50, tags={"Literature.Book", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Photo", basePrice=50, tags={"Literature.Book", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Photo_VeryOld", basePrice=50, tags={"Literature.Book", "Rarity.Common"}, stockRange={min=5, max=25} },

    -- [Literature.Book] [Rarity.Rare] (189 items)
    { item="Base.Book", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_AdventureNonFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Art", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Baseball", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Bible", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Biography", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Business", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Childs", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Cinema", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Classic", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_ClassicFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_ClassicNonfiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Computer", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_CrimeFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Fantasy", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Farming", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Fashion", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Fiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_GeneralNonFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_GeneralReference", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Golf", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_History", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Horror", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Legal", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_LiteraryFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Medical", basePrice=8, tags={"Literature.Book", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Book_Military", basePrice=8, tags={"Literature.Book", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Book_MilitaryHistory", basePrice=8, tags={"Literature.Book", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Book_Music", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Nature", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Occult", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Philosophy", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Policing", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Politics", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Quackery", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Religion", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Rich", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Romance", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_SadNonFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_SchoolTextbook", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Science", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_SciFi", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Sports", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Thriller", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Travel", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Book_Western", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookAimingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookBlacksmithSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookButcheringSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookCarpentrySet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookCarvingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookCookingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookElectricianSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookFancy_Bible", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Classic", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_ClassicFiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_ClassicNonfiction", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_History", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Legal", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Medical", basePrice=8, tags={"Literature.Book", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_MilitaryHistory", basePrice=8, tags={"Literature.Book", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Occult", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Philosophy", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Politics", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Religion", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFarmingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookFirstAidSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookFishingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookFlintKnappingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookForagingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookGlassmakingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookHusbandrySet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookLongBladeSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookMaintenanceSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookMasonrySet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookMechanicsSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookMetalWeldingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookPotterySet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookReloadingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookTailoringSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookTrackingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BookTrappingSet", basePrice=2, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Brochure", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Catalog", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChildsPictureBook", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Diary1", basePrice=28, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Diary2", basePrice=28, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Doodle", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DoodleKids", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flier", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flier_Nolans", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GenericMail", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GraphPaper", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HollowBook", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowBook_Handgun", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowBook_Kids", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowBook_Prison", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowBook_Valuables", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowBook_Whiskey", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HollowFancyBook", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HottieZ", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HottieZ_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.IDcard", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IndexCard", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Journal", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MenuCard", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Newspaper", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_Dispatch_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_Herald_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_Knews_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_Recent", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Newspaper_Times_New", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Notebook", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Notepad", basePrice=42, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.OfficialDocument", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paperback", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_AdventureNonFiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Art", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Baseball", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Bible", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Biography", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Business", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Childs", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Cinema", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Classic", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_ClassicFiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_ClassicNonfiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Computer", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Conspiracy", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_CrimeFiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Diet", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Fantasy", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Fashion", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Fiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Golf", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Hass", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_History", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Horror", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Legal", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_LiteraryFiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Medical", basePrice=17, tags={"Literature.Book", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Military", basePrice=17, tags={"Literature.Book", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_MilitaryHistory", basePrice=17, tags={"Literature.Book", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Music", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Nature", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_NewAge", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Occult", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Philosophy", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Play", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Policing", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Politics", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Poor", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Quackery", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Quigley", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Relationship", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Religion", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Rich", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Romance", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_SadNonFiction", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Scary", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Science", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_SciFi", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_SelfHelp", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Sexy", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Sports", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Teens", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Thriller", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Travel", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_TrueCrime", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Western", basePrice=17, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Paperwork", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ParkingTicket", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Passport", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Phonebook", basePrice=4, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Photo_Hass", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Photo_Racy", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Photo_Secret", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PhotoBook", basePrice=8, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PressID", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Receipt", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RPGmanual", basePrice=11, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ScratchTicket", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ScratchTicket_Loser", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ScratchTicket_Winner", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SewingPattern", basePrice=28, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SheetPaper2", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SpeedingTicket", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.StockCertificate", basePrice=85, tags={"Literature.Book", "Rarity.Rare"}, stockRange={min=0, max=10} },
})

print("[DynamicTrading] Book Registry Complete")
