-- ============================================================================
-- Literature Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Literature.Book] [Rarity.Common] (4 items)
    { item="Base.LetterHandwritten", basePrice=1218, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Note", basePrice=1218, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Photo", basePrice=1218, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Photo_VeryOld", basePrice=1218, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },

    -- [Literature.Book] [Rarity.Rare] (182 items)
    { item="Base.Book", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_AdventureNonFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Art", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Baseball", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Bible", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Biography", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Business", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Childs", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Cinema", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Classic", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_ClassicFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_ClassicNonfiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Computer", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_CrimeFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fantasy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Farming", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fashion", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_GeneralNonFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_GeneralReference", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Golf", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_History", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Horror", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Legal", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_LiteraryFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Medical", basePrice=2188, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=3} },
    { item="Base.Book_Military", basePrice=2907, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.Book_MilitaryHistory", basePrice=2907, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.Book_Music", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Nature", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Occult", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Philosophy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Policing", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Politics", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Quackery", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Religion", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Rich", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Romance", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SadNonFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SchoolTextbook", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Science", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SciFi", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Sports", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Thriller", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Travel", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Western", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookAimingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookBlacksmithSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookButcheringSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCarpentrySet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCarvingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCookingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookElectricianSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFancy_Bible", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Classic", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_ClassicFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_ClassicNonfiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_History", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Legal", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Medical", basePrice=2188, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=3} },
    { item="Base.BookFancy_MilitaryHistory", basePrice=2907, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.BookFancy_Occult", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Philosophy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Politics", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Religion", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFarmingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFirstAidSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFishingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFlintKnappingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookForagingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookGlassmakingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookHusbandrySet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookLongBladeSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMaintenanceSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMasonrySet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMechanicsSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMetalWeldingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookPotterySet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookReloadingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTailoringSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTrackingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTrappingSet", basePrice=1952, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Brochure", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Catalog", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.ChildsPictureBook", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Diary1", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Diary2", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Doodle", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.DoodleKids", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Flier", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Flier_Nolans", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.GenericMail", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.GraphPaper", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.HottieZ", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.HottieZ_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.IDcard", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.IndexCard", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Journal", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.MenuCard", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Newspaper", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Dispatch_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Herald_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Knews_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Recent", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Times_New", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Notebook", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Notepad", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.OfficialDocument", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Paperback", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_AdventureNonFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Art", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Baseball", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Bible", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Biography", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Business", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Childs", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Cinema", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Classic", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_ClassicFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_ClassicNonfiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Computer", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Conspiracy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_CrimeFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Diet", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fantasy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fashion", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Golf", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Hass", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_History", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Horror", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Legal", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_LiteraryFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Medical", basePrice=2189, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Military", basePrice=2908, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_MilitaryHistory", basePrice=2908, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Music", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Nature", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_NewAge", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Occult", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Philosophy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Play", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Policing", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Politics", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Poor", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Quackery", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Quigley", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Relationship", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Religion", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Rich", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Romance", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SadNonFiction", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Scary", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Science", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SciFi", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SelfHelp", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Sexy", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Sports", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Teens", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Thriller", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Travel", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_TrueCrime", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Western", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperwork", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ParkingTicket", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Passport", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Phonebook", basePrice=1953, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Photo_Hass", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Photo_Racy", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Photo_Secret", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.PhotoBook", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.PressID", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Receipt", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=27} },
    { item="Base.RPGmanual", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.ScratchTicket", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ScratchTicket_Loser", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ScratchTicket_Winner", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.SewingPattern", basePrice=1954, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.SheetPaper2", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.SpeedingTicket", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.StockCertificate", basePrice=1955, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
})

print("[DynamicTrading] Book Registry Complete")
