-- ============================================================================
-- Literature Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Literature.Recipe] [Rarity.Rare] (82 items)
    { item="Base.ArmorMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag6", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorMag7", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.ArmorSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=10} },
    { item="Base.BSToolsSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CookingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookingMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookingMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookingMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookingMag6", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookwareSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ElectronicsMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ElectronicsMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ElectronicsMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ElectronicsMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ElectronicsMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.EngineerMagazine1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.EngineerMagazine2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.EngineerMagazine3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ExplosiveSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FishingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.FishingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.GlassmakingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.GlassmakingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.GlassmakingMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HempMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HerbalistMag", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KeyMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KnittingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KnittingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MechanicMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MechanicMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MechanicMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MeleeWeaponSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=10} },
    { item="Base.MetalworkMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MetalworkMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MetalworkMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MetalworkMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PrimitiveToolMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PrimitiveToolMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PrimitiveToolMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RecipeClipping", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SmithingMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag10", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag11", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag6", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag7", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag8", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingMag9", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SurvivalSchematic", basePrice=85, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=10} },
    { item="Base.TailoringMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag10", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag6", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag7", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag8", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TailoringMag9", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TrickMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TrickMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag1", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag2", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag3", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag4", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag5", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag6", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
    { item="Base.WeaponMag7", basePrice=102, tags={"Literature.Recipe", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Recipe Registry Complete")
