-- =============================================================================
-- DYNAMIC TRADING: LITERATURE - RECIPE
-- =============================================================================
-- Root Category: Literature
-- Sub Category: Recipe
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.ArmorMag1",          basePrice=300, tags={"Literature.Recipe.Armor", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Tire Armor,
    { item="Base.ArmorMag2",          basePrice=250, tags={"Literature.Recipe.Armor", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Bone/Wood,
    { item="Base.ArmorMag3",          basePrice=350, tags={"Literature.Recipe.Armor", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Scrap Metal,
    { item="Base.ArmorMag4",          basePrice=400, tags={"Literature.Recipe.Armor", "Rarity.Legendary"}, stockRange={min=0, max=1} }, -- Plate Armor,
    { item="Base.ArmorMag5",          basePrice=350, tags={"Literature.Recipe.Armor", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Iron Age,
    { item="Base.ArmorMag6",          basePrice=300, tags={"Literature.Recipe.Armor", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Spiked,
    { item="Base.ArmorMag7",          basePrice=500, tags={"Literature.Recipe.Armor", "Rarity.Legendary"}, stockRange={min=0, max=1} }, -- Bulletproof,
    { item="Base.ArmorSchematic",     basePrice=150, tags={"Literature.Recipe.Armor"}, stockRange={min=0, max=2} },
    { item="Base.BSToolsSchematic",   basePrice=200, tags={"Literature.Recipe.Tool"}, stockRange={min=0, max=1} },
    { item="Base.CookwareSchematic",  basePrice=100, tags={"Literature.Recipe.Tool"}, stockRange={min=0, max=2} },
    { item="Base.ElectronicsMag1",    basePrice=200, tags={"Literature.Recipe.Electronics", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Remote,
    { item="Base.ElectronicsMag2",    basePrice=200, tags={"Literature.Recipe.Electronics", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Timer,
    { item="Base.ElectronicsMag3",    basePrice=200, tags={"Literature.Recipe.Electronics", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Sensors,
    { item="Base.ElectronicsMag4",    basePrice=1500, tags={"Literature.Recipe", "Rarity.Legendary"}, stockRange={min=0, max=1} }, -- Generator,
    { item="Base.ElectronicsMag5",    basePrice=150, tags={"Literature.Recipe.Electronics", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Lights,
    { item="Base.EngineerMagazine1",  basePrice=300, tags={"Literature.Recipe.Engineer", "Quality.Illegal", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Noise Makers,
    { item="Base.EngineerMagazine2",  basePrice=350, tags={"Literature.Recipe.Engineer", "Quality.Illegal", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Smoke/Gas,
    { item="Base.EngineerMagazine3",  basePrice=500, tags={"Literature.Recipe.Engineer", "Quality.Illegal", "Rarity.Legendary"}, stockRange={min=0, max=1} }, -- Pipe Bombs,
    { item="Base.ExplosiveSchematic", basePrice=400, tags={"Literature.Recipe.Engineer"}, stockRange={min=0, max=1} },
    { item="Base.FarmingMag1",        basePrice=100, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Mildew,
    { item="Base.FarmingMag2",        basePrice=100, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Cure,
    { item="Base.FarmingMag3",        basePrice=120, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Flowers,
    { item="Base.FarmingMag4",        basePrice=120, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Scarecrow,
    { item="Base.FarmingMag5",        basePrice=200, tags={"Literature.Recipe.Cooking", "Theme.Storage", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Jarring (Food Preservation),
    { item="Base.FarmingMag6",        basePrice=150, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Crops,
    { item="Base.FarmingMag7",        basePrice=150, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Veggies,
    { item="Base.FarmingMag8",        basePrice=120, tags={"Literature.Recipe.Farming", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Herbs,
    { item="Base.FarmingMag9",        basePrice=150, tags={"Literature.Recipe.Medicine", "Theme.Clinical", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Medicinal,
    { item="Base.FishingMag1",        basePrice=120, tags={"Literature.Recipe.Fishing", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Rods,
    { item="Base.FishingMag2",        basePrice=150, tags={"Literature.Recipe.Fishing", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Nets,
    { item="Base.GlassmakingMag1",    basePrice=200, tags={"Literature.Recipe.Industrial", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.GlassmakingMag2",    basePrice=200, tags={"Literature.Recipe.Industrial", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.GlassmakingMag3",    basePrice=250, tags={"Literature.Recipe.Industrial", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Bottles/Jars,
    { item="Base.HempMag1",           basePrice=200, tags={"Literature.Recipe.Farming", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Hemp,
    { item="Base.HerbalistMag",       basePrice=1200, tags={"Literature.Recipe", "Rarity.Legendary"}, stockRange={min=0, max=1} }, -- Herbalist,
    { item="Base.HuntingMag1",        basePrice=120, tags={"Literature.Recipe.Trapping", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Snare,
    { item="Base.HuntingMag2",        basePrice=150, tags={"Literature.Recipe.Trapping", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Crate/Stick,
    { item="Base.HuntingMag3",        basePrice=150, tags={"Literature.Recipe.Trapping", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Cage/Box,
    { item="Base.HuntingMag4",        basePrice=100, tags={"Literature.Recipe.Trapping", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Trophy,
    { item="Base.MechanicMag1",       basePrice=150, tags={"Literature.Recipe.Mechanic", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Standard,
    { item="Base.MechanicMag2",       basePrice=200, tags={"Literature.Recipe.Mechanic", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Commercial,
    { item="Base.MechanicMag3",       basePrice=250, tags={"Literature.Recipe.Mechanic", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Performance,
    { item="Base.MeleeWeaponSchematic",basePrice=150,tags={"Literature.Recipe.Weapon"}, stockRange={min=0, max=2} },
    { item="Base.MetalworkMag1",      basePrice=300, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.MetalworkMag2",      basePrice=300, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.MetalworkMag3",      basePrice=300, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.MetalworkMag4",      basePrice=250, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.PrimitiveToolMag1",  basePrice=150, tags={"Literature.Recipe.Tool", "Origin.Nomad", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.PrimitiveToolMag2",  basePrice=150, tags={"Literature.Recipe.Tool", "Origin.Nomad", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.PrimitiveToolMag3",  basePrice=150, tags={"Literature.Recipe.Tool", "Origin.Nomad", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.RadioMag1",          basePrice=150, tags={"Literature.Recipe.Radio", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.RadioMag2",          basePrice=150, tags={"Literature.Recipe.Radio", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.RadioMag3",          basePrice=150, tags={"Literature.Recipe.Radio", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.RecipeClipping",     basePrice=50,  tags={"Literature.Recipe"}, stockRange={min=0, max=3} },
    { item="Base.SewingPattern",      basePrice=80,  tags={"Literature.Recipe.Armor"}, stockRange={min=0, max=3} },
    { item="Base.SmithingMag1",       basePrice=350, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag10",      basePrice=650, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag11",      basePrice=450, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag2",       basePrice=350, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag3",       basePrice=350, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag4",       basePrice=350, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag5",       basePrice=450, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag6",       basePrice=750, tags={"Literature.Recipe", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag7",       basePrice=500, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag8",       basePrice=500, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmithingMag9",       basePrice=600, tags={"Literature.Recipe", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SurvivalSchematic",  basePrice=200, tags={"Literature.Recipe.Survival"}, stockRange={min=0, max=1} },
    { item="Base.WeaponMag1",         basePrice=150, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Bone Weapons,
    { item="Base.WeaponMag2",         basePrice=300, tags={"Literature.Recipe.Utility", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Gas Masks/Filters,
    { item="Base.WeaponMag3",         basePrice=200, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Prison,
    { item="Base.WeaponMag4",         basePrice=150, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Barbed Wire,
    { item="Base.WeaponMag5",         basePrice=200, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Street,
    { item="Base.WeaponMag6",         basePrice=150, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Peasants,
    { item="Base.WeaponMag7",         basePrice=150, tags={"Literature.Recipe.Weapon", "Rarity.Uncommon"}, stockRange={min=0, max=1} }, -- Bat Carving,
})

print("[DynamicTrading] Literature/Recipe Registry Loaded.")
