-- =============================================================================
-- DYNAMIC TRADING: LITERATURE - SKILLBOOK
-- =============================================================================
-- Root Category: Literature
-- Sub Category: SkillBook
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.BookAiming1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookAiming2",        basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookAiming3",        basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookAiming4",        basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookAiming5",        basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookBlacksmith1", basePrice=120, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookBlacksmith2",    basePrice=120,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookBlacksmith3",    basePrice=200, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookBlacksmith4",    basePrice=400, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookBlacksmith5",    basePrice=700, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookButchering1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookButchering2",    basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookButchering3",    basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookButchering4",    basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookButchering5",    basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookCarpentry1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookCarpentry2",     basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookCarpentry3",     basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookCarpentry4",     basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookCarpentry5",     basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookCarving1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookCarving2",       basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookCarving3",       basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookCarving4",       basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookCarving5",       basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookCooking1", basePrice=60, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookCooking2",       basePrice=60, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookCooking3",       basePrice=120, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookCooking4",       basePrice=200, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookCooking5",       basePrice=400, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookElectrician1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookElectrician2",   basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookElectrician3",   basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookElectrician4",   basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookElectrician5",   basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookFarming1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookFarming2",       basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookFarming3",       basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookFarming4",       basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookFarming5",       basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookFirstAid1", basePrice=60, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookFirstAid2",      basePrice=60, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookFirstAid3",      basePrice=120, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookFirstAid4",      basePrice=200, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookFirstAid5",      basePrice=400, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookFishing1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookFishing2",       basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookFishing3",       basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookFishing4",       basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookFishing5",       basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookFlintKnapping1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookFlintKnapping2", basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookFlintKnapping3", basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookFlintKnapping4", basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookFlintKnapping5", basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookForaging1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookForaging2",      basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookForaging3",      basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookForaging4",      basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookForaging5",      basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookGlassmaking1", basePrice=120, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookGlassmaking2",   basePrice=120,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookGlassmaking3",   basePrice=200, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookGlassmaking4",   basePrice=400, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookGlassmaking5",   basePrice=700, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookHusbandry1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookHusbandry2",     basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookHusbandry3",     basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookHusbandry4",     basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookHusbandry5",     basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookLongBlade1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookLongBlade2",     basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookLongBlade3",     basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookLongBlade4",     basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookLongBlade5",     basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookMaintenance1", basePrice=120, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} }, -- Very useful,
    { item="Base.BookMaintenance2",   basePrice=120,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookMaintenance3",   basePrice=200, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookMaintenance4",   basePrice=400, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookMaintenance5",   basePrice=700, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookMasonry1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookMasonry2",       basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookMasonry3",       basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookMasonry4",       basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookMasonry5",       basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookMechanic1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookMechanic2",      basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookMechanic3",      basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookMechanic4",      basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookMechanic5",      basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookMetalWelding1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookMetalWelding2",  basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookMetalWelding3",  basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookMetalWelding4",  basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookMetalWelding5",  basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookPottery1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookPottery2",       basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookPottery3",       basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookPottery4",       basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookPottery5",       basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookReloading1", basePrice=100, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookReloading2",     basePrice=100,tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookReloading3",     basePrice=180, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookReloading4",     basePrice=350, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookReloading5",     basePrice=600, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookTailoring1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookTailoring2",     basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookTailoring3",     basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookTailoring4",     basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookTailoring5",     basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookTracking1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookTracking2",      basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookTracking3",      basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookTracking4",      basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookTracking5",      basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.BookTrapping1", basePrice=80, tags={"Literature.SkillBook", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.BookTrapping2",      basePrice=80, tags={"Literature.SkillBook", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.BookTrapping3",      basePrice=150, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.BookTrapping4",      basePrice=300, tags={"Literature.SkillBook", "Rarity.Rare"}, stockRange={min=1, max=1} },
    { item="Base.BookTrapping5",      basePrice=500, tags={"Literature.SkillBook", "Rarity.Legendary"}, stockRange={min=0, max=1} },
})

print("[DynamicTrading] Literature/SkillBook Registry Loaded.")
