-- ============================================================================
-- Container Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Container.Bag.General] [Rarity.Rare] (81 items)
    { item="Base.Bag_BirthdayBasket", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BowlingBallBag", basePrice=192, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Dancer", basePrice=193, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadMice", basePrice=245, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRats", basePrice=245, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRoaches", basePrice=245, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DoctorBag", basePrice=228, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_FluteCase", basePrice=163, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GardenBasket", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Gunny", basePrice=274, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_JanitorToolbox", basePrice=202, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Bag_Laundry", basePrice=274, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_LaundryHospital", basePrice=307, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_LaundryLinen", basePrice=274, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Mail", basePrice=274, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_PicnicBasket", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Survivalist", basePrice=227, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Tools", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky", basePrice=250, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio", basePrice=250, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1", basePrice=250, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=250, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist", basePrice=279, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard", basePrice=250, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary", basePrice=321, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2", basePrice=321, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary", basePrice=261, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=292, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Theme.Clinical", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=261, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmall", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Combat", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist", basePrice=210, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie", basePrice=181, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice", basePrice=215, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary", basePrice=241, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid", basePrice=241, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1", basePrice=241, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie", basePrice=241, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police", basePrice=234, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase_Police2", basePrice=234, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase_Police3", basePrice=234, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCaseGreen", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen2", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SaxophoneCase", basePrice=175, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCase_Police", basePrice=234, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ShotgunCaseGreen", basePrice=198, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrashBag", basePrice=275, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=7} },
    { item="Base.Bag_TreasureBag", basePrice=245, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TrumpetCase", basePrice=163, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ViolinCase", basePrice=163, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase", basePrice=203, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase_Money", basePrice=203, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Garbagebag", basePrice=275, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=7} },
    { item="Base.GroceryBag1", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag2", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag3", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag4", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag5", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBagGourmet", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Lunchbag", basePrice=170, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Paperbag_Jays", basePrice=170, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Paperbag_Spiffos", basePrice=170, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag_Bags", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag_Clothing", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.SeedBag_Farming", basePrice=164, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Toolbox_Mechanic", basePrice=202, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Tote", basePrice=193, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Bags", basePrice=193, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Clothing", basePrice=193, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Bag Registry Complete")
