require "DT/Common/Config"

DynamicTrading.RegisterDialogue("General", "Tracking", {
    EN = {
        ReplyLive = {
            "Copy, {player.firstname}. I'm at {coords}, {site}.",
            "You have me now. {coords}. I'm {site}.",
            "Signal is clean enough. Mark {coords}; I'm {site}.",
            "Reading you. I'm holding at {coords}, {site}.",
            "Keep this frequency open. I'm at {coords}, {site}.",
            "Loud and clear. You can find me at {coords}, {site}.",
            "This is my spot for now. {coords}, {site}. Come find me.",
            "Still here, still breathing. {coords}, {site}.",
            "Got your call. I haven't moved; {coords}, {site}.",
            "Your timing is good, I just settled in. {coords}, {site}.",
            "Affirmative. Sending current location: {coords}. I'm {site}.",
            "Yeah, I hear you. Sitting tight at {coords}, {site}.",
            "You'll find me at {coords}. I'm {site}, keeping low.",
            "Checked my bearing for you: {coords}, {site}. Come on over.",
            "Don't keep me waiting. I'm at {coords}, {site}.",
            "Read you five-by-five. Current position is {coords}, {site}.",
            "Here's my mark: {coords}. I'm {site}, shouldn't be hard to spot.",
            "Good to hear a voice. I'm at {coords}, {site}. Approach when ready.",
            "Holding position at {coords}, {site}. Frequency is open.",
            "Lock onto {coords}. I'm {site} and I'll be here a while.",
        },
        ReplyLastKnown = {
            "Last clean ping had me at {coords}, {site}. I may have moved since then.",
            "My last solid position was {coords}. I was {site} when the relay caught me.",
            "If the tracker slips, start at {coords}. Last report had me {site}.",
            "The relay only caught my last beacon: {coords}, {site}.",
            "Best lead I've got for you is {coords}. I was {site} on the last burst.",
            "Signal's a bit spotty, but last fix was {coords}. I was {site}.",
            "Can't guarantee I'm still there, but {coords} was my last known. I was {site}.",
            "Static's building. Last good position: {coords}, {site}.",
            "I dropped a ping at {coords} before the line got rough. Was {site}.",
            "Your best bet is {coords}. That's where I was before the relay hiccupped, {site}.",
            "Don't bank on it being exact, but my last mark was {coords}, {site}.",
            "Hard to say where I am right now. Last thing I sent was {coords}, {site}.",
            "Relay caught me at {coords}, {site}. Could be anywhere by now, though.",
            "Here's what I've got: {coords}, {site}. But that was a while back.",
            "If I haven't wandered too far, start at {coords}. I was {site}.",
            "Last solid beacon put me at {coords}, {site}. Signal's been rough since.",
            "I was pinged at {coords} — {site}. No guarantees after that.",
            "My tracker flagged {coords}. I was {site} when it last caught me.",
            "Take this with a grain of salt: {coords}, {site}. Signal's been fading.",
            "Could be stale, but here goes: {coords}. I was {site} the last time I checked in.",
        },
        Approach3000 = {
            "Three klicks out? That's a day's walk in this mess. Pace yourself.",
            "You're way out there, {player.firstname}. I'm not going anywhere, take your time.",
            "Three thousand meters. You'd better have good shoes and a clear route.",
            "That's a serious hike. Watch the roads and keep your head down between towns.",
            "I can barely read you at this range. You've got a long journey ahead.",
            "Three klicks. I'd tell you to take a car but good luck finding one that runs.",
            "You're on the horizon. Literally. It's going to be a while.",
            "Copy your position. That's... far. Real far. Stay alive on the way in.",
            "Three thousand meters of open territory between us. Don't get lost out there.",
            "At that distance, I won't even hear you scream. Stay smart, {player.firstname}.",
            "Long road ahead. Keep the radio charged, you'll want it before you get here.",
            "Three klicks. You're basically in another zip code. Start walking.",
            "I'll keep the signal lit. Three thousand meters is no joke in this world.",
            "That's a trek and a half. Stay off the main roads if you can.",
            "Three thousand. I've seen people disappear in shorter distances. Stay sharp.",
            "You've got the whole dead zone between us. Hunker down and push through.",
            "At this range we're more pen pals than radio contacts. Get moving.",
            "Three klicks, {player.firstname}. I'll be here. Question is whether you'll make it.",
            "That's expedition territory. Watch your supplies on the way.",
            "I hope you packed light because you've got three thousand meters of trouble ahead.",
        },
        Approach2000 = {
            "Two klicks. Still a haul, but at least you're gaining ground.",
            "Two thousand meters, {player.firstname}. You've cut into the distance.",
            "Better than before. Two klicks to go, keep the pace steady.",
            "You're still pretty far out. Two thousand meters. Don't rush, don't stop.",
            "Two klicks on the tracker. I can hear the signal getting slightly stronger.",
            "Making progress. Two thousand meters is manageable if you keep moving.",
            "Still a long walk, but you're past the worst of it. Two klicks.",
            "Two thousand meters. About the length of a small town. Push through it.",
            "Getting closer, but don't celebrate yet. Two klicks is still a lot of ground.",
            "Two kilometers. The signal's a touch cleaner. Must be heading right.",
            "I can tell you're moving the right way. Two thousand meters to go.",
            "Two klicks. Stay quiet through the open stretches. Sound carries out there.",
            "You're eating into the distance. Two thousand meters. Good work.",
            "Two klicks down from where you started. Keep that momentum.",
            "At two thousand meters I can start to feel hopeful. Keep coming.",
            "The gap's shrinking. Two klicks. I'll keep the light on for you.",
            "Two thousand meters. That's maybe forty minutes if nothing goes sideways.",
            "Steady heading. Two klicks out. You're doing fine, {player.firstname}.",
            "You're inside the outer ring now. Two thousand meters. Stay course.",
            "Two klicks. Long enough to get in trouble, short enough to see the end.",
        },
        Approach1500 = {
            "Fifteen hundred meters. You're past the halfway point from the start.",
            "A klick and a half. The signal's actually useful at this range.",
            "Fifteen hundred. I can track your approach now, faintly. Keep coming.",
            "You've covered some serious ground. Fifteen hundred meters to go.",
            "One and a half klicks. Not close, but not far in the grand scheme.",
            "Fifteen hundred meters, {player.firstname}. The hard middle stretch is behind you.",
            "Getting into a range where I'm starting to pay attention. Fifteen hundred.",
            "A klick and a half. You're inside what I'd call my extended neighborhood.",
            "Fifteen hundred meters. Things might get more populated from here. Stay careful.",
            "I can feel the signal getting more consistent. Fifteen hundred meters.",
            "You're cutting through nicely. A klick and a half left.",
            "Fifteen hundred. That's maybe twenty minutes of steady walking.",
            "The distance is starting to feel real now. Fifteen hundred meters.",
            "One point five klicks. I'm starting to actually expect you. Keep moving.",
            "Fifteen hundred meters. Stay on that bearing and you'll walk right to me.",
            "Good progress, {player.firstname}. Fifteen hundred meters isn't nothing, but it's doable.",
            "A klick and a half. Watch for the terrain changes around this range.",
            "Fifteen hundred meters out. The hardest part of the walk might be over.",
            "You're in striking distance now, loosely speaking. Fifteen hundred meters.",
            "I can hear you better with every check-in. Fifteen hundred meters to go.",
        },
        Approach1000 = {
            "One klick. You're inside a thousand meters now. That's real distance closed.",
            "A thousand meters, {player.firstname}. Single digits on the klick counter.",
            "One kilometer. I'd say you're getting warm. Keep it up.",
            "A thousand meters out. At this range I can't ignore you anymore.",
            "One klick even. You should start seeing signs of the area I described.",
            "Under a thousand. That's inside my patrol range. You're getting close.",
            "Thousand meters. In the old world that's a ten-minute walk. Out here, who knows.",
            "One klick. The signal's settling into a comfortable steady pulse.",
            "A thousand meters and closing. I like the direction this is headed.",
            "One kilometer, {player.firstname}. You're in the home region now.",
            "Thousand meters. Close enough that I'd hear gunshots from your position.",
            "Inside one klick. The last thousand always feels the longest. Hang in there.",
            "One kilometer. That's close enough to start talking about landmarks.",
            "A thousand meters. I can almost start giving you directions instead of coordinates.",
            "One klick to go. You've done the hard part. The rest is just walking.",
            "Thousand meters. It's starting to feel like you might actually show up.",
            "Under a klick now. My receiver is picking you up more clearly.",
            "One thousand meters. That's practically next door by wasteland standards.",
            "A klick even. You should be hitting my area soon. Eyes open.",
            "Thousand meters, {player.firstname}. Final stretch of the long haul.",
        },
        Approach750 = {
            "Seven fifty. You're three quarters of a klick out. Solid progress.",
            "Seven hundred fifty meters. Getting into the zone now.",
            "Three quarters of a klick, {player.firstname}. You're really narrowing it down.",
            "Seven fifty meters. At this range I start getting twitchy. In a good way.",
            "You're at seven fifty. Close enough that the bearing matters a lot now.",
            "Seven hundred fifty meters. Make sure you're still heading straight.",
            "Under a klick and tightening. Seven fifty meters. Keep it smooth.",
            "Three quarters out. The tracker's reading consistent now. Seven fifty.",
            "Seven fifty meters. You should be in familiar terrain soon if I described it right.",
            "Getting into the pocket, {player.firstname}. Seven fifty meters.",
            "Seven hundred fifty. At this distance a wrong turn costs you minutes, not hours.",
            "Seven fifty. I'm starting to think about what you look like, honestly.",
            "Three quarters of a klick. Watch for the transition between open and built-up areas.",
            "Seven fifty meters. You're inside the ring I'd call genuinely close.",
            "Seven hundred fifty and counting down. You're doing this.",
            "Seven fifty meters, {player.firstname}. The signal is sweet and strong.",
            "Under a klick by a quarter now. Seven fifty and shrinking.",
            "Seven hundred fifty meters. Close enough for landmarks to start making sense.",
            "Seven fifty. I'd start jogging if I were you, but then again, noise carries.",
            "Three quarters out. Almost time to switch from navigating to searching.",
        },
        Approach500 = {
            "Half a klick. You're close enough that I should start watching for you.",
            "Five hundred meters, {player.firstname}. That's spitting distance in the old world.",
            "Half a klick out. The signal says you're locked on. Good.",
            "Five hundred meters. We're getting into real approach territory now.",
            "You're at five hundred. Close enough to hear a car horn, if anyone had one.",
            "Half a kilometer. I wouldn't call it close yet, but I wouldn't call it far either.",
            "Five hundred meters. Maybe ten minutes of careful walking. Stay alert.",
            "Half a klick, {player.firstname}. This is where it gets interesting.",
            "Five hundred meters and the receiver is humming. You're on target.",
            "Half a klick. Start watching the alleys and doorways. My area is near.",
            "Five hundred meters. You'll start noticing things that match what I told you.",
            "Half a kilometer out. Close enough to shout if we both had good lungs.",
            "Five hundred, {player.firstname}. The last stretch before it gets really tight.",
            "Half a klick. Keep the radio close, I'll start giving you finer directions soon.",
            "Five hundred meters and I'm getting antsy. I can feel you getting closer.",
            "You're at five hundred. The dead zone between us is thinning out.",
            "Half a klick. If something goes wrong now, I might actually hear it.",
            "Five hundred meters. This is the transition from travel to tracking.",
            "Half a kilometer. Switch from walking-mode to hunting-mode, {player.firstname}.",
            "Five hundred meters. Almost time to start using your eyes more than the radio.",
        },
        Approach300 = {
            "Three hundred meters. You're definitely in my area now.",
            "Three hundred, {player.firstname}. I can almost feel your footsteps from here.",
            "You're at three hundred. Close enough that direction really matters.",
            "Three hundred meters out. You should start recognizing the terrain I described.",
            "We're getting tight. Three hundred meters. Watch every corner.",
            "Three hundred meters. Another few minutes and we'll be face to face.",
            "You're inside three hundred. That's a short sprint in the open.",
            "Three hundred, {player.firstname}. The signal is painting you clearly now.",
            "Three hundred meters. I could throw a flare and you'd see it.",
            "Under three hundred meters. My hands are starting to relax a little.",
            "Three hundred. That's building-to-building distance. You're right here.",
            "Three hundred meters and everything about the signal says on-target.",
            "You're practically local at three hundred meters. Keep pushing in.",
            "Three hundred, {player.firstname}. Start scanning the area for signs of life.",
            "Three hundred meters. If I stamped my feet hard enough, you'd feel it.",
            "Getting real cozy on the tracker. Three hundred meters out.",
            "Three hundred. Short enough that I'd wave if I thought you could see me.",
            "Under three hundred meters now. The worst of the walk is behind you.",
            "Three hundred, and the receiver is locked solid. You're right on course.",
            "Three hundred meters. Let's close this gap. I'm ready for company.",
        },
        Approach200 = {
            "You're out there somewhere. I can barely read you, but keep heading this way.",
            "Faint signal from you. You're still a ways out, but you're on the right heading.",
            "I think that's you on the edge of range. Still far off. Keep coming.",
            "There's a blip that might be you. Couple hundred meters maybe. Stay the course.",
            "Getting a whisper of your signal. Long walk still, but you're pointed right.",
            "If that's you pinging, you've still got some ground to cover. Keep moving.",
            "Barely picking you up. You're distant, but the heading looks good.",
            "Faint trace. Could be you, could be noise. Either way, keep coming {player.firstname}.",
            "You're on the scope, but just barely. Still a fair distance out.",
            "I hear something on the channel. You're far, but moving the right direction.",
            "That hiss on the line might be you. You've got a couple blocks to go at least.",
            "Not close enough to make out your footsteps. But the bearing's right, keep going.",
            "Starting to pick up something. You're well outside visual range though.",
            "My receiver perked up a bit. You're in the neighborhood, loosely speaking.",
            "Getting the faintest read. You've got distance to cover still, {player.firstname}.",
            "Signal's thin but it's there. Must be you. Head straight and don't wander.",
            "If I strain, I can hear you on the frequency. That's a good sign. Keep coming.",
            "There's something at the fringe of my range. I'll assume that's you.",
            "You're registering, but barely. Let's get that signal stronger. Keep walking.",
            "Long way to go still, but at least I know you're out there now.",
        },
        Approach150 = {
            "Getting stronger. You're closing in, maybe a hundred fifty meters.",
            "Better. I can actually hear your signal properly now. Keep the pace.",
            "You're tightening up. Not close yet, but getting there.",
            "Good progress. The signal's firming up on my end.",
            "A hundred fifty or so. You're making ground, {player.firstname}.",
            "I can feel the signal getting closer. Stay on that heading.",
            "Whatever you're doing, keep doing it. You're on the right line.",
            "The static is clearing up little by little. You're narrowing the gap.",
            "We're getting somewhere. Watch for landmarks and keep heading in.",
            "Signal's picking up strength. You're past the halfway mark by my reckoning.",
            "Closer now. Not sprinting distance yet, but the signal says you're gaining.",
            "I can hear the crunch through the channel. You're moving this way, good.",
            "You've cut the distance nicely. Stay sharp — area might have company.",
            "Hundred fifty meters, give or take. You're doing fine, just keep moving.",
            "The line's cleaner now. You're getting into my neighborhood.",
            "If my read is right, you're well on your way. Don't slow down.",
            "Coming through louder. I'd say a couple minutes of walking left.",
            "Good heading. The signal confirms it. You'll be here before long.",
            "Nice and steady. Don't rush, just keep the bearing true.",
            "Starting to feel like you might actually find me. Keep it up.",
        },
        Approach100 = {
            "You're close. Keep following the signal and watch the approaches.",
            "About right. I'm nearby, still {site}.",
            "I hear you getting closer. Stay sharp and keep coming.",
            "Hundred meters. Close enough that I'm getting comfortable calling it close.",
            "You're in the right zone. Won't be long now at this rate.",
            "Don't second-guess the signal. It's reading true; you're right on top of me almost.",
            "Getting loud on my end too. A hundred meters or so. Stay on it.",
            "I think I can hear footsteps. Or maybe that's the dead. Either way, you're near.",
            "Close quarters now. A hundred meters feels like nothing out here. Keep coming.",
            "Signal says you're basically a block away. Look for {building}.",
            "Right. Hundred meters. This is the home stretch, {player.firstname}.",
            "Starting to feel real. You're right around the corner, relatively speaking.",
            "The noise floor just dropped. You're getting into my circle. Stay sharp.",
            "Almost there. Keep your head on a swivel the last stretch.",
            "Close now. If you see anything moving, that's probably me. Hopefully.",
            "You've got maybe a minute of walking. The signal's strong.",
            "A hundred meters. I'd wave but I don't want to attract the wrong kind of attention.",
            "I can almost feel the air change when someone gets this close. Keep coming.",
            "Not far now. Look for anything that looks like someone's been living out here.",
            "You're within shouting distance if I dared. Almost there.",
        },
        Approach75 = {
            "Getting tighter. You're within seventy-five meters now. Watch your step.",
            "Close enough that I'm starting to feel nervous. Friendly nervous. Keep coming.",
            "Seventy-five meters. If the wind was right, I could probably hear you breathing.",
            "Real close now. Take it slow and keep your eyes open.",
            "Almost on top of me. Seventy-five meters is nothing. Stay careful.",
            "I'm starting to look out for you. Seventy-five meters, give or take.",
            "You're in my backyard now. Slow and steady, {player.firstname}.",
            "Close enough to worry about line of sight. Look for {building}.",
            "Seventy-five. You could throw a rock and I'd probably hear it land.",
            "Things get tense at this range. Friend or zed, you never know. But I know it's you.",
            "The signal is almost pegging the meter. You're real close.",
            "We're in spitting distance. Not that I'd recommend it. Keep coming.",
            "I'm watching the approaches now. Seventy-five meters, you're almost here.",
            "Interesting how seventy-five meters feels like miles when you're waiting. Come on.",
            "Right in the pocket. Scan around for anything that looks occupied.",
            "I'm tucked in but I can feel you getting closer on the receiver.",
            "Not much farther. The signal's crystal clear at this range.",
            "Seventy-five meters. If something moves near {building}, that's me.",
            "You're practically next door. Just a little further.",
            "Close enough that I should probably stop broadcasting and start looking for you.",
        },
        Approach50 = {
            "Fifty meters sounds right. Look for movement near {building}.",
            "You're almost on me now. I'm still {site}.",
            "Close enough now that you should start seeing my position.",
            "Fifty meters. I can practically count your steps through the static.",
            "Getting tight. Watch for signs of someone {site}.",
            "You should be able to spot me soon. Fifty meters and closing.",
            "I'm not going anywhere. Fifty meters, {player.firstname}. Take your time.",
            "Half a football field. That's nothing. Open your eyes wide.",
            "Fifty meters and the signal is screaming. You're right on me.",
            "Look carefully. I might not be obvious, but I'm here. Fifty meters.",
            "We're practically neighbors now. I'm {site}, look around.",
            "Fifty meters. If you can't see me, try looking near {building}.",
            "Should be obvious soon. Fifty meters out and I'm {site}.",
            "You could shout and I'd hear you. But please don't. Fifty meters.",
            "Right on the money. Fifty meters or less. Scan your surroundings.",
            "Getting real cozy on the scanner. You're right here, almost.",
            "Close enough to make me twitch. I'm {site}, look sharp.",
            "Fifty meters. The hard part is over. Just find the right corner.",
            "I'm holding still. Fifty meters. Don't overthink it, just look.",
            "At this range I can practically wave you in. Almost there.",
        },
        Approach25 = {
            "Twenty-five meters. You're right here. Look around carefully.",
            "I could toss you something from here if I wanted. Look for me.",
            "Twenty-five meters, {player.firstname}. I'm right in your eyeline if you look.",
            "Stop scanning the radio and start scanning the area. I'm right here.",
            "You're stepping on my doorstep. Twenty-five meters. Eyes up.",
            "Nearly there. I should be visible if you look toward {building}.",
            "We're so close I'm about to just call out. Twenty-five meters.",
            "Right here. Twenty-five meters. You should see something out of place.",
            "This is the final stretch. Twenty-five meters. I'm not hiding, exactly.",
            "If you look to your left or right, one of those views has me in it.",
            "I'm practically breathing down your neck on this signal. Twenty-five meters.",
            "Turn in a circle. I'm one of the things you'll see. Twenty-five meters.",
            "You're in arm's reach, relatively speaking. I'm {site}.",
            "Twenty-five meters. I'm the one that doesn't look dead.",
            "Look alive, {player.firstname}. You're basically on top of me.",
            "Close enough that I can hear the radio echo from your set. Look up.",
            "Twenty-five meters. If you keep walking, you'll bump into me.",
            "I'm right here. Don't make it weird, just come over.",
            "Almost face to face. Twenty-five meters. Look near {building}.",
            "At this distance, talking on the radio feels silly. But here I am.",
        },
        Approach10 = {
            "There you are. I've got you in sight too.",
            "Visual confirmed. Lower the radio and look my way.",
            "I can see you now. No need to shout into the handset anymore.",
            "Right there. I see you. Come on over, we're done with the radio part.",
            "Eyes on you. You can put that thing away now.",
            "That's you, isn't it? Yeah, I can see you. Come over here.",
            "We're practically standing together. Radio off, let's talk face to face.",
            "I see movement and it's not the dead kind. That's you. Welcome.",
            "Contact. You made it. Bring it in, {player.firstname}.",
            "There we go. Visual. The frequency did its job.",
            "Found you. Or you found me. Either way, we're good.",
            "Seeing you now. You can let go of the talk button.",
            "Ten meters. I can count the buttons on your jacket. Come on over.",
            "You walked right to me. Good signal work. Let's talk properly.",
            "That's close enough for a handshake. I've got visual.",
            "Face to face at last. The radio's done its part. Come on in.",
            "I can see you clear as day. Drop the handset, we're here.",
            "There's the face behind the voice. Good to see you in person.",
            "Hey. Over here. Yeah, that's me. Welcome, {player.firstname}.",
            "Signal matched, visual matched. Come on, let's do this proper.",
        },
        Away = {
            "Yeah, you're fading out man. Pick it up.",
            "Wait, the signal is dropping. Are you heading the wrong way?",
            "I'm losing you, {player.firstname}. Double check your bearing.",
            "You're drifting out of range. Stay on the signal or we're done.",
            "The ping's getting weaker. You heading back to the start or something?",
            "Static's building on my end. You're walking away, {player.firstname}!",
            "I can barely hear you through the soup. Turn around!",
            "Where you going? You're dropping off the scope.",
            "Signal lock is failing. You're headed for the wilderness, man.",
            "Keep this up and we're going to lose the line. Focus!",
        }
    }
})