-- ============================================================================
-- Misc Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Misc.General] [Rarity.Common] (14 items)
    { item="Base.Badge", basePrice=5, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.BrokenGlass", basePrice=2, tags={"Misc.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=3, max=15} },
    { item="Base.Clitter", basePrice=5, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.CocktailUmbrella", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Crystal", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Crystal_Large", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.DogTag_Pet", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.DogTag_Pet_Blank", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Key1", basePrice=15, tags={"Misc.General", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.Pillow_Heart", basePrice=4, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Pillow_Star", basePrice=4, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Stairs", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.ToyBadge", basePrice=5, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.WaterDrop", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },

    -- [Misc.General] [Rarity.Rare] (232 items)
    { item="Base.Amethyst", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Animal_Brain", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Animal_Brain_Small", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Animal_Item_Dummy", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.AnimalSinew", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Awl", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Awl_Bone", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Awl_Stone", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BackgammonBoard", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Baseball", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Basketball", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bell", basePrice=102, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bellows", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Birdie", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BobPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Book_Prop", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BookFancy_Prop", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BorisBadger", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BoxOfJars", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Brush", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bull_Skull", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BusinessCard", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Calf_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Camera", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CameraDisposable", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CameraExpensive", basePrice=2, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=4} },
    { item="Base.CameraFilm", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CapGunCap", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CapGunCapBox", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarKey", basePrice=29, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CaseyPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CatToy", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicMortarandPestle", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CheckerBoard", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ChessBlack", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChessWhite", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Chicken_Chick_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Chicken_Hen_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Chicken_Rooster_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChickenFeather", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Chopsticks", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChrisPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasHanging", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ChristmasOrnament_Gold1", basePrice=3, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Gold2", basePrice=3, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Gold3", basePrice=3, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Green1", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Green2", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Green3", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Red1", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Red2", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasOrnament_Red3", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChristmasWreath", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ClayPlate", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ClayTool_Carved", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Comb", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CompassDirectional", basePrice=19, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Cork", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CortmanPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Cow_Skull", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Crayons", basePrice=4, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CreditCard", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeWhetstone", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CrudeWoodenTongs", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cube", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Dart", basePrice=22, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerDoe_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DeerFawn_Skull", basePrice=4, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.DeerStag_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Diamond", basePrice=17, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=20} },
    { item="Base.Dice", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_00", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_10", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_12", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_20", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_4", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_6", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_8", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_Bone", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dice_Wood", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.DogChew", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Doll", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DryerLint", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.DryFirestarterBlock", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Dung_Chicken", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dung_Cow", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Dung_Deer", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Dung_Mouse", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dung_Pig", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Dung_Rabbit", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Dung_Raccoon", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Dung_Rat", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Dung_Sheep", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Dung_Turkey", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Emerald", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.EyeOfCthulhu", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FluffyfootBunny", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Football", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FreddyFox", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Frog", basePrice=4, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Funnel", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.FurbertSquirrel", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FurTuft_Black", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FurTuft_Browndark", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FurTuft_Brownlight", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FurTuft_Grey", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FurTuft_White", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GamePieceBlack", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GamePieceRed", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GamePieceWhite", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GoldCoin", basePrice=17, tags={"Misc.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=20} },
    { item="Base.GolfBall", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GolfTee", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GuitarPick", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HandDrill", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HankPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Harmonica", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HolePuncher", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hominid_Skull", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Hominid_Skull_Fragment", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Hominid_Skull_Partial", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HopsDried", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.JacquesBeaver", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.JamesPic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.JarLid", basePrice=34, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Katana_Handle", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KatePic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Key_Blank", basePrice=26, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KnittingNeedles", basePrice=13, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KnittingNeedles_Bone", basePrice=13, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KnittingNeedles_Wood", basePrice=13, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Lamb_Skull", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.LargeMeteorite", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Macandcheese_Box", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.MagnesiumShavings", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.MariannePic", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MasonsTrowel_Wood", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MeasuringTape", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MetalworkingPliers", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Mirror", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MoleyMole", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MortarPestle", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Needle", basePrice=20, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Needle_Bone", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Needle_Brass", basePrice=20, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Needle_Forged", basePrice=20, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.OilPress", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.OujaBoard", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PancakeHedgehog", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PanchoDog", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PercedWood", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Pig_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Piglet_Skull", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PigTusk", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pillow_Happyface", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Pinecone", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasticFork", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasticKnife", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasticSpoon", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasticTray", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Plate", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Pliers", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Plushabug", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Pocketwatch", basePrice=9, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PokerChips", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PoolBall", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PotScrubberFrog", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Rabbit_KittenSkull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Rabbit_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Raccoon_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Ram_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Razor", basePrice=13, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RubberBand", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Rubberducky", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RubberHose", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RubberSpider", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Ruby", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Sapphire", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SharpBoneFragment", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Sheep_Skull", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SilverCoin", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SmallAnimalBone", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmallFileSet", basePrice=4, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmallPunchSet", basePrice=4, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SnowGlobe", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SoccerBall", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Beetles", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Brain", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Butterflies", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Centipedes", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_FetalCalf", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_FetalLamb", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_FetalPiglet", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Insects", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Minerals", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_MonkeyHead", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Octopus", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Specimen_Tapeworm", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Spiffo", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SpiffoBig", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Splinters", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Spork", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Stapler", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Staples", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.StoneChisel", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneDrill", basePrice=34, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Straw2", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SuspiciousPackage", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TennisBall", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ToiletPaper", basePrice=13, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tongs", basePrice=7, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Toothbrush", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Toothpaste", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ToyBear", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ToyBear_Crafted_Burlap", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ToyBear_Crafted_Cotton", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ToyCar", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ToyPlane", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TrashGoblin", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Tsquare", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Turkey_PoultSkull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Turkey_Skull", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TurkeyFeather", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TwigsBundle", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.UnusableMetal", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.UnusableWood", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ViseGrips", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Whetstone", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Whistle", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Whistle_Bone", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Yoyo", basePrice=8, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Zipties", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },

    -- [Misc.General] [Rarity.Uncommon] (1 item)
    { item="Base.MilitaryMedal", basePrice=13, tags={"Misc.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=5, max=25} },
})

print("[DynamicTrading] General Registry Complete")
