-- ============================================================================
-- DT_General.lua
-- Misc Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_General = DT_General or {}
DT_General.items = {
    -- Added by ItemGenerator
    { item="Base.Animal", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.x2Scope", basePrice=18, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.x4Scope", basePrice=14, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.x8Scope", basePrice=7, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AmmoStraps", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TritiumSights", basePrice=42, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RecoilPad", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Laser", basePrice=7, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RedDot", basePrice=11, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChokeTubeFull", basePrice=37, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChokeTubeImproved", basePrice=37, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pocketwatch", basePrice=9, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.AlarmClock2", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CowLeather_Simmental_Fur_Tan", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Medium", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Small", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DeerLeather_Fur_Tan", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.DeerLeather_Fur_Tan_Small", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DappleDeerHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.DeerHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Hematite", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HematiteLarge", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Malachite", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MalachiteLarge", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBellows", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_UprightCoffin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlatCoffin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_KeyDuplicator", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BenchGrinder", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cow_Skull_Wall", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Bull_Skull_Wall", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Sheep_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Pig_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.DeerStag_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Antlers_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CampingTentKit2", basePrice=1, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=0, max=2} },
    { item="Base.ImprovisedTentKit", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.HideTent", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SleepingBag_RedPlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_BluePlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Green", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_GreenPlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Camo", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Green", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Blue", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Green2", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Spiffo", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_HighQuality_Brown", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Hide", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentYellow", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentBlue", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentBrown", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentGreen", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Moveable", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BacklessWoodenBench", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeachChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BluePlasticChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueRattanChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkBlueChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyBlackChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyWhiteChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FoldingChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalStool", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakBench", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OfficeChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeFuton", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeModernChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PileOCrepeChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleRattanChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },


}

return DT_General.items
