-- ============================================================================
-- DT_General.lua
-- Misc Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_General = DT_General or {}
DT_General.items = {
    -- Added by ItemGenerator
    { item="Base.Mov_Projector", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SatelliteDish", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityWallMonitors", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityTerminal", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityTerminal2", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TVCamera", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeigeRotaryPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackRotaryPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedRotaryPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteRotaryPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteModernPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackModernPhone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_HaystackDouble", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_HaystackSingle", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_SaltLick", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagAdmin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSA", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSALarge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FridgeMini", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialFridge", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlainFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrailerFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFridge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteIndustrialFridge", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ChestFreezer", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PopsicleFreezer", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=2, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp1", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp2", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp3", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp4", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp5", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp6", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LightConstruction", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=2, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_NeonOpenSign", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=2, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=2, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetMedical", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DegreeDoctor", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DegreeSurgeon", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FirstAidCabinet", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microscope", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MobileBloodbag", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MobileCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ScaleMedical", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },

    -- Added by ItemGenerator
    { item="Base.Mov_PalletEmpty", basePrice=2, tags={"Misc.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadBarrier", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadCone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadCone2", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FireHydrant", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_StopSign", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BinRound", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueWallLocker", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetTool", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CardboardBox", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ClothesStand", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayGarbageBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenGarbageBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenWallLocker", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LargeOpenToppedGarbageBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Mailbox", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MilitaryCrate", basePrice=3, tags={"Misc.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MilitaryLocker", basePrice=3, tags={"Misc.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PublicGarbageBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PublicMailBox", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RecycleBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ShoppingBaskets", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallChest", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SnackVendingMachine", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SodaVendingMachine", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WashingBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WheelieBin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_YellowWallLocker", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_AntiqueStove", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackBBQ", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CoffeeMaker", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DeepFryer", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Espresso", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ExtractorHood", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenOven", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyOven", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_HotdogMachine", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialOven", basePrice=2, tags={"Misc.General", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microwave", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microwave2", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernOven", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PopcornMachine", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedBBQ", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedOven", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Toaster", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrailerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeigeCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayLongCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinkCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCurtain", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchDrawers", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPineCabinet", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_AirConditioner", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ArcadeMachine1", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ArcadeMachine2", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackCashRegister", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CashRegister", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DesktopComputer", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Jukebox", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microphone", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PayPhones", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinballMachine", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- Added by ItemGenerator
    { item="Base.Mov_RedWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_YellowModernChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenStool", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ConcreteMixer", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ConcreteRoadBlock", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PalletBricks", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- Added by ItemGenerator
    { item="Base.Animal", basePrice=10, tags={"Misc.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.x2Scope", basePrice=18, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.x4Scope", basePrice=14, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.x8Scope", basePrice=7, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AmmoStraps", basePrice=3, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TritiumSights", basePrice=42, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RecoilPad", basePrice=17, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Laser", basePrice=7, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RedDot", basePrice=11, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ChokeTubeFull", basePrice=37, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChokeTubeImproved", basePrice=37, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pocketwatch", basePrice=9, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.AlarmClock2", basePrice=6, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CowLeather_Simmental_Fur_Tan", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Medium", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Small", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DeerLeather_Fur_Tan", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.DeerLeather_Fur_Tan_Small", basePrice=2, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DappleDeerHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.DeerHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CowHide", basePrice=1, tags={"Misc.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Hematite", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HematiteLarge", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Malachite", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MalachiteLarge", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBellows", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_UprightCoffin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlatCoffin", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_KeyDuplicator", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BenchGrinder", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cow_Skull_Wall", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Bull_Skull_Wall", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Sheep_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Pig_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.DeerStag_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Antlers_Wall", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CampingTentKit2", basePrice=1, tags={"Misc.General", "Rarity.Common", "Theme.Survival"}, stockRange={min=0, max=2} },
    { item="Base.ImprovisedTentKit", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.HideTent", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SleepingBag_RedPlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_BluePlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Green", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_GreenPlaid", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Camo", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Green", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Blue", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Cheap_Green2", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Spiffo", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_HighQuality_Brown", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SleepingBag_Hide", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentYellow", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentBlue", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentBrown", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TentGreen", basePrice=1, tags={"Misc.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Moveable", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BacklessWoodenBench", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeachChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BluePlasticChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueRattanChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkBlueChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyBlackChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyWhiteChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FoldingChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyComfyChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalStool", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakBench", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OfficeChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeFuton", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeModernChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PileOCrepeChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleRattanChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedChair", basePrice=2, tags={"Misc.General", "Rarity.Common"}, stockRange={min=3, max=15} },


}

return DT_General.items
