-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Head] [Rarity.Common] (137 items)
    { item="Base.Hat_Bandana", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Bandana_Green", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTied", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTied_Green", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTiedTINT", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTINT", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BaseballCap", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_3N", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_3N_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanEats", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanEats_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanTire", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanTire_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BodyChisel", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BodyChisel_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_FireDept", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_FireDept_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil02", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil02_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Gas2Go", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Gas2Go_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_HuntingCamo", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_HuntingCamo_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_JaysChicken", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_JaysChicken_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KnoxDistillery", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KnoxDistillery_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KYTransit", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KYTransit_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LBMW", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LBMW_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LSU", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LSU_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_MassGenfac", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_MassGenfac_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_PizzaWhirled", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_PizzaWhirled_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Sheriff", basePrice=55, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=11} },
    { item="Base.Hat_BaseballCap_Sheriff_Reverse", basePrice=55, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=11} },
    { item="Base.Hat_BaseballCap_Spiffos", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Spiffos_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SpiffosLogo", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SpiffosLogo_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SWAT", basePrice=35, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SWAT_Reverse", basePrice=35, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_USL", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_USL_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapBlue", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapBlue_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapGreen", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapGreen_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Red", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Red_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapRed", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapRed_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapTINT", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapTINT_Reverse", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Beany", basePrice=26, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Beret", basePrice=21, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_CamoGreen", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_DesertCamo", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_DesertCamoNew", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_MiliusCamo", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_OliveDrab", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_TigerStripeCamo", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BucketHat", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BucketHatFishing", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_ChefHat", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Cowboy", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Angus", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Black", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_CowHide", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Holstein", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Plastic", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Simmental", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_White", basePrice=23, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_EarMuff_Protectors", basePrice=24, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_EarMuffs", basePrice=25, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood_IceCream", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood_Spiffo", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Fedora", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Fedora_Delmonte", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FishermanRainHat", basePrice=31, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_GolfHat", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_GolfHatTINT", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HeadMirrorDOWN", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HeadMirrorUP", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HideHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Jay", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_LeatherStripTied", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_NewspaperHat", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PartyHat_Stars", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PartyHat_TINT", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PeakedCapYacht", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Pilgrim", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Pirate", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Raccoon", basePrice=31, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=4} },
    { item="Base.Hat_RagBandana", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_RagBandanaTied", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Ranger", basePrice=26, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SantaHat", basePrice=28, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_SantaHatGreen", basePrice=28, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Sheriff", basePrice=54, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=3, max=18} },
    { item="Base.Hat_ShowerCap", basePrice=18, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Spiffo", basePrice=31, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe_Black", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe_UncleSam", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_StrawHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SummerFlowerHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SummerHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SurgicalCap", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=3, max=17} },
    { item="Base.Hat_Sweatband", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_TarpHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_TinFoilHat", basePrice=19, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_WinterHat", basePrice=51, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_WinterHat_SheepSkin", basePrice=51, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Witch", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Wizard", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_WoolyHat", basePrice=34, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },

    -- [Clothing.Head] [Rarity.Rare] (34 items)
    { item="Base.Animal_BowtieGold", basePrice=171, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=4} },
    { item="Base.Animal_BowtieGreen", basePrice=49, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Animal_BowtieRed", basePrice=49, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Hat_Antlers", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_BunnyEarsBlack", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_BunnyEarsWhite", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_DeerHeadress", basePrice=39, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_FurryEars", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_GoldStar", basePrice=148, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Hat_HeadSack_Burlap", basePrice=58, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Cotton", basePrice=56, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Garbage", basePrice=56, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Hide", basePrice=58, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Tarp", basePrice=58, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_JokeArrow", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_JokeKnife", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_SantaHatDebug", basePrice=49, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Burlap", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Cotton", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Green", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Burlap", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Cotton", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Green", basePrice=62, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_WeddingVeil", basePrice=34, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.HazmatSuit", basePrice=57, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hoodie_Hide_UP", basePrice=61, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_UP", basePrice=49, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.HoodieUP_WhiteTINT", basePrice=49, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGarbageBag", basePrice=44, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGreen", basePrice=46, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoTarp", basePrice=46, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoYellow", basePrice=46, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },

    -- [Clothing.Head] [Rarity.Uncommon] (9 items)
    { item="Base.Hat_ArmyWWII", basePrice=180, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Police", basePrice=68, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCap_Police_Reverse", basePrice=68, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCapArmy", basePrice=78, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCapArmy_Reverse", basePrice=78, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BeretArmy", basePrice=81, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_PeakedCapArmy", basePrice=80, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_Police", basePrice=67, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=2, max=15} },
    { item="Base.Hat_Police_Grey", basePrice=67, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=2, max=15} },
})

print("[DynamicTrading] Head Registry Complete")
