-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Outerwear] [Rarity.Rare] (100 items)
    { item="Base.Apron_BBQ", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Black", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Garbage", basePrice=37, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Hide", basePrice=49, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_IceCream", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Jay", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Leather", basePrice=92, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PileOCrepe", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PizzaWhirled", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Spiffos", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Tarp", basePrice=39, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_White", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_WhiteTEXTURE", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.BlackRobe", basePrice=38, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_AngusCalfHide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_AngusHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoDesert", basePrice=180, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoDesertNew", basePrice=180, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoGreen", basePrice=185, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoMilius", basePrice=180, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoTigerStripe", basePrice=180, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoUrban", basePrice=185, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyOliveDrab", basePrice=185, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Black", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Chef", basePrice=38, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_CoatArmy", basePrice=179, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_CowHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_DeerHide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Hide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinCalfHide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HuntingCamo", basePrice=108, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather_Punk", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBarrelDogs", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBlack", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBrown", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherIronRodent", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherWildRacoons", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_NavyBlue", basePrice=98, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded", basePrice=67, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamo", basePrice=67, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamoDOWN", basePrice=69, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_PaddedDOWN", basePrice=69, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Police", basePrice=155, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Ranger", basePrice=102, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SheepSkin", basePrice=107, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Shellsuit_Black", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Blue", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Green", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Pink", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Teal", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_TINT", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Sheriff", basePrice=155, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_SimmentalCalfHide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SimmentalHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Varsity", basePrice=64, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_WhiteTINT", basePrice=72, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusCalfHide", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Black", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_CowHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Doctor", basePrice=71, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Clothing.ScratchResistant", "Clothing.Medical"}, stockRange={min=0, max=1} },
    { item="Base.JacketLong_Hide", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinCalfHide", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Random", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Santa", basePrice=78, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SantaGreen", basePrice=78, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SheepSkin", basePrice=65, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalCalfHide", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalHide", basePrice=101, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.LongCoat_Bathrobe", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.LongCoat_Hide", basePrice=58, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGarbageBagDOWN", basePrice=45, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGreenDOWN", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoTarpDOWN", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoYellowDOWN", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Suit_Jacket", basePrice=52, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_Jacket_White", basePrice=52, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_JacketTINT", basePrice=52, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Foreman", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_HighViz", basePrice=41, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Camo", basePrice=62, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_CamoGreen", basePrice=62, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Grey", basePrice=65, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Khaki", basePrice=65, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Orange", basePrice=62, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_BarrelDogs", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Biker", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_IronRodents", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Veteran", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_WildRaccoons", basePrice=89, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_SheepSkin", basePrice=116, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Trucker", basePrice=65, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat", basePrice=43, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat_GigaMart", basePrice=43, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_WaistcoatTINT", basePrice=43, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.WeddingJacket", basePrice=46, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
})

print("[DynamicTrading] Outerwear Registry Complete")
