require "DT/Common/GeolocatorDefinitions/DT_GeolocatorDefinitions"

DT_GeolocatorSystem = DT_GeolocatorSystem or {}

DT_GeolocatorSystem.RegisterRegionDefinition({
    id = "Maplewood",
    mod = "Maplewood",
    isVanilla = false,
    activation = {
        modIDs = {
            "Maplewood",
        },
        mapFolders = {
            "Maplewood",
        },
        worldMaps = {
            "Maplewood",
        },
    },
    locations = {
        {
            id = "maplewood",
            longName = "Maplewood, KY",
            shortName = "Maplewood",
            startX = 7800,
            endX = 10200,
            startY = 8100,
            endY = 10500,
        },
    },
    towns = {
        {
            name = "Maplewood",
            minX = 7800,
            maxX = 10200,
            minY = 8100,
            maxY = 10500,
        },
    },
    counties = {
        {
            name = "Maplewood",
            bounds = {
                minX = 7800,
                maxX = 10200,
                minY = 8100,
                maxY = 10500,
            },
            towns = {
                "Maplewood",
            },
        },
    },
    pois = {
        {
            id = "maplewood",
            name = "Maplewood",
            type = "Label",
            x = 8273,
            y = 8560,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-annotations",
                symbolType = "text-town",
                label_method = "annotation",
            },
        },
        {
            id = "zombiestype_trailer_park_8350_8600",
            name = "Trailer Park",
            type = "Landmark",
            x = 8350,
            y = 8600,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "TrailerPark",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_pharmacist_8191_8546",
            name = "Pharmacist",
            type = "Landmark",
            x = 8191,
            y = 8546,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "Pharmacist",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_street_sports_8170_8471",
            name = "Street Sports",
            type = "Landmark",
            x = 8170,
            y = 8471,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "StreetSports",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_bank_8248_8582",
            name = "Bank",
            type = "Landmark",
            x = 8248,
            y = 8582,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "Bank",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_car_repair_8203_8611",
            name = "Car Repair",
            type = "Landmark",
            x = 8203,
            y = 8611,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "CarRepair",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_fire_dept_8159_8584",
            name = "Fire Dept",
            type = "Landmark",
            x = 8159,
            y = 8584,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "FireDept",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_thunder_gas_8297_8577",
            name = "Thunder Gas",
            type = "Landmark",
            x = 8297,
            y = 8577,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "ThunderGas",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_athletic_8221_8581",
            name = "Athletic",
            type = "Landmark",
            x = 8221,
            y = 8581,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "Athletic",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_bar_8201_8578",
            name = "Bar",
            type = "Landmark",
            x = 8201,
            y = 8578,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "Bar",
                label_method = "object-name",
            },
        },
        {
            id = "ranch_pig_8197_8673",
            name = "Pig",
            type = "Landmark",
            x = 8197,
            y = 8673,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "Ranch",
                originalName = "pig",
                label_method = "object-name",
            },
        },
        {
            id = "ranch_chicken_8207_8479",
            name = "Chicken",
            type = "Landmark",
            x = 8207,
            y = 8479,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "Ranch",
                originalName = "chicken",
                label_method = "object-name",
            },
        },
        {
            id = "zombiestype_police_8305_8544",
            name = "Police",
            type = "Landmark",
            x = 8305,
            y = 8544,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "objects-lua",
                objectType = "ZombiesType",
                originalName = "Police",
                label_method = "object-name",
            },
        },
        {
            id = "retail_2_8297_5_8454_5",
            name = "Auto Garage",
            type = "Retail",
            x = 8297,
            y = 8454,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "retail",
                featureCount = 6,
                area = 1975,
                clusterSize = "medium",
                label_method = "deterministic",
                dominantBuilding = "Residential",
                dominantRoomTone = "Garage",
            },
        },
        {
            id = "retail_5_8256_0_8411_5",
            name = "Auto Garage",
            type = "Retail",
            x = 8256,
            y = 8411,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "retail",
                featureCount = 1,
                area = 20,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "Residential",
                dominantRoomTone = "Garage",
            },
        },
        {
            id = "retail_6_8373_5_8484_0",
            name = "Auto Garage",
            type = "Retail",
            x = 8373,
            y = 8484,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "retail",
                featureCount = 1,
                area = 20,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "Residential",
                dominantRoomTone = "Garage",
            },
        },
        {
            id = "retail_8_8297_0_8411_5",
            name = "Auto Garage",
            type = "Retail",
            x = 8297,
            y = 8411,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "retail",
                featureCount = 2,
                area = 80,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "Residential",
                dominantRoomTone = "Garage",
            },
        },
        {
            id = "retail_9_8376_0_8550_0",
            name = "Grocery Center",
            type = "Retail",
            x = 8376,
            y = 8550,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "retail",
                featureCount = 1,
                area = 32,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "RetailAndCommercial",
                dominantRoomTone = "Grocery",
            },
        },
        {
            id = "civic_14_8133_5_8531_5",
            name = "Church Grounds",
            type = "CommunityServices",
            x = 8133,
            y = 8531,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "civic",
                featureCount = 1,
                area = 253,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "CommunityServices",
                dominantRoomTone = "Church",
            },
        },
        {
            id = "industrial_24_8250_5_8667_5",
            name = "Industrial Yard",
            type = "Industrial",
            x = 8250,
            y = 8667,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "industrial",
                featureCount = 1,
                area = 9,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "Industrial",
                dominantRoomTone = "Shed",
            },
        },
        {
            id = "industrial_26_8389_5_8433_5",
            name = "Industrial Yard",
            type = "Industrial",
            x = 8389,
            y = 8433,
            town = "Maplewood",
            county = "Maplewood",
            metadata = {
                source = "worldmap-xml-cluster",
                bucket = "industrial",
                featureCount = 1,
                area = 15,
                clusterSize = "small",
                label_method = "deterministic",
                dominantBuilding = "Industrial",
                dominantRoomTone = "Shed",
            },
        },
    },
})
