-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.Canned] [Rarity.Rare] (91 items)
    { item="Base.CannedBellPepper", basePrice=294, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBellPepper_Open", basePrice=207, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBolognese", basePrice=198, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBolognese_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedBologneseOpen", basePrice=194, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBroccoli", basePrice=291, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBroccoli_Open", basePrice=203, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCabbage", basePrice=297, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCabbage_Open", basePrice=212, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrots", basePrice=287, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots2", basePrice=157, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCarrots_Open", basePrice=197, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrotsOpen", basePrice=145, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedChili", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedChili_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedChiliOpen", basePrice=158, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCorn", basePrice=168, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCorn_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeef", basePrice=205, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCornedBeef_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeefOpen", basePrice=196, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCornOpen", basePrice=160, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedEggplant", basePrice=296, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedEggplant_Open", basePrice=211, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedFruitBeverage", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedFruitCocktailOpen", basePrice=161, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedLeek", basePrice=294, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedLeek_Open", basePrice=208, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedMilk", basePrice=196, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup", basePrice=162, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedMushroomSoupOpen", basePrice=161, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.CannedPeaches", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeaches_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeachesOpen", basePrice=161, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPeas", basePrice=167, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeas_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeasOpen", basePrice=158, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPineapple", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPineapple_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPineappleOpen", basePrice=161, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotato", basePrice=294, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato2", basePrice=163, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPotato_Open", basePrice=208, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotatoOpen", basePrice=162, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRedRadish", basePrice=290, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRedRadish_Open", basePrice=202, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRoe", basePrice=292, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRoe_Open", basePrice=134, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedSardines", basePrice=163, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.CannedSardines_Box", basePrice=141, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedSardinesOpen", basePrice=149, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato", basePrice=292, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato2", basePrice=160, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedTomato_Open", basePrice=204, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedTomatoOpen", basePrice=151, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.cheese_powdered", basePrice=205, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Chocolate_Candy", basePrice=179, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=15} },
    { item="Base.DentedCan", basePrice=157, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DentedCan_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DentedCan_Open", basePrice=103, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.Dogfood", basePrice=196, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DogfoodOpen", basePrice=188, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.DriedApricots", basePrice=189, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.DriedBlackBeans", basePrice=222, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedChickpeas", basePrice=221, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedKidneyBeans", basePrice=222, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedLentils", basePrice=222, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedSplitPeas", basePrice=220, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedWhiteBeans", basePrice=221, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.HotdogPack", basePrice=184, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan", basePrice=157, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.MysteryCan_Open", basePrice=103, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.OpenBeans", basePrice=204, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.PoppyPodsDried", basePrice=143, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.RyeSheafDried", basePrice=153, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedBeans", basePrice=159, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TinnedBeans_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TinnedSoup", basePrice=161, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedSoup_Box", basePrice=137, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TinnedSoupOpen", basePrice=200, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.TunaTin", basePrice=171, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.TunaTinOpen", basePrice=162, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.WaterRationCan", basePrice=177, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.WheatSheafDried", basePrice=153, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
})

print("[DynamicTrading] Canned Registry Complete")
