-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Ingredient] [Rarity.Rare] (121 items)
    { item="Base.AligatorGar", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BaloneySlice", basePrice=80, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.BeanBowl", basePrice=99, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BlackCrappie", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Bluegill", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BrusselSprouts", basePrice=131, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BucketOfSoup", basePrice=250, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.BucketOfStew", basePrice=250, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Cauliflower", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecream", basePrice=134, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamToppings", basePrice=134, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle", basePrice=124, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps", basePrice=162, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps2", basePrice=162, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps3", basePrice=162, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps4", basePrice=162, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.DeadBird", basePrice=133, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadMouse", basePrice=110, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePups", basePrice=95, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePupsSkinned", basePrice=95, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMouseSkinned", basePrice=110, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadRabbit", basePrice=241, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.DeadRat", basePrice=163, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBaby", basePrice=113, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBabySkinned", basePrice=113, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatSkinned", basePrice=163, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadSquirrel", basePrice=205, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Dough", basePrice=184, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DoughnutFrosted", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutJelly", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutPlain", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Egg", basePrice=125, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Eggplant", basePrice=138, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.FrenchFries", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.FreshwaterDrum", basePrice=146, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.FudgeePop", basePrice=144, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Greenpeas", basePrice=94, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.HalloweenPumpkin", basePrice=228, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Ham", basePrice=262, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=4} },
    { item="Base.HamSlice", basePrice=115, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hotdog_single", basePrice=108, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Icecream", basePrice=216, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich", basePrice=125, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Kale", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LargemouthBass", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Lobster", basePrice=185, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Marshmallows", basePrice=78, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.MushroomGeneric1", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric2", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric3", basePrice=116, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric4", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric5", basePrice=116, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric6", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric7", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomsButton", basePrice=95, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Muskellunge", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Mussels", basePrice=79, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MuttonChop", basePrice=166, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipe", basePrice=119, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipeForged", basePrice=119, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Oysters", basePrice=79, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Peanuts", basePrice=89, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pie", basePrice=196, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.PieDough", basePrice=115, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.PieWholeRaw", basePrice=126, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PizzaRecipe", basePrice=234, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PizzaWhole", basePrice=279, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Popsicle", basePrice=143, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.PotForgedSoupRecipe", basePrice=250, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotForgedStew", basePrice=254, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoup", basePrice=214, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoupRecipe", basePrice=250, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfStew", basePrice=254, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Pretzel", basePrice=94, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pumpkin", basePrice=228, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PumpkinSliced", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PumpkinSmashed", basePrice=126, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.RamenBowl", basePrice=86, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.RatKing", basePrice=149, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.RefriedBeans", basePrice=86, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.SalamiSlice", basePrice=118, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Salmon", basePrice=167, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Sandwich", basePrice=119, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sauger", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Shrimp", basePrice=93, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFriedCraft", basePrice=107, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SmallmouthBass", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Smore", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SoupBowl", basePrice=120, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SoupBowlClay", basePrice=120, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Spinach", basePrice=97, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SpottedBass", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Squash", basePrice=153, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SquidCalamari", basePrice=94, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Steak", basePrice=209, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.StewBowl", basePrice=109, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StewBowlClay", basePrice=109, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StripedBass", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SugarBeet", basePrice=106, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SugarBeetPulpPot", basePrice=194, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.SugarBeetSugarPot", basePrice=165, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SugarBeetSyrupPot", basePrice=144, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.TatoDots", basePrice=111, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Toast", basePrice=108, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Tofu", basePrice=143, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TortillaChips", basePrice=151, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.TortillaChipsBaked", basePrice=120, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyEgg", basePrice=132, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyFillet", basePrice=203, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyLegs", basePrice=194, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyWhole", basePrice=277, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TurkeyWings", basePrice=165, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Turnip", basePrice=159, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TVDinner", basePrice=183, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Venison", basePrice=199, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Walleye", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteBass", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteCrappie", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WildEggs", basePrice=125, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.YellowPerch", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Zucchini", basePrice=141, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
})

print("[DynamicTrading] Cooking Registry Complete")
