-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Spice] [Rarity.Rare] (108 items)
    { item="Base.BaconBits", basePrice=68, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.BalsamicVinegar", basePrice=94, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Basil", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.BasilDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.BBQSauce", basePrice=117, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.BellPepper", basePrice=81, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.BouillonCube", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Butter", basePrice=138, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Candycane", basePrice=70, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Capers", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Chamomile", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ChamomileDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Chives", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ChivesDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cilantro", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.CilantroDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CilantroSeed", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.Cinnamon", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cornflour2", basePrice=85, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Cornmeal2", basePrice=70, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Dip_NachoCheese", basePrice=194, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dip_Ranch", basePrice=198, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dip_Salsa", basePrice=164, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.FishRoe", basePrice=90, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.FlaxSeed", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.Flour2", basePrice=86, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FourLeafClover", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Garlic", basePrice=83, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GingerPickled", basePrice=84, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GingerRoot", basePrice=80, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Gravy", basePrice=79, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GreenOnions", basePrice=81, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Guacamole", basePrice=81, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Honey", basePrice=119, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Hotsauce", basePrice=106, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Ketchup", basePrice=103, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Lard", basePrice=150, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Lavender", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LavenderPetalsDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Lemon", basePrice=87, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LemonGrass", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Lime", basePrice=87, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MapleSyrup", basePrice=131, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Margarine", basePrice=139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Marigold", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MarigoldDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Marinara", basePrice=82, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.MayonnaiseFull", basePrice=162, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.MintHerb", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MintHerbDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Mustard", basePrice=109, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Nettles", basePrice=79, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OilOlive", basePrice=125, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.OilVegetable", basePrice=119, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Olives", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Oregano", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OreganoDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Parsley", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ParsleyDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pepper", basePrice=76, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.PepperHabanero", basePrice=73, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PepperHabaneroDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PepperJalapeno", basePrice=73, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PepperJalapenoDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Peppermint", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pepperoni", basePrice=102, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Pickles", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PoppySeed", basePrice=70, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.PowderedGarlic", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.PowderedOnion", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.PumpkinSeed", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.RemouladeFull", basePrice=128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.RiceVinegar", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.Rosehips", basePrice=81, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Rosemary", basePrice=79, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.RosemaryDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RosePetalsDried", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Roses", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sage", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SageDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Salt", basePrice=76, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Sausage", basePrice=84, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Seasoning_Basil", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Chives", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Cilantro", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Oregano", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Parsley", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Rosemary", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Sage", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Thyme", basePrice=66, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.SeasoningSalt", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seaweed", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.SesameOil", basePrice=68, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.SourCream", basePrice=118, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Soysauce", basePrice=87, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Sugar", basePrice=166, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarBrown", basePrice=118, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarCubes", basePrice=71, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=25} },
    { item="Base.SugarPacket", basePrice=67, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=25} },
    { item="Base.SunflowerSeeds", basePrice=67, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Thistle", basePrice=79, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Thyme", basePrice=75, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ThymeDried", basePrice=65, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.TomatoPaste", basePrice=78, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Vinegar2", basePrice=110, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Vinegar_Jug", basePrice=128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Violets", basePrice=76, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Wasabi", basePrice=92, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Spice Registry Complete")
