-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.Canned] [Rarity.Rare] (91 items)
    { item="Base.CannedBellPepper", basePrice=89, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBellPepper_Open", basePrice=47, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBolognese", basePrice=72, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBolognese_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedBologneseOpen", basePrice=106, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBroccoli", basePrice=83, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBroccoli_Open", basePrice=43, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCabbage", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCabbage_Open", basePrice=48, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots", basePrice=77, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots2", basePrice=66, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCarrots_Open", basePrice=39, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrotsOpen", basePrice=85, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedChili", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedChili_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedChiliOpen", basePrice=92, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCorn", basePrice=70, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCorn_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeef", basePrice=75, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCornedBeef_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeefOpen", basePrice=108, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCornOpen", basePrice=95, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedEggplant", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedEggplant_Open", basePrice=48, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitBeverage", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedFruitCocktailOpen", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedLeek", basePrice=89, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedLeek_Open", basePrice=47, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMilk", basePrice=72, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedMushroomSoupOpen", basePrice=85, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeaches", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeaches_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeachesOpen", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeas", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeas_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeasOpen", basePrice=93, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPineapple", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPineapple_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPineappleOpen", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato", basePrice=89, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato2", basePrice=68, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPotato_Open", basePrice=47, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotatoOpen", basePrice=97, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRedRadish", basePrice=83, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRedRadish_Open", basePrice=42, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRoe", basePrice=87, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRoe_Open", basePrice=12, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedSardines", basePrice=159, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.CannedSardines_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedSardinesOpen", basePrice=206, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.CannedTomato", basePrice=87, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato2", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedTomato_Open", basePrice=46, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomatoOpen", basePrice=89, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.cheese_powdered", basePrice=29, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Chocolate_Candy", basePrice=41, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.DentedCan", basePrice=65, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DentedCan_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DentedCan_Open", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dogfood", basePrice=72, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DogfoodOpen", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=5} },
    { item="Base.DriedApricots", basePrice=78, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.DriedBlackBeans", basePrice=55, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DriedChickpeas", basePrice=54, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DriedKidneyBeans", basePrice=56, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DriedLentils", basePrice=55, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DriedSplitPeas", basePrice=51, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DriedWhiteBeans", basePrice=54, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.HotdogPack", basePrice=25, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan", basePrice=65, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.MysteryCan_Open", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.OpenBeans", basePrice=74, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=5} },
    { item="Base.PoppyPodsDried", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RyeSheafDried", basePrice=5, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedBeans", basePrice=68, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedBeans_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TinnedSoup", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedSoup_Box", basePrice=1, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TinnedSoupOpen", basePrice=104, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TunaTin", basePrice=166, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TunaTinOpen", basePrice=225, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.WaterRationCan", basePrice=65, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.WheatSheafDried", basePrice=5, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
})

print("[DynamicTrading] Canned Registry Complete")
