-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.Canned] [Rarity.Rare] (91 items)
    { item="Base.CannedBellPepper", basePrice=2586, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBellPepper_Open", basePrice=1858, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBolognese", basePrice=2490, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBolognese_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedBologneseOpen", basePrice=1844, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBroccoli", basePrice=2584, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBroccoli_Open", basePrice=1854, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCabbage", basePrice=2589, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCabbage_Open", basePrice=1862, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrots", basePrice=2579, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots2", basePrice=2048, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCarrots_Open", basePrice=1847, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrotsOpen", basePrice=1507, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedChili", basePrice=2057, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedChili_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedChiliOpen", basePrice=1519, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCorn", basePrice=2059, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCorn_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeef", basePrice=2497, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCornedBeef_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeefOpen", basePrice=1846, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCornOpen", basePrice=1521, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedEggplant", basePrice=2589, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedEggplant_Open", basePrice=1862, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedFruitBeverage", basePrice=2057, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail", basePrice=2057, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedFruitCocktailOpen", basePrice=1523, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedLeek", basePrice=2587, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedLeek_Open", basePrice=1859, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedMilk", basePrice=2488, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup", basePrice=2053, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedMushroomSoupOpen", basePrice=1522, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.CannedPeaches", basePrice=2057, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeaches_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeachesOpen", basePrice=1523, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPeas", basePrice=2058, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeas_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeasOpen", basePrice=1519, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPineapple", basePrice=2057, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPineapple_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPineappleOpen", basePrice=1523, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotato", basePrice=2587, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato2", basePrice=2054, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPotato_Open", basePrice=1858, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotatoOpen", basePrice=1524, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRedRadish", basePrice=2583, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRedRadish_Open", basePrice=1853, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRoe", basePrice=2584, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRoe_Open", basePrice=1496, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedSardines", basePrice=2054, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.CannedSardines_Box", basePrice=2032, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedSardinesOpen", basePrice=1511, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato", basePrice=2584, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato2", basePrice=2051, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedTomato_Open", basePrice=1854, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedTomatoOpen", basePrice=1513, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.cheese_powdered", basePrice=2096, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Chocolate_Candy", basePrice=2070, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=15} },
    { item="Base.DentedCan", basePrice=2047, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DentedCan_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DentedCan_Open", basePrice=1465, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.Dogfood", basePrice=2489, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DogfoodOpen", basePrice=1838, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.DriedApricots", basePrice=2080, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.DriedBlackBeans", basePrice=2113, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedChickpeas", basePrice=2112, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedKidneyBeans", basePrice=2113, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedLentils", basePrice=2112, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedSplitPeas", basePrice=2111, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedWhiteBeans", basePrice=2112, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.HotdogPack", basePrice=2075, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan", basePrice=2047, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.MysteryCan_Open", basePrice=1465, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.OpenBeans", basePrice=2496, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.PoppyPodsDried", basePrice=2034, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.RyeSheafDried", basePrice=2044, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedBeans", basePrice=2050, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TinnedBeans_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TinnedSoup", basePrice=2052, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedSoup_Box", basePrice=2027, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TinnedSoupOpen", basePrice=1851, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.TunaTin", basePrice=2062, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.TunaTinOpen", basePrice=1523, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.WaterRationCan", basePrice=2068, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.WheatSheafDried", basePrice=2044, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=5} },
})

print("[DynamicTrading] Canned Registry Complete")
