-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Ingredient] [Rarity.Rare] (121 items)
    { item="Base.AligatorGar", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BaloneySlice", basePrice=1144, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.BeanBowl", basePrice=1565, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BlackCrappie", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Bluegill", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BrusselSprouts", basePrice=1196, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BucketOfSoup", basePrice=1716, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.BucketOfStew", basePrice=1716, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Cauliflower", basePrice=1176, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecream", basePrice=1600, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamToppings", basePrice=1600, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle", basePrice=1188, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps", basePrice=1628, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps2", basePrice=1628, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps3", basePrice=1628, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps4", basePrice=1628, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.DeadBird", basePrice=1198, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadMouse", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePups", basePrice=1159, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePupsSkinned", basePrice=1159, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMouseSkinned", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadRabbit", basePrice=1305, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.DeadRat", basePrice=1629, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBaby", basePrice=1177, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBabySkinned", basePrice=1177, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatSkinned", basePrice=1629, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadSquirrel", basePrice=1671, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Dough", basePrice=1650, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DoughnutFrosted", basePrice=1168, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutJelly", basePrice=1168, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutPlain", basePrice=1168, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Egg", basePrice=1189, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Eggplant", basePrice=1202, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.FrenchFries", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.FreshwaterDrum", basePrice=1210, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.FudgeePop", basePrice=1208, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Greenpeas", basePrice=1158, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.HalloweenPumpkin", basePrice=1694, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Ham", basePrice=1326, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=4} },
    { item="Base.HamSlice", basePrice=1179, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hotdog_single", basePrice=1172, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Icecream", basePrice=1280, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich", basePrice=1189, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Kale", basePrice=1201, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LargemouthBass", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Lobster", basePrice=1651, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Marshmallows", basePrice=1142, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.MushroomGeneric1", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric2", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric3", basePrice=1180, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric4", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric5", basePrice=1180, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric6", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric7", basePrice=1176, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomsButton", basePrice=1160, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Muskellunge", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Mussels", basePrice=1143, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MuttonChop", basePrice=1632, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipe", basePrice=1183, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipeForged", basePrice=1183, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Oysters", basePrice=1143, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Peanuts", basePrice=1154, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pie", basePrice=1662, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.PieDough", basePrice=1581, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.PieWholeRaw", basePrice=1190, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PizzaRecipe", basePrice=1298, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PizzaWhole", basePrice=1344, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Popsicle", basePrice=1208, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.PotForgedSoupRecipe", basePrice=1716, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotForgedStew", basePrice=1720, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoup", basePrice=1679, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoupRecipe", basePrice=1716, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfStew", basePrice=1720, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Pretzel", basePrice=1158, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pumpkin", basePrice=1694, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PumpkinSliced", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PumpkinSmashed", basePrice=1191, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.RamenBowl", basePrice=1151, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.RatKing", basePrice=1213, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.RefriedBeans", basePrice=1150, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.SalamiSlice", basePrice=1182, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Salmon", basePrice=1633, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Sandwich", basePrice=1183, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sauger", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Shrimp", basePrice=1157, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFriedCraft", basePrice=1172, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SmallmouthBass", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Smore", basePrice=1201, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SoupBowl", basePrice=1184, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SoupBowlClay", basePrice=1184, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Spinach", basePrice=1161, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SpottedBass", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Squash", basePrice=1218, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SquidCalamari", basePrice=1158, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Steak", basePrice=1675, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.StewBowl", basePrice=1173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StewBowlClay", basePrice=1173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StripedBass", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SugarBeet", basePrice=1170, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SugarBeetPulpPot", basePrice=1660, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.SugarBeetSugarPot", basePrice=1631, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SugarBeetSyrupPot", basePrice=1610, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.TatoDots", basePrice=1175, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Toast", basePrice=1172, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Tofu", basePrice=1207, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TortillaChips", basePrice=1617, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.TortillaChipsBaked", basePrice=1184, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyEgg", basePrice=1196, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyFillet", basePrice=1669, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyLegs", basePrice=1660, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyWhole", basePrice=1341, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TurkeyWings", basePrice=1631, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Turnip", basePrice=1224, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TVDinner", basePrice=1648, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Venison", basePrice=1263, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Walleye", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteBass", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteCrappie", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WildEggs", basePrice=1189, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.YellowPerch", basePrice=1181, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Zucchini", basePrice=1206, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
})

print("[DynamicTrading] Cooking Registry Complete")
