-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.Canned] [Rarity.Rare] (91 items)
    { item="Base.CannedBellPepper", basePrice=173, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBellPepper_Open", basePrice=120, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBolognese", basePrice=78, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBolognese_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedBologneseOpen", basePrice=107, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedBroccoli", basePrice=171, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedBroccoli_Open", basePrice=116, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCabbage", basePrice=176, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCabbage_Open", basePrice=125, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrots", basePrice=167, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots2", basePrice=58, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCarrots_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCarrots_Open", basePrice=110, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCarrotsOpen", basePrice=74, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedChili", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedChili_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedChiliOpen", basePrice=87, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCorn", basePrice=69, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCorn_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeef", basePrice=84, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedCornedBeef_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedCornedBeefOpen", basePrice=109, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedCornOpen", basePrice=89, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedEggplant", basePrice=176, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedEggplant_Open", basePrice=125, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedFruitBeverage", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedFruitCocktail_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedFruitCocktailOpen", basePrice=90, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedLeek", basePrice=174, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedLeek_Open", basePrice=121, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedMilk", basePrice=75, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup", basePrice=64, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedMushroomSoup_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedMushroomSoupOpen", basePrice=90, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.CannedPeaches", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeaches_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeachesOpen", basePrice=90, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPeas", basePrice=68, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPeas_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPeasOpen", basePrice=87, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPineapple", basePrice=67, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPineapple_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPineappleOpen", basePrice=90, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotato", basePrice=174, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato2", basePrice=64, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedPotato_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedPotato_Open", basePrice=121, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedPotatoOpen", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRedRadish", basePrice=170, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRedRadish_Open", basePrice=115, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedRoe", basePrice=171, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedRoe_Open", basePrice=63, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedSardines", basePrice=64, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.CannedSardines_Box", basePrice=42, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedSardinesOpen", basePrice=78, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato", basePrice=171, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato2", basePrice=61, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.CannedTomato_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CannedTomato_Open", basePrice=117, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.CannedTomatoOpen", basePrice=80, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.cheese_powdered", basePrice=107, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Chocolate_Candy", basePrice=81, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=15} },
    { item="Base.DentedCan", basePrice=58, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DentedCan_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.DentedCan_Open", basePrice=32, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.Dogfood", basePrice=76, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=5} },
    { item="Base.DogfoodOpen", basePrice=101, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.DriedApricots", basePrice=90, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.DriedBlackBeans", basePrice=123, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedChickpeas", basePrice=123, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedKidneyBeans", basePrice=123, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedLentils", basePrice=123, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedSplitPeas", basePrice=122, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DriedWhiteBeans", basePrice=123, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.HotdogPack", basePrice=86, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan", basePrice=58, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.MysteryCan_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.MysteryCan_Open", basePrice=32, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=9} },
    { item="Base.OpenBeans", basePrice=83, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.PoppyPodsDried", basePrice=45, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.RyeSheafDried", basePrice=55, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedBeans", basePrice=61, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TinnedBeans_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TinnedSoup", basePrice=63, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.TinnedSoup_Box", basePrice=38, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TinnedSoupOpen", basePrice=114, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.TunaTin", basePrice=72, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=8} },
    { item="Base.TunaTinOpen", basePrice=91, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
    { item="Base.WaterRationCan", basePrice=78, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.WheatSheafDried", basePrice=55, tags={"Food.NonPerishable.Canned", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=5} },
})

print("[DynamicTrading] Canned Registry Complete")
