-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Ingredient] [Rarity.Rare] (127 items)
    { item="Base.AligatorGar", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.BaloneySlice", basePrice=69, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.BeanBowl", basePrice=5, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.BlackCrappie", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Bluegill", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.BrusselSprouts", basePrice=9, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.BucketOfSoup", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.BucketOfStew", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.CanPipe_Tobacco", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cauliflower", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Cigar", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.CigaretteRolled", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.CigaretteSingle", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.Cigarillo", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.ConeIcecream", basePrice=86, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ConeIcecreamToppings", basePrice=86, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Creamocle", basePrice=113, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Crisps", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Crisps2", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Crisps3", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Crisps4", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.DeadBird", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.DeadMouse", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=20} },
    { item="Base.DeadMousePups", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=20} },
    { item="Base.DeadMousePupsSkinned", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=20} },
    { item="Base.DeadMouseSkinned", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=20} },
    { item="Base.DeadRabbit", basePrice=28, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.DeadRat", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.DeadRatBaby", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.DeadRatBabySkinned", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.DeadRatSkinned", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.DeadSquirrel", basePrice=2, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Dough", basePrice=99, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutFrosted", basePrice=71, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.DoughnutJelly", basePrice=71, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.DoughnutPlain", basePrice=71, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Egg", basePrice=99, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Eggplant", basePrice=18, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.FrenchFries", basePrice=58, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.FreshwaterDrum", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.FudgeePop", basePrice=113, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Greenpeas", basePrice=29, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.HalloweenPumpkin", basePrice=34, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.Ham", basePrice=94, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=4} },
    { item="Base.HamSlice", basePrice=61, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Hotdog_single", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Icecream", basePrice=244, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=10} },
    { item="Base.IcecreamSandwich", basePrice=115, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Kale", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.LargemouthBass", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Lobster", basePrice=103, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Marshmallows", basePrice=36, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric1", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric2", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric3", basePrice=73, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric4", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric5", basePrice=73, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric6", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomGeneric7", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MushroomsButton", basePrice=36, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Muskellunge", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Mussels", basePrice=43, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MuttonChop", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OmeletteRecipe", basePrice=34, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OmeletteRecipeForged", basePrice=34, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Oysters", basePrice=43, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Peanuts", basePrice=41, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Pie", basePrice=73, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PieDough", basePrice=25, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PieWholeRaw", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.PizzaRecipe", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.PizzaWhole", basePrice=128, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Popsicle", basePrice=112, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PotForgedSoupRecipe", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.PotForgedStew", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.PotOfSoup", basePrice=18, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.PotOfSoupRecipe", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.PotOfStew", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Pretzel", basePrice=107, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Pumpkin", basePrice=34, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.PumpkinSliced", basePrice=87, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PumpkinSmashed", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.RamenBowl", basePrice=12, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.RatKing", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.RefriedBeans", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SalamiSlice", basePrice=126, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.Salmon", basePrice=105, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sandwich", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Sauger", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Shrimp", basePrice=82, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ShrimpFriedCraft", basePrice=121, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SmallmouthBass", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SmokingPipe_Tobacco", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Smore", basePrice=116, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SoupBowl", basePrice=26, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SoupBowlClay", basePrice=26, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Spinach", basePrice=49, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SpottedBass", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Squash", basePrice=21, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SquidCalamari", basePrice=83, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Steak", basePrice=134, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.StewBowl", basePrice=20, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.StewBowlClay", basePrice=20, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.StripedBass", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SugarBeet", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.SugarBeetPulpPot", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.SugarBeetSugarPot", basePrice=13, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SugarBeetSyrupPot", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.TatoDots", basePrice=58, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Toast", basePrice=79, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Tofu", basePrice=75, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TortillaChips", basePrice=124, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.TortillaChipsBaked", basePrice=76, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.TurkeyEgg", basePrice=120, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.TurkeyFillet", basePrice=165, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyLegs", basePrice=141, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyWhole", basePrice=202, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=4} },
    { item="Base.TurkeyWings", basePrice=103, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Turnip", basePrice=307, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.TVDinner", basePrice=3, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Venison", basePrice=171, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Walleye", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.WhiteBass", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.WhiteCrappie", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.WildEggs", basePrice=99, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.YellowPerch", basePrice=1, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Zucchini", basePrice=60, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Cooking Registry Complete")
