-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Ingredient] [Rarity.Rare] (121 items)
    { item="Base.AligatorGar", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BaloneySlice", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.BeanBowl", basePrice=22, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BlackCrappie", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Bluegill", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.BrusselSprouts", basePrice=76, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.BucketOfSoup", basePrice=173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.BucketOfStew", basePrice=173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Cauliflower", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecream", basePrice=57, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamToppings", basePrice=57, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle", basePrice=69, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps", basePrice=85, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps2", basePrice=85, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps3", basePrice=85, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Crisps4", basePrice=85, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.DeadBird", basePrice=78, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadMouse", basePrice=55, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePups", basePrice=40, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMousePupsSkinned", basePrice=40, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadMouseSkinned", basePrice=55, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.DeadRabbit", basePrice=186, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.DeadRat", basePrice=87, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBaby", basePrice=58, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatBabySkinned", basePrice=58, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadRatSkinned", basePrice=87, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.DeadSquirrel", basePrice=129, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Dough", basePrice=107, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.DoughnutFrosted", basePrice=48, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutJelly", basePrice=48, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DoughnutPlain", basePrice=48, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Egg", basePrice=70, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Eggplant", basePrice=82, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.FrenchFries", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.FreshwaterDrum", basePrice=91, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.FudgeePop", basePrice=89, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Greenpeas", basePrice=39, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.HalloweenPumpkin", basePrice=151, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Ham", basePrice=207, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=4} },
    { item="Base.HamSlice", basePrice=60, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hotdog_single", basePrice=53, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Icecream", basePrice=161, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich", basePrice=70, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Kale", basePrice=82, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LargemouthBass", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Lobster", basePrice=108, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Marshmallows", basePrice=23, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.MushroomGeneric1", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric2", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric3", basePrice=61, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric4", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric5", basePrice=61, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric6", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomGeneric7", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MushroomsButton", basePrice=40, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Muskellunge", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Mussels", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MuttonChop", basePrice=89, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipe", basePrice=64, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.OmeletteRecipeForged", basePrice=64, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Oysters", basePrice=24, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Peanuts", basePrice=34, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pie", basePrice=119, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.PieDough", basePrice=39, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.PieWholeRaw", basePrice=71, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PizzaRecipe", basePrice=179, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PizzaWhole", basePrice=224, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Popsicle", basePrice=88, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.PotForgedSoupRecipe", basePrice=173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotForgedStew", basePrice=177, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoup", basePrice=137, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfSoupRecipe", basePrice=173, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.PotOfStew", basePrice=177, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=1} },
    { item="Base.Pretzel", basePrice=39, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pumpkin", basePrice=151, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.PumpkinSliced", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PumpkinSmashed", basePrice=71, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.RamenBowl", basePrice=31, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.RatKing", basePrice=93, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=4} },
    { item="Base.RefriedBeans", basePrice=30, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.SalamiSlice", basePrice=63, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Salmon", basePrice=91, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Sandwich", basePrice=64, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sauger", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Shrimp", basePrice=38, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFriedCraft", basePrice=52, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SmallmouthBass", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Smore", basePrice=82, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SoupBowl", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SoupBowlClay", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Spinach", basePrice=42, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SpottedBass", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Squash", basePrice=98, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SquidCalamari", basePrice=39, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Steak", basePrice=132, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.StewBowl", basePrice=54, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StewBowlClay", basePrice=54, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.StripedBass", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.SugarBeet", basePrice=51, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SugarBeetPulpPot", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.SugarBeetSugarPot", basePrice=89, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=2} },
    { item="Base.SugarBeetSyrupPot", basePrice=67, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.TatoDots", basePrice=56, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Toast", basePrice=53, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Tofu", basePrice=88, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.TortillaChips", basePrice=74, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.TortillaChipsBaked", basePrice=65, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyEgg", basePrice=77, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TurkeyFillet", basePrice=126, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyLegs", basePrice=117, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TurkeyWhole", basePrice=222, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.TurkeyWings", basePrice=88, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Turnip", basePrice=104, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TVDinner", basePrice=106, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Venison", basePrice=143, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Walleye", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteBass", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WhiteCrappie", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.WildEggs", basePrice=70, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.YellowPerch", basePrice=62, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.Zucchini", basePrice=86, tags={"Food.Cooking.Ingredient", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
})

print("[DynamicTrading] Cooking Registry Complete")
