-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.General] [Rarity.Rare] (25 items)
    { item="Base.Allsorts", basePrice=2023, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CinnamonRoll", basePrice=2040, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CocoaPowder", basePrice=2573, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Crackers", basePrice=2014, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dogfood_Box", basePrice=1998, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.GrahamCrackers", basePrice=2014, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GranolaBar", basePrice=2044, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GrassTuft", basePrice=2016, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GreenpeasSeed", basePrice=2001, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Gum", basePrice=2003, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HayTuft", basePrice=2027, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HiHis", basePrice=2030, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JamMarmalade", basePrice=2512, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JellyBeans", basePrice=2005, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Jujubes", basePrice=2012, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Lollipop", basePrice=2033, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Macaroni", basePrice=2083, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Modjeska", basePrice=2025, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PeanutButter", basePrice=2168, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Plonkies", basePrice=2030, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RyeSeed", basePrice=2011, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.SnoGlobes", basePrice=2030, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.SoybeansSeed", basePrice=2001, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Teabag2", basePrice=2039, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.WheatSeed", basePrice=2011, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },

    -- [Food.Perishable.General] [Rarity.Rare] (82 items)
    { item="Base.Baloney", basePrice=1631, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Biscuit", basePrice=1162, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Blackbeans", basePrice=1146, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Burger", basePrice=1642, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurgerRecipe", basePrice=1630, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Burrito", basePrice=1644, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurritoRecipe", basePrice=1158, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.CatFoodBag", basePrice=1235, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.CatTreats", basePrice=1173, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Caviar", basePrice=1188, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cheese", basePrice=1209, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cherry", basePrice=1163, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cone", basePrice=1183, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamMelted", basePrice=1604, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle_Melted", basePrice=1192, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Croissant", basePrice=1170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cucumber", basePrice=1206, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Daikon", basePrice=1191, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Dandelions", basePrice=1173, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Danish", basePrice=1171, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DogFoodBag", basePrice=1235, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.Edamame", basePrice=1158, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggBoiled", basePrice=1172, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggCarton", basePrice=1169, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.EggOmelette", basePrice=1198, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggPoached", basePrice=1172, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggScrambled", basePrice=1198, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Fries", basePrice=1175, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Frozen_FrenchFries", basePrice=1143, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Frozen_TatoDots", basePrice=1143, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FudgeePop_Melted", basePrice=1212, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.GrapeLeaves", basePrice=1173, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Grapes", basePrice=1198, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hops", basePrice=1170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Hotdog", basePrice=1197, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.IcecreamMelted", basePrice=1284, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich_Melted", basePrice=1193, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Icing", basePrice=1180, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.JellyRoll", basePrice=1170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Ladybug", basePrice=1161, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.Macandcheese", basePrice=1768, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.HighQuality"}, stockRange={min=0, max=7} },
    { item="Base.Maki", basePrice=1155, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Mango", basePrice=1241, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Onigiri", basePrice=1160, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OystersFried", basePrice=1166, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Painauchocolat", basePrice=1612, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Peas", basePrice=1216, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Perogies", basePrice=1171, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PiePrep", basePrice=1186, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PiePumpkin", basePrice=1662, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Pizza", basePrice=1662, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Poppies", basePrice=1161, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PoppyPods", basePrice=1161, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Popsicle_Melted", basePrice=1211, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Processedcheese", basePrice=1189, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Ramen", basePrice=1239, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.RedRadish", basePrice=1157, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.RyeSheaf", basePrice=1181, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Salad", basePrice=1238, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.SaladClay", basePrice=1238, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Salami", basePrice=1229, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SeedPaste", basePrice=1262, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SeedPasteBowl", basePrice=1262, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.ShrimpDumpling", basePrice=1170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFried", basePrice=1172, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Soybeans", basePrice=1141, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Springroll", basePrice=1184, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Squid", basePrice=1631, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Strewberrie", basePrice=1156, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SushiEgg", basePrice=1150, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Taco", basePrice=1641, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TacoRecipe", basePrice=1184, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TacoShell", basePrice=1184, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TofuFried", basePrice=1204, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Tortilla", basePrice=1158, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Waffles", basePrice=1182, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.WafflesRecipe", basePrice=1182, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Watermelon", basePrice=1409, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.WatermelonSliced", basePrice=1208, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.WatermelonSmashed", basePrice=1219, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.WheatSheaf", basePrice=1181, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Yoghurt", basePrice=1217, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
})

print("[DynamicTrading] General Registry Complete")
