-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.General] [Rarity.Rare] (25 items)
    { item="Base.Allsorts", basePrice=34, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CinnamonRoll", basePrice=51, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CocoaPowder", basePrice=160, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Crackers", basePrice=24, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dogfood_Box", basePrice=9, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.GrahamCrackers", basePrice=24, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GranolaBar", basePrice=54, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GrassTuft", basePrice=26, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GreenpeasSeed", basePrice=11, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Gum", basePrice=13, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HayTuft", basePrice=38, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HiHis", basePrice=40, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JamMarmalade", basePrice=99, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JellyBeans", basePrice=15, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Jujubes", basePrice=23, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Lollipop", basePrice=43, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Macaroni", basePrice=94, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Modjeska", basePrice=35, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PeanutButter", basePrice=179, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Plonkies", basePrice=40, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RyeSeed", basePrice=22, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.SnoGlobes", basePrice=40, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.SoybeansSeed", basePrice=11, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Teabag2", basePrice=49, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.WheatSeed", basePrice=22, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },

    -- [Food.Perishable.General] [Rarity.Rare] (82 items)
    { item="Base.Baloney", basePrice=88, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Biscuit", basePrice=43, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Blackbeans", basePrice=27, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Burger", basePrice=99, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurgerRecipe", basePrice=88, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Burrito", basePrice=101, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurritoRecipe", basePrice=39, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.CatFoodBag", basePrice=115, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.CatTreats", basePrice=54, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Caviar", basePrice=69, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cheese", basePrice=90, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cherry", basePrice=44, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cone", basePrice=63, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamMelted", basePrice=61, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle_Melted", basePrice=73, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Croissant", basePrice=51, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cucumber", basePrice=86, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Daikon", basePrice=72, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Dandelions", basePrice=54, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Danish", basePrice=51, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DogFoodBag", basePrice=115, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.Edamame", basePrice=38, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggBoiled", basePrice=53, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggCarton", basePrice=50, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.EggOmelette", basePrice=78, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggPoached", basePrice=53, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggScrambled", basePrice=78, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Fries", basePrice=56, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Frozen_FrenchFries", basePrice=24, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Frozen_TatoDots", basePrice=24, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FudgeePop_Melted", basePrice=93, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.GrapeLeaves", basePrice=53, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Grapes", basePrice=79, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hops", basePrice=51, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Hotdog", basePrice=77, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.IcecreamMelted", basePrice=165, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich_Melted", basePrice=74, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Icing", basePrice=61, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.JellyRoll", basePrice=50, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Ladybug", basePrice=42, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.Macandcheese", basePrice=225, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.HighQuality"}, stockRange={min=0, max=7} },
    { item="Base.Maki", basePrice=35, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Mango", basePrice=121, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Onigiri", basePrice=40, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OystersFried", basePrice=46, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Painauchocolat", basePrice=69, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Peas", basePrice=97, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Perogies", basePrice=52, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PiePrep", basePrice=67, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PiePumpkin", basePrice=119, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Pizza", basePrice=119, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Poppies", basePrice=41, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PoppyPods", basePrice=41, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Popsicle_Melted", basePrice=92, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Processedcheese", basePrice=70, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Ramen", basePrice=119, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.RedRadish", basePrice=38, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.RyeSheaf", basePrice=61, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Salad", basePrice=119, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.SaladClay", basePrice=119, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Salami", basePrice=109, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SeedPaste", basePrice=143, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SeedPasteBowl", basePrice=143, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.ShrimpDumpling", basePrice=51, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFried", basePrice=52, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Soybeans", basePrice=22, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Springroll", basePrice=64, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Squid", basePrice=88, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Strewberrie", basePrice=37, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SushiEgg", basePrice=31, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Taco", basePrice=98, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TacoRecipe", basePrice=65, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TacoShell", basePrice=65, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TofuFried", basePrice=85, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Tortilla", basePrice=39, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Waffles", basePrice=63, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.WafflesRecipe", basePrice=63, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Watermelon", basePrice=289, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.WatermelonSliced", basePrice=89, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.WatermelonSmashed", basePrice=99, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.WheatSheaf", basePrice=61, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Yoghurt", basePrice=97, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
})

print("[DynamicTrading] General Registry Complete")
