-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.NonPerishable.General] [Rarity.Rare] (25 items)
    { item="Base.Allsorts", basePrice=132, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CinnamonRoll", basePrice=149, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CocoaPowder", basePrice=280, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Crackers", basePrice=123, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dogfood_Box", basePrice=107, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.GrahamCrackers", basePrice=123, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GranolaBar", basePrice=153, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GrassTuft", basePrice=125, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.GreenpeasSeed", basePrice=110, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Gum", basePrice=112, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HayTuft", basePrice=136, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.HiHis", basePrice=139, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JamMarmalade", basePrice=220, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.JellyBeans", basePrice=114, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Jujubes", basePrice=122, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Lollipop", basePrice=142, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.Macaroni", basePrice=192, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Modjeska", basePrice=134, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PeanutButter", basePrice=277, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Plonkies", basePrice=139, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RyeSeed", basePrice=120, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.SnoGlobes", basePrice=139, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.SoybeansSeed", basePrice=110, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=29} },
    { item="Base.Teabag2", basePrice=148, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.WheatSeed", basePrice=120, tags={"Food.NonPerishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },

    -- [Food.Perishable.General] [Rarity.Rare] (82 items)
    { item="Base.Baloney", basePrice=165, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Biscuit", basePrice=98, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Blackbeans", basePrice=82, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Burger", basePrice=176, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurgerRecipe", basePrice=164, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Burrito", basePrice=178, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.BurritoRecipe", basePrice=94, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.CatFoodBag", basePrice=170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.CatTreats", basePrice=109, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Caviar", basePrice=124, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cheese", basePrice=145, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cherry", basePrice=99, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cone", basePrice=118, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ConeIcecreamMelted", basePrice=138, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Creamocle_Melted", basePrice=128, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Croissant", basePrice=106, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Cucumber", basePrice=141, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Daikon", basePrice=127, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Dandelions", basePrice=109, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Danish", basePrice=107, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.DogFoodBag", basePrice=170, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=1} },
    { item="Base.Edamame", basePrice=93, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggBoiled", basePrice=108, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggCarton", basePrice=105, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.EggOmelette", basePrice=133, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggPoached", basePrice=108, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.EggScrambled", basePrice=133, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Fries", basePrice=111, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Frozen_FrenchFries", basePrice=79, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Frozen_TatoDots", basePrice=79, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FudgeePop_Melted", basePrice=148, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.GrapeLeaves", basePrice=108, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Grapes", basePrice=134, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hops", basePrice=106, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Hotdog", basePrice=132, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.IcecreamMelted", basePrice=220, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.IcecreamSandwich_Melted", basePrice=129, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Icing", basePrice=116, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.JellyRoll", basePrice=105, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Ladybug", basePrice=97, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=13} },
    { item="Base.Macandcheese", basePrice=302, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.HighQuality"}, stockRange={min=0, max=7} },
    { item="Base.Maki", basePrice=90, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Mango", basePrice=176, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Onigiri", basePrice=95, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OystersFried", basePrice=101, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Painauchocolat", basePrice=146, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Peas", basePrice=152, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.Perogies", basePrice=107, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PiePrep", basePrice=122, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.PiePumpkin", basePrice=196, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Pizza", basePrice=196, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Poppies", basePrice=96, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PoppyPods", basePrice=96, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Popsicle_Melted", basePrice=147, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Processedcheese", basePrice=125, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Ramen", basePrice=174, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.RedRadish", basePrice=93, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.RyeSheaf", basePrice=116, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Salad", basePrice=174, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.SaladClay", basePrice=174, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Salami", basePrice=165, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SeedPaste", basePrice=198, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.SeedPasteBowl", basePrice=198, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=3} },
    { item="Base.ShrimpDumpling", basePrice=106, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ShrimpFried", basePrice=107, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Soybeans", basePrice=77, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Springroll", basePrice=120, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Squid", basePrice=165, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Strewberrie", basePrice=92, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SushiEgg", basePrice=86, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Taco", basePrice=175, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=3} },
    { item="Base.TacoRecipe", basePrice=120, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TacoShell", basePrice=120, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.TofuFried", basePrice=140, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Tortilla", basePrice=94, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Waffles", basePrice=118, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.WafflesRecipe", basePrice=118, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=3} },
    { item="Base.Watermelon", basePrice=344, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=1} },
    { item="Base.WatermelonSliced", basePrice=144, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=4} },
    { item="Base.WatermelonSmashed", basePrice=154, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.WheatSheaf", basePrice=116, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Yoghurt", basePrice=152, tags={"Food.Perishable.General", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=7} },
})

print("[DynamicTrading] General Registry Complete")
