-- =============================================================================
-- DYNAMIC TRADING: FOOD - PERISHABLE
-- =============================================================================
-- Root Category: Food
-- Sub Category: Perishable
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.AligatorGar",      basePrice=37, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 15,
    { item="Base.Apple",            basePrice=20, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.Avocado",          basePrice=40, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 16,
    { item="Base.Bacon",            basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 12,
    { item="Base.BaconBits",        basePrice=10, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 4,
    { item="Base.BaconRashers",     basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 5,
    { item="Base.BagelPlain",       basePrice=7,  tags={"Food.Perishable.Grain", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 3,
    { item="Base.BaguetteDough",    basePrice=10, tags={"Food.Perishable.Grain", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 4,
    { item="Base.BaitFish",         basePrice=5,  tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Baloney",          basePrice=37, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 15,
    { item="Base.BaloneySlice",     basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 5,
    { item="Base.Banana",           basePrice=30, tags={"Food.Perishable.Fruit", "Quality.Luxury"}, stockRange={min=1, max=7} }, -- Hung: 12,
    { item="Base.Basil",            basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Beef", basePrice=40, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 16,
    { item="Base.BellPepper",       basePrice=20, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.BerryBlack",       basePrice=5,  tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=10, max=50} }, -- Hung: 2,
    { item="Base.BerryBlue",        basePrice=5,  tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=10, max=50} }, -- Hung: 2,
    { item="Base.BlackCrappie",     basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.BlueCatfish",      basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Bluegill",         basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 6,
    { item="Base.Bread",            basePrice=12, tags={"Food.Perishable.Grain", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 5,
    { item="Base.Broccoli",         basePrice=22, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 9,
    { item="Base.BunsHamburger",    basePrice=10, tags={"Food.Perishable.Grain", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 4,
    { item="Base.Burger",           basePrice=25, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=0, max=5} },
    { item="Base.Burrito",          basePrice=20, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=0, max=5} },
    { item="Base.Butter",           basePrice=30, tags={"Food.Perishable.Cooking", "Quality.Luxury"}, stockRange={min=2, max=8} }, -- Hung: 12,
    { item="Base.Cabbage",          basePrice=60, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 24,
    { item="Base.CakeSlice",        basePrice=17, tags={"Food.Perishable.Sweets", "Quality.Luxury"}, stockRange={min=0, max=5} }, -- Hung: 7,
    { item="Base.CannedChiliOpen",      basePrice=5,  tags={"Food.Perishable.Canned", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Carrots",          basePrice=20, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.Centipede",        basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.ChannelCatfish",   basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Cherry",           basePrice=5,  tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=10, max=50} }, -- Hung: 2,
    { item="Base.Chicken", basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 6,
    { item="Base.ChickenFillet", basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 8,
    { item="Base.ChickenNuggets",   basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 6,
    { item="Base.ChickenWhole", basePrice=50, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 20,
    { item="Base.ChickenWings", basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 5,
    { item="Base.Chives",           basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Cilantro",         basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Cockroach",        basePrice=1, tags={"Food.Perishable.Bait", "Quality.Waste"}, stockRange={min=5, max=25} },
    { item="Base.Corn",             basePrice=25, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.Crayfish",         basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 5,
    { item="Base.Cricket",          basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 1,
    { item="Base.Croissant",        basePrice=10, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 4,
    { item="Base.Cupcake",          basePrice=10, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 4,
    { item="Base.DeadBird",         basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 5,
    { item="Base.DeadMouse",        basePrice=2,  tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 1,
    { item="Base.DeadRabbit",       basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.DeadRat",          basePrice=5,  tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 2,
    { item="Base.DeadSquirrel",     basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 5,
    { item="Base.Egg",              basePrice=17, tags={"Food.Perishable.Protein", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 7,
    { item="Base.EggCarton",        basePrice=200, tags={"Food.Perishable.Protein", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 84 (approx),
    { item="Base.Eggplant",         basePrice=30, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 12,
    { item="Base.FishFillet",       basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.FishRoe",          basePrice=37, tags={"Food.Perishable.Meat", "Quality.Luxury"}, stockRange={min=0, max=2} }, -- Hung: 15,
    { item="Base.FlatheadCatfish",  basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.FreshwaterDrum",   basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.Fries",            basePrice=12, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=0, max=5} },
    { item="Base.FrogMeat", basePrice=7, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 3,
    { item="Base.Garlic",           basePrice=12, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.GingerRoot",       basePrice=12, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 5,
    { item="Base.Grapefruit",       basePrice=30, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 12,
    { item="Base.Grapes",           basePrice=25, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.Grasshopper",      basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.GreenSunfish",     basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 6,
    { item="Base.Ham",              basePrice=62, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=1} }, -- Hung: 25,
    { item="Base.HamSlice",         basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.HotdogPack",       basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 12,
    { item="Base.Hotdog_single",    basePrice=7,  tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 3,
    { item="Base.Icecream",         basePrice=37, tags={"Food.Perishable.Sweets", "Quality.Luxury"}, stockRange={min=0, max=5} }, -- Hung: 15,
    { item="Base.Lard",             basePrice=25, tags={"Food.Perishable.Cooking", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.LargemouthBass",   basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Leech",            basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 1,
    { item="Base.Leek",             basePrice=20, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.Lemon",            basePrice=12, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 5,
    { item="Base.Lettuce",          basePrice=15, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 6,
    { item="Base.Lime",             basePrice=12, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 5,
    { item="Base.Lobster",          basePrice=62, tags={"Food.Perishable.Meat", "Quality.Luxury"}, stockRange={min=0, max=1} }, -- Hung: 25,
    { item="Base.Maggots",          basePrice=1, tags={"Food.Perishable.Bait", "Quality.Waste"}, stockRange={min=10, max=50} },
    { item="Base.Mango",            basePrice=37, tags={"Food.Perishable.Fruit", "Quality.Luxury"}, stockRange={min=0, max=2} }, -- Hung: 15,
    { item="Base.Margarine",        basePrice=25, tags={"Food.Perishable.Cooking", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.MayonnaiseFull",   basePrice=30, tags={"Food.Perishable.Cooking", "Rarity.Common"}, stockRange={min=2, max=6} }, -- Hung: 12,
    { item="Base.MeatDumpling",     basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 5,
    { item="Base.MeatPatty",        basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 5,
    { item="Base.Millipede",        basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.MincedMeat",       basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.Muskellunge",      basePrice=35, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 14,
    { item="Base.Mussels",          basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 6,
    { item="Base.MuttonChop", basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 12,
    { item="Base.Onion",            basePrice=25, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.OpenBeans",            basePrice=5,  tags={"Food.Perishable.Canned", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Orange",           basePrice=25, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 10,
    { item="Base.Oregano",          basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Oysters",          basePrice=20, tags={"Food.Perishable.Meat", "Quality.Luxury"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.Paddlefish",       basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 12,
    { item="Base.Parsley",          basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Peach",            basePrice=20, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 8,
    { item="Base.Pear",             basePrice=20, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 8,
    { item="Base.Pepperoni",        basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.PieApple",         basePrice=25, tags={"Food.Perishable.Sweets", "Quality.Luxury"}, stockRange={min=0, max=2} }, -- Hung: 10,
    { item="Base.Pineapple",        basePrice=50, tags={"Food.Perishable.Fruit", "Quality.Luxury"}, stockRange={min=0, max=2} }, -- Hung: 20,
    { item="Base.Pizza",            basePrice=20, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=0, max=5} },
    { item="Base.Pork", basePrice=35, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 14,
    { item="Base.PorkChop", basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 12,
    { item="Base.Potato",           basePrice=45, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 18,
    { item="Base.Pumpkin",          basePrice=75, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 30,
    { item="Base.Rabbitmeat", basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 10,
    { item="Base.RatKing",          basePrice=150, tags={"Food.Perishable.Meat", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Hung: 20, Manual Rare upgrade,
    { item="Base.RedRadish",        basePrice=15, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 6,
    { item="Base.RedearSunfish",    basePrice=15, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 6,
    { item="Base.Rosemary",         basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Sage",             basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Salami",           basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 10,
    { item="Base.SalamiSlice",      basePrice=10, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 4,
    { item="Base.Salmon",           basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 12,
    { item="Base.Sandwich",         basePrice=25, tags={"Food.Perishable.Cooking", "Rarity.Common"}, stockRange={min=0, max=5} }, -- Hung: 10,
    { item="Base.Sauger",           basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.Sausage",          basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 8,
    { item="Base.Shrimp",           basePrice=12, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 5,
    { item="Base.Slug",             basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 1,
    { item="Base.Smallanimalmeat", basePrice=10, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 4,
    { item="Base.Smallbirdmeat", basePrice=10, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 4,
    { item="Base.SmallmouthBass",   basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Snail",            basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 1,
    { item="Base.SpottedBass",      basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Squid",            basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Steak", basePrice=45, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 18,
    { item="Base.StripedBass",      basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Taco",             basePrice=15, tags={"Food.Perishable.Sweets", "Rarity.Common"}, stockRange={min=0, max=5} },
    { item="Base.Thyme",            basePrice=5, tags={"Food.Perishable.Spice", "Origin.Healthcare"}, stockRange={min=2, max=12} },
    { item="Base.Tomato",           basePrice=30, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=2, max=12} }, -- Hung: 12,
    { item="Base.TunaTinOpen",          basePrice=5,  tags={"Food.Perishable.Canned", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.TurkeyEgg",        basePrice=25, tags={"Food.Perishable.Protein", "Rarity.Common"}, stockRange={min=2, max=12} } -- Hung: 10,
    { item="Base.TurkeyFillet", basePrice=30, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 12,
    { item="Base.TurkeyLegs", basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 10,
    { item="Base.TurkeyWhole", basePrice=75, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=1} }, -- Hung: 30,
    { item="Base.TurkeyWings", basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 8,
    { item="Base.Venison", basePrice=45, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 18,
    { item="Base.Walleye",          basePrice=25, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 10,
    { item="Base.Watermelon",       basePrice=75, tags={"Food.Perishable.Fruit", "Rarity.Common"}, stockRange={min=0, max=2} }, -- Hung: 30,
    { item="Base.WhiteBass",        basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.WhiteCrappie",     basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.WildEggs",         basePrice=17, tags={"Food.Perishable.Protein", "Rarity.Common"}, stockRange={min=5, max=25} }, -- Hung: 7,
    { item="Base.Worm",             basePrice=2, tags={"Food.Perishable.Bait", "Rarity.Common"}, stockRange={min=10, max=50} }, -- Hung: 1,
    { item="Base.YellowPerch",      basePrice=20, tags={"Food.Perishable.Meat", "Rarity.Common"}, stockRange={min=1, max=5} }, -- Hung: 8,
    { item="Base.Zucchini",         basePrice=25, tags={"Food.Perishable.Vegetable", "Rarity.Common"}, stockRange={min=1, max=7} }, -- Hung: 10,
})

print("[DynamicTrading] Food/Perishable Registry Loaded.")
