-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Spice] [Rarity.Rare] (108 items)
    { item="Base.BaconBits", basePrice=13, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.BalsamicVinegar", basePrice=39, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Basil", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.BasilDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.BBQSauce", basePrice=40, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.BellPepper", basePrice=26, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.BouillonCube", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Butter", basePrice=83, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Candycane", basePrice=15, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Capers", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Chamomile", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ChamomileDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Chives", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ChivesDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Cilantro", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.CilantroDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.CilantroSeed", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.Cinnamon", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Cornflour2", basePrice=30, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Cornmeal2", basePrice=14, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Dip_NachoCheese", basePrice=117, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Dip_Ranch", basePrice=121, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Dip_Salsa", basePrice=109, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.FishRoe", basePrice=34, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.FlaxSeed", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.Flour2", basePrice=31, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FourLeafClover", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Garlic", basePrice=28, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.GingerPickled", basePrice=29, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.GingerRoot", basePrice=25, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Gravy", basePrice=24, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.GreenOnions", basePrice=26, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Guacamole", basePrice=26, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Honey", basePrice=42, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Hotsauce", basePrice=29, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Ketchup", basePrice=48, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Lard", basePrice=95, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Lavender", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.LavenderPetalsDried", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Lemon", basePrice=32, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.LemonGrass", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Lime", basePrice=32, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MapleSyrup", basePrice=76, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Margarine", basePrice=84, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.Marigold", basePrice=31, tags={"Food.Cooking.Spice", "Rarity.Rare", "Quality.Luxury", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MarigoldDried", basePrice=14, tags={"Food.Cooking.Spice", "Rarity.Rare", "Quality.Luxury", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Marinara", basePrice=27, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MayonnaiseFull", basePrice=107, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.MintHerb", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.MintHerbDried", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Mustard", basePrice=32, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Nettles", basePrice=24, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.OilOlive", basePrice=70, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.OilVegetable", basePrice=64, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Olives", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Oregano", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.OreganoDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Parsley", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ParsleyDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Pepper", basePrice=21, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.PepperHabanero", basePrice=18, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PepperHabaneroDried", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PepperJalapeno", basePrice=18, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PepperJalapenoDried", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Peppermint", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Pepperoni", basePrice=47, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Pickles", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PoppySeed", basePrice=15, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.PowderedGarlic", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.PowderedOnion", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.PumpkinSeed", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.RemouladeFull", basePrice=51, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=6} },
    { item="Base.RiceVinegar", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Rosehips", basePrice=26, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Rosemary", basePrice=24, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.RosemaryDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.RosePetalsDried", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Roses", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Sage", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SageDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Salt", basePrice=21, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Sausage", basePrice=29, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Basil", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Chives", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Cilantro", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Oregano", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Parsley", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Rosemary", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Sage", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seasoning_Thyme", basePrice=11, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.SeasoningSalt", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Seaweed", basePrice=9, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.SesameOil", basePrice=13, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.SourCream", basePrice=42, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Soysauce", basePrice=32, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Sugar", basePrice=58, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarBrown", basePrice=41, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarCubes", basePrice=16, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.SugarPacket", basePrice=12, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=20} },
    { item="Base.SunflowerSeeds", basePrice=12, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Thistle", basePrice=23, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Thyme", basePrice=20, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.ThymeDried", basePrice=10, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.TomatoPaste", basePrice=23, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Vinegar2", basePrice=15, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=10} },
    { item="Base.Vinegar_Jug", basePrice=17, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Violets", basePrice=21, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
    { item="Base.Wasabi", basePrice=37, tags={"Food.Cooking.Spice", "Rarity.Rare", "Food.LowNutrition"}, stockRange={min=0, max=10} },
})

print("[DynamicTrading] Spice Registry Complete")
