-- ============================================================================
-- Food Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Food.Cooking.Spice] [Rarity.Rare] (108 items)
    { item="Base.BaconBits", basePrice=1132, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.BalsamicVinegar", basePrice=1159, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Basil", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.BasilDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.BBQSauce", basePrice=1583, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.BellPepper", basePrice=1145, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.BouillonCube", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=14} },
    { item="Base.Butter", basePrice=1202, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Candycane", basePrice=1135, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Capers", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Chamomile", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ChamomileDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Chives", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ChivesDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cilantro", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.CilantroDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.CilantroSeed", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.Cinnamon", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Cornflour2", basePrice=1150, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Cornmeal2", basePrice=1134, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=2} },
    { item="Base.Dip_NachoCheese", basePrice=1660, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dip_Ranch", basePrice=1664, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Dip_Salsa", basePrice=1229, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.FishRoe", basePrice=1154, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.FlaxSeed", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=24} },
    { item="Base.Flour2", basePrice=1150, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=2} },
    { item="Base.FourLeafClover", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Garlic", basePrice=1148, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GingerPickled", basePrice=1148, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GingerRoot", basePrice=1144, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Gravy", basePrice=1143, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.GreenOnions", basePrice=1145, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Guacamole", basePrice=1146, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Honey", basePrice=1585, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=7} },
    { item="Base.Hotsauce", basePrice=1572, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Ketchup", basePrice=1168, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Lard", basePrice=1214, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Lavender", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LavenderPetalsDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Lemon", basePrice=1152, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.LemonGrass", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Lime", basePrice=1152, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MapleSyrup", basePrice=1195, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Margarine", basePrice=1203, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.Marigold", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MarigoldDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Marinara", basePrice=1146, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.MayonnaiseFull", basePrice=1227, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.MintHerb", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.MintHerbDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Mustard", basePrice=1575, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Nettles", basePrice=1143, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OilOlive", basePrice=1189, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.OilVegetable", basePrice=1183, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Olives", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Oregano", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.OreganoDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Parsley", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ParsleyDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pepper", basePrice=1141, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.PepperHabanero", basePrice=1138, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PepperHabaneroDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PepperJalapeno", basePrice=1138, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.PepperJalapenoDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Peppermint", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Pepperoni", basePrice=1166, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Pickles", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.PoppySeed", basePrice=1135, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=13} },
    { item="Base.PowderedGarlic", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.PowderedOnion", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.PumpkinSeed", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.RemouladeFull", basePrice=1618, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=7} },
    { item="Base.RiceVinegar", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.Rosehips", basePrice=1146, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Rosemary", basePrice=1143, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.RosemaryDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.RosePetalsDried", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Roses", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Sage", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.SageDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Salt", basePrice=1141, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Sausage", basePrice=1148, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Seasoning_Basil", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Chives", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Cilantro", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Oregano", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Parsley", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Rosemary", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Sage", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seasoning_Thyme", basePrice=1130, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.SeasoningSalt", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=14} },
    { item="Base.Seaweed", basePrice=1128, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.SesameOil", basePrice=1132, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=15} },
    { item="Base.SourCream", basePrice=1584, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Soysauce", basePrice=1152, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Sugar", basePrice=2218, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarBrown", basePrice=1584, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.MediumNutrition"}, stockRange={min=0, max=4} },
    { item="Base.SugarCubes", basePrice=1135, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=25} },
    { item="Base.SugarPacket", basePrice=1132, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=25} },
    { item="Base.SunflowerSeeds", basePrice=1132, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.Thistle", basePrice=1143, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Thyme", basePrice=1139, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.ThymeDried", basePrice=1129, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=12} },
    { item="Base.TomatoPaste", basePrice=1143, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Vinegar2", basePrice=1940, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition", "Food.LowQuality"}, stockRange={min=0, max=12} },
    { item="Base.Vinegar_Jug", basePrice=2256, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.HighNutrition", "Food.LowQuality"}, stockRange={min=0, max=2} },
    { item="Base.Violets", basePrice=1141, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
    { item="Base.Wasabi", basePrice=1157, tags={"Food.Cooking.Spice", "Rarity.Rare", "Origin.Vanilla", "Food.LowNutrition"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Spice Registry Complete")
