-- ============================================================================
-- Weapon Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Weapon.Melee.General] [Rarity.Common] (188 items)
    { item="Base.AnimalBone", basePrice=61, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.BadmintonRacket", basePrice=44, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Banjo", basePrice=69, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.BanjoNeck_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.BarBell", basePrice=166, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.BarBell_Forged", basePrice=166, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.BareHands", basePrice=61, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.BlockMaul", basePrice=152, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.BluePen", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.BoltCutters", basePrice=156, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.BowlingPin", basePrice=64, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.BowlingPin_Nails", basePrice=70, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Branch_Broken", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Branch_Broken_Nails", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.BrassNameplate", basePrice=58, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Broom", basePrice=87, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Broom_BarbedWire", basePrice=92, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Broom_Twig", basePrice=87, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.CanoePadel", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.CanoePadelX2", basePrice=135, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.CanoePadelX2_Broken", basePrice=37, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.CarpentryChisel", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.CarvingFork2", basePrice=56, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.ChairLeg", basePrice=53, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ChairLeg_Nails", basePrice=57, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ClosedUmbrellaBlack", basePrice=83, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ClosedUmbrellaBlue", basePrice=83, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ClosedUmbrellaRed", basePrice=83, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ClosedUmbrellaTINTED", basePrice=83, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.ClosedUmbrellaWhite", basePrice=83, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Cudgel_Bone", basePrice=135, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_Brake", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_GardenForkHead", basePrice=140, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_Nails", basePrice=129, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_Railspike", basePrice=136, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_ScrapSheet", basePrice=47, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_SpadeHead", basePrice=140, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Cudgel_Spike", basePrice=139, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Drumstick", basePrice=36, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DumbBell", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.DumbBell_Forged", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.EngineMaul", basePrice=129, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FieldHockeyStick", basePrice=103, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.FieldHockeyStick_Broken", basePrice=20, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FieldHockeyStick_Broken_Nails", basePrice=22, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FieldHockeyStick_Nails", basePrice=111, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.File", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.FireplacePoker", basePrice=98, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Firewood", basePrice=49, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Firewood_Nails", basePrice=57, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Flute", basePrice=35, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Fork", basePrice=47, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Fork_Bone", basePrice=42, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Fork_Gold", basePrice=132, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Fork_Silver", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.ForkForged", basePrice=47, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.GardenForkHead", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.GardenForkHead_Forged", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.GardenToolHandle_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Gavel", basePrice=36, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.GlassShiv", basePrice=51, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.GreenPen", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.GuitarAcoustic", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.GuitarAcousticNeck_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.GuitarElectric", basePrice=113, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.GuitarElectricBass", basePrice=122, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.GuitarElectricBassNeck_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.GuitarElectricNeck_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.HandguardDagger", basePrice=75, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Handle", basePrice=65, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Handle_Can", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Handle_Nails", basePrice=68, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.HobbyHorse", basePrice=99, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.IceHockeyStick", basePrice=103, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.IceHockeyStick_BarbedWire", basePrice=111, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.IcePick", basePrice=84, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.IronBar", basePrice=110, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.IronBarHalf", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.JawboneBovide", basePrice=64, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.JawboneBovide_Morningstar", basePrice=188, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Keytar", basePrice=68, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LaCrosseStick", basePrice=114, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.LargeAnimalBone", basePrice=63, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LargeBranch", basePrice=122, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.LargeHook", basePrice=61, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LetterOpener", basePrice=51, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.LongHandle", basePrice=88, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongHandle_Brake", basePrice=65, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongHandle_Broken", basePrice=21, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.LongHandle_Broken_Nails", basePrice=23, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.LongHandle_Can", basePrice=104, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongHandle_Nails", basePrice=95, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongHandle_Railspike", basePrice=94, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongHandle_RakeHead", basePrice=67, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongStick", basePrice=96, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.LongStick_Broken", basePrice=20, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.MasonsChisel", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.MasonsTrowel", basePrice=60, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.MetalBar", basePrice=98, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.MetalworkingChisel", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.MetalworkingPunch", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Mop", basePrice=87, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Morningstar_Scrap", basePrice=33, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Morningstar_Scrap_Short", basePrice=25, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Pan", basePrice=68, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.PanForged", basePrice=68, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Pen", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.Pencil", basePrice=43, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.PencilSpiffo", basePrice=43, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.PenMultiColor", basePrice=48, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.PenSpiffo", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.Plank", basePrice=76, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Plank_Brake", basePrice=65, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Plank_Broken", basePrice=20, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Plank_Broken_Nails", basePrice=22, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Plank_Nails", basePrice=86, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Plank_Saw", basePrice=85, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Plunger", basePrice=49, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Plunger_BarbedWire", basePrice=62, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Poolcue", basePrice=97, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.RailroadSpike", basePrice=98, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.RailroadSpikePuller", basePrice=161, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RailroadSpikePullerOld", basePrice=161, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RedPen", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=15} },
    { item="Base.RollingPin", basePrice=73, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Sapling", basePrice=96, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Saw_Flint", basePrice=76, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Saxophone", basePrice=56, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Scissors", basePrice=62, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.ScissorsForged", basePrice=62, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.ScrapMaul", basePrice=39, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ScrapWeapon_Brake", basePrice=29, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla", "Theme.Combat"}, stockRange={min=0, max=3} },
    { item="Base.ScrapWeaponGardenFork", basePrice=39, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla", "Theme.Combat"}, stockRange={min=0, max=3} },
    { item="Base.ScrapWeaponRakeHead", basePrice=30, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla", "Theme.Combat"}, stockRange={min=0, max=3} },
    { item="Base.ScrapWeaponSpade", basePrice=39, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla", "Theme.Combat"}, stockRange={min=0, max=3} },
    { item="Base.Screwdriver", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Screwdriver_Improvised", basePrice=64, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Screwdriver_Old", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.SharpBone_Long", basePrice=72, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.SmashedBottle", basePrice=35, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.SpadeForged", basePrice=134, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpadeHead", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.SpadeWood", basePrice=106, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Spear_Bone", basePrice=109, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Spear_BoneLong", basePrice=113, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Spear_Plunger", basePrice=96, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearCrafted", basePrice=105, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearCraftedFireHardened", basePrice=112, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearCrude", basePrice=108, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearCrudeLong", basePrice=114, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearGlass", basePrice=100, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearHandFork", basePrice=113, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearLong", basePrice=127, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearScissors", basePrice=110, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearScrewdriver", basePrice=69, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearShort", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearStone", basePrice=112, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SpearStoneLong", basePrice=116, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Spoon", basePrice=47, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Spoon_Bone", basePrice=42, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Spoon_Gold", basePrice=132, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Spoon_Silver", basePrice=45, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.SpoonForged", basePrice=47, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Stake", basePrice=59, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.SteelBar", basePrice=110, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SteelBarHalf", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.SteelRodHalf", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.StoneMaul", basePrice=125, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TableLeg", basePrice=69, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TableLeg_Broken", basePrice=21, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.TableLeg_Broken_Nails", basePrice=23, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.TableLeg_Chain", basePrice=81, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TableLeg_Nails", basePrice=78, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TennisRacket", basePrice=53, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.TireIron", basePrice=96, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Toothbrush_Shiv", basePrice=63, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.TreeBranch2", basePrice=81, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TreeBranch_Bone", basePrice=81, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TreeBranch_Can", basePrice=91, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TreeBranch_Nails", basePrice=86, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.TreeBranch_Railspike", basePrice=81, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Trumpet", basePrice=58, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Violin", basePrice=40, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.WoodenStick2", basePrice=77, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.WoodenStick_Broken", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.WoodenStick_Broken_Nails", basePrice=20, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.WoodenStick_Can", basePrice=100, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.WoodenStick_Nails", basePrice=82, tags={"Weapon.Melee.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=3} },

    -- [Weapon.Melee.General] [Rarity.Rare] (22 items)
    { item="Base.CompassGeometry", basePrice=76, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.EntrenchingTool", basePrice=139, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Firecracker", basePrice=126, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Firecracker_Crafted", basePrice=126, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.FlameTrap", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlameTrapRemote", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlameTrapSensorV1", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlameTrapSensorV2", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlameTrapSensorV3", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlameTrapTriggered", basePrice=82, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.FlintNodule", basePrice=100, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Multitool", basePrice=125, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrap", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.NoiseTrapRemote", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.NoiseTrapSensorV1", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.NoiseTrapSensorV2", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.NoiseTrapSensorV3", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.NoiseTrapTriggered", basePrice=123, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.PenFancy", basePrice=78, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Ratchet", basePrice=119, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.SheetMetalSnips", basePrice=136, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
    { item="Base.Stone2", basePrice=100, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=3} },
})

print("[DynamicTrading] Melee Registry Complete")
