-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material.Leather] [Rarity.Rare] (95 items)
    { item="Base.BrainTan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CowHide", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Medium", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Angus_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Medium", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Medium", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DappleDeerHide", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DeerHide", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.DeerLeather_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.FawnLeather_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Large", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.LeatherStrips", basePrice=8, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsBundle", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.LeatherStripsDirty", basePrice=8, tags={"Resource.Material.Leather", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsDirtyBundle", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Black_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PigletLeather_Black_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Full", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Full", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan_Small", basePrice=2, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Fur_Tan_Wet", basePrice=1, tags={"Resource.Material.Leather", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
})

print("[DynamicTrading] Leather Registry Complete")
