-- =============================================================================
-- DYNAMIC TRADING: RESOURCE - MATERIAL
-- =============================================================================
-- Root Category: Resource
-- Sub Category: Material
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.Aluminum",          tags={"Resource.Material.Metal", "Rarity.Common"}, basePrice=30, stockRange={min=5, max=15} }, -- Worth: 15.0,
    { item="Base.AluminumScrap",     tags={"Resource.Material.Metal", "Quality.Waste"},  basePrice=10, stockRange={min=5, max=15} }, -- Worth: 5.0,
    { item="Base.AnimalBone",           basePrice=5,   tags={"Resource.Material.Bone", "Rarity.Common"}, stockRange={min=5, max=20} },
    { item="Base.AnimalSinew",          basePrice=25,  tags={"Resource.Material.Thread", "Origin.Animal", "Rarity.Uncommon"}, stockRange={min=2, max=10} }, -- Useful for stitching,
    { item="Base.BrassIngot",        tags={"Resource.Material.Metal", "Rarity.Uncommon"}, basePrice=160, stockRange={min=1, max=4} }, -- Worth: 80.0,
    { item="Base.BrassScrap",        tags={"Resource.Material.Metal", "Quality.Waste"},  basePrice=20, stockRange={min=5, max=20} },
    { item="Base.Broom_Twig",           basePrice=5,  tags={"Resource.Material.Wood", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Bull_Head_Angus",          basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Bull_Head_Holstein",       basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Bull_Head_Simmental",      basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Bull_Skull",               basePrice=15, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Calf_Head_Angus",          basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Calf_Head_Holstein",       basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Calf_Head_Simmental",      basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Calf_Skull",               basePrice=3,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.CameraFilm",           basePrice=20,  tags={"Resource.Material.Chemical", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.ChickenFeather",       basePrice=1,   tags={"Resource.Material.Feather", "Quality.Waste"}, stockRange={min=10, max=50} },
    { item="Base.Chicken_Hen_Brown_Head",     basePrice=1, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.Chicken_Hen_Skull",        basePrice=1,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.Chicken_Hen_White_Head",     basePrice=1, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.Chicken_Rooster_Head_Brown", basePrice=1, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.Chicken_Rooster_Head_White", basePrice=1, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.Chicken_Rooster_Skull",    basePrice=1,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.ClayBrick",         tags={"Resource.Material.Build", "Rarity.Common"},                          basePrice=15, stockRange={min=10, max=40} },
    { item="Base.Claybag",           tags={"Resource.Material.Industrial", "Quality.Basic", "Rarity.Common"}, basePrice=60, stockRange={min=2, max=8} },
    { item="Base.CopperIngot",       tags={"Resource.Material.Metal", "Rarity.Uncommon"}, basePrice=120, stockRange={min=2, max=6} }, -- Worth: 60.0,
    { item="Base.CopperOre",         tags={"Resource.Material.Raw", "Rarity.Common"},    basePrice=60, stockRange={min=1, max=4} },
    { item="Base.CopperScrap",       tags={"Resource.Material.Metal", "Quality.Waste"},  basePrice=16, stockRange={min=5, max=20} },
    { item="Base.CopperSheet",       tags={"Resource.Material.Metal", "Rarity.Common"},  basePrice=90, stockRange={min=2, max=8} },
    { item="Base.CowHide",           tags={"Resource.Material.Bio", "Rarity.Rare"},    basePrice=240, stockRange={min=1, max=3} }, -- Worth: 120.0,
    { item="Base.CowLeather_Angus_Full",      basePrice=180, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.CowLeather_Holstein_Full",   basePrice=180, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.CowLeather_Simmental_Full",  basePrice=180, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.Cow_Head_Angus",           basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Cow_Head_Holstein",        basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Cow_Head_Simmental",       basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Cow_Skull",                basePrice=12, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.DeerDoe_Skull",            basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.DeerFawn_Skull",           basePrice=3,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.DeerLeather_Full",           basePrice=150, tags={"Resource.Material.Leather", "Theme.Survival", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.DeerStag_Skull",           basePrice=25, tags={"Resource.Material.Trophy", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Deer_Buck_Head",           basePrice=20, tags={"Resource.Material.Trophy", "Rarity.Rare"}, stockRange={min=0, max=1} }, -- Impressive rack,
    { item="Base.Deer_Doe_Head",            basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Deer_Fawn_Head",           basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.DishCloth", basePrice=10, tags={"Resource.Material.Cloth", "Tool.Cleaning.Hygiene", "Rarity.Common"}, stockRange={min=2, max=8} },
    { item="Base.DuctTape",          tags={"Resource.Material.Utility", "Rarity.Uncommon"}, basePrice=170, stockRange={min=1, max=5} }, -- Worth: 85.0,
    { item="Base.ElectricWire",          basePrice=10,  tags={"Resource.Material.Utility", "Rarity.Common"}, stockRange={min=5, max=15} },
    { item="Base.Epoxy",             tags={"Resource.Material.Utility", "Rarity.Uncommon"}, basePrice=150, stockRange={min=1, max=4} }, -- Worth: 75.0,
    { item="Base.FabricRoll_Cotton", tags={"Resource.Material.Textile", "Rarity.Uncommon"}, basePrice=240, stockRange={min=1, max=3} }, -- Worth: 120.0,
    { item="Base.FireAxeHead",       tags={"Resource.Material.Metal", "Rarity.Uncommon"}, basePrice=220, stockRange={min=1, max=3} }, -- Worth: 110.0,
    { item="Base.FlintNodule",        tags={"Resource.Material.Raw", "Theme.Survival"},      basePrice=15, stockRange={min=2, max=8} },
    { item="Base.GardenForkHead",     tags={"Resource.Material.Metal", "Tool.Farmer", "Rarity.Common"}, basePrice=55, stockRange={min=1, max=5} },
    { item="Base.GlassPanel",        tags={"Resource.Material.Glass", "Rarity.Uncommon"}, basePrice=100, stockRange={min=2, max=10} }, -- Worth: 50.0,
    { item="Base.Glue",              tags={"Resource.Material.Utility", "Rarity.Common"},   basePrice=70,  stockRange={min=2, max=8} }, -- Worth: 35.0,
    { item="Base.GoldBar",           tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Legendary"}, basePrice=5000, stockRange={min=0, max=1} },
    { item="Base.GoldScrap",         tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Uncommon"},  basePrice=400,  stockRange={min=1, max=5} },
    { item="Base.GunPowder",         tags={"Resource.Material.Chemical", "Rarity.Rare"}, basePrice=10, stockRange={min=1, max=4} },
    { item="Base.HerbivoreTeeth",       basePrice=1,   tags={"Resource.Material.Bone", "Quality.Waste"}, stockRange={min=1, max=10} },
    { item="Base.IndustrialDye",    tags={"Resource.Material.Dye", "Rarity.Uncommon"},        basePrice=25, stockRange={min=1, max=5} },
    { item="Base.IronBar",           tags={"Resource.Material.Metal", "Rarity.Common"},  basePrice=90, stockRange={min=2, max=10} },
    { item="Base.IronBlock",         tags={"Resource.Material.Metal", "Rarity.Uncommon"},basePrice=200,stockRange={min=1, max=4} },
    { item="Base.IronIngot",         tags={"Resource.Material.Metal", "Rarity.Common"},  basePrice=140, stockRange={min=2, max=8} },
    { item="Base.IronOre",           tags={"Resource.Material.Raw", "Rarity.Common"},    basePrice=70, stockRange={min=1, max=4} },
    { item="Base.IronScrap",         tags={"Resource.Material.Metal", "Quality.Waste"},  basePrice=24, stockRange={min=10, max=30} },
    { item="Base.JawboneBovide",        basePrice=10,  tags={"Resource.Material.Bone", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Lamb_Skull",               basePrice=3,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.LargeAnimalBone",      basePrice=15,  tags={"Resource.Material.Bone", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Leather_Crude_Large",tags={"Resource.Material.Bio", "Theme.Survival"}, basePrice=120, stockRange={min=1, max=4} }, -- Worth: 60.0,
    { item="Base.Limestone",         tags={"Resource.Material.Industrial", "Rarity.Common"},                 basePrice=10, stockRange={min=10, max=30} },
    { item="Base.Nails",             tags={"Resource.Material.General", "Rarity.Common"},   basePrice=4,   stockRange={min=50, max=200} }, -- Worth: 2.0,
    { item="Base.NailsBox",          tags={"Resource.Material.General", "Rarity.Uncommon"}, basePrice=360, stockRange={min=2, max=10} }, -- Worth: 180.0,
    { item="Base.SheetPaper2",             tags={"Resource.Material.Paper", "Rarity.Common"}, basePrice=2, stockRange={min=5, max=20} },
    { item="Base.PaperNapkins2",        basePrice=5,   tags={"Resource.Material.Paper", "Misc.Hygiene", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PigLeather_Black_Full",      basePrice=100, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.PigLeather_Landrace_Full",   basePrice=100, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.PigTusk",              basePrice=15,  tags={"Resource.Material.Trophy", "Rarity.Uncommon"}, stockRange={min=1, max=5} },
    { item="Base.Pig_Boar_Head_Black",      basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Boar_Head_Pink",       basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Piglet_Head_Black",    basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Piglet_Head_Pink",     basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Skull",                basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Sow_Head_Black",       basePrice=6,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Pig_Sow_Head_Pink",        basePrice=6,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Piglet_Skull",             basePrice=3,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Plank",              tags={"Resource.Material.Wood", "Rarity.Common"}, basePrice=15,  stockRange={min=5, max=20} },
    { item="Base.PlasticTray",          basePrice=5,   tags={"Resource.Material.Plastic", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.RabbitLeather_Full",tags={"Resource.Material.Bio", "Rarity.Common"},  basePrice=50,  stockRange={min=2, max=8} }, -- Worth: 25.0,
    { item="Base.Rabbit_Skull",             basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=3} },
    { item="Base.RaccoonLeather_Grey_Full",   basePrice=45,  tags={"Resource.Material.Leather", "Theme.Survival", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Raccoon_Boar_Head",        basePrice=5,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Raccoon_Skull",            basePrice=3,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Raccoon_Sow_Head",         basePrice=5,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Ram_Skull",                basePrice=12, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.RatPoison",        basePrice=60, tags={"Resource.Material.Chemical", "Origin.Healthcare", "Rarity.Uncommon"}, stockRange={min=1, max=5} },
    { item="Base.Rope",              tags={"Resource.Material.Cordage", "Rarity.Common"}, basePrice=70,  stockRange={min=2, max=10} }, -- Worth: 35.0,
    { item="Base.RubberBand",           basePrice=2,   tags={"Resource.Material.Plastic", "Quality.Waste"}, stockRange={min=5, max=20} },
    { item="Base.SharpBoneFragment",    basePrice=1,   tags={"Resource.Material.Bone", "Quality.Waste"}, stockRange={min=5, max=30} },
    { item="Base.SharpedStone",      tags={"Resource.Material.Raw", "Rarity.Common"},    basePrice=20, stockRange={min=5, max=15} },
    { item="Base.SheepLeather_Full",          basePrice=100, tags={"Resource.Material.Leather", "Origin.Industrial", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.Sheep_Lamb_Head_Black",    basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Sheep_Lamb_Head_White",    basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.Sheep_Ram_Head_Black",     basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Sheep_Ram_Head_White",     basePrice=8,  tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Sheep_Skull",              basePrice=10, tags={"Resource.Material.Trophy", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.Sheet",             tags={"Resource.Material.Textile", "Rarity.Common"},   basePrice=30,  stockRange={min=5, max=20} }, -- Worth: 15.0,
    { item="Base.SilverBar",         tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Rare"},      basePrice=2500, stockRange={min=0, max=2} },
    { item="Base.SilverScrap",       tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Common"},    basePrice=200,  stockRange={min=2, max=10} },
    { item="Base.SledgehammerHead",  tags={"Resource.Material.Metal", "Rarity.Rare"}, basePrice=700, stockRange={min=0, max=2} }, -- Worth: 350.0,
    { item="Base.SmallAnimalBone",      basePrice=2,   tags={"Resource.Material.Bone", "Quality.Waste"}, stockRange={min=5, max=30} },
    { item="Base.SmallGoldBar",      tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Rare"},      basePrice=1500, stockRange={min=0, max=2} },
    { item="Base.SmallSilverBar",    tags={"Resource.Material.Precious", "Quality.Luxury", "Rarity.Uncommon"},  basePrice=800,  stockRange={min=1, max=4} },
    { item="Base.SpadeHead",          tags={"Resource.Material.Metal", "Tool.Farmer", "Rarity.Common"}, basePrice=55, stockRange={min=1, max=5} },
    { item="Base.SpearHead",         tags={"Resource.Material.Metal", "Rarity.Common"},   basePrice=90,  stockRange={min=2, max=6} }, -- Worth: 45.0,
    { item="Base.SteelBar",          tags={"Resource.Material.Metal", "Rarity.Rare"},    basePrice=180, stockRange={min=2, max=6} },
    { item="Base.SteelBlock",        tags={"Resource.Material.Metal", "Rarity.Rare"},    basePrice=320, stockRange={min=1, max=4} },
    { item="Base.SteelIngot",        tags={"Resource.Material.Metal", "Rarity.Rare"},    basePrice=240, stockRange={min=1, max=4} },
    { item="Base.SteelScrap",        tags={"Resource.Material.Metal", "Rarity.Common"},  basePrice=60,  stockRange={min=5, max=15} },
    { item="Base.SteelSlug",         tags={"Resource.Material.Metal", "Rarity.Common"},  basePrice=20,  stockRange={min=10, max=50} },
    { item="Base.Stone2",             tags={"Resource.Material.Raw", "Origin.Nomad"},  basePrice=5,  stockRange={min=5, max=15} },
    { item="Base.StoneBlock",        tags={"Resource.Material.Raw", "Rarity.Common"},    basePrice=40, stockRange={min=5, max=15} },
    { item="Base.StoneWheel",        tags={"Resource.Material.Raw", "Rarity.Rare"},      basePrice=300, stockRange={min=0, max=2} },
    { item="Base.Thread",            tags={"Resource.Material.Cordage", "Rarity.Common"}, basePrice=24,  stockRange={min=5, max=20} }, -- Worth: 12.0,
    { item="Base.TinCanEmpty",      tags={"Resource.Material.Metal", "Origin.Civ", "Rarity.Common"}, basePrice=1, stockRange={min=10, max=30} },
    { item="Base.Tissue",               basePrice=2,  tags={"Resource.Material.Paper", "Rarity.Common"}, stockRange={min=1, max=10} },
    { item="Base.TurkeyFeather",        basePrice=1,   tags={"Resource.Material.Feather", "Quality.Waste"}, stockRange={min=10, max=50} },
    { item="Base.Turkey_Gobbler_Head",        basePrice=2, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=3} },
    { item="Base.Turkey_Hen_Head",            basePrice=2, tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=3} },
    { item="Base.Turkey_Skull",             basePrice=2,  tags={"Resource.Material.Trophy", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Twine",             tags={"Resource.Material.Cordage", "Rarity.Common"}, basePrice=30,  stockRange={min=5, max=15} }, -- Worth: 15.0,
    { item="Base.UnusableMetal",        basePrice=5,   tags={"Resource.Material.Metal", "Quality.Waste"}, stockRange={min=5, max=20} },
    { item="Base.UnusableWood",         basePrice=2,   tags={"Resource.Material.Wood", "Quality.Waste"}, stockRange={min=5, max=20} },
    { item="Base.WeldingRods",       tags={"Resource.Material.Utility", "Rarity.Uncommon"}, basePrice=120, stockRange={min=2, max=10} }, -- Worth: 60.0,
    { item="Base.Wire",              tags={"Resource.Material.Utility", "Rarity.Common"},   basePrice=70,  stockRange={min=2, max=8} }, -- Worth: 35.0,
    { item="Base.Woodglue",          tags={"Resource.Material.Utility", "Rarity.Uncommon"}, basePrice=130, stockRange={min=1, max=5} }, -- Worth: 65.0,
})

print("[DynamicTrading] Resource/Material Registry Loaded.")
