-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material.Metal] [Rarity.Common] (4 items)
    { item="Base.Badge", basePrice=6, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=20, max=50} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=1, max=4} },
    { item="Base.DogTag_Pet", basePrice=6, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=20, max=50} },
    { item="Base.DogTag_Pet_Blank", basePrice=6, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=20, max=50} },

    -- [Resource.Material.Metal] [Rarity.Rare] (90 items)
    { item="Base.Aluminum", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.AluminumFragments", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.AluminumScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.BenchAnvil", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BenchAnvilUntreated", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BlacksmithAnvil", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvil", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvilUntreated", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.BrassIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.BrassScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.Bullhorn", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Calipers", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.CopperIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.CopperScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.CopperSheet", basePrice=109, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchVise", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchViseParts", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBlade", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.DrawPlate", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.GoldBar", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.GoldCoin", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.GoldScrap", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.GoldSheet", basePrice=51, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.HeadingTool", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.IronBand", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.IronBandSmall", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.IronBarMold", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.IronBarQuarter", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.IronBlock", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.IronBloom", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.IronChunk", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.IronIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.IronIngotMold", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.IronPiece", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.IronScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.JarLid", basePrice=20, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.Katana_Blade", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Katana_Blade_Broken", basePrice=2, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.KeyPadlock", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.LargeMeteorite", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.Leash", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.Lighter", basePrice=21, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.LighterBBQ", basePrice=20, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.LighterDisposable", basePrice=20, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.LongCrudeBlade", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Loupe", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.MarigoldBagSeed_Empty", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.MeatCleaverBlade", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Oxygen_Tank", basePrice=18, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PackFrame", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PackFrameLarge", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PiercedIronBlock", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PiercedIronChunk", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.PiercedIronIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.PiercedSteelBlock", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.PiercedSteelChunk", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.PiercedSteelIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.Pocketwatch", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.ScrapMetal", basePrice=13, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.SheepShears", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SheepShearsForged", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SheetMetal", basePrice=101, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SilverBar", basePrice=6, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.SilverCoin", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.SilverScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=100} },
    { item="Base.SilverSheet", basePrice=32, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SmallCopperSheet", basePrice=34, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SmallGoldBar", basePrice=13, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SmallSheetMetal", basePrice=32, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SmallSilverBar", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.SpadeHead_Forged", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.SpearLongHead", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.Stapler", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.Staples", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.SteelBarMold", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.SteelBarQuarter", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SteelBlock", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.SteelChunk", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SteelIngot", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.SteelIngotMold", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.SteelPiece", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.SteelRodQuarter", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SteelScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SteelSlug", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.Thimble", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.Tsquare", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=20} },
    { item="Base.TuningFork", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=50} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.WoodenIngotCastMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
})

print("[DynamicTrading] Metal Registry Complete")
