-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material.Metal] [Rarity.Common] (4 items)
    { item="Base.Badge", basePrice=542, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=535, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.DogTag_Pet", basePrice=542, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },
    { item="Base.DogTag_Pet_Blank", basePrice=542, tags={"Resource.Material.Metal", "Rarity.Common", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=4, max=26} },

    -- [Resource.Material.Metal] [Rarity.Rare] (89 items)
    { item="Base.Aluminum", basePrice=995, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumFragments", basePrice=995, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumScrap", basePrice=292, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Aluminum", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.BenchAnvil", basePrice=969, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BenchAnvilUntreated", basePrice=969, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvil", basePrice=964, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=964, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvil", basePrice=987, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvilUntreated", basePrice=987, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BrassIngot", basePrice=1022, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Brass", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BrassScrap", basePrice=294, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Brass", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.Bullhorn", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.Calipers", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.CopperIngot", basePrice=1028, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.CopperScrap", basePrice=295, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.CopperSheet", basePrice=1128, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBenchVise", basePrice=973, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBenchViseParts", basePrice=973, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBlade", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.DrawPlate", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.GoldBar", basePrice=3580, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.GoldCoin", basePrice=3563, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Coin", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.GoldScrap", basePrice=3533, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.GoldSheet", basePrice=3651, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.HeadingTool", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBand", basePrice=999, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Band", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBandSmall", basePrice=999, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Band", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBarMold", basePrice=970, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronBarQuarter", basePrice=1009, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBlock", basePrice=1012, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBloom", basePrice=984, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Bloom", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronChunk", basePrice=1003, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronIngot", basePrice=1013, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronIngotMold", basePrice=970, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronPiece", basePrice=990, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Piece", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.IronScrap", basePrice=293, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=10} },
    { item="Base.JarLid", basePrice=992, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Katana_Blade", basePrice=994, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Katana_Blade_Broken", basePrice=298, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.KeyPadlock", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=28} },
    { item="Base.LargeMeteorite", basePrice=964, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Leash", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Lighter", basePrice=1002, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LighterBBQ", basePrice=1000, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.LighterDisposable", basePrice=1000, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LongCrudeBlade", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.Loupe", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.MeatCleaverBlade", basePrice=994, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.Oxygen_Tank", basePrice=999, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrame", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrameLarge", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronBlock", basePrice=1012, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronChunk", basePrice=1003, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.PiercedIronIngot", basePrice=1019, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Iron", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.PiercedSteelBlock", basePrice=1035, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.PiercedSteelChunk", basePrice=1026, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.PiercedSteelIngot", basePrice=1022, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Pocketwatch", basePrice=976, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.ScrapMetal", basePrice=300, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SheepShears", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheepShearsForged", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheetMetal", basePrice=1122, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SilverBar", basePrice=1042, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SilverCoin", basePrice=1029, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Coin", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SilverScrap", basePrice=303, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=13} },
    { item="Base.SilverSheet", basePrice=1084, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.SmallCopperSheet", basePrice=1058, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Copper", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SmallGoldBar", basePrice=3586, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Resource.Material.MetalFamily.Gold", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SmallSheetMetal", basePrice=1053, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Sheet", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SmallSilverBar", basePrice=1044, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Silver", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SpadeHead_Forged", basePrice=980, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.SpearLongHead", basePrice=994, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=3} },
    { item="Base.Stapler", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Staples", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelBarMold", basePrice=979, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelBarQuarter", basePrice=1032, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Bar", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelBlock", basePrice=1035, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Block", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelChunk", basePrice=1026, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Chunk", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelIngot", basePrice=1022, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Ingot", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelIngotMold", basePrice=979, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelPiece", basePrice=999, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Piece", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelRodQuarter", basePrice=1000, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Rod", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SteelScrap", basePrice=300, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Scrap", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SteelSlug", basePrice=1000, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalFamily.Steel", "Resource.Material.MetalForm.Slug", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Thimble", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Tsquare", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.TuningFork", basePrice=974, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=960, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.WoodenIngotCastMold", basePrice=960, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Vanilla", "Resource.Material.MetalForm.Mold", "Resource.Craftable"}, stockRange={min=0, max=8} },
})

print("[DynamicTrading] Metal Registry Complete")
