-- ============================================================================
-- DT_Material.lua
-- Resource Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_Material = DT_Material or {}
DT_Material.items = {
    -- Added by ItemGenerator
    { item="Base.WalkieTalkie1", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie2", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie3", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie4", basePrice=40, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie5", basePrice=33, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkieMakeShift", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ManPackRadio", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HamRadio1", basePrice=3, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.HamRadio2", basePrice=3, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.HamRadioMakeShift", basePrice=3, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.CDplayer", basePrice=62, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TvAntique", basePrice=5, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.TvBlack", basePrice=5, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.TvWideScreen", basePrice=5, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.Garbagebag_box", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CeramicCrucible_Iron", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucible_Steel", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Iron", basePrice=9, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Steel", basePrice=9, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TestWaterMug", basePrice=62, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayMilk", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayAphids", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayCigarettes", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Hairgel", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Hairspray2", basePrice=62, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Lipstick", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MakeupEyeshadow", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MakeupFoundation", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AnimalMilkPowder", basePrice=38, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.AnimalFeedBag", basePrice=12, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GrassBag", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepElectricShears", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.InsectRepellent", basePrice=62, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WaterPurificationTablets", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Woodglue", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Soap2", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Claybag", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Dirtbag", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Gravelbag", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Sandbag", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BucketClayCement", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketConcreteFull", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedClayCement", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedConcreteFull", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketPlasterFull", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedPlasterFull", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DuctTape", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Epoxy", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FiberglassTape", basePrice=62, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Glue", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Wire", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BucketWallpaperPaste", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedWallpaperPaste", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_BeigeStripe", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_BlackFloral", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_BlueStripe", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_GreenDiamond", basePrice=5, tags={"Resource.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_GreenFloral", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_PinkChevron", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_PinkFloral", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Battery", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SlugRepellent", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BBQStarterFluid", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Lighter", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LighterDisposable", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LighterFluid", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MagnesiumFirestarter", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Matchbox", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FishingLine", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PremiumFishingLine", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Yeast", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.BakingSoda", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GravyMix", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.PancakeMix", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Vinegar2", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Vinegar_Jug", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CompostBag", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Fertilizer", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicCrucibleWithGlass", basePrice=8, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PaperNapkins2", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.HandTorch", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FlashLight_AngleHead", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FlashLight_AngleHead_Army", basePrice=100, tags={"Resource.Material", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=30} },
    { item="Base.Torch", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PenLight", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Lantern_HurricaneLit", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_CopperLit", basePrice=25, tags={"Resource.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Copper", basePrice=25, tags={"Resource.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_ForgedLit", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Forged", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_GoldLit", basePrice=25, tags={"Resource.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Gold", basePrice=25, tags={"Resource.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_SilverLit", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Silver", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_CraftedElectric", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flashlight_Crafted", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.AlcoholedCottonBalls", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AlcoholWipes", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.TissueBox", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WeldingRods", basePrice=33, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BlowTorch", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Extinguisher", basePrice=25, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GunPowder", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Oxygen_Tank", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RatPoison", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RespiratorFilters", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.RespiratorFiltersRecharged", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CorrectionFluid", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LighterBBQ", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Twine", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PaintBlack", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintBlue", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintBrown", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintCyan", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintGreen", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintGrey", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintLightBlue", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintLightBrown", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintOrange", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintPink", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintPurple", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintRed", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintTurquoise", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintWhite", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintYellow", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SprayPaint", basePrice=50, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Matches", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CigarettePack", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CigaretteRollingPapers", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.TobaccoLoose", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.TobaccoChewing", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Candle", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CandleLit", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.BathTowel", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.DishCloth", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FabricRoll_Cotton", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimBlack", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimBlue", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimDarkBlue", basePrice=5, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Thread", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Aramid", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Sinew", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SteelWool", basePrice=166, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CarBattery1", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarBattery2", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarBattery3", basePrice=10, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lighter_Battery", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.DentalFloss", basePrice=500, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.RemouladeFull", basePrice=100, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Sugar", basePrice=83, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },

    -- Added by ItemGenerator
    { item="Base.GunLight", basePrice=250, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },


}

return DT_Material.items
