-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material.Metal] [Rarity.Common] (4 items)
    { item="Base.Badge", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=4, max=27} },
    { item="Base.BlacksmithAnvilAssembled", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.DogTag_Pet", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=4, max=27} },
    { item="Base.DogTag_Pet_Blank", basePrice=7, tags={"Resource.Material.Metal", "Rarity.Common", "Resource.Craftable"}, stockRange={min=4, max=27} },

    -- [Resource.Material.Metal] [Rarity.Rare] (90 items)
    { item="Base.Aluminum", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumFragments", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.AluminumScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=9} },
    { item="Base.BenchAnvil", basePrice=5, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BenchAnvilUntreated", basePrice=5, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvil", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvil", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BlockAnvilUntreated", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.BrassIngot", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.BrassScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=9} },
    { item="Base.Bullhorn", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.Calipers", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.CopperIngot", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.CopperScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.CopperSheet", basePrice=111, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.CrudeBenchVise", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBenchViseParts", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBlade", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.DrawPlate", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.GoldBar", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.GoldCoin", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=21} },
    { item="Base.GoldScrap", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=21} },
    { item="Base.GoldSheet", basePrice=53, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=5} },
    { item="Base.HeadingTool", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBand", basePrice=15, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBandSmall", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBarMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronBarQuarter", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronBlock", basePrice=15, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.IronBloom", basePrice=5, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronChunk", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.IronIngot", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronIngotMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.IronPiece", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.IronScrap", basePrice=5, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=9} },
    { item="Base.JarLid", basePrice=28, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Katana_Blade", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.Katana_Blade_Broken", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.KeyPadlock", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.LargeMeteorite", basePrice=4, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Leash", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Lighter", basePrice=37, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LighterBBQ", basePrice=36, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.LighterDisposable", basePrice=36, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.LongCrudeBlade", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.Loupe", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.MarigoldBagSeed_Empty", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=21} },
    { item="Base.MeatCleaverBlade", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.Oxygen_Tank", basePrice=35, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrame", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PackFrameLarge", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronBlock", basePrice=15, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedIronChunk", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.PiercedIronIngot", basePrice=14, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.PiercedSteelBlock", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.PiercedSteelChunk", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.PiercedSteelIngot", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.Pocketwatch", basePrice=11, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.ScrapMetal", basePrice=15, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SheepShears", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheepShearsForged", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SheetMetal", basePrice=123, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.SilverBar", basePrice=8, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SilverCoin", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=30} },
    { item="Base.SilverScrap", basePrice=3, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=36} },
    { item="Base.SilverSheet", basePrice=33, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SmallCopperSheet", basePrice=36, tags={"Resource.Material.Metal", "Rarity.Rare", "Origin.Police", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SmallGoldBar", basePrice=15, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Luxury", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SmallSheetMetal", basePrice=54, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SmallSilverBar", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SpadeHead_Forged", basePrice=16, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SpearLongHead", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=4} },
    { item="Base.Stapler", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.Staples", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelBarMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelBarQuarter", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelBlock", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=2} },
    { item="Base.SteelChunk", basePrice=30, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.SteelIngot", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelIngotMold", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=1} },
    { item="Base.SteelPiece", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.SteelRodQuarter", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.SteelScrap", basePrice=9, tags={"Resource.Material.Metal", "Rarity.Rare", "Quality.Waste", "Resource.Craftable"}, stockRange={min=0, max=7} },
    { item="Base.SteelSlug", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Thimble", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.Tsquare", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=6} },
    { item="Base.TuningFork", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=14} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
    { item="Base.WoodenIngotCastMold", basePrice=10, tags={"Resource.Material.Metal", "Rarity.Rare", "Resource.Craftable"}, stockRange={min=0, max=8} },
})

print("[DynamicTrading] Metal Registry Complete")
