-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Material] [Rarity.Common] (3 items)
    { item="Base.HamRadio1", basePrice=1, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.HamRadio2", basePrice=1, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.HamRadioMakeShift", basePrice=1, tags={"Resource.Material", "Rarity.Common"}, stockRange={min=1, max=4} },

    -- [Resource.Material] [Rarity.Rare] (122 items)
    { item="Base.AlcoholedCottonBalls", basePrice=170, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AlcoholWipes", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.AnimalFeedBag", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BakingSoda", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.BathTowel", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Battery", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.BBQStarterFluid", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.BlowTorch", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Candle", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CandleLit", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CarBattery1", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarBattery2", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarBattery3", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CDplayer", basePrice=17, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CeramicCrucible_Iron", basePrice=1, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucible_Steel", basePrice=1, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Iron", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Steel", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleWithGlass", basePrice=2, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CigarettePack", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CigaretteRollingPapers", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Claybag", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CompostBag", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CorrectionFluid", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.DentalFloss", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Dirtbag", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DishCloth", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.DuctTape", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Epoxy", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Extinguisher", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Fertilizer", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FiberglassTape", basePrice=17, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FishingLine", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FlashLight_AngleHead", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.FlashLight_AngleHead_Army", basePrice=27, tags={"Resource.Material", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=30} },
    { item="Base.Flashlight_Crafted", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Garbagebag_box", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayAphids", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayCigarettes", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GardeningSprayMilk", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Glue", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GrassBag", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Gravelbag", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GravyMix", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.GunLight", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.GunPowder", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Hairgel", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Hairspray2", basePrice=17, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.HandTorch", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.InsectRepellent", basePrice=17, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Lantern_CraftedElectric", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Copper", basePrice=7, tags={"Resource.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_CopperLit", basePrice=7, tags={"Resource.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Forged", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_ForgedLit", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Gold", basePrice=7, tags={"Resource.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_GoldLit", basePrice=7, tags={"Resource.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_Silver", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_Hurricane_SilverLit", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lantern_HurricaneLit", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Lighter", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Lighter_Battery", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LighterBBQ", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.LighterDisposable", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LighterFluid", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Lipstick", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MagnesiumFirestarter", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MakeupEyeshadow", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MakeupFoundation", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ManPackRadio", basePrice=1, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Matchbox", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Matches", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Oxygen_Tank", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintBlack", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintBlue", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintBrown", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintCyan", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintGreen", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintGrey", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintLightBlue", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintLightBrown", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintOrange", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintPink", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintPurple", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintRed", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintTurquoise", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintWhite", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaintYellow", basePrice=3, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PancakeMix", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.PaperNapkins2", basePrice=64, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.PenLight", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.PremiumFishingLine", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.RatPoison", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RespiratorFilters", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.RespiratorFiltersRecharged", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Sandbag", basePrice=7, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepElectricShears", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SlugRepellent", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Soap2", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SprayPaint", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SteelWool", basePrice=85, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.TestWaterMug", basePrice=21, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Thread", basePrice=136, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Aramid", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Sinew", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.TissueBox", basePrice=102, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TobaccoChewing", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.TobaccoLoose", basePrice=45, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Torch", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Twine", basePrice=27, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.WalkieTalkie1", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie2", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie3", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie4", basePrice=11, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkie5", basePrice=9, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WalkieTalkieMakeShift", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WaterPurificationTablets", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.WeldingRods", basePrice=9, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Wire", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Woodglue", basePrice=14, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Yeast", basePrice=68, tags={"Resource.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
})

print("[DynamicTrading] Material Registry Complete")
