-- ============================================================================
-- Resource Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Resource.Parts] [Rarity.Rare] (95 items)
    { item="Base.BallPeenHammerHead", basePrice=68, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CeramicCrucibleSmallUnfired", basePrice=8, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicCrucibleUnfired", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CeramicIngotCastUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CeramicMortarandPestleUnfired", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicTeacupUnfired", basePrice=8, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CircularSawblade", basePrice=17, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CircularSawblade_Half", basePrice=17, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ClawhammerHead", basePrice=68, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBarMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBarMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBenchAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBenchAnvilMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBlacksmithAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBlacksmithAnvilMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBlockAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBlockAnvilMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBowlUnfired", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBrickUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayCrudeBenchVisePartsMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayCrudeBenchVisePartsMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayIngotMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayIngotMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayJarUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayMugUnfired", basePrice=8, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ClayPipeSegmentUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayPlateUnfired", basePrice=8, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ClayPotUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClaySheetMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClaySheetMoldUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayShingleUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayTileUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClubHammerHead", basePrice=17, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CrudeBlade", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CrudeShortSwordBlade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CrudeShortSwordBlade_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CrudeSword_Shard", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CrudeSwordBlade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CrudeSwordBlade_Broken", basePrice=1, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.CrudeSwordBlade_Broken_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.CrudeSwordBlade_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.FireAxeHead", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.GardenHoeHead", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GlassBlowingPipeUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HacksawBlade", basePrice=68, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HandAxeHead", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HandScytheBlade", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HatchetHead_Bone", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingKnifeBlade", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronBarMold", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.IronIngotMold", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Katana_Blade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Katana_Blade_Broken", basePrice=1, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.Katana_Shard", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.KitchenKnifeBlade", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.LargeKnifeBlade", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LongCrudeBlade", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MaceHead", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MacheteBlade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.MacheteBlade_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.MeatCleaverBlade", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.OldAxeHead", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.PickAxeHead", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ScytheBlade", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShortSwordBlade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShortSwordBlade_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SledgehammerHead", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallSawblade", basePrice=68, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmithingHammerHead", basePrice=68, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SmokingPipeUnfired", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SpadeHead_Forged", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SpearHead", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SteelBarMold", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SteelIngotMold", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.StoneAxeHead", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneBlade", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.StoneBladeLong", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneMaceHead", basePrice=2, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Sword_Scrap_Shard", basePrice=3, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=6} },
    { item="Base.Sword_Shard", basePrice=3, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.SwordBlade", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.SwordBlade_Broken", basePrice=1, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.SwordBlade_Broken_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.SwordBlade_NoTang", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.WoodAxeHead", basePrice=1, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.WoodenBarCastMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenBenchAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenBlacksmithAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenBlockAnvilMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenBrickMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenCrucibleMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenIngotCastMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenShingleMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WoodenTileMold", basePrice=6, tags={"Resource.Parts", "Rarity.Rare"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Parts Registry Complete")
