-- =============================================================================
-- GEOLOCATOR SYSTEM: DATA
-- =============================================================================

DT_GeolocatorSystem = DT_GeolocatorSystem or {}

DT_GeolocatorSystem.MOD_DATA_KEY = "DT_Buildings"
DT_GeolocatorSystem.ActiveLocations = DT_GeolocatorSystem.ActiveLocations or {}
DT_GeolocatorSystem.LocationIndex = DT_GeolocatorSystem.LocationIndex or {}
DT_GeolocatorSystem.RegionCandidates = DT_GeolocatorSystem.RegionCandidates or {}
DT_GeolocatorSystem.RegionCandidatesDirty = true
DT_GeolocatorSystem.CacheInitialized = DT_GeolocatorSystem.CacheInitialized or false

DT_GeolocatorSystem.KnownLocations = DT_GeolocatorSystem.KnownLocations or {
    {
        longName = "Bunker, March Ridge, KY",
        shortName = "March Ridge Bunker",
        id = "marchridge_bunker",
        mod = "Vanilla",
        isVanilla = true,
        startX = 9902,
        endX = 9950,
        startY = 12589,
        endY = 12662,
    },
    {
        longName = "Dixie, KY",
        shortName = "Dixie",
        id = "dixie",
        mod = "Vanilla",
        isVanilla = true,
        startX = 5400,
        endX = 5700,
        startY = 9300,
        endY = 9900,
    },
    {
        longName = "Doe Valley, KY",
        shortName = "Doe Valley",
        id = "doe_valley",
        mod = "Vanilla",
        isVanilla = true,
        startX = 6600,
        endX = 6900,
        startY = 9900,
        endY = 10200,
    },
    {
        longName = "Fallas Lake, KY",
        shortName = "Fallas Lake",
        id = "fallas_lake",
        mod = "Vanilla",
        isVanilla = true,
        startX = 6900,
        endX = 7500,
        startY = 8100,
        endY = 8700,
    },
    {
        longName = "Louisville, KY",
        shortName = "Louisville",
        id = "louisville",
        mod = "Vanilla",
        isVanilla = true,
        startX = 11700,
        endX = 14100,
        startY = 1200,
        endY = 4500,
    },
    {
        longName = "Muldraugh, KY",
        shortName = "Muldraugh",
        id = "muldraugh",
        mod = "Vanilla",
        isVanilla = true,
        startX = 10500,
        endX = 11100,
        startY = 9000,
        endY = 10800,
    },
    {
        longName = "March Ridge, KY",
        shortName = "March Ridge",
        id = "march_ridge",
        mod = "Vanilla",
        isVanilla = true,
        startX = 9600,
        endX = 10500,
        startY = 12300,
        endY = 13200,
    },
    {
        longName = "Riverside, KY",
        shortName = "Riverside",
        id = "riverside",
        mod = "Vanilla",
        isVanilla = true,
        startX = 5700,
        endX = 6900,
        startY = 5100,
        endY = 5700,
    },
    {
        longName = "Riverside Trailer Park, KY",
        shortName = "Riverside Trailer Park",
        id = "riverside_trailer_park",
        mod = "Vanilla",
        isVanilla = true,
        startX = 5100,
        endX = 5400,
        startY = 5700,
        endY = 6300,
    },
    {
        longName = "Rosewood, KY",
        shortName = "Rosewood",
        id = "rosewood",
        mod = "Vanilla",
        isVanilla = true,
        startX = 7900,
        endX = 8700,
        startY = 11100,
        endY = 12300,
    },
    {
        longName = "Kentucky State Prison, KY",
        shortName = "Kentucky State Prison",
        id = "kentucky_state_prison",
        mod = "Vanilla",
        isVanilla = true,
        startX = 7500,
        endX = 7840,
        startY = 11800,
        endY = 12000,
    },
    {
        longName = "Valley Station, KY",
        shortName = "Valley Station",
        id = "valley_station",
        mod = "Vanilla",
        isVanilla = true,
        startX = 12300,
        endX = 13200,
        startY = 4500,
        endY = 6300,
    },
    {
        longName = "West Point, KY",
        shortName = "West Point",
        id = "west_point",
        mod = "Vanilla",
        isVanilla = true,
        startX = 10800,
        endX = 12600,
        startY = 6600,
        endY = 7500,
    },
    {
        longName = "Echo Creek, KY",
        shortName = "Echo Creek",
        id = "echo_creek",
        mod = "Vanilla",
        isVanilla = true,
        startX = 3365,
        endX = 3894,
        startY = 10854,
        endY = 11394,
    },
    {
        longName = "Ekron, KY",
        shortName = "Ekron",
        id = "ekron",
        mod = "Vanilla",
        isVanilla = true,
        startX = 1,
        endX = 1150,
        startY = 9221,
        endY = 10477,
    },
    {
        longName = "Scenic Grove Mobile Home Park, KY",
        shortName = "Scenic Grove Mobile Home Park",
        id = "scenic_grove_mobile_home_park",
        mod = "Vanilla",
        isVanilla = true,
        startX = 5248,
        endX = 5634,
        startY = 5840,
        endY = 6140,
    },
    {
        longName = "Brandenburg, KY",
        shortName = "Brandenburg",
        id = "brandenburg",
        mod = "Vanilla",
        isVanilla = true,
        startX = 798,
        endX = 3090,
        startY = 5115,
        endY = 7484,
    },
    {
        longName = "Irvington, KY",
        shortName = "Irvington",
        id = "irvington",
        mod = "Vanilla",
        isVanilla = true,
        startX = 822,
        endX = 3881,
        startY = 12557,
        endY = 15044,
    },
}