-- ============================================================================
-- Generated Fluid Registry for Dynamic Trading
-- This file is generated by Scripts/ItemGenerator. Do not hand-edit it.
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.Fluids = DynamicTrading.Fluids or {}

local registry = {
    ["Beer"] = { basePricePerLiter=90.0, tags={"Fluid.Drink.Alcohol"}, displayName="Beer", sourceItems={"Base.BeerBottle", "Base.BeerCan", "Base.BeerImported"} },
    ["Bleach"] = { basePricePerLiter=38.0, tags={"Fluid.Cleaning.Bleach"}, displayName="Bleach", sourceItems={"Base.Bleach"} },
    ["Brandy"] = { basePricePerLiter=40.0, tags={"Fluid.Drink.Alcohol"}, displayName="Brandy", sourceItems={"Base.Brandy"} },
    ["Champagne"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Champagne", sourceItems={"Base.Champagne"} },
    ["Cider"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Cider", sourceItems={"Base.Cider"} },
    ["CleaningLiquid"] = { basePricePerLiter=60.0, tags={"Fluid.Cleaning.General"}, displayName="Cleaning Liquid", sourceItems={"Base.CleaningLiquid2"} },
    ["CoffeeLiqueur"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Coffee Liqueur", sourceItems={"Base.CoffeeLiquer"} },
    ["Cola"] = { basePricePerLiter=80.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Cola", sourceItems={"Base.Pop2"} },
    ["ColaDiet"] = { basePricePerLiter=80.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Diet Cola", sourceItems={"Base.Pop"} },
    ["Cologne"] = { basePricePerLiter=260.0, tags={"Fluid.Appearance.Cosmetic"}, displayName="Cologne", sourceItems={"Base.Cologne"} },
    ["CowMilk"] = { basePricePerLiter=33.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Milk", sourceItems={"Base.Milk", "Base.MilkBottle", "Base.Milk_Personalsized"} },
    ["Curacao"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Curacao", sourceItems={"Base.Curacao"} },
    ["Gin"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Gin", sourceItems={"Base.Gin"} },
    ["GingerAle"] = { basePricePerLiter=80.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Ginger Ale", sourceItems={"Base.Pop3"} },
    ["Grenadine"] = { basePricePerLiter=30.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Grenadine", sourceItems={"Base.Grenadine"} },
    ["JuiceApple"] = { basePricePerLiter=115.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Apple", sourceItems={"Base.JuiceBoxApple"} },
    ["JuiceCranberry"] = { basePricePerLiter=33.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Cranberry", sourceItems={"Base.JuiceCranberry"} },
    ["JuiceFruitpunch"] = { basePricePerLiter=74.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Fruit Punch", sourceItems={"Base.JuiceBoxFruitpunch", "Base.JuiceFruitpunch"} },
    ["JuiceGrape"] = { basePricePerLiter=74.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Grape", sourceItems={"Base.JuiceBox", "Base.JuiceGrape"} },
    ["JuiceLemon"] = { basePricePerLiter=33.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Lemon", sourceItems={"Base.JuiceLemon"} },
    ["JuiceOrange"] = { basePricePerLiter=74.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Orange", sourceItems={"Base.JuiceBoxOrange", "Base.JuiceOrange"} },
    ["JuiceTomato"] = { basePricePerLiter=33.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Juice Tomato", sourceItems={"Base.JuiceTomato"} },
    ["MilkChocolate"] = { basePricePerLiter=96.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Chocolate Milk", sourceItems={"Base.MilkChocolate_Personalsized"} },
    ["Perfume"] = { basePricePerLiter=260.0, tags={"Fluid.Appearance.Cosmetic"}, displayName="Perfume", sourceItems={"Base.Perfume"} },
    ["Petrol"] = { basePricePerLiter=25.65, tags={"Fluid.Fuel.Gasoline"}, displayName="Gasoline", sourceItems={"Base.JerryCan", "Base.PetrolCan"} },
    ["Port"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Port", sourceItems={"Base.Port"} },
    ["RubbingAlcohol"] = { basePricePerLiter=70.0, tags={"Fluid.Medical.Alcohol"}, displayName="Rubbing Alcohol", sourceItems={"Base.Disinfectant"} },
    ["Rum"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Rum", sourceItems={"Base.Rum"} },
    ["Scotch"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Scotch", sourceItems={"Base.Scotch"} },
    ["Sherry"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Sherry", sourceItems={"Base.Sherry"} },
    ["SimpleSyrup"] = { basePricePerLiter=33.0, tags={"Fluid.Drink.NonAlcoholic"}, displayName="Simple Syrup", sourceItems={"Base.SimpleSyrup"} },
    ["TaintedWater"] = { basePricePerLiter=60.0, tags={"Fluid.Water.Tainted"}, displayName="Tainted Water", sourceItems={"Base.WaterDish"} },
    ["Tequila"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Tequila", sourceItems={"Base.Tequila"} },
    ["Vermouth"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Vermouth", sourceItems={"Base.Vermouth"} },
    ["Vodka"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Vodka", sourceItems={"Base.Vodka"} },
    ["Water"] = { basePricePerLiter=14.3, tags={"Fluid.Water"}, displayName="Water", sourceItems={"Base.Bag_HydrationBackpack", "Base.Bag_HydrationBackpack_Camo", "Base.Bag_LeatherWaterBag", "Base.BucketWaterDebug", "Base.Canteen", "Base.CanteenCowboy", "Base.CanteenMilitaryFull", "Base.DebugFluid", "Base.FountainCupWater", "Base.Sportsbottle", "Base.TestDebugWater", "Base.WaterDispenserBottle"} },
    ["Whiskey"] = { basePricePerLiter=40.0, tags={"Fluid.Drink.Alcohol"}, displayName="Whiskey", sourceItems={"Base.Whiskey"} },
    ["Wine"] = { basePricePerLiter=39.0, tags={"Fluid.Drink.Alcohol"}, displayName="Wine", sourceItems={"Base.Wine", "Base.Wine2", "Base.Wine2Open", "Base.WineAged", "Base.WineBox", "Base.WineOpen", "Base.WineScrewtop"} },
}

for fluidKey, data in pairs(registry) do
    DynamicTrading.Fluids[fluidKey] = data
    if string.sub(fluidKey, 1, 5) ~= "Base." then
        DynamicTrading.Fluids["Base." .. fluidKey] = data
    end
end

print("[DynamicTrading] Fluid Registry Complete")
