-- ============================================================================
-- Literature Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Literature.Book] [Rarity.Common] (4 items)
    { item="Base.LetterHandwritten", basePrice=481, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Note", basePrice=481, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Photo", basePrice=481, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },
    { item="Base.Photo_VeryOld", basePrice=481, tags={"Literature.Book", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=25} },

    -- [Literature.Book] [Rarity.Rare] (182 items)
    { item="Base.Book", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_AdventureNonFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Art", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Baseball", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Bible", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Biography", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Business", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Childs", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Cinema", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Classic", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_ClassicFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_ClassicNonfiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Computer", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_CrimeFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fantasy", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Farming", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fashion", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Fiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_GeneralNonFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_GeneralReference", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Golf", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_History", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Horror", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Legal", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_LiteraryFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Medical", basePrice=790, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=3} },
    { item="Base.Book_Military", basePrice=844, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.Book_MilitaryHistory", basePrice=844, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.Book_Music", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Nature", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Occult", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Philosophy", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Policing", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Politics", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Quackery", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Religion", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Rich", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Romance", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SadNonFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SchoolTextbook", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Science", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_SciFi", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Sports", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Thriller", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Travel", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.Book_Western", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookAimingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookBlacksmithSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookButcheringSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCarpentrySet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCarvingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookCookingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookElectricianSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFancy_Bible", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Classic", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_ClassicFiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_ClassicNonfiction", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_History", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Legal", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Medical", basePrice=790, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=3} },
    { item="Base.BookFancy_MilitaryHistory", basePrice=844, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=3} },
    { item="Base.BookFancy_Occult", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Philosophy", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Politics", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFancy_Religion", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.BookFarmingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFirstAidSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFishingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookFlintKnappingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookForagingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookGlassmakingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookHusbandrySet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookLongBladeSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMaintenanceSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMasonrySet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMechanicsSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookMetalWeldingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookPotterySet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookReloadingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTailoringSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTrackingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.BookTrappingSet", basePrice=703, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Brochure", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Catalog", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.ChildsPictureBook", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Diary1", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Diary2", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Doodle", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.DoodleKids", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Flier", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Flier_Nolans", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.GenericMail", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.GraphPaper", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.HottieZ", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.HottieZ_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.IDcard", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.IndexCard", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Journal", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.MenuCard", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Newspaper", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Dispatch_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Herald_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Knews_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Recent", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Newspaper_Times_New", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Notebook", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Notepad", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.OfficialDocument", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Paperback", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_AdventureNonFiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Art", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Baseball", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Bible", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Biography", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Business", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Childs", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Cinema", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Classic", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_ClassicFiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_ClassicNonfiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Computer", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Conspiracy", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_CrimeFiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Diet", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fantasy", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fashion", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Fiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Golf", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Hass", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_History", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Horror", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Legal", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_LiteraryFiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Medical", basePrice=790, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Military", basePrice=845, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_MilitaryHistory", basePrice=845, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=6} },
    { item="Base.Paperback_Music", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Nature", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_NewAge", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Occult", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Philosophy", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Play", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Policing", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Politics", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Poor", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Quackery", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Quigley", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Relationship", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Religion", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Rich", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Romance", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SadNonFiction", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Scary", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Science", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SciFi", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_SelfHelp", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Sexy", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Sports", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Teens", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Thriller", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Travel", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_TrueCrime", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperback_Western", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Paperwork", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ParkingTicket", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Passport", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Phonebook", basePrice=704, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Photo_Hass", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Photo_Racy", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Photo_Secret", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.PhotoBook", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.PressID", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.Receipt", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=27} },
    { item="Base.RPGmanual", basePrice=705, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=5} },
    { item="Base.ScratchTicket", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ScratchTicket_Loser", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.ScratchTicket_Winner", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.SewingPattern", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.SheetPaper2", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.SpeedingTicket", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
    { item="Base.StockCertificate", basePrice=706, tags={"Literature.Book", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=13} },
})

print("[DynamicTrading] Book Registry Complete")
