DynamicTrading = DynamicTrading or {}

if not DynamicTrading.RegisterInteractionStrings then
    return nil
end

DynamicTrading.RegisterInteractionStrings("Lottery", "Wallet", {
    Anticipation = {
        "Sorry, pal, you don't need this anymore...",
        "Let's see who you were...",
        "Feels heavy, that's a good sign...",
        "Nice leather. Hope it's full.",
        "Please be cash, not just receipts...",
        "Forgive me...",
        "Just need a little help here...",
        "Let's see what you're hiding.",
        "Don't let me down.",
        "Rent's due in hell, I guess.",
        "Checking the folds...",
        "Zipper is stuck... come on.",
        "Who were you? A banker? A mechanic?",
        "Blood on the corner... grim.",
        "This one feels thick.",
        "Just one lucky break, please.",
        "I promise to spend it well.",
        "Maybe enough for some gas?",
        "Velcro wallet? Probably empty.",
        "Let's check the secret compartment."
    },
    BulkStart = {
        "Grim work, sorting through these.",
        "Let's see what the dead left behind.",
        "Okay, let's see if anyone was carrying cash.",
        "Sorting time. Hope it's worth the guilt.",
        "Someone had to empty these eventually.",
        "Let's count the inheritance.",
        "A whole life in a pocket... let's look.",
        "Okay, systemizing the loot.",
        "Let's get this over with.",
        "Pockets to pile. Let's go.",
        "Starting the audit.",
        "Does anyone even use cash anymore? I do.",
        "Lined up and ready to check.",
        "Checking the harvest.",
        "Let's see who was prepared.",
        "This is going to take a minute.",
        "Systematic approach. Open, check, drop.",
        "Hope at least one of these is a winner.",
        "Sorting the dead's pockets. My life now.",
        "Let's see the total haul."
    },
    BulkLoop = {
        "Next...",
        "Another ID...",
        "Toss the plastic.",
        "Moving on...",
        "Just personal stuff...",
        "Checking...",
        "Emptying...",
        "Sorting...",
        "Aside.",
        "Flip it.",
        "And another.",
        "Check the coin pouch.",
        "Nothing interesting.",
        "Standard issue.",
        "Keep going.",
        "On to the next.",
        "Done with that one.",
        "Another leather one.",
        "Rummaging...",
        "Searching..."
    },
    Empty = {
        "Just a picture of their kids... damn.",
        "Video rental card. Useless now.",
        "Maxed out credit cards.",
        "Grocery receipt from July.",
        "Just a driver's license from Muldraugh.",
        "Nothing but dust and lint.",
        "Totally cleaned out.",
        "Just a library card.",
        "Business cards... 'Insurance Agent'.",
        "A folded gum wrapper. Great.",
        "Bone dry.",
        "Just an appointment card for the dentist.",
        "A shopping list: Milk, Eggs, Bread.",
        "Unpaid parking ticket. Lucky you.",
        "Just a gym membership card.",
        "Condom in the wrapper. Optimist.",
        "Social Security card. Identity theft is over.",
        "Just a frequent diner punch card.",
        "Checkbook. Can't cash these anymore.",
        "Absolutely nothing. Why carry it?"
    },
    Low = {
        "Couple of singles.",
        "Just loose change.",
        "Barely enough for a coffee.",
        "Lint and a quarter.",
        "He kept the big bills elsewhere.",
        "Pocket change.",
        "Better than nothing, I suppose.",
        "Couple of ones crumpled up.",
        "Just a fiver.",
        "Gas money, maybe.",
        "Thin pickings.",
        "Enough for a gumball.",
        "Just some pennies and a dime.",
        "Was this guy broke too?",
        "A wrinkled dollar bill.",
        "Spare change.",
        "Not exactly a fortune.",
        "Guess he spent it all.",
        "Just a few coins rattling around.",
        "Minimum wage wallet."
    },
    Medium = {
        "Okay, twenties. Not bad.",
        "This helps.",
        "Solid stash.",
        "Kept a little emergency fund.",
        "That's a week's worth of groceries.",
        "Nice and crisp.",
        "Respectable amount.",
        "Someone just got paid.",
        "Adding to the pile.",
        "Fair enough.",
        "Good find.",
        "This will buy some rounds.",
        "A decent handful of cash.",
        "Okay, we're getting somewhere.",
        "Not rich, but not poor.",
        "Useful paper.",
        "I'll take it.",
        "Lunch money secured.",
        "Someone was responsible.",
        "A few decent bills tucked away."
    },
    High = {
        "Holy... was this guy a banker?",
        "Stashed away for a rainy day!",
        "Thick wad of hundreds!",
        "Jackpot. Sorry pal, I need this more.",
        "This guy was loaded!",
        "Look at that stack...",
        "Retirement fund secured.",
        "Must have been heading to the casino.",
        "Unbelievable find.",
        "We are eating good tonight.",
        "Saving up for something big, huh?",
        "Motherlode!",
        "Did he just rob a bank?",
        "That is a LOT of cash.",
        "My hands are shaking... look at this.",
        "Who carries this much cash?!",
        "Top tier loot right here.",
        "Winner winner.",
        "I could buy a car with this... if they ran.",
        "This is what I'm talking about!"
    }
})

return DynamicTrading.GetInteractionStrings("Lottery", "Wallet")
