-- if isClient() and not isServer() then return end

require "DT/Common/Faction/TradingSys/DynamicTrading_Factions"
require "DT/Common/Faction/TradingSys/DynamicTrading_Roster"
require "DT/Common/Faction/TradingSys/Factions/SimulationConfig"
require "DT/Common/Trading/DT_Economy_Common"

DynamicTrading = DynamicTrading or {}
DynamicTrading.Economy = DynamicTrading.Economy or {}
DynamicTrading.Economy.V2 = {}

local Common = DynamicTrading.Economy.Common
print("[DynamicTrading] V2 Economy Module (Shared Wrapper) loaded.")

-- =============================================================================
-- 1. V2 STOCK GENERATOR (Wrapper) - SERVER ONLY
-- =============================================================================
function DynamicTrading.Economy.V2.GenerateStock(traderUUID)
    if isClient() and not isServer() then return {} end
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    if not soul then return {} end
    
    local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
    local archetype = DynamicTrading.Archetypes[soul.archetypeID] or DynamicTrading.Archetypes["General"]
    
    local masterList = DynamicTrading.Config.MasterList
    if not masterList then return {} end

    -- Difficulty (V2 might need its own or use Common)
    local diff = DynamicTrading.Config.GetDifficultyData()

    -- Modifiers (V2 specific)
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        globalStockMult = 1.0
    }
    
    -- [V2 Revamp] Event Integration (Unified)
    if DynamicTrading.Events and DynamicTrading.Events.UpdateFaction then
        modifiers.getVolumeModifier = function(tags)
            return DynamicTrading.Events.GetFactionVolumeModifier(faction, tags)
        end
        modifiers.eventInjections = DynamicTrading.Events.GetFactionInjections(faction)
        modifiers.expertTags = DynamicTrading.Events.GetFactionExpertTags(faction)
        modifiers.forbidTags = DynamicTrading.Events.GetFactionForbidTags(faction)
    end

    -- Delegate to Common
    local rawStock = Common.GenerateStock(archetype, masterList, diff, modifiers)

    -- Adapt to V2 Format { [item] = {qty=..., basePrice=..., dynamicMod=..., customData=...} }
    local finalItems = {}
    for itemKey, entry in pairs(rawStock) do
        local itemData = masterList[itemKey]
        if itemData then
            finalItems[itemKey] = {
                qty = entry.qty,
                basePrice = itemData.basePrice,
                dynamicMod = 1.0, -- Placeholder for dynamic pricing variations
                customData = entry.customData -- Already generated by Common!
            }
        end
    end
    
    return finalItems
end

-- =============================================================================
-- 2. V2 PRICING LOGIC (Wrapper)
-- =============================================================================

function DynamicTrading.Economy.V2.GetBuyPrice(traderUUID, itemFullType, customData, verbose, skipEvents)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 99999 end
    
    -- Always verbose if DynamicTrading.Debug is true
    verbose = verbose or DynamicTrading.Debug

    -- Fetch customData from stock if not provided (e.g. for server-side verification)
    if not customData then
        if soul.stocks and soul.stocks[itemFullType] then
            customData = soul.stocks[itemFullType].customData
        end
    end

    local engineData = DynamicTrading_Engine.GetEngineData()
    local globalHeat = engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {}

    local diff = DynamicTrading.Config.GetDifficultyData()
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        customData = customData,
        globalHeat = globalHeat,
        -- Event Modifiers (Unified Manager Integration)
        getPriceModifier = function(tags)
            if not skipEvents and DynamicTrading.Events and DynamicTrading.Events.GetFactionPriceModifier then
                local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
                return DynamicTrading.Events.GetFactionPriceModifier(faction, tags, verbose)
            end
            return 1.0
        end
    }
    
    local price = Common.GetBuyPrice(itemFullType, itemData, diff, modifiers, verbose)
    
    return price
end

function DynamicTrading.Economy.V2.GetSellPrice(traderUUID, itemObj, itemFullType, verbose, skipEvents)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 0 end
    
    -- Always verbose if DynamicTrading.Debug is true
    verbose = verbose or DynamicTrading.Debug

    local engineData = DynamicTrading_Engine.GetEngineData()
    local globalHeat = engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {}

    -- [NEW] Fetch Local Deflation from Stock
    local localDeflationCount = 0
    if DynamicTrading_Stock then
        local stockData = DynamicTrading_Stock.GetStock(traderUUID)
        if stockData and stockData.deflation then
            localDeflationCount = stockData.deflation[itemFullType] or 0
        end
    end

    local diff = DynamicTrading.Config.GetDifficultyData()
    local archetype = soul.archetypeID and DynamicTrading.Archetypes[soul.archetypeID]
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        globalHeat = globalHeat,
        localDeflationCount = localDeflationCount,
        -- Event Modifiers (Unified Manager Integration)
        getPriceModifier = function(tags)
            if not skipEvents and DynamicTrading.Events and DynamicTrading.Events.GetFactionPriceModifier then
                local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
                return DynamicTrading.Events.GetFactionPriceModifier(faction, tags, verbose)
            end
            return 1.0
        end
    }
    
    local price = Common.GetSellPrice(itemFullType, itemData, itemObj, diff, archetype, modifiers, verbose)
    
    return price
end
