-- if isClient() and not isServer() then return end

require "DT/Common/Faction/TradingSys/DynamicTrading_Factions"
require "DT/Common/Faction/TradingSys/RosterLogic/DT_RosterLogic"
require "DT/Common/Faction/TradingSys/Factions/SimulationLogic/DT_SimulationLogic_Config"
require "DT/Common/Trading/EconomyCommon/DT_EconomyCommon"

DynamicTrading = DynamicTrading or {}
DynamicTrading.Economy = DynamicTrading.Economy or {}
DynamicTrading.Economy.V2 = {}

local Common = DynamicTrading.Economy.Common
DynamicTrading.Log("DTCommons", "Init", "Economy", "V2 Economy Module (Shared Wrapper) loaded")

local function clampHeatValue(value)
    if value > 2.0 then return 2.0 end
    if value < -0.8 then return -0.8 end
    return value
end

local function copyHeatTable(source)
    local clone = {}
    for key, value in pairs(source or {}) do
        clone[key] = value
    end
    return clone
end

local function buildBuyPriceModifiers(soul, customData, globalHeat, verbose, skipEvents)
    return {
        tagsConfig = DynamicTrading.Config.Tags,
        customData = customData,
        globalHeat = globalHeat or {},
        getPriceModifier = function(tags)
            if not skipEvents and DynamicTrading.Events and DynamicTrading.Events.GetFactionPriceModifier then
                local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
                return DynamicTrading.Events.GetFactionPriceModifier(faction, tags, verbose)
            end
            return 1.0
        end
    }
end

local function resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, globalHeat, verbose, skipEvents)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 99999 end

    verbose = verbose or DynamicTrading.Debug

    if not customData then
        if soul.stocks and soul.stocks[itemFullType] then
            customData = soul.stocks[itemFullType].customData
        end
    end

    local diff = DynamicTrading.Config.GetDifficultyData()
    local modifiers = buildBuyPriceModifiers(soul, customData, globalHeat, verbose, skipEvents)

    return Common.GetBuyPrice(itemFullType, itemData, diff, modifiers, verbose)
end

-- =============================================================================
-- 1. V2 STOCK GENERATOR (Wrapper) - SERVER ONLY
-- =============================================================================
function DynamicTrading.Economy.V2.GenerateStock(traderUUID)
    if isClient() and not isServer() then return {} end
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    if not soul then return {} end
    
    local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
    local archetype = DynamicTrading.Archetypes[soul.archetypeID] or DynamicTrading.Archetypes["General"]
    
    local masterList = DynamicTrading.Config.MasterList
    if not masterList then return {} end

    -- Difficulty (V2 might need its own or use Common)
    local diff = DynamicTrading.Config.GetDifficultyData()

    -- Modifiers (V2 specific)
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        globalStockMult = 1.0
    }
    
    -- [V2 Revamp] Event Integration (Unified)
    if DynamicTrading.Events and DynamicTrading.Events.UpdateFaction then
        modifiers.getVolumeModifier = function(tags)
            return DynamicTrading.Events.GetFactionVolumeModifier(faction, tags)
        end
        modifiers.eventInjections = DynamicTrading.Events.GetFactionInjections(faction)
        modifiers.expertTags = DynamicTrading.Events.GetFactionExpertTags(faction)
        modifiers.forbidTags = DynamicTrading.Events.GetFactionForbidTags(faction)
    end

    -- Delegate to Common
    local rawStock = Common.GenerateStock(archetype, masterList, diff, modifiers)

    -- Adapt to V2 Format { [item] = {qty=..., basePrice=..., dynamicMod=..., customData=...} }
    local finalItems = {}
    for itemKey, entry in pairs(rawStock) do
        local itemData = masterList[itemKey]
        if itemData then
            local basePrice = itemData.basePrice
            if DynamicTrading.PriceConfig and DynamicTrading.PriceConfig.GetEffectiveBasePrice then
                basePrice = DynamicTrading.PriceConfig.GetEffectiveBasePrice(itemKey, itemData)
            end
            finalItems[itemKey] = {
                qty = entry.qty,
                basePrice = basePrice,
                dynamicMod = 1.0, -- Placeholder for dynamic pricing variations
                customData = entry.customData -- Already generated by Common!
            }
        end
    end
    
    return finalItems
end

-- =============================================================================
-- 2. V2 PRICING LOGIC (Wrapper)
-- =============================================================================

function DynamicTrading.Economy.V2.GetBuyPrice(traderUUID, itemFullType, customData, verbose, skipEvents)
    local engineData = DynamicTrading_Engine.GetEngineData()
    local globalHeat = engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {}
    return resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, globalHeat, verbose, skipEvents)
end

function DynamicTrading.Economy.V2.GetBulkBuyPreview(traderUUID, itemFullType, customData, qty, verbose)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData then
        return { qty = 0, totalPrice = 0, totalBasePrice = 0, firstUnitPrice = 0, lastUnitPrice = 0 }
    end

    local requestedQty = math.max(0, math.floor(tonumber(qty) or 0))
    if requestedQty <= 0 then
        return { qty = 0, totalPrice = 0, totalBasePrice = 0, firstUnitPrice = 0, lastUnitPrice = 0 }
    end

    local engineData = DynamicTrading_Engine.GetEngineData()
    local simulatedHeat = copyHeatTable(engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {})
    local category = Common.GetPrimaryTradeTag(itemData, customData and customData.fluidType, customData and customData.fluidAmount)
    local sensitivity = (SandboxVars.DynamicTrading and SandboxVars.DynamicTrading.CategoryInflation) or 0.05

    local totalPrice = 0
    local totalBasePrice = 0
    local firstUnitPrice = 0
    local lastUnitPrice = 0

    for i = 1, requestedQty do
        local unitPrice = resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, simulatedHeat, verbose, false)
        local baseUnitPrice = resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, simulatedHeat, false, true)

        if i == 1 then
            firstUnitPrice = unitPrice
        end

        lastUnitPrice = unitPrice
        totalPrice = totalPrice + unitPrice
        totalBasePrice = totalBasePrice + baseUnitPrice

        if category and category ~= "Misc" then
            simulatedHeat[category] = clampHeatValue((simulatedHeat[category] or 0) + sensitivity)
        end
    end

    return {
        qty = requestedQty,
        totalPrice = totalPrice,
        totalBasePrice = totalBasePrice,
        firstUnitPrice = firstUnitPrice,
        lastUnitPrice = lastUnitPrice
    }
end

function DynamicTrading.Economy.V2.GetMaxAffordableBuyQuantity(traderUUID, itemFullType, customData, maxQty, budget)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    local maxAllowed = math.max(0, math.floor(tonumber(maxQty) or 0))
    local availableBudget = math.max(0, math.floor(tonumber(budget) or 0))

    if not itemData or maxAllowed <= 0 or availableBudget <= 0 then
        return { qty = 0, totalPrice = 0, totalBasePrice = 0 }
    end

    local engineData = DynamicTrading_Engine.GetEngineData()
    local simulatedHeat = copyHeatTable(engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {})
    local category = Common.GetPrimaryTradeTag(itemData, customData and customData.fluidType, customData and customData.fluidAmount)
    local sensitivity = (SandboxVars.DynamicTrading and SandboxVars.DynamicTrading.CategoryInflation) or 0.05

    local totalPrice = 0
    local totalBasePrice = 0
    local quantity = 0

    for _ = 1, maxAllowed do
        local unitPrice = resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, simulatedHeat, false, false)
        local baseUnitPrice = resolveBuyPriceWithHeat(traderUUID, itemFullType, customData, simulatedHeat, false, true)

        if totalPrice + unitPrice > availableBudget then
            break
        end

        quantity = quantity + 1
        totalPrice = totalPrice + unitPrice
        totalBasePrice = totalBasePrice + baseUnitPrice

        if category and category ~= "Misc" then
            simulatedHeat[category] = clampHeatValue((simulatedHeat[category] or 0) + sensitivity)
        end
    end

    return {
        qty = quantity,
        totalPrice = totalPrice,
        totalBasePrice = totalBasePrice
    }
end

function DynamicTrading.Economy.V2.GetSellPrice(traderUUID, itemObj, itemFullType, verbose, skipEvents)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 0 end
    
    -- Always verbose if DynamicTrading.Debug is true
    verbose = verbose or DynamicTrading.Debug

    local engineData = DynamicTrading_Engine.GetEngineData()
    local globalHeat = engineData and engineData.WorldEconomy and engineData.WorldEconomy.GlobalHeat or {}

    -- [NEW] Fetch Local Deflation from Stock
    local localDeflationCount = 0
    if DynamicTrading_Stock then
        local stockData = DynamicTrading_Stock.GetStock(traderUUID)
        if stockData and stockData.deflation then
            localDeflationCount = stockData.deflation[itemFullType] or 0
        end
    end

    local diff = DynamicTrading.Config.GetDifficultyData()
    local archetype = soul.archetypeID and DynamicTrading.Archetypes[soul.archetypeID]
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        globalHeat = globalHeat,
        localDeflationCount = localDeflationCount,
        -- Event Modifiers (Unified Manager Integration)
        getPriceModifier = function(tags)
            if not skipEvents and DynamicTrading.Events and DynamicTrading.Events.GetFactionPriceModifier then
                local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
                return DynamicTrading.Events.GetFactionPriceModifier(faction, tags, verbose)
            end
            return 1.0
        end
    }
    
    local price = Common.GetSellPrice(itemFullType, itemData, itemObj, diff, archetype, modifiers, verbose)
    
    return price
end
