-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Furniture.Bed] [Rarity.Common] (4 items)
    { item="Base.Mattress", basePrice=1, tags={"Building.Furniture.Bed", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_FlatCoffin", basePrice=3, tags={"Building.Furniture.Bed", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeFuton", basePrice=3, tags={"Building.Furniture.Bed", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_UprightCoffin", basePrice=3, tags={"Building.Furniture.Bed", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Bench] [Rarity.Common] (2 items)
    { item="Base.Mov_BacklessWoodenBench", basePrice=3, tags={"Building.Furniture.Bench", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakBench", basePrice=3, tags={"Building.Furniture.Bench", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Chair] [Rarity.Common] (30 items)
    { item="Base.Mov_BeachChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueComfyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BluePlasticChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueRattanChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownComfyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkBlueChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkWoodenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DrumStool", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyBlackChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyWhiteChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FoldingChair", basePrice=1, tags={"Building.Furniture.Chair", "Rarity.Common", "Quality.Waste"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenComfyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyComfyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalStool", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OfficeChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeModernChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PileOCrepeChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleRattanChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedWoodenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteComfyChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenStool", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_YellowModernChair", basePrice=3, tags={"Building.Furniture.Chair", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Counter] [Rarity.Common] (23 items)
    { item="Base.Mov_BirchCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MobileCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrailerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCounter", basePrice=3, tags={"Building.Furniture.Counter", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Decor] [Rarity.Common] (88 items)
    { item="Base.Antlers_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Bull_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Cow_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DeerStag_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Mov_BeigeCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagAdmin", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSA", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSALarge", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayLongCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp1", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp2", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp3", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp4", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp5", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp6", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorLarge", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorSmall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorSmallWide", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorTall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorWood", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_NeonOpenSign", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAaaaah", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAbeLincoln", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAppleFacedMan", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingBejaminFranklin", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingBetty", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingCalvinist", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingChromaticAccident", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingDesertLandscape", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingElisa", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingGeorgeWashington", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingGreen", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingHelianthus", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingIslandBeach", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingJohnAdams", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLakeside", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLibrary", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLillysWaterpond", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingManWithOneEar", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingMargarite", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingMountNeverRest", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingNightWithStars", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingNomadAboveTheGloom", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingRiverside", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingShesGotIt", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingSirBrakefire", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingThomasJefferson", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingTwoFrame", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingVioletta", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinkCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterDroids", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterElement", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterMedical", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterOmega", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPaws", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieBlue", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieGreen", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPiePink", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieRed", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SaleSign", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignCitrus", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas_Fossoil", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas_Gas2Go", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignRestricted", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignWarning", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SquareWallClock", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_StopSign", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WallClock", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCurtain", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Pig_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Sheep_Skull_Wall", basePrice=3, tags={"Building.Furniture.Decor", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Decor] [Rarity.Rare] (1 item)
    { item="Base.Frame", basePrice=4, tags={"Building.Furniture.Decor", "Rarity.Rare"}, stockRange={min=0, max=4} },

    -- [Building.Furniture.Decor] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_SignArmy", basePrice=4, tags={"Building.Furniture.Decor", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.General] [Rarity.Common] (1 item)
    { item="Base.MetalDrum", basePrice=3, tags={"Building.Furniture.General", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Storage] [Rarity.Common] (17 items)
    { item="Base.Mov_BirchDrawers", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackSpeakerCabinet", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetMedical", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetTool", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FirstAidCabinet", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Mailbox", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalWallShelves", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakShelves", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PublicMailBox", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPineCabinet", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodSpeakerCabinet", basePrice=3, tags={"Building.Furniture.Storage", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Storage] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_MilitaryCrate", basePrice=4, tags={"Building.Furniture.Storage", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },

    -- [Building.Furniture.Table] [Rarity.Common] (12 items)
    { item="Base.Mov_BlackLowModernTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownLowTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyDarkTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyLowTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LightRoundTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakRoundTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingFlowersOnTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticLowTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoundTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallTable", basePrice=3, tags={"Building.Furniture.Table", "Rarity.Common"}, stockRange={min=3, max=15} },
})

print("[DynamicTrading] Furniture Registry Complete")
