-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Furniture.Bed] [Rarity.Common] (4 items)
    { item="Base.Mattress", basePrice=520, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Mov_FlatCoffin", basePrice=520, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeFuton", basePrice=520, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_UprightCoffin", basePrice=520, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Bench] [Rarity.Common] (2 items)
    { item="Base.Mov_BacklessWoodenBench", basePrice=452, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakBench", basePrice=452, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Chair] [Rarity.Common] (30 items)
    { item="Base.Mov_BeachChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueComfyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BluePlasticChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueRattanChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownComfyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkBlueChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkWoodenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DrumStool", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyBlackChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyWhiteChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FoldingChair", basePrice=156, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=1, max=15} },
    { item="Base.Mov_GreenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenComfyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyComfyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalStool", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OfficeChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeModernChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PileOCrepeChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleRattanChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedWoodenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteComfyChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenStool", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_YellowModernChair", basePrice=520, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Counter] [Rarity.Common] (23 items)
    { item="Base.Mov_BirchCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MobileCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrailerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCounter", basePrice=454, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Common] (88 items)
    { item="Base.Antlers_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Bull_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Cow_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerStag_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Mov_BeigeCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagAdmin", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSA", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSALarge", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayLongCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp1", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp2", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp3", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp4", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp5", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp6", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorLarge", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmallWide", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorTall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorWood", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_NeonOpenSign", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAaaaah", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAbeLincoln", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAppleFacedMan", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBejaminFranklin", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBetty", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingCalvinist", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingChromaticAccident", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingDesertLandscape", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingElisa", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGeorgeWashington", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGreen", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingHelianthus", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingIslandBeach", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingJohnAdams", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLakeside", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLibrary", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLillysWaterpond", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingManWithOneEar", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMargarite", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMountNeverRest", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNightWithStars", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNomadAboveTheGloom", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingRiverside", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingShesGotIt", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingSirBrakefire", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingThomasJefferson", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingTwoFrame", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingVioletta", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PinkCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterDroids", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterElement", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterMedical", basePrice=500, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_PosterOmega", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPaws", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieBlue", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieGreen", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPiePink", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieRed", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SaleSign", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignCitrus", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Fossoil", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Gas2Go", basePrice=456, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignRestricted", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignWarning", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SquareWallClock", basePrice=457, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_StopSign", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WallClock", basePrice=457, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCurtain", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Pig_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Sheep_Skull_Wall", basePrice=447, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Rare] (1 item)
    { item="Base.Frame", basePrice=648, tags={"Building.Furniture.Decor", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },

    -- [Building.Furniture.Decor] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_SignArmy", basePrice=606, tags={"Building.Furniture.Decor", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.General] [Rarity.Common] (1 item)
    { item="Base.MetalDrum", basePrice=448, tags={"Building.Furniture.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Common] (17 items)
    { item="Base.Mov_BirchDrawers", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=460, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackSpeakerCabinet", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_CabinetMedical", basePrice=513, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_CabinetTool", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FirstAidCabinet", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Mailbox", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalWallShelves", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakShelves", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PublicMailBox", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPineCabinet", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=466, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=14} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodSpeakerCabinet", basePrice=458, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_MilitaryCrate", basePrice=621, tags={"Building.Furniture.Storage", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.Table] [Rarity.Common] (12 items)
    { item="Base.Mov_BlackLowModernTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownLowTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyDarkTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyLowTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LightRoundTable", basePrice=458, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakRoundTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingFlowersOnTable", basePrice=454, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticLowTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallTable", basePrice=452, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
})

print("[DynamicTrading] Furniture Registry Complete")
