-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Furniture.Bed] [Rarity.Common] (4 items)
    { item="Base.Mattress", basePrice=1001, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Mov_FlatCoffin", basePrice=1004, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeFuton", basePrice=1004, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_UprightCoffin", basePrice=1004, tags={"Building.Furniture.Bed", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Bench] [Rarity.Common] (2 items)
    { item="Base.Mov_BacklessWoodenBench", basePrice=665, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakBench", basePrice=665, tags={"Building.Furniture.Bench", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Chair] [Rarity.Common] (30 items)
    { item="Base.Mov_BeachChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueComfyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BluePlasticChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueRattanChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownComfyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkBlueChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkWoodenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DrumStool", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyBlackChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyWhiteChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FoldingChair", basePrice=223, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=1, max=15} },
    { item="Base.Mov_GreenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenComfyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreyComfyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalStool", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OfficeChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OrangeModernChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PileOCrepeChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleRattanChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RedWoodenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteComfyChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenStool", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_YellowModernChair", basePrice=742, tags={"Building.Furniture.Chair", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Counter] [Rarity.Common] (23 items)
    { item="Base.Mov_BirchCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MobileCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PineCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SteelCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrailerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodenCounter", basePrice=667, tags={"Building.Furniture.Counter", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Common] (88 items)
    { item="Base.Antlers_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Bull_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Cow_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerDoe_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.DeerStag_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=9} },
    { item="Base.Mov_BeigeCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlueCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=1072, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagAdmin", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSA", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FlagUSALarge", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GrayLongCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_GreenCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp1", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp2", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp3", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp4", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp5", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Lamp6", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorLarge", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorSmallWide", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorTall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MirrorWood", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=1072, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_NeonOpenSign", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=1072, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAaaaah", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAbeLincoln", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingAppleFacedMan", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBejaminFranklin", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingBetty", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingCalvinist", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingChromaticAccident", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingDesertLandscape", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingElisa", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGeorgeWashington", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingGreen", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingHelianthus", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingIslandBeach", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingJohnAdams", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLakeside", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLibrary", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingLillysWaterpond", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingManWithOneEar", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMargarite", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingMountNeverRest", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNightWithStars", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingNomadAboveTheGloom", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingRiverside", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingShesGotIt", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingSirBrakefire", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingThomasJefferson", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingTwoFrame", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingVioletta", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PinkCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterDroids", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterElement", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterMedical", basePrice=739, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_PosterOmega", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPaws", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieBlue", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieGreen", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPiePink", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PosterPieRed", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=1072, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla", "Theme.Survival"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SaleSign", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignCitrus", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Fossoil", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignOutOfGas_Gas2Go", basePrice=669, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignRestricted", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SignWarning", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SquareWallClock", basePrice=670, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_StopSign", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WallClock", basePrice=670, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteCurtain", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Pig_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Sheep_Skull_Wall", basePrice=660, tags={"Building.Furniture.Decor", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Decor] [Rarity.Rare] (1 item)
    { item="Base.Frame", basePrice=1145, tags={"Building.Furniture.Decor", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },

    -- [Building.Furniture.Decor] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_SignArmy", basePrice=1530, tags={"Building.Furniture.Decor", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.General] [Rarity.Common] (1 item)
    { item="Base.MetalDrum", basePrice=661, tags={"Building.Furniture.General", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Common] (17 items)
    { item="Base.Mov_BirchDrawers", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=673, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BlackSpeakerCabinet", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_CabinetMedical", basePrice=751, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=0, max=9} },
    { item="Base.Mov_CabinetTool", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FirstAidCabinet", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Mailbox", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_MetalWallShelves", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakShelves", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PublicMailBox", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallPineCabinet", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=679, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=14} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_WoodSpeakerCabinet", basePrice=671, tags={"Building.Furniture.Storage", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },

    -- [Building.Furniture.Storage] [Rarity.Uncommon] (1 item)
    { item="Base.Mov_MilitaryCrate", basePrice=1545, tags={"Building.Furniture.Storage", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia"}, stockRange={min=0, max=8} },

    -- [Building.Furniture.Table] [Rarity.Common] (12 items)
    { item="Base.Mov_BlackLowModernTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_BrownLowTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyDarkTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyLowTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_FancyTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LightRoundTable", basePrice=671, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_LongTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_OakRoundTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PaintingFlowersOnTable", basePrice=667, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_PlasticLowTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_RoundTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
    { item="Base.Mov_SmallTable", basePrice=665, tags={"Building.Furniture.Table", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=13} },
})

print("[DynamicTrading] Furniture Registry Complete")
