-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Garden] [Rarity.Common] (11 items)
    { item="Base.Mov_BonsaiTree", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_BrickPlanter", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_Cactus", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_CastIronPlant", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_ChineseEvergreen", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_DragonTree", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_Fern", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_Ficus", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_RaisedPlantbed", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_SnakePlant", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_VioletFlowers", basePrice=1, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=1, max=5} },

    -- [Building.Garden] [Rarity.Rare] (12 items)
    { item="Base.AnimalFeedBag", basePrice=1, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CompostBag", basePrice=1, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Fertilizer", basePrice=1, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.GardeningSprayAphids", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayCigarettes", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayEmpty", basePrice=1, tags={"Building.Garden", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=6} },
    { item="Base.GardeningSprayMilk", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GrassBag", basePrice=3, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HerbivoreTeeth", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SlugRepellent", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SunflowerHead", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SunflowerHeadDried", basePrice=4, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=10} },

    -- [Building.Garden.Seed] [Rarity.Rare] (100 items)
    { item="Base.BarleyBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BasilBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BasilSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BellPepperBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BellPepperSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BlackSageBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BlackSageSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BroadleafPlantainBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BroadleafPlantainSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BroccoliBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BroccoliSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CabbageBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CabbageSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CarrotBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CarrotSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CauliflowerBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CauliflowerSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ChamomileBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChamomileSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ChivesBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ChivesSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CilantroBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ComfreyBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ComfreySeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CommonMallowBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CommonMallowSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CornBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CornBagSeed_Empty", basePrice=1, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.CucumberBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CucumberSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FlaxBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GarlicBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GarlicSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.GreenpeasBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HabaneroBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HabaneroSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.HempBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HempSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.HopsBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HopsSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.JalapenoBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JalapenoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KaleBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.KaleSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LavenderBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LavenderSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LeekBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LeekSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LemonGrassBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LemonGrassSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LettuceBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LettuceSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.MarigoldBagSeed", basePrice=1, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.MarigoldSeed", basePrice=1, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.MintBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MintSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.OnionBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.OnionSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.OreganoBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.OreganoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ParsleyBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ParsleySeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PoppyBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PotatoBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PotatoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PumpkinBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RedRadishBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RedRadishSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RoseBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RosemaryBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.RosemarySeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RoseSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RyeBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SageBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SageSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SoybeansBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SpinachBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SpinachSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StrewberrieBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.StrewberrieSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SugarBeetBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SugarBeetSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SunflowerBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SweetPotatoBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SweetPotatoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ThymeBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ThymeSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TobaccoBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TobaccoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TomatoBagSeed2", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TomatoSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TurnipBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TurnipSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WatermelonBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WatermelonSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WheatBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WildGarlicBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WildGarlicSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ZucchiniBagSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ZucchiniSeed", basePrice=4, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=20} },
})

print("[DynamicTrading] Garden Registry Complete")
