-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Garden] [Rarity.Common] (11 items)
    { item="Base.Mov_BonsaiTree", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_BrickPlanter", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Cactus", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_CastIronPlant", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_ChineseEvergreen", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_DragonTree", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Fern", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_Ficus", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_RaisedPlantbed", basePrice=17, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_SnakePlant", basePrice=7, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },
    { item="Base.Mov_VioletFlowers", basePrice=5, tags={"Building.Garden", "Rarity.Common"}, stockRange={min=0, max=4} },

    -- [Building.Garden] [Rarity.Rare] (12 items)
    { item="Base.AnimalFeedBag", basePrice=25, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.CompostBag", basePrice=36, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Fertilizer", basePrice=37, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.GardeningSprayAphids", basePrice=39, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayCigarettes", basePrice=39, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GardeningSprayEmpty", basePrice=10, tags={"Building.Garden", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=7} },
    { item="Base.GardeningSprayMilk", basePrice=39, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GrassBag", basePrice=26, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.HerbivoreTeeth", basePrice=13, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.SlugRepellent", basePrice=39, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SunflowerHead", basePrice=13, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.SunflowerHeadDried", basePrice=13, tags={"Building.Garden", "Rarity.Rare"}, stockRange={min=0, max=12} },

    -- [Building.Garden.Seed] [Rarity.Rare] (100 items)
    { item="Base.BarleyBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BasilBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BasilSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.BellPepperBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BellPepperSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.BlackSageBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BlackSageSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.BroadleafPlantainBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BroadleafPlantainSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.BroccoliBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.BroccoliSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CabbageBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CabbageSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CarrotBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CarrotSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CauliflowerBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CauliflowerSeed", basePrice=26, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.ChamomileBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ChamomileSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.ChivesBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ChivesSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CilantroBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ComfreyBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ComfreySeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CommonMallowBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CommonMallowSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.CornBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CornBagSeed_Empty", basePrice=7, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=52} },
    { item="Base.CucumberBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.CucumberSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.FlaxBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.GarlicBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.GarlicSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.GreenpeasBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.HabaneroBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.HabaneroSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.HempBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.HempSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.HopsBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.HopsSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.JalapenoBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.JalapenoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.KaleBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.KaleSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.LavenderBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.LavenderSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.LeekBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.LeekSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.LemonGrassBagSeed", basePrice=32, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=15} },
    { item="Base.LemonGrassSeed", basePrice=32, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.LettuceBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.LettuceSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.MarigoldBagSeed", basePrice=7, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=26} },
    { item="Base.MarigoldSeed", basePrice=7, tags={"Building.Garden.Seed", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=52} },
    { item="Base.MintBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.MintSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.OnionBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.OnionSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.OreganoBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.OreganoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.ParsleyBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ParsleySeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.PoppyBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.PotatoBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.PotatoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.PumpkinBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.RedRadishBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.RedRadishSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.RoseBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.RosemaryBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.RosemarySeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.RoseSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.RyeBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SageBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SageSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.SoybeansBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SpinachBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SpinachSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.StrewberrieBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.StrewberrieSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.SugarBeetBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SugarBeetSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.SunflowerBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SweetPotatoBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.SweetPotatoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.ThymeBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ThymeSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.TobaccoBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.TobaccoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.TomatoBagSeed2", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.TomatoSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.TurnipBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.TurnipSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.WatermelonBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.WatermelonSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.WheatBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.WildGarlicBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.WildGarlicSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
    { item="Base.ZucchiniBagSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=22} },
    { item="Base.ZucchiniSeed", basePrice=23, tags={"Building.Garden.Seed", "Rarity.Rare"}, stockRange={min=0, max=44} },
})

print("[DynamicTrading] Garden Registry Complete")
