-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Moveable] [Rarity.Common] (92 items)
    { item="Base.Mov_AirConditioner", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine1", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine2", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BenchGrinder", basePrice=313, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BinRound", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Birdbath", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackBBQ", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackCashRegister", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Brazier", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CardboardBox", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CashRegister", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ClothesStand", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CoffeeMaker", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteMixer", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteRoadBlock", basePrice=301, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CorkBoard", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Cot", basePrice=302, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Mov_DarkGreenBarrel", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DeepFryer", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DegreeDoctor", basePrice=329, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DegreeSurgeon", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DesktopComputer", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Doghouse", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Espresso", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ExtractorHood", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FireHydrant", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FitnessContraption", basePrice=302, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=20} },
    { item="Base.Mov_GardenGnome", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveArched", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveRound", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveSquare", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveWorn", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GrayGarbageBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GreenGarbageBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GuitarAmplifier", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Gurney", basePrice=289, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Mov_GymnMat", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HaystackDouble", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HaystackSingle", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HotdogMachine", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HuntingTrophy", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Jukebox", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KeyDuplicator", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KickDrum", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LargeOpenToppedGarbageBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightConstruction", basePrice=315, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightGreenBarrel", basePrice=300, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinFemale", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinMale", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MapUSA", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MetalTurnstile", basePrice=309, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microphone", basePrice=301, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microscope", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MobileBloodbag", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_OrangeBarrel", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletBricks", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletEmpty", basePrice=88, tags={"Building.Moveable", "Rarity.Common", "Quality.Waste", "Origin.Vanilla"}, stockRange={min=2, max=21} },
    { item="Base.Mov_PinballMachine", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo2", basePrice=292, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PopcornMachine", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Projector", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PublicGarbageBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RecycleBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RedBBQ", basePrice=311, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadBarrier", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone2", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SaltLick", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SatelliteDish", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ScaleMedical", basePrice=329, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Scarecrow", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal2", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityWallMonitors", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ShoppingBaskets", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SkeletonDisplay", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SmallChest", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SnareDrum", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_StandingVault", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TomDrum", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TVCamera", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WashingBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WheelieBin", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowChrome", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowSlider", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowTiled", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhite", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhiteTiled", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWooden", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WoodPegboard", basePrice=294, tags={"Building.Moveable", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=1, max=18} },
})

print("[DynamicTrading] Moveable Registry Complete")
