-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Moveable] [Rarity.Common] (92 items)
    { item="Base.Mov_AirConditioner", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine1", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ArcadeMachine2", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BenchGrinder", basePrice=25, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BinRound", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Birdbath", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackBBQ", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_BlackCashRegister", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Brazier", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CardboardBox", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CashRegister", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ClothesStand", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CoffeeMaker", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteMixer", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ConcreteRoadBlock", basePrice=13, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_CorkBoard", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Cot", basePrice=14, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_DarkGreenBarrel", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DeepFryer", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DegreeDoctor", basePrice=7, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_DegreeSurgeon", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_DesktopComputer", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Doghouse", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Espresso", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ExtractorHood", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FireHydrant", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_FitnessContraption", basePrice=14, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=2, max=20} },
    { item="Base.Mov_GardenGnome", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveArched", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveRound", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveSquare", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GraveWorn", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GrayGarbageBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GreenGarbageBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_GuitarAmplifier", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Gurney", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_GymnMat", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HaystackDouble", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HaystackSingle", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=6} },
    { item="Base.Mov_HotdogMachine", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_HuntingTrophy", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Jukebox", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KeyDuplicator", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_KickDrum", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LargeOpenToppedGarbageBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightConstruction", basePrice=27, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_LightGreenBarrel", basePrice=12, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinFemale", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MannequinMale", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MapUSA", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MetalTurnstile", basePrice=21, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microphone", basePrice=13, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Microscope", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_MobileBloodbag", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_OrangeBarrel", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletBricks", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PalletEmpty", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=21} },
    { item="Base.Mov_PinballMachine", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PinkFlamingo2", basePrice=4, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PopcornMachine", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_Projector", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_PublicGarbageBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RecycleBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RedBBQ", basePrice=23, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadBarrier", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_RoadCone2", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SaltLick", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SatelliteDish", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ScaleMedical", basePrice=7, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=1, max=13} },
    { item="Base.Mov_Scarecrow", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityTerminal2", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SecurityWallMonitors", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_ShoppingBaskets", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SkeletonDisplay", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SmallChest", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_SnareDrum", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_StandingVault", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TomDrum", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_TVCamera", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WashingBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WheelieBin", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowChrome", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowSlider", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowTiled", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhite", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWhiteTiled", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WindowWooden", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
    { item="Base.Mov_WoodPegboard", basePrice=6, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=18} },
})

print("[DynamicTrading] Moveable Registry Complete")
