-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Material] [Rarity.Common] (7 items)
    { item="Base.BlacksmithAnvilAssembled", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.Hematite", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.HematiteLarge", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.LargeBellows", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.LargeStone", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.Malachite", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.MalachiteLarge", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },

    -- [Building.Material] [Rarity.Rare] (316 items)
    { item="Base.AdhesiveTapeBox", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.AlcoholRippedSheets", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Aluminum", basePrice=26, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AluminumFragments", basePrice=26, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AluminumScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.BarbedWire", basePrice=5, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BarleyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BarricadeCube_Folded", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.BasilBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BellPepperBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BenchAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BenchAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlackSageBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BlacksmithAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlowerFan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BoneBead_Large", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.BrainTan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BrassIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BrassScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.Bricktoys", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.BroadleafPlantainBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BroccoliBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Buckle", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Bullhorn", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BurlapPiece", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Button", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CabbageBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CalfLeather_Angus_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Calipers", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CarrotBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CauliflowerBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CeramicIngotCast", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ChamomileBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Charcoal", basePrice=64, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CharcoalCrafted", basePrice=64, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CheeseCloth", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ChivesBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CilantroBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Clay", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayBrick", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayPipeSegment", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayPot", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayShingle", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayTile", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayTool", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Coke", basePrice=102, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ComfreyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CommonMallowBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.ConcretePowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CopperIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.CopperOre", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.CopperScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Origin.Police", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.CopperSheet", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Corkscrew", basePrice=13, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CowHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Angus_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchVise", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchViseParts", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CucumberBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.DappleDeerHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.DeerLeather_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DenimStrips", basePrice=32, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.DenimStripsBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DenimStripsDirty", basePrice=32, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.DenimStripsDirtyBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Dogbane", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Doorknob", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Drawer", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DrawPlate", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.DuctTapeBox", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FawnLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FirewoodBundle", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flax", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.FlaxBroken", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.FlaxDried", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxHeckled", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxRippled", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxScutched", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxTow", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.GarlicBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.GlassBlowingPipe", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GlassPanel", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.GoldBar", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.GoldScrap", basePrice=17, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.GoldSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.GreenpeasBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HabaneroBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HeadingTool", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HeavyChain_Hook", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HeavyChainLink", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HempBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HempBroken", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.HempScutched", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Hinge", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HopsBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.IronBand", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IronBandSmall", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronBarQuarter", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IronBloom", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronOre", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronPiece", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.IronScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.JalapenoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.KaleBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LambLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LanternGlass", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Latch", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.LavenderBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Leash", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Leather_Crude_Large", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LeatherStrips", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LeatherStripsDirty", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsDirtyBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.LeekBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LemonGrassBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LettuceBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Limestone", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Log", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks2", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks3", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks4", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Loupe", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MarigoldBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.MintBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Nails", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.NailsBox", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.NailsCarton", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NutsBolts", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.OnionBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.OreganoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PackFrame", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PackFrameLarge", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paintbrush", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PaintbrushCrafted", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Paperclip", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.PaperclipBox", basePrice=28, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ParsleyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PiercedIronBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PiercedIronChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PiercedIronIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PiercedSteelBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PiercedSteelChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PiercedSteelIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PigLeather_Black_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Black_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigletLeather_Black_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Pillow", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Pillow_Crafted", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PlasterPowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasterTrowel", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PoppyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PotatoBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PumpkinBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Quicklime", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.RabbitLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RailroadTrack", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RailroadTrackPiece", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RakeHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RedRadishBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RippedSheetsBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RippedSheetsDirtyBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.RippedSheetsSterilizedBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Rope", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RopeStack", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RoseBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RosemaryBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RyeBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SageBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Scotchtape", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ScrapMetal", basePrice=7, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.Screws", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.ScrewsBox", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ScrewsCarton", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SewingPattern", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SharpedStone", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepShears", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SheepShearsForged", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Sheet", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheetMetal", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheetRope", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheetRopeBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SilverBar", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SilverScrap", basePrice=17, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SilverSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallCopperSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=30} },
    { item="Base.SmallGoldBar", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.SmallHandle", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallSheetMetal", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallSilverBar", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SmokingPipe", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SoybeansBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Sparklers", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SpearLongHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SpinachBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SteelBarQuarter", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SteelChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SteelPiece", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SteelRodQuarter", basePrice=5, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.SteelSlug", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.StoneAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneBlock", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.StoneMaulHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StoneWheel", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneWheelSmall", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StrewberrieBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.String", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SugarBeetBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SunflowerBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SweetPotatoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Tarp", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TarpPiece", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Thimble", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ThymeBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TirePiece", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TobaccoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TomatoBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TunaTin_Box", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TuningFork", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.TurnipBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Twigs", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.WallpaperPastePowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WatermelonBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.WheatBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.WildGarlicBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.WoolRaw", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Yarn", basePrice=21, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ZucchiniBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
})

print("[DynamicTrading] Material Registry Complete")
