-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Material] [Rarity.Common] (7 items)
    { item="Base.BlacksmithAnvilAssembled", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.Hematite", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.HematiteLarge", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.LargeBellows", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.LargeStone", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=1, max=4} },
    { item="Base.Malachite", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },
    { item="Base.MalachiteLarge", basePrice=1, tags={"Building.Material", "Rarity.Common"}, stockRange={min=4, max=10} },

    -- [Building.Material] [Rarity.Rare] (448 items)
    { item="Base.AdhesiveTapeBox", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Aluminum", basePrice=26, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AluminumFragments", basePrice=26, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.AluminumScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.BarbedWire", basePrice=5, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BarbedWireStack", basePrice=4, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BarleyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BarricadeCube_Folded", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.BasilBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BBQStarterFluid", basePrice=54, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.BellPepperBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BenchAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BenchAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlackSageBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BlacksmithAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlacksmithAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlockAnvilUntreated", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BlowerFan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BoneBead_Large", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.BrainTan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.BrassIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BrassScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.Bricktoys", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.BroadleafPlantainBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BroccoliBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.BucketCarvedClayCement", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedConcreteFull", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedPlasterFull", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarvedWallpaperPaste", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketClayCement", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketConcreteFull", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketPlasterFull", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketWallpaperPaste", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Buckle", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Bullhorn", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BurlapPiece", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Button", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CabbageBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CalfLeather_Angus_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Angus_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Holstein_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CalfLeather_Simmental_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Calipers", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CarrotBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CauliflowerBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CeramicCrucible_Iron", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucible_Steel", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Iron", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmall_Steel", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicCrucibleSmallUnfired", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CeramicCrucibleUnfired", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicCrucibleWithGlass", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CeramicIngotCast", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CeramicIngotCastUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CeramicMortarandPestleUnfired", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CeramicTeacupUnfired", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ChamomileBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Charcoal", basePrice=64, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CharcoalCrafted", basePrice=64, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CheeseCloth", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ChivesBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CilantroBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Clay", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Claybag", basePrice=5, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ClayBarMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBarMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBenchAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBenchAnvilMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBlacksmithAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBlacksmithAnvilMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBlockAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBlockAnvilMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayBowlUnfired", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayBrick", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayBrickUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayCrudeBenchVisePartsMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayCrudeBenchVisePartsMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayIngotMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayIngotMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayJarUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayMugUnfired", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ClayPipeSegment", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayPipeSegmentUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayPlateUnfired", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ClayPot", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayPotUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClaySheetMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClaySheetMoldUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.ClayShingle", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayShingleUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayTile", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayTileUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ClayTool", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Coke", basePrice=102, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ComfreyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.CommonMallowBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.ConcretePowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CopperIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.CopperOre", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.CopperScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Origin.Police", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.CopperSheet", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=10} },
    { item="Base.Corkscrew", basePrice=13, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.CowHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Angus_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Angus_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Holstein_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CowLeather_Simmental_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchVise", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBenchViseParts", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeBlade", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CrudeShortSwordBlade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CrudeShortSwordBlade_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.CrudeSword_Shard", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.CrudeSwordBlade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeSwordBlade_Broken", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.CrudeSwordBlade_Broken_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.CrudeSwordBlade_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CucumberBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.DappleDeerHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerHide", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DeerLeather_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.DeerLeather_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DenimStrips", basePrice=32, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.DenimStripsBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DenimStripsDirty", basePrice=32, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.DenimStripsDirtyBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.DentalFloss", basePrice=68, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Dirtbag", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Dogbane", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Doorknob", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Drawer", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DrawPlate", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.DuctTape", basePrice=11, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.DuctTapeBox", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Epoxy", basePrice=14, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Extinguisher", basePrice=24, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FabricRoll_Cotton", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimBlack", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimBlue", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FabricRoll_DenimDarkBlue", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FawnLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FawnLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FiberglassTape", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.FireAxeHead", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FirewoodBundle", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FlatStone", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Flax", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.FlaxBroken", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.FlaxDried", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxHeckled", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxRippled", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxScutched", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.FlaxTow", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.GarlicBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.GlassBlowingPipe", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GlassBlowingPipeUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GlassPanel", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Glue", basePrice=14, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.GoldBar", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.GoldScrap", basePrice=17, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.GoldSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.Gravelbag", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GreenpeasBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.GunPowder", basePrice=27, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HabaneroBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HandAxeHead", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HatchetHead_Bone", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HeadingTool", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HeavyChain", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HeavyChain_Hook", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HeavyChainLink", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HempBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HempBroken", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.HempScutched", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Hinge", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.HopsBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.HuntingKnifeBlade", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.IronBand", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IronBandSmall", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronBarMold", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.IronBarQuarter", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IronBloom", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.IronIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronIngotMold", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.IronOre", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IronPiece", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.IronScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.JalapenoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.KaleBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Katana_Blade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Katana_Blade_Broken", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.Katana_Shard", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.KitchenKnifeBlade", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.LambLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LambLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LanternGlass", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LargeKnifeBlade", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LargePlank", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Latch", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.LavenderBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Leash", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Leather_Crude_Large", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Large_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Medium_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Leather_Crude_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Leather_Crude_Small_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.LeatherStrips", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.LeatherStripsDirty", basePrice=8, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=50} },
    { item="Base.LeatherStripsDirtyBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.LeekBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LemonGrassBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LettuceBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.LighterFluid", basePrice=136, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Limestone", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Log", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks2", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks3", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LogStacks4", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.LongCrudeBlade", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Loupe", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.MaceHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.MacheteBlade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MacheteBlade_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MarigoldBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.MeatCleaverBlade", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.MintBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Nails", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.NailsBox", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.NailsCarton", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NutsBolts", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.OldAxeHead", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.OnionBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.OreganoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Oxygen_Tank", basePrice=4, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PackFrame", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PackFrameLarge", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paintbrush", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PaintbrushCrafted", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Paperclip", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.PaperclipBox", basePrice=28, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ParsleyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PiercedIronBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PiercedIronChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PiercedIronIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PiercedSteelBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PiercedSteelChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.PiercedSteelIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PigLeather_Black_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Black_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Black_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigLeather_Landrace_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PigletLeather_Black_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Black_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PigletLeather_Landrace_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Pillow", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Pillow_Crafted", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PlasterPowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PlasterTrowel", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.PoppyBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PotatoBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.PropaneTank", basePrice=680, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PumpkinBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Quicklime", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.RabbitLeather_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RabbitLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Full", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RaccoonLeather_Grey_Fur_Tan_Wet", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RailroadTrack", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RailroadTrackPiece", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RakeHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RedRadishBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RippedSheetsBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RippedSheetsDirtyBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.RippedSheetsSterilizedBundle", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Rope", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.RopeStack", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RoseBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RosemaryBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.RyeBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SageBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Sandbag", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Scotchtape", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ScrapMetal", basePrice=7, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.Screws", basePrice=19, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=100} },
    { item="Base.ScrewsBox", basePrice=9, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.ScrewsCarton", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SharpedStone", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Full", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepLeather_Fur_Tan_Small", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheepLeather_Fur_Tan_Wet", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheepShears", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SheepShearsForged", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Sheet", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheetMetal", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SheetRope", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SheetRopeBundle", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShortSwordBlade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.ShortSwordBlade_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SilverBar", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SilverScrap", basePrice=17, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SilverSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallCopperSheet", basePrice=10, tags={"Building.Material", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=30} },
    { item="Base.SmallGoldBar", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.SmallHandle", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallSheetMetal", basePrice=10, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmallSilverBar", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SmokingPipe", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SmokingPipeUnfired", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SoybeansBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SpadeHead_Forged", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Sparklers", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SpearHead", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SpearLongHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.SpinachBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SteelBarMold", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.SteelBarQuarter", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelBlock", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SteelChunk", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelIngot", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SteelIngotMold", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.SteelPiece", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SteelRodQuarter", basePrice=5, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SteelScrap", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.SteelSlug", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SteelWool", basePrice=85, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.StoneAnvil", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneAxeHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StoneBlade", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.StoneBladeLong", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StoneBlock", basePrice=6, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.StoneMaceHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StoneMaulHead", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.StoneWheel", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StoneWheelSmall", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.StrewberrieBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.String", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.SugarBeetBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SunflowerBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.SweetPotatoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Sword_Scrap_Shard", basePrice=3, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.Sword_Shard", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.SwordBlade", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SwordBlade_Broken", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.SwordBlade_Broken_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Waste", "Quality.Waste"}, stockRange={min=0, max=20} },
    { item="Base.SwordBlade_NoTang", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Tarp", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TarpPiece", basePrice=3, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Thimble", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread", basePrice=272, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Aramid", basePrice=68, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Thread_Sinew", basePrice=68, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.ThymeBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TirePiece", basePrice=2, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TobaccoBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TomatoBagSeed2_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.TunaTin_Box", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.TuningFork", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.TurnipBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Twigs", basePrice=8, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Twine", basePrice=14, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.Wallpaper_BeigeStripe", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_BlackFloral", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_BlueStripe", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_GreenDiamond", basePrice=1, tags={"Building.Material", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_GreenFloral", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_PinkChevron", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallpaper_PinkFloral", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.WallpaperPastePowder", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WatermelonBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.WeldingRods", basePrice=54, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WheatBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.WildGarlicBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
    { item="Base.Wire", basePrice=41, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WireStack", basePrice=4, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.WoodAxeHead", basePrice=1, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WoodenBarCastMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenBenchAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenBlacksmithAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenBlockAnvilMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenBrickMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenCrucibleMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenCrudeBenchVisePartsMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenIngotCastMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenShingleMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.WoodenTileMold", basePrice=6, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=30} },
    { item="Base.Woodglue", basePrice=7, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WoolRaw", basePrice=17, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=50} },
    { item="Base.Yarn", basePrice=21, tags={"Building.Material", "Rarity.Rare"}, stockRange={min=0, max=30} },
    { item="Base.ZucchiniBagSeed_Empty", basePrice=510, tags={"Building.Material", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=100} },
})

print("[DynamicTrading] Material Registry Complete")
