-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Moveable] [Rarity.Common] (324 items)
    { item="Base.Mov_AirConditioner", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_AntiqueStove", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ArcadeMachine1", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ArcadeMachine2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BacklessWoodenBench", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeachChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeigeCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BeigeRotaryPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BenchGrinder", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BinRound", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchDrawers", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BirchDrawersMirror", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Birdbath", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackBBQ", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackCashRegister", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackLowModernTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackModernPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackRotaryPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlackSpeakerCabinet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueComboWasherDryer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueComfyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BluePlasticChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueRattanChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BlueWallLocker", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BonsaiTree", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_Brazier", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrickPlanter", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_BrownComfyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_BrownLowTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetMedical", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CabinetTool", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Cactus", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_CardboardBox", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CashRegister", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CastIronPlant", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_ChemicalToilet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ChestFreezer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ChineseEvergreen", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_ChromeSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ClothesStand", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CoffeeMaker", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ConcreteMixer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ConcreteRoadBlock", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_CorkBoard", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Cot", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_DarkBlueChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkFancyDrawers", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkGreenBarrel", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkIndustrialSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DarkWoodenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DeepFryer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DegreeDoctor", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DegreeSurgeon", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DesktopComputer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Doghouse", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_DragonTree", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_DrumStool", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ElectricBlowerForge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Espresso", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ExtractorHood", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyBlackChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyChestnutDrawers", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyDarkTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyHangingSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyLowTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyOutdoorLamp", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyToilet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FancyWhiteChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Fern", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_Ficus", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_FireHydrant", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FirstAidCabinet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FitnessContraption", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagAdmin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSA", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlagUSALarge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FlatCoffin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FloatingTrailerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FoldingChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Quality.Waste"}, stockRange={min=3, max=15} },
    { item="Base.Mov_FridgeMini", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GardenGnome", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GraveArched", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GraveRound", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GraveSquare", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GraveWorn", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayGarbageBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GrayLongCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenComfyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenGarbageBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenOven", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreenWallLocker", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyComfyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GreyOven", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_GuitarAmplifier", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Gurney", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Mov_GymnMat", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_HaystackDouble", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_HaystackSingle", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_HotdogMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_HuntingTrophy", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialDishwasher", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialOven", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_IndustrialSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Jukebox", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_KeyDuplicator", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_KickDrum", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp1", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp3", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp4", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp5", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Lamp6", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LargeIndustrialSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LargeOpenToppedGarbageBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LightConstruction", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LightGreenBarrel", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LightRoundTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongBeigeCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LongWhiteCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_LowToilet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Mailbox", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MannequinFemale", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MannequinMale", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MapUSA", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalLocker", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalStool", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalTurnstile", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MetalWallShelves", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microphone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microscope", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microwave", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Microwave2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorLarge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorSmall", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorSmallWide", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorTall", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MirrorWood", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MobileBloodbag", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MobileCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernOutdoorLamp", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ModernOven", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_NapkinDispenser", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_NeonOpenSign", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakBench", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakRoundTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OakShelves", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OfficeChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeBarrel", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeFuton", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OrangeModernChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_OvalOutdoorLamp", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAaaaah", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAbeLincoln", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingAppleFacedMan", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingBejaminFranklin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingBetty", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingCalvinist", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingChromaticAccident", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingDesertLandscape", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingElisa", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingFlowersOnTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingGeorgeWashington", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingGreen", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingHelianthus", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingIslandBeach", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingJohnAdams", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLakeside", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLibrary", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingLillysWaterpond", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingManWithOneEar", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingMargarite", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingMountNeverRest", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingNightWithStars", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingNomadAboveTheGloom", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingRiverside", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingShesGotIt", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingSirBrakefire", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingThomasJefferson", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingTwoFrame", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PaintingVioletta", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PalletBricks", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PalletEmpty", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Quality.Waste"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PayPhones", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PileOCrepeChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinballMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PineCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinkCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinkFlamingo", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PinkFlamingo2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlainFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PlasticLowTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PopcornMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PopsicleFreezer", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterDroids", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterElement", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterMedical", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterOmega", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPaws", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieBlue", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieGreen", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPiePink", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PosterPieRed", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Projector", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PublicGarbageBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PublicMailBox", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleRattanChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_PurpleWoodenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RaisedPlantbed", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_RecycleBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedBBQ", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedOven", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedRotaryPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RedWoodenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadBarrier", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadCone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoadCone2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoundOutdoorLamp", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Theme.Survival"}, stockRange={min=3, max=15} },
    { item="Base.Mov_RoundTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SaleSign", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SaltLick", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SatelliteDish", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ScaleMedical", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Clinical"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Scarecrow", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityTerminal", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityTerminal2", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SecurityWallMonitors", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ShopDisplayCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_ShoppingBaskets", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignCitrus", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas_Fossoil", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignOutOfGas_Gas2Go", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignRestricted", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignWarning", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SkeletonDisplay", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallBordeauxCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallChest", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallGreenCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPearlCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallPineCabinet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallTable", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SmallWhiteCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SnackVendingMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SnakePlant", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_SnareDrum", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SodaMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SodaMachineLarge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SodaVendingMachine", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SquareWallClock", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_StandingVault", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SteelFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_StopSign", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Toaster", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TomDrum", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TowelDispenser", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrailerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrailerFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TrapezoidShopShelves", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_TVCamera", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_UprightCoffin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_Urinal", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_VioletFlowers", basePrice=1, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mov_WallClock", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WallShower", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WashingBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WaterDispenser", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WheelieBin", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteComfyChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteCurtain", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFancyDrawers", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFileCabinet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteHalfCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteHangingSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteIndustrialFridge", basePrice=2, tags={"Building.Moveable", "Rarity.Common", "Origin.Industrial"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteModernPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteRotaryPhone", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteSimpleChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteSink", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WhiteWoodenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowChrome", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowSlider", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowTiled", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowWhite", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowWhiteTiled", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WindowWooden", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCornerCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenCounter", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodenStool", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodPegboard", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_WoodSpeakerCabinet", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_YellowModernChair", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Mov_YellowWallLocker", basePrice=2, tags={"Building.Moveable", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- [Building.Moveable] [Rarity.Uncommon] (3 items)
    { item="Base.Mov_MilitaryCrate", basePrice=3, tags={"Building.Moveable", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },
    { item="Base.Mov_MilitaryLocker", basePrice=3, tags={"Building.Moveable", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },
    { item="Base.Mov_SignArmy", basePrice=3, tags={"Building.Moveable", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=3, max=15} },
})

print("[DynamicTrading] Moveable Registry Complete")
