-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Vehicle] [Rarity.Common] (16 items)
    { item="Base.BigTrunk1", basePrice=329, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.BigTrunk2", basePrice=348, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.BigTrunk3", basePrice=326, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.GloveBox1", basePrice=313, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.GloveBox2", basePrice=314, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.GloveBox3", basePrice=314, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk1", basePrice=326, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalTrunk2", basePrice=331, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalTrunk3", basePrice=327, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk1", basePrice=324, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk2", basePrice=329, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk3", basePrice=324, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk1", basePrice=340, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk2", basePrice=340, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk3", basePrice=340, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.VanSeatsTrunk2", basePrice=330, tags={"Building.Vehicle", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=0, max=1} },

    -- [Building.Vehicle] [Rarity.Rare] (74 items)
    { item="Base.EngineDoor1", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.EngineDoor2", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.EngineDoor3", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.EngineParts", basePrice=453, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.FrontCarDoor1", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FrontCarDoor2", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FrontCarDoor3", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow1", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow2", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow3", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.HoodOrnament_Badger", basePrice=439, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.HoodOrnament_Beaver", basePrice=439, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.HoodOrnament_Spiffo", basePrice=439, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Jack", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.LightbarBlue", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.LightbarRed", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.LightbarRedBlue", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.LightbarYellow", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.LugWrench", basePrice=448, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake1", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernBrake2", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernBrake3", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler1", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler2", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler3", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension1", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension2", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension3", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire1", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire2", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire3", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake1", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake2", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake3", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler1", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler2", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler3", basePrice=443, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat1", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat2", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat3", basePrice=432, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension1", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension2", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension3", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire1", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire2", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire3", basePrice=440, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake1", basePrice=134, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake2", basePrice=134, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake3", basePrice=134, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler1", basePrice=133, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler2", basePrice=133, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler3", basePrice=133, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire1", basePrice=132, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire2", basePrice=132, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire3", basePrice=132, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor1", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor2", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor3", basePrice=434, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble1", basePrice=429, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble2", basePrice=429, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble3", basePrice=429, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow1", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow2", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow3", basePrice=438, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield1", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield2", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield3", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TirePump", basePrice=447, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor1", basePrice=461, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor2", basePrice=461, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor3", basePrice=461, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Windshield1", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Windshield2", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
    { item="Base.Windshield3", basePrice=435, tags={"Building.Vehicle", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=1} },
})

print("[DynamicTrading] Vehicle Registry Complete")
