-- ============================================================================
-- Building Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Building.Vehicle] [Rarity.Common] (16 items)
    { item="Base.BigTrunk1", basePrice=41, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.BigTrunk2", basePrice=60, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.BigTrunk3", basePrice=38, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.GloveBox1", basePrice=25, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.GloveBox2", basePrice=26, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.GloveBox3", basePrice=26, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk1", basePrice=38, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.NormalTrunk2", basePrice=43, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.NormalTrunk3", basePrice=39, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk1", basePrice=36, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk2", basePrice=41, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk3", basePrice=36, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk1", basePrice=52, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk2", basePrice=52, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.TrailerTrunk3", basePrice=52, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },
    { item="Base.VanSeatsTrunk2", basePrice=42, tags={"Building.Vehicle", "Rarity.Common"}, stockRange={min=0, max=1} },

    -- [Building.Vehicle] [Rarity.Rare] (74 items)
    { item="Base.EngineDoor1", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.EngineDoor2", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.EngineDoor3", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.EngineParts", basePrice=35, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.FrontCarDoor1", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FrontCarDoor2", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FrontCarDoor3", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow1", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow2", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FrontWindow3", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.HoodOrnament_Badger", basePrice=21, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HoodOrnament_Beaver", basePrice=21, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HoodOrnament_Spiffo", basePrice=21, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Jack", basePrice=30, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.LightbarBlue", basePrice=22, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.LightbarRed", basePrice=22, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.LightbarRedBlue", basePrice=22, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.LightbarYellow", basePrice=22, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.LugWrench", basePrice=30, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake1", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernBrake2", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernBrake3", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler1", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler2", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernCarMuffler3", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension1", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension2", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernSuspension3", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire1", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire2", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire3", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake1", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake2", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalBrake3", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler1", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler2", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarMuffler3", basePrice=25, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat1", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat2", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat3", basePrice=14, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension1", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension2", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalSuspension3", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire1", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire2", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire3", basePrice=23, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake1", basePrice=9, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake2", basePrice=9, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake3", basePrice=9, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler1", basePrice=8, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler2", basePrice=8, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldCarMuffler3", basePrice=8, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire1", basePrice=7, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire2", basePrice=7, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.OldTire3", basePrice=7, tags={"Building.Vehicle", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor1", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor2", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoor3", basePrice=17, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble1", basePrice=12, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble2", basePrice=12, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearCarDoorDouble3", basePrice=12, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow1", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow2", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindow3", basePrice=20, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield1", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield2", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.RearWindshield3", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.TirePump", basePrice=29, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor1", basePrice=43, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor2", basePrice=43, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.TrunkDoor3", basePrice=43, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Windshield1", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Windshield2", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Windshield3", basePrice=18, tags={"Building.Vehicle", "Rarity.Rare"}, stockRange={min=0, max=1} },
})

print("[DynamicTrading] Vehicle Registry Complete")
