-- ============================================================================
-- DT_Melee.lua
-- Weapon Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_Melee = DT_Melee or {}
DT_Melee.items = {
    -- Added by ItemGenerator
    { item="Base.Molotov", basePrice=5, tags={"Weapon.Explosive", "Rarity.Common"}, stockRange={min=2, max=10} },

    -- Added by ItemGenerator
    { item="Base.DumbBell", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.DumbBell_Forged", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Broken", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Broken_Nails", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.File", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FireplacePoker", basePrice=11, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Firewood", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Firewood_Nails", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FlintNodule", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Flute", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenToolHandle_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Gavel", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GridlePan", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GuitarAcousticNeck_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.GuitarElectricBassNeck_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.GuitarElectricNeck_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Hammer", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HammerForged", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HammerStone", basePrice=5, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Handle", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handle_Can", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handle_Nails", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IronBarHalf", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide_Club", basePrice=11, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeAnimalBone", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBoneClub", basePrice=5, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBoneClub_Spiked", basePrice=12, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeHook", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LeadPipe", basePrice=24, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle_Broken", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LongStick_Broken", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle_Broken_Nails", basePrice=22, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Mace", basePrice=28, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Mace_Stone", basePrice=26, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MasonsChisel", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MasonsTrowel", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalBar", basePrice=11, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe", basePrice=10, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe_Broken", basePrice=10, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.MetalworkingChisel", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalworkingPunch", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Morningstar_Scrap_Short", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Nightstick", basePrice=22, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Pan", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PanForged", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PipeWrench", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Plank_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Plank_Broken_Nails", basePrice=18, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Plunger", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Plunger_BarbedWire", basePrice=18, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Ratchet", basePrice=18, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RollingPin", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Saucepan", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SaucepanCopper", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Saxophone", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SheetMetalSnips", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShortBat", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_Can", basePrice=16, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortBat_RakeHead", basePrice=28, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_Nails", basePrice=17, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SmithingHammer", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SpikedShortBat", basePrice=18, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SteelBarHalf", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SteelRodHalf", basePrice=21, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Stone2", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TableLeg_Broken", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.TableLeg_Broken_Nails", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.TennisRacket", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TireIron", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TreeBranch2", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Bone", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Can", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Nails", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Trumpet", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Violin", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.WoodenMallet", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick2", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodenStick_Broken", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick_Broken_Nails", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick_Nails", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Wrench", basePrice=18, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.YardstickDEBUG", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Sawblade_Hatchet", basePrice=13, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.EntrenchingTool", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HandAxe", basePrice=20, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandAxe_Old", basePrice=15, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HandAxeForged", basePrice=20, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandScythe", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandScytheForged", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Hatchet_Bone", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IceAxe", basePrice=15, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MeatCleaver", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MeatCleaver_Scrap", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.MeatCleaverForged", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe_Railspike", basePrice=10, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PrimitiveScythe", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Saw_Flint", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_RailSpike", basePrice=28, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TreeBranch_Railspike", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Banjo", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat", basePrice=16, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Crafted", basePrice=16, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Can", basePrice=24, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_GardenForkHead", basePrice=12, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal", basePrice=22, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal_Bolts", basePrice=26, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Nails", basePrice=22, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_RakeHead", basePrice=30, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_ScrapSheet", basePrice=26, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Spiked", basePrice=15, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BoltCutters", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom_Twig", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom_BarbedWire", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadel", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadelX2", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadelX2_Broken", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Crowbar", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrowbarForged", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FieldHockeyStick_Nails", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FishingRod", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FishingRodBreak", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Gaffhook", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenHoe", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GardenHoeForged", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Golfclub", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GuitarAcoustic", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HobbyHorse", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.IceHockeyStick", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IceHockeyStick_BarbedWire", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IronBar", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.JawboneBovide_Morningstar", basePrice=22, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LaCrosseStick", basePrice=35, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.LeafRake", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Can", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Nails", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_RakeHead", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongMace", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongMace_Stone", basePrice=19, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongSpikedClub", basePrice=15, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongStick", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mop", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Morningstar_Scrap", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Plank", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Saw", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Nails", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Poolcue", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Rake", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Sapling", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponRakeHead", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Shovel", basePrice=19, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpadeForged", basePrice=19, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpadeWood", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Shovel2", basePrice=19, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SnowShovel", basePrice=19, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SteelBar", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.StoneMaul", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TableLeg", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TableLeg_Nails", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodenStick_Can", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe", basePrice=17, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Old", basePrice=17, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Sawblade", basePrice=12, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_ScrapCleaver", basePrice=11, tags={"Weapon.Melee.Axe", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.AxeStone", basePrice=7, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal_Sawblade", basePrice=22, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_RailSpike", basePrice=15, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Sawblade", basePrice=15, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Sawblade", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide_Axe", basePrice=11, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Railspike", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Sawblade", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.PickAxe", basePrice=19, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.PickAxeForged", basePrice=19, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortBat_Sawblade", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.StoneAxeLarge", basePrice=12, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TableLeg_Sawblade", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BarBell", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BarBell_Forged", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BlockMaul", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BucketMace_Metal", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BucketMace_Wood", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Bone", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Brake", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_GardenForkHead", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Nails", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Railspike", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_ScrapSheet", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Sawblade", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_SpadeHead", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Spike", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.EngineMaul", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.GuitarElectricBass", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GuitarElectric", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Keytar", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.KettleMace_Metal", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.KettleMace_Wood", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.LargeBranch", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.LongHandle_Brake", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Brake", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Sawblade", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.RailroadSpikePuller", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.RailroadSpikePullerOld", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.ScrapMaul", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.ScrapWeapon_Brake", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponGardenFork", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponSpade", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Sledgehammer", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Sledgehammer2", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SledgehammerForged", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TableLeg_Chain", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.WoodAxe", basePrice=30, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodAxeForged", basePrice=30, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrudeShortSword", basePrice=26, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CrudeSword", basePrice=30, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrudeSword_Broken", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Katana", basePrice=80, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Katana_Broken", basePrice=26, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Machete", basePrice=39, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Machete_Crude", basePrice=20, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MacheteForged", basePrice=39, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortSword", basePrice=34, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortSword_Scrap", basePrice=18, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Sword", basePrice=39, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Sword_Broken", basePrice=31, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Sword_Scrap", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Sword_Scrap_Broken", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.BareHands", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaBlack", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaBlue", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaRed", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaTINTED", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaWhite", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenFork", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GardenFork_Forged", basePrice=15, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrafted", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCraftedFireHardened", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrude", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrudeLong", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearHandFork", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearGlass", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearHuntingKnife", basePrice=10, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearKnife", basePrice=8, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearKnifeSmall", basePrice=8, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearLong", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScissors", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScrewdriver", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearShort", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearSteakKnife", basePrice=8, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearStone", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearStoneLong", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_Bone", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_BoneLong", basePrice=7, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_Plunger", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearLargeKnife", basePrice=10, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScrapKnife", basePrice=10, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.SpearFightingKnife", basePrice=10, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BluePen", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.BreadKnife", basePrice=5, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DullBoneKnife", basePrice=5, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.CarvingFork2", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.CompassGeometry", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeKnife", basePrice=15, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ButterKnife", basePrice=9, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ButterKnife_Gold", basePrice=5, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.ButterKnife_Silver", basePrice=6, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.FightingKnife", basePrice=24, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FlintKnife", basePrice=9, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Fork", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Fork_Gold", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.Fork_Silver", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Fork_Bone", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ForkForged", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GlassShiv", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GreenPen", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.HandFork", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandguardDagger", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handiknife", basePrice=25, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingKnife", basePrice=24, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HuntingKnifeForged", basePrice=24, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IcePick", basePrice=60, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KitchenKnife", basePrice=20, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KitchenKnifeForged", basePrice=23, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KnifeButterfly", basePrice=40, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeFillet", basePrice=7, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KnifeParing", basePrice=26, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifePocket", basePrice=40, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeShiv", basePrice=10, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeSushi", basePrice=30, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LargeKnife", basePrice=22, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LargeKnife_Scrap", basePrice=22, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LetterOpener", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.LongCrudeKnife", basePrice=12, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MacheteKnife", basePrice=22, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Multitool", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Pen", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Pencil", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PencilSpiffo", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PenFancy", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PenMultiColor", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PenSpiffo", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.RailroadSpike", basePrice=24, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.RailroadSpikeKnife", basePrice=28, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.RedPen", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Scalpel", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Scissors", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ScissorsForged", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver", basePrice=28, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver_Old", basePrice=28, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver_Improvised", basePrice=8, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SharpBone_Long", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SmallKnife", basePrice=19, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SmashedBottle", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Spoon", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Spoon_Gold", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.Spoon_Silver", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Spoon_Bone", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SpoonForged", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Stake", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SteakKnife", basePrice=14, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.StoneKnifeLong", basePrice=13, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SwitchKnife", basePrice=40, tags={"Weapon.Melee.Blade", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TinOpener_Old", basePrice=13, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Toothbrush_Shiv", basePrice=20, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Firecracker", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Firecracker_Crafted", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },

    -- Added by ItemGenerator
    { item="Base.BadmintonRacket", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BallPeenHammer", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BallPeenHammerForged", basePrice=13, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BanjoNeck_Broken", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BaseballBat_Broken", basePrice=6, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BaseballBat_Broken_Nails", basePrice=8, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BlockMace", basePrice=9, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BoneClub", basePrice=6, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BoneClub_Spiked", basePrice=14, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BowlingPin", basePrice=10, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BowlingPin_Nails", basePrice=14, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Branch_Broken", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Branch_Broken_Nails", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BrassNameplate", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CarpentryChisel", basePrice=12, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ChairLeg", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ChairLeg_Nails", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClubHammer", basePrice=10, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ClubHammerForged", basePrice=10, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Drumstick", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },

    -- Added by ItemGenerator
    { item="Base.PipeBomb", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombRemote", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV1", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV2", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV3", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombTriggered", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBomb", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombRemote", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV1", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV2", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV3", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombTriggered", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },

    -- Added by ItemGenerator
    { item="Base.FlameTrapTriggered", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrap", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapRemote", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV1", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV2", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV3", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapTriggered", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AnimalBone", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },

    -- Added by ItemGenerator
    { item="Base.Aerosolbomb", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombRemote", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV1", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV2", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV3", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombTriggered", basePrice=100, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },

    -- Added by ItemGenerator
    { item="Base.SpadeHead", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenForkHead", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenForkHead_Forged", basePrice=16, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandShovel", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FISH_DEV_ITEM", basePrice=17, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.FlameTrap", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapRemote", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV1", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV2", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV3", basePrice=5, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },


}

return DT_Melee.items
