-- ============================================================================
-- DT_Melee.lua
-- Weapon Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_Melee = DT_Melee or {}
DT_Melee.items = {
    -- Added by ItemGenerator
    { item="Base.Aerosolbomb", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombRemote", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV1", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV2", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombSensorV3", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AerosolbombTriggered", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBomb", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombRemote", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV1", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV2", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombSensorV3", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PipeBombTriggered", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBomb", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombRemote", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV1", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV2", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombSensorV3", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SmokeBombTriggered", basePrice=1, tags={"Weapon.Explosive", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Molotov", basePrice=1, tags={"Weapon.Explosive", "Rarity.Common"}, stockRange={min=2, max=10} },

    -- Added by ItemGenerator
    { item="Base.SpadeHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenForkHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenForkHead_Forged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandShovel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FISH_DEV_ITEM", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.FlameTrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapRemote", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV1", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapSensorV3", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FlameTrapTriggered", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapRemote", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV1", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapSensorV3", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.NoiseTrapTriggered", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.AnimalBone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BadmintonRacket", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BallPeenHammer", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BallPeenHammerForged", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BanjoNeck_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BaseballBat_Broken", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BaseballBat_Broken_Nails", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BlockMace", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BoneClub", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BoneClub_Spiked", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BowlingPin", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.BowlingPin_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Branch_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Branch_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.BrassNameplate", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CarpentryChisel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ChairLeg", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ChairLeg_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClubHammer", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ClubHammerForged", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Drumstick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.DumbBell", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.DumbBell_Forged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.File", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FireplacePoker", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Firewood", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Firewood_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FlintNodule", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Flute", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenToolHandle_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Gavel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GridlePan", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GuitarAcousticNeck_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.GuitarElectricBassNeck_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.GuitarElectricNeck_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Hammer", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HammerForged", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HammerStone", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Handle", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handle_Can", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handle_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IronBarHalf", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide_Club", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeAnimalBone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBoneClub", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeBoneClub_Spiked", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LargeHook", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LeadPipe", basePrice=3, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LongStick_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Mace", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Mace_Stone", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MasonsChisel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MasonsTrowel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalBar", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe_Broken", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.MetalworkingChisel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalworkingPunch", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Morningstar_Scrap_Short", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Nightstick", basePrice=3, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Pan", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PanForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PipeWrench", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Plank_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Plank_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Plunger", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Plunger_BarbedWire", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Ratchet", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RollingPin", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Saucepan", basePrice=4, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SaucepanCopper", basePrice=4, tags={"Weapon.Melee.General", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Saxophone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SheetMetalSnips", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShortBat", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_Can", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortBat_RakeHead", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_Nails", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SmithingHammer", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SpikedShortBat", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SteelBarHalf", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SteelRodHalf", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Stone2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TableLeg_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.TableLeg_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.TennisRacket", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TireIron", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TreeBranch2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Can", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TreeBranch_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Trumpet", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Violin", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.WoodenMallet", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodenStick_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick_Broken_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.WoodenStick_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Wrench", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.YardstickDEBUG", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Sawblade_Hatchet", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.EntrenchingTool", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.HandAxe", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandAxe_Old", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HandAxeForged", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandScythe", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandScytheForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Hatchet_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IceAxe", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MeatCleaver", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MeatCleaver_Scrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.MeatCleaverForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MetalPipe_Railspike", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.PrimitiveScythe", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Saw_Flint", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortBat_RailSpike", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.TreeBranch_Railspike", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Banjo", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Crafted", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Can", basePrice=3, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_GardenForkHead", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal", basePrice=3, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal_Bolts", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Nails", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_RakeHead", basePrice=2, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_ScrapSheet", basePrice=4, tags={"Weapon.Melee.Blunt", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Spiked", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BoltCutters", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom_Twig", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Broom_BarbedWire", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadelX2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CanoePadelX2_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Crowbar", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrowbarForged", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FieldHockeyStick_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FishingRod", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FishingRodBreak", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Gaffhook", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenHoe", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GardenHoeForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Golfclub", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GuitarAcoustic", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.HobbyHorse", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.IceHockeyStick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IceHockeyStick_BarbedWire", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IronBar", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.JawboneBovide_Morningstar", basePrice=6, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LaCrosseStick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.LeafRake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LongHandle", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Can", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_RakeHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongMace", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongMace_Stone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongSpikedClub", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongStick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Mop", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Morningstar_Scrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Plank", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Saw", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Poolcue", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Rake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Sapling", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponRakeHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Shovel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpadeForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpadeWood", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Shovel2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SnowShovel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SteelBar", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.StoneMaul", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TableLeg", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TableLeg_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodenStick_Can", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe", basePrice=3, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Old", basePrice=3, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_Sawblade", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Axe_ScrapCleaver", basePrice=2, tags={"Weapon.Melee.Axe", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.AxeStone", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Metal_Sawblade", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_RailSpike", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BaseballBat_Sawblade", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.FieldHockeyStick_Sawblade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.JawboneBovide_Axe", basePrice=1, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Railspike", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Sawblade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.PickAxe", basePrice=2, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.PickAxeForged", basePrice=2, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortBat_Sawblade", basePrice=1, tags={"Weapon.Melee.Blunt", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.StoneAxeLarge", basePrice=3, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.TableLeg_Sawblade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BarBell", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BarBell_Forged", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BlockMaul", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BucketMace_Metal", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BucketMace_Wood", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Brake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_GardenForkHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Nails", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Railspike", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_ScrapSheet", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Sawblade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_SpadeHead", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Cudgel_Spike", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.EngineMaul", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.GuitarElectricBass", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GuitarElectric", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Keytar", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.KettleMace_Metal", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.KettleMace_Wood", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.LargeBranch", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.LongHandle_Brake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Brake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Plank_Sawblade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.RailroadSpikePuller", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.RailroadSpikePullerOld", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.ScrapMaul", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=0, max=2} },
    { item="Base.ScrapWeapon_Brake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponGardenFork", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.ScrapWeaponSpade", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Sledgehammer", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Sledgehammer2", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SledgehammerForged", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TableLeg_Chain", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.WoodAxe", basePrice=12, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.WoodAxeForged", basePrice=8, tags={"Weapon.Melee.Axe", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrudeShortSword", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.CrudeSword", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.CrudeSword_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Katana", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Katana_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Machete", basePrice=2, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Machete_Crude", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.MacheteForged", basePrice=2, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.ShortSword", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ShortSword_Scrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Sword", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Sword_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.Sword_Scrap", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Sword_Scrap_Broken", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.BareHands", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaBlack", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaBlue", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaRed", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaTINTED", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ClosedUmbrellaWhite", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.GardenFork", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GardenFork_Forged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrafted", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCraftedFireHardened", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrude", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearCrudeLong", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearHandFork", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearGlass", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearHuntingKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearKnifeSmall", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearLong", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScissors", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScrewdriver", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearShort", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearSteakKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearStone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearStoneLong", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_BoneLong", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Spear_Plunger", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearLargeKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.SpearScrapKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.SpearFightingKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.BluePen", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.BreadKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.DullBoneKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.CarvingFork2", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.CompassGeometry", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CrudeKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.ButterKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ButterKnife_Gold", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.ButterKnife_Silver", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.FightingKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.FlintKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Fork", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Fork_Gold", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.Fork_Silver", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Fork_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ForkForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GlassShiv", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.GreenPen", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.HandFork", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HandguardDagger", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Handiknife", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HuntingKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.HuntingKnifeForged", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.IcePick", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KitchenKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KitchenKnifeForged", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KnifeButterfly", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeFillet", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.KnifeParing", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifePocket", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeShiv", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.KnifeSushi", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LargeKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.LargeKnife_Scrap", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.LetterOpener", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.LongCrudeKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.MacheteKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Multitool", basePrice=2, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Pen", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Pencil", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PencilSpiffo", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PenFancy", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PenMultiColor", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.PenSpiffo", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.RailroadSpike", basePrice=4, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.RailroadSpikeKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.RedPen", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Scalpel", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Scissors", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.ScissorsForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver_Old", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Screwdriver_Improvised", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SharpBone_Long", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SmallKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SmashedBottle", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Spoon", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Spoon_Gold", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common", "Quality.Luxury"}, stockRange={min=1, max=6} },
    { item="Base.Spoon_Silver", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Spoon_Bone", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SpoonForged", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Stake", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.SteakKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.StoneKnifeLong", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.SwitchKnife", basePrice=1, tags={"Weapon.Melee.Blade", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TinOpener_Old", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Toothbrush_Shiv", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Firecracker", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Firecracker_Crafted", basePrice=1, tags={"Weapon.Melee.General", "Rarity.Rare"}, stockRange={min=0, max=10} },


}

return DT_Melee.items
