-- =============================================================================
-- DYNAMIC TRADING: WEAPON - MELEE
-- =============================================================================
-- Root Category: Weapon
-- Sub Category: Melee
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.Axe",                tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Rarity.Common"}, basePrice=180, stockRange={min=1, max=5} },
    { item="Base.Axe_Old",            tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Quality.Waste"},  basePrice=120, stockRange={min=1, max=3} },
    { item="Base.Axe_Sawblade",           tags={"Weapon.Melee.Axe", "Origin.Civ", "Quality.Waste"}, basePrice=120, stockRange={min=0, max=2} },
    { item="Base.Axe_Sawblade_Hatchet",   tags={"Weapon.Melee.Axe", "Origin.Civ", "Quality.Waste"}, basePrice=85, stockRange={min=1, max=3} },
    { item="Base.Axe_ScrapCleaver",       tags={"Weapon.Melee.Axe", "Origin.Civ", "Quality.Waste"}, basePrice=60, stockRange={min=1, max=3} },
    { item="Base.Banjo",                basePrice=130, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.BarBell",            tags={"Weapon.Melee.HeavyBlunt", "Quality.Luxury"}, basePrice=300, stockRange={min=0, max=3} },
    { item="Base.BarBell_Forged",     tags={"Weapon.Melee.HeavyBlunt", "Rarity.Rare"},   basePrice=480, stockRange={min=0, max=1} }, -- Worth: 40.0,
    { item="Base.BaseballBat",                tags={"Weapon.Melee.Blunt", "Rarity.Common"},      basePrice=120, stockRange={min=2, max=10} }, -- Worth: 10.0,
    { item="Base.BaseballBat_Can",            tags={"Weapon.Melee.Blunt", "Quality.Waste"},      basePrice=108, stockRange={min=0, max=4} },
    { item="Base.BaseballBat_Crafted",        tags={"Weapon.Melee.Blunt", "Theme.Survival"},    basePrice=96,  stockRange={min=2, max=10} }, -- Worth: 8.0,
    { item="Base.BaseballBat_GardenForkHead", tags={"Weapon.Melee.Blunt", "Theme.Survival"},    basePrice=180, stockRange={min=0, max=3} }, -- Worth: 15.0,
    { item="Base.BaseballBat_Metal",          tags={"Weapon.Melee.Blunt", "Rarity.Rare"},        basePrice=240, stockRange={min=0, max=3} }, -- Worth: 20.0,
    { item="Base.BaseballBat_Metal_Bolts",    tags={"Weapon.Melee.Blunt", "Rarity.Rare"},        basePrice=300, stockRange={min=0, max=2} }, -- Worth: 25.0,
    { item="Base.BaseballBat_Metal_Sawblade", tags={"Weapon.Melee.Blunt", "Rarity.Rare"},        basePrice=360, stockRange={min=0, max=2} }, -- Worth: 30.0,
    { item="Base.BaseballBat_Nails",          tags={"Weapon.Melee.Blunt", "Theme.Survival"},    basePrice=132, stockRange={min=1, max=5} }, -- Worth: 11.0,
    { item="Base.BaseballBat_RailSpike",     tags={"Weapon.Melee.Blunt", "Origin.Civ", "Quality.Waste"}, basePrice=75, stockRange={min=0, max=2} },
    { item="Base.BaseballBat_RakeHead",       tags={"Weapon.Melee.Blunt", "Theme.Survival"},    basePrice=168, stockRange={min=0, max=3} }, -- Worth: 14.0,
    { item="Base.BaseballBat_Sawblade",      tags={"Weapon.Melee.Blunt", "Origin.Civ", "Quality.Waste"}, basePrice=95, stockRange={min=0, max=2} },
    { item="Base.BaseballBat_ScrapSheet",     tags={"Weapon.Melee.Blunt", "Quality.Waste"},      basePrice=156, stockRange={min=0, max=3} },
    { item="Base.BaseballBat_Spiked",         tags={"Weapon.Melee.Blunt", "Theme.Survival"},    basePrice=144, stockRange={min=1, max=5} }, -- Worth: 12.0,
    { item="Base.BlockMaul",          tags={"Weapon.Melee.HeavyBlunt", "Rarity.Uncommon"},     basePrice=300, stockRange={min=0, max=3} }, -- Worth: 25.0,
    { item="Base.BoneClub",             basePrice=60,  tags={"Weapon.Melee.Primitive", "Quality.Primitive", "Rarity.Common"}, stockRange={min=1, max=2} },
    { item="Base.BoneClub_Spiked",      basePrice=85,  tags={"Weapon.Melee.Primitive", "Quality.Primitive", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.BreadKnife",           basePrice=8,  tags={"Weapon.Melee.Sharp", "Theme.Cooking", "Rarity.Common"}, stockRange={min=2, max=8} },
    { item="Base.Broom", basePrice=25, tags={"Weapon.Melee.LongBlunt", "Tool.Cleaning.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.BucketMace_Metal",   tags={"Weapon.Melee.HeavyBlunt", "Quality.Waste"}, basePrice=120, stockRange={min=0, max=3} }, -- Worth: 10.0,
    { item="Base.BucketMace_Wood",    tags={"Weapon.Melee.HeavyBlunt", "Quality.Waste"}, basePrice=96,  stockRange={min=0, max=3} },
    { item="Base.ButterKnife",          basePrice=2,  tags={"Weapon.Melee.Sharp", "Quality.Waste", "Rarity.Common"}, stockRange={min=5, max=20} },
    { item="Base.ButterKnife_Gold",     basePrice=15, tags={"Weapon.Melee.Sharp", "Quality.Luxury", "Rarity.Legendary"}, stockRange={min=0, max=2} },
    { item="Base.ButterKnife_Silver",   basePrice=10, tags={"Weapon.Melee.Sharp", "Quality.Luxury", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ClosedUmbrellaBlack",  basePrice=45, tags={"Weapon.Melee.Spear", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Crowbar",            tags={"Weapon.Melee.Blunt", "Tool.General", "Rarity.Common"},        basePrice=180, stockRange={min=2, max=10} }, -- Worth: 15.0,
    { item="Base.CrowbarForged",      tags={"Weapon.Melee.Blunt", "Tool.General", "Rarity.Rare"},          basePrice=360, stockRange={min=0, max=3} }, -- Worth: 30.0,
    { item="Base.Cudgel_Bone",          tags={"Weapon.Melee.ShortBlunt", "Theme.Survival", "Rarity.Common"}, basePrice=120, stockRange={min=1, max=5} }, -- Worth: 10.0,
    { item="Base.Cudgel_Brake",           tags={"Weapon.Melee.HeavyBlunt", "Origin.Civ", "Rarity.Uncommon"}, basePrice=125, stockRange={min=0, max=1} },
    { item="Base.Cudgel_GardenForkHead",  tags={"Weapon.Melee.ShortBlunt", "Tool.Farmer", "Rarity.Uncommon"},   basePrice=120, stockRange={min=1, max=3} },
    { item="Base.Cudgel_Nails",           tags={"Weapon.Melee.ShortBlunt", "Theme.Survival", "Quality.Waste"},   basePrice=75, stockRange={min=1, max=4} },
    { item="Base.Cudgel_Railspike",       tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=115, stockRange={min=1, max=3} },
    { item="Base.Cudgel_Sawblade",        tags={"Weapon.Melee.HeavyBlunt", "Origin.Civ", "Rarity.Uncommon"}, basePrice=115, stockRange={min=0, max=1} },
    { item="Base.Cudgel_ScrapSheet",      tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=125, stockRange={min=0, max=2} },
    { item="Base.Cudgel_SpadeHead",       tags={"Weapon.Melee.HeavyBlunt", "Origin.Civ", "Rarity.Uncommon"}, basePrice=105, stockRange={min=0, max=1} },
    { item="Base.Cudgel_Spike",           tags={"Weapon.Melee.ShortBlunt", "Theme.Survival", "Quality.Waste"},   basePrice=85, stockRange={min=1, max=3} },
    { item="Base.Drumstick",            basePrice=15, tags={"Weapon.Melee.ShortBlunt", "Literature.Music.Instrument", "Quality.Waste"}, stockRange={min=2, max=10} },
    { item="Base.DullBoneKnife",        basePrice=2,  tags={"Weapon.Melee.Sharp", "Origin.Nomad", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.EngineMaul",         tags={"Weapon.Melee.HeavyBlunt", "Origin.Industrial"},   basePrice=240, stockRange={min=0, max=1} }, -- Worth: 20.0,
    { item="Base.EntrenchingTool",    tags={"Weapon.Melee.ShortBlunt", "Tool.General", "Origin.Militia", "Rarity.Common"},basePrice=75, stockRange={min=1, max=3} },
    { item="Base.FieldHockeyStick",           tags={"Weapon.Melee.LongBlunt", "Rarity.Common"},  basePrice=48,  stockRange={min=2, max=10} }, -- Worth: 4.0,
    { item="Base.FieldHockeyStick_Sawblade", tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=55, stockRange={min=0, max=2} },
    { item="Base.GardenFork",             tags={"Weapon.Melee.Spear", "Tool.Farmer", "Rarity.Common"}, basePrice=110, stockRange={min=1, max=3} },
    { item="Base.GardenFork_Forged",      tags={"Weapon.Melee.Spear", "Tool.Farmer", "Rarity.Rare"},   basePrice=180, stockRange={min=0, max=2} },
    { item="Base.GardenHoe",          tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Rarity.Common"},  basePrice=75, stockRange={min=1, max=3} },
    { item="Base.GardenHoeForged",    tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Rarity.Rare"},    basePrice=110, stockRange={min=0, max=2} },
    { item="Base.Golfclub",                   tags={"Weapon.Melee.LongBlunt", "Rarity.Common"},  basePrice=60,  stockRange={min=2, max=10} }, -- Worth: 5.0,
    { item="Base.GuitarAcoustic",       basePrice=150, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Uncommon"}, stockRange={min=0, max=1} },
    { item="Base.GuitarElectric",       basePrice=250, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.GuitarElectricBass",   basePrice=260, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.HandAxe",            tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Rarity.Common"}, basePrice=90,  stockRange={min=2, max=10} }, -- Worth: 7.5,
    { item="Base.HandAxeForged",      tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Rarity.Rare"},    basePrice=150, stockRange={min=0, max=3} },  -- Worth: 12.5,
    { item="Base.HandAxe_Old",        tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Quality.Waste"},  basePrice=60,  stockRange={min=2, max=6} },
    { item="Base.HandScythe",         tags={"Weapon.Melee.Axe", "Tool.Farmer", "Rarity.Common"},        basePrice=72,  stockRange={min=1, max=5} },  -- Worth: 6.0,
    { item="Base.HandScytheForged",   tags={"Weapon.Melee.Axe", "Tool.Farmer", "Rarity.Rare"},          basePrice=144, stockRange={min=0, max=2} },  -- Worth: 12.0,
    { item="Base.Hatchet_Bone",         tags={"Weapon.Melee.Axe", "Theme.Survival", "Rarity.Common"}, basePrice=36, stockRange={min=2, max=10} }, -- Worth: 3.0,
    { item="Base.IceAxe",             tags={"Weapon.Melee.Axe", "Theme.Survival", "Rarity.Rare"},        basePrice=180, stockRange={min=0, max=2} },  -- Worth: 15.0,
    { item="Base.IceHockeyStick",             tags={"Weapon.Melee.LongBlunt", "Rarity.Common"},  basePrice=48,  stockRange={min=2, max=10} },
    { item="Base.IcePick",              basePrice=5,  tags={"Weapon.Melee.Sharp", "Theme.Cooking", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.JawboneBovide_Axe",    tags={"Weapon.Melee.Axe", "Theme.Survival", "Rarity.Common"}, basePrice=48, stockRange={min=2, max=10} }, -- Worth: 4.0,
    { item="Base.KettleMace_Metal",   tags={"Weapon.Melee.HeavyBlunt", "Quality.Waste"}, basePrice=144, stockRange={min=0, max=3} },
    { item="Base.KettleMace_Wood",    tags={"Weapon.Melee.HeavyBlunt", "Quality.Waste"}, basePrice=120, stockRange={min=0, max=3} },
    { item="Base.Keytar",               basePrice=450, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.KitchenKnife",         basePrice=85, tags={"Weapon.Melee.Sharp", "Theme.Survival", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.KitchenKnifeForged",   basePrice=140, tags={"Weapon.Melee.Sharp", "Quality.Luxury", "Rarity.Uncommon"}, stockRange={min=0, max=2} },
    { item="Base.KnifeParing",          basePrice=5,  tags={"Weapon.Melee.Sharp", "Theme.Cooking", "Rarity.Common"}, stockRange={min=2, max=8} },
    { item="Base.LaCrosseStick",              tags={"Weapon.Melee.LongBlunt", "Rarity.Common"},  basePrice=60,  stockRange={min=1, max=5} },
    { item="Base.LargeBoneClub",        basePrice=85,  tags={"Weapon.Melee.Primitive", "Quality.Primitive", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.LargeBoneClub_Spiked", tags={"Weapon.Melee.Blunt", "Theme.Survival", "Rarity.Common"}, basePrice=60, stockRange={min=1, max=5} }, -- Worth: 5.0,
    { item="Base.LargeBranch",        tags={"Weapon.Melee.LongBlunt", "Origin.Nomad"}, basePrice=25, stockRange={min=2, max=8} },
    { item="Base.LeafRake",           tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Quality.Waste"}, basePrice=30, stockRange={min=1, max=4} },
    { item="Base.LetterOpener",     basePrice=15, tags={"Weapon.Melee.SmallBlade", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.LongHandle_Brake",       tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=85,  stockRange={min=0, max=3} },
    { item="Base.LongHandle_Can",         tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=55,  stockRange={min=1, max=5} },
    { item="Base.LongHandle_Nails",       tags={"Weapon.Melee.LongBlunt", "Theme.Survival", "Quality.Waste"},  basePrice=45,  stockRange={min=1, max=5} },
    { item="Base.LongHandle_Railspike",   tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=45,  stockRange={min=0, max=3} },
    { item="Base.LongHandle_RakeHead",    tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Quality.Waste"},     basePrice=65,  stockRange={min=1, max=4} },
    { item="Base.LongHandle_Sawblade",    tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=50,  stockRange={min=0, max=3} },
    { item="Base.LongMace",           tags={"Weapon.Melee.HeavyBlunt", "Theme.Survival"},      basePrice=180, stockRange={min=0, max=3} }, -- Worth: 15.0,
    { item="Base.LongMace_Stone",     tags={"Weapon.Melee.HeavyBlunt", "Theme.Survival"},      basePrice=60,  stockRange={min=1, max=5} }, -- Worth: 5.0,
    { item="Base.LongStick",          tags={"Weapon.Melee.LongBlunt", "Origin.Nomad"}, basePrice=12, stockRange={min=2, max=10} },
    { item="Base.MeatCleaver",          basePrice=180, tags={"Weapon.Melee.Sharp", "Theme.Survival", "Rarity.Uncommon"}, stockRange={min=0, max=2} },
    { item="Base.MeatCleaverForged",    basePrice=250, tags={"Weapon.Melee.Sharp", "Quality.Luxury", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.MeatCleaver_Scrap",      tags={"Weapon.Melee.Axe", "Origin.Civ", "Quality.Waste"}, basePrice=35, stockRange={min=1, max=4} },
    { item="Base.MetalPipe_Railspike",       tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=55, stockRange={min=0, max=2} },
    { item="Base.Mop", basePrice=30, tags={"Weapon.Melee.LongBlunt", "Tool.Cleaning.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Plank_Brake",            tags={"Weapon.Melee.Blunt", "Origin.Civ", "Quality.Waste"}, basePrice=65, stockRange={min=0, max=3} },
    { item="Base.Plank_Nails",        tags={"Weapon.Melee.LongBlunt", "Theme.Survival", "Quality.Waste"}, basePrice=25, stockRange={min=2, max=10} },
    { item="Base.Plank_Saw",          tags={"Weapon.Melee.LongBlunt", "Theme.Survival", "Quality.Waste"}, basePrice=35, stockRange={min=1, max=5} },
    { item="Base.Plank_Sawblade",         tags={"Weapon.Melee.Blunt", "Origin.Civ", "Quality.Waste"}, basePrice=55, stockRange={min=0, max=3} },
    { item="Base.PlasticKnife",         basePrice=0,  tags={"Weapon.Melee.Sharp", "Quality.Waste", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.Plunger", basePrice=15, tags={"Weapon.Melee.ShortBlunt", "Tool.Cleaning.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Poolcue",                    tags={"Weapon.Melee.LongBlunt", "Rarity.Common"},  basePrice=24,  stockRange={min=2, max=10} }, -- Worth: 2.0,
    { item="Base.PrimitiveScythe",      tags={"Weapon.Melee.Axe", "Theme.Survival", "Rarity.Common"}, basePrice=36, stockRange={min=1, max=5} }, -- Worth: 3.0,
    { item="Base.Rake",               tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Rarity.Common"},  basePrice=45, stockRange={min=1, max=4} },
    { item="Base.RollingPin",           basePrice=10, tags={"Weapon.Melee.Blunt", "Theme.Cooking", "Resource.Material.Wood", "Rarity.Common"}, stockRange={min=2, max=8} }, -- Solid blunt weapon,
    { item="Base.Saxophone",            basePrice=300, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ScrapMaul",          tags={"Weapon.Melee.HeavyBlunt", "Quality.Waste"},        basePrice=150, stockRange={min=0, max=3} },
    { item="Base.ScrapWeaponGardenFork", tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=85, stockRange={min=0, max=2} },
    { item="Base.ScrapWeaponSpade",   tags={"Weapon.Melee.LongBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=80, stockRange={min=0, max=2} },
    { item="Base.ScrapWeapon_Brake",      tags={"Weapon.Melee.HeavyBlunt", "Origin.Civ", "Rarity.Uncommon"}, basePrice=110, stockRange={min=0, max=2} },
    { item="Base.ShortBat_RailSpike",        tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=45, stockRange={min=1, max=3} },
    { item="Base.ShortBat_Sawblade",         tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=55, stockRange={min=1, max=3} },
    { item="Base.Shovel",             tags={"Weapon.Melee.LongBlunt", "Tool.General", "Rarity.Common"}, basePrice=85, stockRange={min=1, max=4} },
    { item="Base.Shovel2",            tags={"Weapon.Melee.LongBlunt", "Tool.General", "Rarity.Common"}, basePrice=85, stockRange={min=1, max=4} },
    { item="Base.SnowShovel",         tags={"Weapon.Melee.LongBlunt", "Tool.General", "Rarity.Common"}, basePrice=65, stockRange={min=1, max=3} },
    { item="Base.SpadeForged",        tags={"Weapon.Melee.LongBlunt", "Tool.Farmer", "Rarity.Rare"},    basePrice=120, stockRange={min=0, max=2} },
    { item="Base.SpearCrafted",           tags={"Weapon.Melee.Spear", "Rarity.Common"},        basePrice=15,  stockRange={min=2, max=6} },
    { item="Base.SpearCraftedFireHardened", tags={"Weapon.Melee.Spear", "Rarity.Common"},      basePrice=25,  stockRange={min=1, max=5} },
    { item="Base.SpearFightingKnife",     tags={"Weapon.Melee.Spear", "Origin.Militia", "Rarity.Rare"},    basePrice=180, stockRange={min=0, max=1} },
    { item="Base.SpearHuntingKnife",      tags={"Weapon.Melee.Spear", "Theme.Combat", "Rarity.Uncommon"}, basePrice=160, stockRange={min=0, max=1} },
    { item="Base.SpearKnife",             tags={"Weapon.Melee.Spear", "Origin.Civ", "Quality.Waste"},  basePrice=85,  stockRange={min=1, max=4} },
    { item="Base.SpearLargeKnife",        tags={"Weapon.Melee.Spear", "Theme.Combat", "Rarity.Uncommon"}, basePrice=150, stockRange={min=0, max=2} },
    { item="Base.SpearLong",              tags={"Weapon.Melee.Spear", "Rarity.Rare"},          basePrice=125, stockRange={min=0, max=2} },
    { item="Base.SpearScrewdriver",       tags={"Weapon.Melee.Spear", "Origin.Civ", "Quality.Waste"},  basePrice=75,  stockRange={min=1, max=3} },
    { item="Base.SpearShort",             tags={"Weapon.Melee.Spear", "Origin.Civ", "Quality.Waste"},  basePrice=95,  stockRange={min=1, max=3} },
    { item="Base.SpearStone",             tags={"Weapon.Melee.Spear", "Theme.Survival", "Origin.Nomad"}, basePrice=65, stockRange={min=1, max=4} },
    { item="Base.Spear_Plunger",        basePrice=25, tags={"Weapon.Melee.Spear", "Quality.Waste"}, stockRange={min=0, max=5} },
    { item="Base.SteakKnife",           basePrice=8,  tags={"Weapon.Melee.Sharp", "Theme.Cooking", "Rarity.Common"}, stockRange={min=2, max=8} },
    { item="Base.StoneMaul",          tags={"Weapon.Melee.HeavyBlunt", "Theme.Survival"},      basePrice=72,  stockRange={min=1, max=5} }, -- Worth: 6.0,
    { item="Base.StraightRazor",    basePrice=45, tags={"Weapon.Melee.SmallBlade", "Tool.Cleaning.Hygiene", "Rarity.Uncommon"}, stockRange={min=1, max=5} }, -- Good short blade,
    { item="Base.TableLeg_Sawblade",         tags={"Weapon.Melee.ShortBlunt", "Origin.Civ", "Quality.Waste"}, basePrice=45, stockRange={min=0, max=2} },
    { item="Base.ToiletBrush", basePrice=5, tags={"Weapon.Melee.ShortBlunt", "Tool.Cleaning.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.TreeBranch_Railspike",      tags={"Weapon.Melee.ShortBlunt", "Theme.Survival", "Quality.Waste"}, basePrice=25, stockRange={min=1, max=4} },
    { item="Base.Trumpet",              basePrice=220, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Rare"}, stockRange={min=1, max=3} },
    { item="Base.Violin",               basePrice=280, tags={"Weapon.Melee.Blunt", "Literature.Music.Instrument", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.WoodAxe",            tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Rarity.Uncommon"}, basePrice=300, stockRange={min=1, max=3} },
    { item="Base.WoodAxeForged",      tags={"Weapon.Melee.Axe", "Tool.Resource.Wood", "Rarity.Rare"},     basePrice=420, stockRange={min=0, max=2} },
})

print("[DynamicTrading] Weapon/Melee Registry Loaded.")
