-- ============================================================================
-- Container Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Container.Backpack] [Rarity.Rare] (171 items)
    { item="Base.Bag_ALICEpack", basePrice=110, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ALICEpack_Army", basePrice=110, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ALICEpack_DesertCamo", basePrice=110, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_AmmoBox", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_308", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_38", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_44", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_45", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_9mm", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_Hunting", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_Mixed", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_ShotgunShells", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BaseballBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BigHikingBag", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BigHikingBag_Travel", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BirthdayBasket", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BowlingBallBag", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BreakdownBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BurglarBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Burlap", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Cotton", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Denim", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_DenimBlack", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_DenimLight", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CraftedFramepack_Large", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_CraftedFramepack_Large2", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_CraftedFramepack_Large3", basePrice=65, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_CraftedFramepack_Small", basePrice=72, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CrudeLeatherBag", basePrice=98, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CrudeTarpBag", basePrice=95, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Dancer", basePrice=76, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadMice", basePrice=191, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRats", basePrice=191, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRoaches", basePrice=191, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DoctorBag", basePrice=51, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_DuffelBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_DuffelBagTINT", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FishingBasket", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FluteCase", basePrice=6, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FoodCanned", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FoodSnacks", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GardenBasket", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GolfBag", basePrice=105, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GolfBag_Melee", basePrice=105, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Gunny", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_HideSack", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_HideSatchel", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HideSlingBag", basePrice=119, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HikingBag_Travel", basePrice=124, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HydrationBackpack", basePrice=94, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HydrationBackpack_Camo", basePrice=94, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_InmateEscapedBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_JanitorToolbox", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_Laundry", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryHospital", basePrice=255, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryLinen", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Mail", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_MedicalBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Military", basePrice=126, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_MoneyBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_NormalHikingBag", basePrice=124, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_PicnicBasket", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Police", basePrice=126, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Survivalist", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Tools", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist", basePrice=102, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_308", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_38", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_44", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_45", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_556", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_9mm", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_Hunting", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_ShotgunShells", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard", basePrice=102, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary", basePrice=102, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2", basePrice=102, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police2", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police3", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseCloth", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseCloth2", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseClothCamo", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen2", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Fishing", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Leather", basePrice=91, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Mail", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Medical", basePrice=84, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Military", basePrice=84, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SatchelPhoto", basePrice=84, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SaxophoneCase", basePrice=19, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag", basePrice=108, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Kids", basePrice=108, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Medical", basePrice=87, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Patches", basePrice=108, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Travel", basePrice=108, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SheetSlingBag", basePrice=80, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Sheriff", basePrice=126, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCase_Police", basePrice=45, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseCloth", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseCloth2", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseGreen", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunDblBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunDblSawnoffBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunSawnoffBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SurvivorBag", basePrice=110, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_SWAT", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TarpFramepack_Large", basePrice=72, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_TarpFramepack_Small", basePrice=70, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TarpSack", basePrice=255, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TarpSlingBag", basePrice=99, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TennisBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ToolBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrashBag", basePrice=1275, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bag_TreasureBag", basePrice=191, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TrumpetCase", basePrice=6, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ViolinCase", basePrice=6, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_WeaponBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=4} },
    { item="Base.Bag_WorkerBag", basePrice=126, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DiceBag", basePrice=55, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.EmptySandbag", basePrice=191, tags={"Container.Backpack", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=6} },
    { item="Base.Garbagebag", basePrice=1275, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GemBag", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag1", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag2", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag3", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag4", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag5", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBagGourmet", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Handbag", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Lunchbag", basePrice=128, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaperBag", basePrice=128, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Jays", basePrice=128, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Spiffos", basePrice=128, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Bags", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Clothing", basePrice=510, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SeedBag", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SeedBag_Farming", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Tote_Bags", basePrice=76, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Backpack Registry Complete")
