-- =============================================================================
-- DYNAMIC TRADING: CONTAINER - BACKPACK
-- =============================================================================
-- Root Category: Container
-- Sub Category: Backpack
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.Bag_ALICE_BeltSus",            basePrice=350, tags={"Container.Backpack.Tactical", "Origin.Militia", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ALICE_BeltSus_Camo",       basePrice=350, tags={"Container.Backpack.Tactical", "Origin.Militia", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ALICE_BeltSus_Green",      basePrice=350, tags={"Container.Backpack.Tactical", "Origin.Militia", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ALICEpack",                basePrice=800, tags={"Container.Backpack.Military", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ALICEpack_Army",           basePrice=800, tags={"Container.Backpack.Military", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ALICEpack_DesertCamo",     basePrice=800, tags={"Container.Backpack.Military", "Rarity.Legendary"}, stockRange={min=0, max=1} },
    { item="Base.Bag_BaseballBag",              basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Bag_BigHikingBag",             basePrice=450, tags={"Container.Backpack.Civ", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.Bag_BigHikingBag_Travel",      basePrice=450, tags={"Container.Backpack.Civ", "Rarity.Rare"}, stockRange={min=1, max=2} },
    { item="Base.Bag_BreakdownBag",             basePrice=220, tags={"Container.Backpack.Survival", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.Bag_BurglarBag",               basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=2} },
    { item="Base.Bag_ChestRig",                 basePrice=300, tags={"Container.Backpack.Tactical", "Origin.Militia", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_ChestRig_Tarp",            basePrice=120, tags={"Container.Backpack.Tactical", "Theme.Survival", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.Bag_ClothSatchel_Burlap",      basePrice=45, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_ClothSatchel_Cotton",      basePrice=45, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_ClothSatchel_Denim",       basePrice=55, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_ClothSatchel_DenimBlack",  basePrice=55, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_ClothSatchel_DenimLight",  basePrice=55, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_CraftedFramepack_Large",   basePrice=80,  tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=1, max=3} },
    { item="Base.Bag_CraftedFramepack_Large2",  basePrice=120, tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=0, max=2} }, -- 25 Cap,
    { item="Base.Bag_CraftedFramepack_Large3",  basePrice=180, tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=0, max=1} }, -- 35 Cap,
    { item="Base.Bag_CraftedFramepack_Small",   basePrice=40,  tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=1, max=5} },
    { item="Base.Bag_CrudeLeatherBag",          basePrice=65, tags={"Container.Backpack.Sling", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_CrudeTarpBag",             basePrice=45, tags={"Container.Backpack.Sling", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_DuffelBag",                basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Bag_DuffelBagTINT",            basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FannyPackBack",            basePrice=30,  tags={"Container.Backpack.FannyPack", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Bag_FannyPackBack_Hide",       basePrice=30,  tags={"Container.Backpack.FannyPack", "Origin.Nomad"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FannyPackBack_Tarp",       basePrice=20,  tags={"Container.Backpack.FannyPack", "Origin.Nomad"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FannyPackFront",           basePrice=30,  tags={"Container.Backpack.FannyPack", "Rarity.Common"}, stockRange={min=2, max=10} },
    { item="Base.Bag_FannyPackFront_Hide",      basePrice=30,  tags={"Container.Backpack.FannyPack", "Origin.Nomad"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FannyPackFront_Tarp",      basePrice=20,  tags={"Container.Backpack.FannyPack", "Origin.Nomad"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FishingBasket",            basePrice=80,  tags={"Container.Backpack.Civ", "Theme.Survival", "Rarity.Common"}, stockRange={min=2, max=8} },
    { item="Base.Bag_FoodCanned",               basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=2} },
    { item="Base.Bag_FoodSnacks",               basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=2} },
    { item="Base.Bag_GolfBag",                  basePrice=110, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Bag_GolfBag_Melee",            basePrice=110, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.Bag_HideSatchel",              basePrice=80, tags={"Container.Backpack.Satchel", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_HideSlingBag",             basePrice=55, tags={"Container.Backpack.Sling", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_HikingBag_Travel",         basePrice=300, tags={"Container.Backpack.Civ", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.Bag_HydrationBackpack",      tags={"Container.Backpack.Hydration", "Origin.Militia", "Rarity.Rare"}, basePrice=450, stockRange={min=0, max=1} },
    { item="Base.Bag_HydrationBackpack_Camo", tags={"Container.Backpack.Hydration", "Origin.Militia", "Rarity.Rare"}, basePrice=450, stockRange={min=0, max=1} },
    { item="Base.Bag_InmateEscapedBag",         basePrice=160, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=2} },
    { item="Base.Bag_MedicalBag",      tags={"Container.Backpack", "Origin.Medical", "Rarity.Uncommon"}, basePrice=350, stockRange={min=1, max=5} },
    { item="Base.Bag_Military",                 basePrice=350, tags={"Container.Backpack.Military", "Rarity.Uncommon"}, stockRange={min=1, max=2} },
    { item="Base.Bag_MoneyBag",                 basePrice=300, tags={"Container.Backpack.Duffel", "Quality.Luxury", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_NormalHikingBag",          basePrice=300, tags={"Container.Backpack.Civ", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.Bag_Police",                   basePrice=180,  tags={"Container.Backpack.Duffel", "Origin.Police", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Bag_SWAT",                     basePrice=350,  tags={"Container.Backpack.Duffel", "Origin.Police", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.Bag_Satchel",                  basePrice=90, tags={"Container.Backpack.Satchel", "Rarity.Common"}, stockRange={min=5, max=10} },
    { item="Base.Bag_SatchelPhoto",             basePrice=95, tags={"Container.Backpack.Satchel", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Satchel_Fishing",          basePrice=90, tags={"Container.Backpack.Satchel", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Satchel_Leather",          basePrice=140, tags={"Container.Backpack.Satchel", "Quality.Premium", "Rarity.Uncommon"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Satchel_Mail",             basePrice=90, tags={"Container.Backpack.Satchel", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Satchel_Medical",          basePrice=110, tags={"Container.Backpack.Satchel", "Origin.Healthcare", "Rarity.Uncommon"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Satchel_Military",         basePrice=180, tags={"Container.Backpack.Satchel", "Origin.Militia", "Rarity.Uncommon"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Schoolbag",                basePrice=120, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=5, max=15} },
    { item="Base.Bag_Schoolbag_Kids",           basePrice=120, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=5, max=15} },
    { item="Base.Bag_Schoolbag_Medical",        basePrice=140, tags={"Container.Backpack.Civ", "Origin.Healthcare", "Rarity.Uncommon"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Schoolbag_Patches",        basePrice=130, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Bag_Schoolbag_Travel",         basePrice=120, tags={"Container.Backpack.Civ", "Rarity.Common"}, stockRange={min=2, max=5} },
    { item="Base.Bag_SheetSlingBag",            basePrice=25, tags={"Container.Backpack.Sling", "Quality.Waste"}, stockRange={min=5, max=15} },
    { item="Base.Bag_Sheriff",                  basePrice=180,  tags={"Container.Backpack.Duffel", "Origin.Police", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ShotgunBag",               basePrice=35,  tags={"Container.Backpack.Duffel", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ShotgunDblBag",            basePrice=35,  tags={"Container.Backpack.Duffel", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ShotgunDblSawnoffBag",     basePrice=35,  tags={"Container.Backpack.Duffel", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ShotgunSawnoffBag",        basePrice=35,  tags={"Container.Backpack.Duffel", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_SurvivorBag",              basePrice=650, tags={"Container.Backpack.Survival", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bag_TarpFramepack_Large",      basePrice=70,  tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=1, max=3} },
    { item="Base.Bag_TarpFramepack_Small",      basePrice=35,  tags={"Container.Backpack.Survival", "Quality.Standard"}, stockRange={min=1, max=5} },
    { item="Base.Bag_TarpSlingBag",             basePrice=35, tags={"Container.Backpack.Sling", "Theme.Survival"}, stockRange={min=2, max=8} },
    { item="Base.Bag_TennisBag",                basePrice=180, tags={"Container.Backpack.Duffel", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ToolBag",                  basePrice=200, tags={"Container.Backpack.Duffel", "Theme.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.Bag_WeaponBag",                basePrice=220, tags={"Container.Backpack.Duffel", "Origin.Militia", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
    { item="Base.Bag_WorkerBag",                basePrice=180, tags={"Container.Backpack.Duffel", "Theme.Utility", "Rarity.Common"}, stockRange={min=1, max=3} },
    { item="Base.HolsterShoulder",              basePrice=250, tags={"Container.Backpack.Tactical", "Rarity.Uncommon"}, stockRange={min=1, max=3} },
})

print("[DynamicTrading] Container/Backpack Registry Loaded.")
