-- ============================================================================
-- Container Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Container.Bag.General] [Rarity.Rare] (81 items)
    { item="Base.Bag_BirthdayBasket", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BowlingBallBag", basePrice=38, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Dancer", basePrice=76, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadMice", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRats", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRoaches", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DoctorBag", basePrice=51, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Clinical", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FluteCase", basePrice=6, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GardenBasket", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Gunny", basePrice=255, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_JanitorToolbox", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Bag_Laundry", basePrice=255, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryHospital", basePrice=255, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Clinical", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryLinen", basePrice=255, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Mail", basePrice=255, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_PicnicBasket", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Survivalist", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Tools", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Theme.Survival", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Theme.Combat", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police2", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police3", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen2", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SaxophoneCase", basePrice=19, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCase_Police", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseGreen", basePrice=45, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrashBag", basePrice=1275, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Bag_TreasureBag", basePrice=191, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TrumpetCase", basePrice=6, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ViolinCase", basePrice=6, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase", basePrice=34, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase_Money", basePrice=34, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Garbagebag", basePrice=1275, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag1", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag2", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag3", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag4", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag5", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBagGourmet", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Lunchbag", basePrice=128, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Jays", basePrice=128, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Spiffos", basePrice=128, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Bags", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Clothing", basePrice=510, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.SeedBag_Farming", basePrice=64, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=10} },
    { item="Base.Toolbox_Mechanic", basePrice=26, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Tote", basePrice=76, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Bags", basePrice=76, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Clothing", basePrice=76, tags={"Container.Bag.General", "Rarity.Rare", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Bag Registry Complete")
