-- ============================================================================
-- Container Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Container.Bag.General] [Rarity.Rare] (81 items)
    { item="Base.Bag_BirthdayBasket", basePrice=100, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BowlingBallBag", basePrice=101, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Dancer", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadMice", basePrice=154, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRats", basePrice=154, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRoaches", basePrice=154, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DoctorBag", basePrice=126, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_FluteCase", basePrice=72, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GardenBasket", basePrice=100, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Gunny", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_JanitorToolbox", basePrice=111, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Bag_Laundry", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_LaundryHospital", basePrice=205, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_LaundryLinen", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Mail", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_PicnicBasket", basePrice=100, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Survivalist", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Tools", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard", basePrice=159, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary", basePrice=123, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=137, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Theme.Clinical", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=123, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmall", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Combat", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Survival", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie", basePrice=89, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice", basePrice=96, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary", basePrice=103, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid", basePrice=103, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1", basePrice=103, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie", basePrice=103, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police", basePrice=115, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase_Police2", basePrice=115, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCase_Police3", basePrice=115, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_RifleCaseGreen", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen2", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SaxophoneCase", basePrice=83, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCase_Police", basePrice=115, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=3} },
    { item="Base.Bag_ShotgunCaseGreen", basePrice=107, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrashBag", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=7} },
    { item="Base.Bag_TreasureBag", basePrice=154, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Medium", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TrumpetCase", basePrice=72, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ViolinCase", basePrice=72, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase", basePrice=112, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase_Money", basePrice=112, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=4} },
    { item="Base.Garbagebag", basePrice=183, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.High", "Container.WeightReduction.Medium"}, stockRange={min=0, max=7} },
    { item="Base.GroceryBag1", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag2", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag3", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag4", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBag5", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.GroceryBagGourmet", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Lunchbag", basePrice=79, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Paperbag_Jays", basePrice=79, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Paperbag_Spiffos", basePrice=79, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag_Bags", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Plasticbag_Clothing", basePrice=114, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.SeedBag_Farming", basePrice=73, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Tiny", "Container.WeightReduction.Medium"}, stockRange={min=0, max=11} },
    { item="Base.Toolbox_Mechanic", basePrice=111, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=2} },
    { item="Base.Tote", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Bags", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Clothing", basePrice=102, tags={"Container.Bag.General", "Rarity.Rare", "Origin.Vanilla", "Container.Capacity.Low", "Container.WeightReduction.Medium"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Bag Registry Complete")
