-- ============================================================================
-- DT_Backpack.lua
-- Container Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_Backpack = DT_Backpack or {}
DT_Backpack.items = {
    -- Added by ItemGenerator
    { item="Base.Bag_GolfBag", basePrice=61, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GolfBag_Melee", basePrice=61, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag", basePrice=63, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Kids", basePrice=63, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_NormalHikingBag", basePrice=72, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BigHikingBag", basePrice=66, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SurvivorBag", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ALICEpack", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ALICEpack_Army", basePrice=64, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=2} },
    { item="Base.Bag_WeaponBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=4} },
    { item="Base.Bag_InmateEscapedBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_MoneyBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_WorkerBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_DuffelBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BreakdownBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_DuffelBagTINT", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Plasticbag", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Clothing", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Garbagebag", basePrice=750, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.EmptySandbag", basePrice=112, tags={"Container.Backpack", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRats", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadMice", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_DeadRoaches", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TreasureBag", basePrice=112, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Handbag", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseCloth", basePrice=28, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseCloth2", basePrice=28, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseCloth", basePrice=28, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseCloth2", basePrice=28, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseClothCamo", basePrice=28, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police2", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCase_Police3", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCase_Police", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_RifleCaseGreen2", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunCaseGreen", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FluteCase", basePrice=10, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ViolinCase", basePrice=10, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrumpetCase", basePrice=10, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SaxophoneCase", basePrice=11, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_JanitorToolbox", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ShotgunBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunSawnoffBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunDblBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ShotgunDblSawnoffBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BowlingBallBag", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BurglarBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SatchelPhoto", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TrashBag", basePrice=750, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Plasticbag_Bags", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Tote_Bags", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Dancer", basePrice=45, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_ProtectiveCase", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Survivalist", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCase_Tools", basePrice=26, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=26, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Theme.Combat"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1", basePrice=15, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_556", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_308", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_ShotgunShells", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_9mm", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_38", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_44", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_45", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_Hunting", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary", basePrice=60, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist", basePrice=60, tags={"Container.Backpack", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2", basePrice=60, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard", basePrice=60, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Police", basePrice=74, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Sheriff", basePrice=74, tags={"Container.Backpack", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SWAT", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FishingBasket", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_GardenBasket", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_PicnicBasket", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BirthdayBasket", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Patches", basePrice=63, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Travel", basePrice=63, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BigHikingBag_Travel", basePrice=66, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HikingBag_Travel", basePrice=72, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Fishing", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Medical", basePrice=49, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Military", basePrice=49, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Schoolbag_Medical", basePrice=51, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Gunny", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Laundry", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryLinen", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_LaundryHospital", basePrice=150, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Mail", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_Satchel_Mail", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Satchel_Leather", basePrice=53, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_308", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_ShotgunShells", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_9mm", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_38", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_44", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_45", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_Mixed", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_AmmoBox_Hunting", basePrice=22, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_BaseballBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TennisBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FoodCanned", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_FoodSnacks", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_MedicalBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Bag_Military", basePrice=74, tags={"Container.Backpack", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ToolBag", basePrice=74, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GroceryBag1", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag2", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag3", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag4", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBag5", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GroceryBagGourmet", basePrice=300, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bag_DoctorBag", basePrice=30, tags={"Container.Backpack", "Rarity.Rare", "Origin.Clinical"}, stockRange={min=0, max=4} },
    { item="Base.Lunchbag", basePrice=75, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PaperBag", basePrice=75, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Jays", basePrice=75, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Paperbag_Spiffos", basePrice=75, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SeedBag", basePrice=37, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SeedBag_Farming", basePrice=37, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GemBag", basePrice=37, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DiceBag", basePrice=32, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bag_ALICEpack_DesertCamo", basePrice=64, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting", basePrice=15, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Burlap", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Cotton", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_Denim", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_DenimBlack", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_ClothSatchel_DenimLight", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CrudeLeatherBag", basePrice=57, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CrudeTarpBag", basePrice=56, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HideSlingBag", basePrice=70, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HideSack", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_TarpSack", basePrice=150, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bag_HideSatchel", basePrice=49, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_SheetSlingBag", basePrice=46, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TarpSlingBag", basePrice=58, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CraftedFramepack_Large", basePrice=43, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_CraftedFramepack_Small", basePrice=42, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_CraftedFramepack_Large2", basePrice=37, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_CraftedFramepack_Large3", basePrice=38, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_TarpFramepack_Small", basePrice=41, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_TarpFramepack_Large", basePrice=42, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Bag_HydrationBackpack", basePrice=55, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bag_HydrationBackpack_Camo", basePrice=55, tags={"Container.Backpack", "Rarity.Rare"}, stockRange={min=0, max=4} },


}

return DT_Backpack.items
