-- =============================================================================
-- DYNAMIC TRADING: CONTAINER - ORGANIZER
-- =============================================================================
-- Root Category: Container
-- Sub Category: Organizer
-- =============================================================================

require "DT/Common/Config" 
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    { item="Base.Bag_AmmoBox",                  basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=5, max=15} },
    { item="Base.Bag_AmmoBox_308",              basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_38",               basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_44",               basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_45",               basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_9mm",              basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_Hunting",          basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_Mixed",            basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_AmmoBox_ShotgunShells",    basePrice=10,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_DoctorBag",                basePrice=20,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=1, max=5} },
    { item="Base.Bag_FluteCase",                basePrice=10,  tags={"Container.Organizer", "Literature.Music"}, stockRange={min=1, max=3} },
    { item="Base.Bag_JanitorToolbox",           basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Bag_ProtectiveCase",           basePrice=25,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseBulky",      basePrice=30,  tags={"Container.Organizer", "Quality.Heavy"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo",  basePrice=30,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_308",basePrice=30, tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_38",basePrice=30,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_44",basePrice=30,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_45",basePrice=30,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_556",basePrice=30, tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_9mm",basePrice=30, tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_Hunting",basePrice=30,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyAmmo_ShotgunShells",basePrice=30,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyHazard",basePrice=35,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary",basePrice=40,tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulkyMilitary_HAMRadio2",basePrice=45,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulky_Audio",basePrice=30,  tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulky_HAMRadio1",basePrice=35,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulky_SCBA", basePrice=30,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseBulky_Survivalist",basePrice=35,tags={"Container.Organizer", "Theme.Survival"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary",   basePrice=35,  tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary_Medical", basePrice=35, tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseMilitary_Tools", basePrice=35, tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCaseSmall",      basePrice=15,  tags={"Container.Organizer"}, stockRange={min=2, max=8} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary",basePrice=20,tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_FirstAid",basePrice=25,tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_Pistol1",basePrice=20,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmallMilitary_WalkieTalkie",basePrice=20,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Armorer",basePrice=20,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Electronics",basePrice=20,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_FirstAid",basePrice=20,tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_KeyCutting",basePrice=15,tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol1",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol2",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Pistol3",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver1",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver2",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Revolver3",basePrice=15,tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_Survivalist",basePrice=20,tags={"Container.Organizer", "Theme.Survival"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkie",basePrice=15,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCaseSmall_WalkieTalkiePolice",basePrice=15,tags={"Container.Organizer", "Theme.Digital"}, stockRange={min=1, max=5} },
    { item="Base.Bag_ProtectiveCase_Survivalist",basePrice=30, tags={"Container.Organizer", "Theme.Survival"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ProtectiveCase_Tools",     basePrice=30,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=1, max=3} },
    { item="Base.Bag_RifleCase",                basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_RifleCaseCloth",           basePrice=20,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_RifleCaseCloth2",          basePrice=20,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_RifleCaseClothCamo",       basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=1, max=3} },
    { item="Base.Bag_RifleCaseGreen",           basePrice=30,  tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=3} },
    { item="Base.Bag_RifleCaseGreen2",          basePrice=30,  tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=3} },
    { item="Base.Bag_RifleCase_Police",         basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_RifleCase_Police2",        basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_RifleCase_Police3",        basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_SaxophoneCase",            basePrice=20,  tags={"Container.Organizer", "Literature.Music"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ShotgunCaseCloth",         basePrice=20,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_ShotgunCaseCloth2",        basePrice=20,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_ShotgunCaseGreen",         basePrice=30,  tags={"Container.Organizer", "Origin.Militia"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ShotgunCase_Police",       basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Bag_TrumpetCase",              basePrice=15,  tags={"Container.Organizer", "Literature.Music"}, stockRange={min=1, max=3} },
    { item="Base.Bag_ViolinCase",               basePrice=15,  tags={"Container.Organizer", "Literature.Music"}, stockRange={min=1, max=3} },
    { item="Base.Briefcase",                    basePrice=15,  tags={"Container.Organizer", "Theme.Office"}, stockRange={min=2, max=8} },
    { item="Base.Briefcase_Money",              basePrice=40,  tags={"Container.Organizer", "Quality.Luxury"}, stockRange={min=1, max=3} },
    { item="Base.Cashbox",                      basePrice=10,  tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.CigarBox",                     basePrice=5,   tags={"Container.Organizer"}, stockRange={min=2, max=10} },
    { item="Base.CigarBox_Gaming",              basePrice=8,   tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.CigarBox_Keepsakes",           basePrice=8,   tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.CigarBox_Kids",                basePrice=5,   tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.Cooler",                       basePrice=20,  tags={"Container.Organizer", "Food"}, stockRange={min=2, max=8} },
    { item="Base.Cooler_Beer",                  basePrice=25,  tags={"Container.Organizer", "Food"}, stockRange={min=1, max=5} },
    { item="Base.Cooler_Meat",                  basePrice=30,  tags={"Container.Organizer", "Food"}, stockRange={min=1, max=5} },
    { item="Base.Cooler_Seafood",               basePrice=30,  tags={"Container.Organizer", "Food"}, stockRange={min=1, max=5} },
    { item="Base.Cooler_Soda",                  basePrice=25,  tags={"Container.Organizer", "Food"}, stockRange={min=1, max=5} },
    { item="Base.FirstAidKit",          basePrice=40, tags={"Container.Organizer.Medical", "Origin.Healthcare"}, stockRange={min=1, max=5} },
    { item="Base.FirstAidKit_Camping",          basePrice=10,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=2, max=8} },
    { item="Base.FirstAidKit_Camping_New",      basePrice=10,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=2, max=8} },
    { item="Base.FirstAidKit_Military",         basePrice=15,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=2, max=8} },
    { item="Base.FirstAidKit_New",              basePrice=10,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=5, max=15} },
    { item="Base.FirstAidKit_NewPro",           basePrice=12,  tags={"Container.Organizer", "Theme.Clinical"}, stockRange={min=5, max=15} },
    { item="Base.Flightcase",                   basePrice=20,  tags={"Container.Organizer", "Container.Misc"}, stockRange={min=1, max=5} },
    { item="Base.Garbagebag_box",               basePrice=10,  tags={"Container.Organizer", "Quality.Waste"}, stockRange={min=1, max=5} },
    { item="Base.Guitarcase",                   basePrice=20,  tags={"Container.Organizer", "Literature.Music"}, stockRange={min=1, max=3} },
    { item="Base.Hatbox",                       basePrice=5,   tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.Lunchbag",                     basePrice=5,   tags={"Container.Organizer", "Food"}, stockRange={min=5, max=15} },
    { item="Base.Lunchbox",                     basePrice=8,   tags={"Container.Organizer", "Food"}, stockRange={min=2, max=10} },
    { item="Base.Lunchbox2",                    basePrice=8,   tags={"Container.Organizer", "Food"}, stockRange={min=2, max=10} },
    { item="Base.MakeupCase_Professional",      basePrice=15,  tags={"Container.Organizer"}, stockRange={min=1, max=5} },
    { item="Base.PencilCase",                   basePrice=5,   tags={"Container.Organizer"}, stockRange={min=5, max=15} },
    { item="Base.PencilCase_Gaming",            basePrice=5,   tags={"Container.Organizer"}, stockRange={min=2, max=8} },
    { item="Base.PistolCase1",                  basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.PistolCase2",                  basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.PistolCase3",                  basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.RevolverCase1",                basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.RevolverCase2",                basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.RevolverCase3",                basePrice=15,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=8} },
    { item="Base.RifleCase1",                   basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.RifleCase2",                   basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.RifleCase3",                   basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.RifleCase4",                   basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.SewingKit",                    basePrice=10,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Shoebox",                      basePrice=2,   tags={"Container.Organizer"}, stockRange={min=5, max=20} },
    { item="Base.ShotgunCase1",                 basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.ShotgunCase2",                 basePrice=25,  tags={"Container.Organizer", "Theme.Combat"}, stockRange={min=2, max=5} },
    { item="Base.Suitcase",                     basePrice=15,  tags={"Container.Organizer", "Container.Misc"}, stockRange={min=2, max=8} },
    { item="Base.Tacklebox",                    basePrice=12,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.ToolRoll_Fabric",              basePrice=8,   tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.ToolRoll_Leather",             basePrice=12,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox",                      basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox_Farming",              basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox_Fishing",              basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox_Gardening",            basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox_Mechanic",             basePrice=15,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
    { item="Base.Toolbox_Wooden",               basePrice=10,  tags={"Container.Organizer", "Theme.Utility"}, stockRange={min=2, max=10} },
})

print("[DynamicTrading] Container/Organizer Registry Loaded.")
