-- ============================================================================
-- Container Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Container.General] [Rarity.Common] (20 items)
    { item="Base.BigTrunk1", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BigTrunk2", basePrice=8, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BigTrunk3", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.Canteen", basePrice=6, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.DebugFluid", basePrice=2500, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.GloveBox1", basePrice=2, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GloveBox2", basePrice=6, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GloveBox3", basePrice=6, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.KeyRing_Kitty", basePrice=46, tags={"Container.General", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.NormalTrunk1", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk2", basePrice=5, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk3", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SmallTrunk1", basePrice=3, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SmallTrunk2", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SmallTrunk3", basePrice=4, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TestDebugWater", basePrice=2500, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.TrailerTrunk1", basePrice=8, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TrailerTrunk2", basePrice=8, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TrailerTrunk3", basePrice=8, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.VanSeatsTrunk2", basePrice=6, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },

    -- [Container.General] [Rarity.Rare] (218 items)
    { item="Base.AmmoStrap_Brown_Bullets", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.AmmoStrap_Brown_Shells", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.AmmoStrap_Bullets", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.AmmoStrap_Bullets_308", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.AmmoStrap_Shells", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.BeerCanEmpty", basePrice=13, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.BeerEmpty", basePrice=42, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.BigGasTank1", basePrice=17, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BigGasTank2", basePrice=14, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BigGasTank3", basePrice=17, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Bleach", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BottleCrafted", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Brandy", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Briefcase", basePrice=34, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase_Money", basePrice=34, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Bucket", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarved", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BucketEmpty", basePrice=42, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.BucketForged", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketLargeWood", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BucketWaterDebug", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketWood", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CanteenClay", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Cashbox", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CeramicCrucible", basePrice=3, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CeramicCrucibleSmall", basePrice=32, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicTeacup", basePrice=2, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Champagne", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cider", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CigarBox", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Gaming", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Keepsakes", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Kids", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayJar", basePrice=35, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayJarGlazed", basePrice=35, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CleaningLiquid2", basePrice=7, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Cologne", basePrice=2, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CookieJar", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CookieJar_Bear", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Beer", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Meat", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Seafood", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Soda", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Curacao", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.DrinkingGlass", basePrice=3, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.EmptyJar", basePrice=21, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.FeedingBottle", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FirstAidKit", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FirstAidKit_Camping", basePrice=42, tags={"Container.General", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=6} },
    { item="Base.FirstAidKit_Camping_New", basePrice=42, tags={"Container.General", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=6} },
    { item="Base.FirstAidKit_Military", basePrice=42, tags={"Container.General", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=6} },
    { item="Base.FirstAidKit_New", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FirstAidKit_NewPro", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Flask", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flightcase", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FountainCup", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.FountainCupWater", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Gin", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.GlassChampagne", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GlassTumbler", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GlassWine", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Goblet", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Gold", basePrice=4, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Silver", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Wood", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Grenadine", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Guitarcase", basePrice=32, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.HairDyeCommon", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HairDyeRare", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HairDyeUncommon", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HalloweenCandyBucket", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hatbox", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HotWaterBottle", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Humidor", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.IndustrialDye", basePrice=85, tags={"Container.General", "Rarity.Rare", "Origin.Industrial"}, stockRange={min=0, max=10} },
    { item="Base.JarCrafted", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JerryCan", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.JewelleryBox", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.JewelleryBox_Fancy", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.KeyRing", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Bass", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_BlueFox", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Bug", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_CarDealer", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Clover", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_EagleFlag", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_EightBall", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Forged", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Forged_Gold", basePrice=79, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Forged_Silver", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Hotdog", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Large", basePrice=157, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Nolans", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Panther", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_PineTree", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_PrayingHands", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_RabbitFoot", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.KeyRing_Racing12", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Racing34", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Racing58", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_RainbowStar", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_RubberDuck", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_SecurityPass", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Sexy", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Spiffos", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_StinkyFace", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_WestMaple", basePrice=79, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Lunchbox", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Lunchbox2", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MakeupCase_Professional", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.MayonnaiseEmpty", basePrice=8, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.ModernBrake1", basePrice=57, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake2", basePrice=57, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake3", basePrice=57, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernTire1", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire2", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire3", basePrice=11, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.MugSpiffo", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.NormalBrake1", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalBrake2", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalBrake3", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalCarSeat1", basePrice=6, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat2", basePrice=6, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat3", basePrice=6, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank1", basePrice=16, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank2", basePrice=16, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank3", basePrice=16, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake1", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.OldBrake2", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.OldBrake3", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.OldTire1", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldTire2", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldTire3", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.PaintbucketEmpty", basePrice=42, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_ExtraLarge", basePrice=85, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_ExtraSmall", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Large", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Medium", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Small", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PencilCase", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PencilCase_Gaming", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Perfume", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PetrolCan", basePrice=27, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.PhotoAlbum", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PhotoAlbum_Old", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PistolCase1", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PistolCase2", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PistolCase3", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PlasticCup", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pop2Empty", basePrice=13, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Pop3Empty", basePrice=13, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.PopEmpty", basePrice=13, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Port", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_ExtraLarge", basePrice=85, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_ExtraSmall", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Large", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Medium", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Small", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_ExtraLarge", basePrice=85, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_ExtraSmall", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Large", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Medium", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Small", basePrice=8, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Purse", basePrice=40, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RemouladeEmpty", basePrice=85, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.RevolverCase1", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RevolverCase2", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RevolverCase3", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RifleCase1", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase2", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase3", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase4", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Rum", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Scotch", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SewingKit", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Sherry", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Shoebox", basePrice=13, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ShotgunCase1", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShotgunCase2", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.SimpleSyrup", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SmallGasTank1", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallGasTank2", basePrice=17, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallGasTank3", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.Sportsbottle", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Suitcase", basePrice=34, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Tacklebox", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TakeoutBox_Chinese", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TakeoutBox_Styrofoam", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Teacup", basePrice=2, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Tequila", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TinCanEmpty", basePrice=6, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Toolbox", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Farming", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Fishing", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Gardening", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Mechanic", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Wooden", basePrice=38, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ToolRoll_Fabric", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ToolRoll_Leather", basePrice=51, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tote", basePrice=76, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Clothing", basePrice=76, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TrophyBronze", basePrice=1, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.TrophyGold", basePrice=1, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=2} },
    { item="Base.TrophySilver", basePrice=1, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Vermouth", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Vodka", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallet_Hide", basePrice=21, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WaterBottle", basePrice=42, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WaterDish", basePrice=4, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WaterDispenserBottle", basePrice=32, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.WateredCan", basePrice=17, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.WheatSack", basePrice=191, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WheatSeedSack", basePrice=191, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Whiskey", basePrice=6, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },

    -- [Container.General] [Rarity.Uncommon] (2 items)
    { item="Base.CanteenMilitary", basePrice=8, tags={"Container.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=5, max=25} },
    { item="Base.CanteenMilitaryFull", basePrice=8, tags={"Container.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=5, max=25} },
})

print("[DynamicTrading] Organizer Registry Complete")
