-- ============================================================================
-- DT_Organizer.lua
-- Container Items Registry for Dynamic Trading
-- Auto-generated item list with pricing and stock ranges
-- ============================================================================

DT_Organizer = DT_Organizer or {}
DT_Organizer.items = {
    -- Added by ItemGenerator
    { item="Base.BucketLargeWood", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.PotForged", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.TestDebugWater", basePrice=2500, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Cologne", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HairDyeCommon", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HairDyeUncommon", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.HairDyeRare", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Perfume", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.EmptyJar", basePrice=12, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.JarCrafted", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bleach", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CleaningLiquid2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bowl", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.GlassTumbler", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GlassChampagne", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.GlassWine", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Mugl", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.MugWhite", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MugSpiffo", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Teacup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pot", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Kettle", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Kettle_Copper", basePrice=10, tags={"Container.General", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=4} },
    { item="Base.DebugFluid", basePrice=2500, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Milk", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BeerBottle", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.BeerCan", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.BeerImported", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Brandy", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Champagne", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cider", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CoffeeLiquer", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Curacao", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Gin", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Grenadine", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Port", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Rum", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Scotch", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Sherry", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Tequila", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Vermouth", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Vodka", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Whiskey", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wine", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Wine2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WineOpen", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Wine2Open", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WineAged", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.WineScrewtop", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.JuiceBox", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceBoxApple", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceBoxFruitpunch", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceBoxOrange", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceCranberry", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceFruitpunch", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceGrape", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceLemon", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceOrange", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.JuiceTomato", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Pop", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Pop2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Pop3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PopBottle", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PopBottleRare", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.SodaCan", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PetrolCan", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BottleCrafted", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BeerCanEmpty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.BeerEmpty", basePrice=25, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.PlasticCup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MayonnaiseEmpty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.RemouladeEmpty", basePrice=50, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.FountainCup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.PopEmpty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Pop2Empty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Pop3Empty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.TinCanEmpty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.WaterRationCanEmpty", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=10} },
    { item="Base.Disinfectant", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.TrophyBronze", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.TrophyGold", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=2} },
    { item="Base.TrophySilver", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.WaterDish", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayBowl", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayJar", basePrice=20, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayJarGlazed", basePrice=20, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ClayMug", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicCrucible", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.CeramicCrucibleSmall", basePrice=18, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.CeramicTeacup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.IndustrialDye", basePrice=50, tags={"Container.General", "Rarity.Rare", "Origin.Industrial"}, stockRange={min=0, max=10} },
    { item="Base.OldTire1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldTire2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldTire3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalTire3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.ModernTire3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.OldBrake1", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalBrake1", basePrice=29, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake1", basePrice=33, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.OldBrake2", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalBrake2", basePrice=29, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake2", basePrice=33, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.OldBrake3", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.NormalBrake3", basePrice=29, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.ModernBrake3", basePrice=33, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.SmallGasTank1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BigGasTank1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallGasTank2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BigGasTank2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallGasTank3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalGasTank3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.BigGasTank3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.SmallTrunk1", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk1", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BigTrunk1", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.VanSeatsTrunk2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SmallTrunk2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BigTrunk2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.SmallTrunk3", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.NormalTrunk3", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.BigTrunk3", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TrailerTrunk1", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TrailerTrunk2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.TrailerTrunk3", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=0, max=2} },
    { item="Base.GloveBox1", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GloveBox2", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.GloveBox3", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=1, max=5} },
    { item="Base.NormalCarSeat1", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat2", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.NormalCarSeat3", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=1} },
    { item="Base.FeedingBottle", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.BucketEmpty", basePrice=25, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.PaintbucketEmpty", basePrice=25, tags={"Container.General", "Rarity.Rare", "Quality.Waste"}, stockRange={min=0, max=4} },
    { item="Base.WateredCan", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BucketWaterDebug", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.WaterBottle", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Bucket", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketWood", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.BucketCarved", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.BucketForged", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CanteenMilitary", basePrice=10, tags={"Container.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=5, max=25} },
    { item="Base.CanteenMilitaryFull", basePrice=10, tags={"Container.General", "Rarity.Uncommon", "Origin.Militia"}, stockRange={min=5, max=25} },
    { item="Base.Canteen", basePrice=10, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.CanteenClay", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.DrinkingGlass", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.FountainCupWater", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Goblet", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Gold", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Silver", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Goblet_Wood", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HotWaterBottle", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.JerryCan", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.SimpleSyrup", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MilkBottle", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Flask", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Sportsbottle", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WaterDispenserBottle", basePrice=18, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.MetalCup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CopperCup", basePrice=10, tags={"Container.General", "Rarity.Rare", "Origin.Police"}, stockRange={min=0, max=6} },
    { item="Base.GoldCup", basePrice=10, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.SilverCup", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Milk_Personalsized", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.MilkChocolate_Personalsized", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.WineBox", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.Tote", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tote_Clothing", basePrice=45, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Purse", basePrice=23, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Suitcase", basePrice=20, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Farming", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Wooden", basePrice=22, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FirstAidKit", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Lunchbox", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Lunchbox2", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Flightcase", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Guitarcase", basePrice=18, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase", basePrice=20, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.PistolCase1", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PistolCase2", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PistolCase3", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RevolverCase1", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RevolverCase2", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.RevolverCase3", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Toolbox_Mechanic", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Cooler_Beer", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Meat", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Soda", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Briefcase_Money", basePrice=20, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Toolbox_Fishing", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Toolbox_Gardening", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.FirstAidKit_New", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FirstAidKit_NewPro", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Tacklebox", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase1", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase2", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase3", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.RifleCase4", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShotgunCase1", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ShotgunCase2", basePrice=26, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_ExtraSmall", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Small", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Medium", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_Large", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Parcel_ExtraLarge", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_ExtraSmall", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Small", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Medium", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_Large", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Present_ExtraLarge", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Wallet", basePrice=12, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Wallet_Female", basePrice=12, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Wallet_Male", basePrice=12, tags={"Container.General", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.SewingKit", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.KeyRing", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_CarDealer", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Bass", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_BlueFox", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Bug", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Clover", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_EagleFlag", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_EightBall", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Hotdog", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Kitty", basePrice=46, tags={"Container.General", "Rarity.Common"}, stockRange={min=10, max=50} },
    { item="Base.KeyRing_Large", basePrice=92, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Nolans", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Panther", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_PineTree", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_PrayingHands", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_RabbitFoot", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },
    { item="Base.KeyRing_RainbowStar", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_RubberDuck", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_SecurityPass", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Sexy", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Spiffos", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_StinkyFace", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_WestMaple", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Racing12", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Racing34", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Racing58", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.WheatSack", basePrice=112, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WheatSeedSack", basePrice=112, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TakeoutBox_Styrofoam", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.TakeoutBox_Chinese", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PencilCase", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PencilCase_Gaming", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Humidor", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CigarBox", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Gaming", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Keepsakes", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CigarBox_Kids", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.CookieJar", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.CookieJar_Bear", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.JewelleryBox", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.JewelleryBox_Fancy", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.FirstAidKit_Camping", basePrice=25, tags={"Container.General", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=6} },
    { item="Base.FirstAidKit_Camping_New", basePrice=25, tags={"Container.General", "Rarity.Rare", "Theme.Survival"}, stockRange={min=0, max=6} },
    { item="Base.FirstAidKit_Military", basePrice=25, tags={"Container.General", "Rarity.Rare", "Origin.Militia"}, stockRange={min=0, max=6} },
    { item="Base.HalloweenCandyBucket", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.MakeupCase_Professional", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cashbox", basePrice=15, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ToolRoll_Leather", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ToolRoll_Fabric", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hatbox", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shoebox", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PhotoAlbum", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.PhotoAlbum_Old", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.ProduceBox_ExtraSmall", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Small", basePrice=10, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Medium", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_Large", basePrice=25, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.ProduceBox_ExtraLarge", basePrice=50, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Cooler_Seafood", basePrice=30, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.KeyRing_Forged", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Forged_Gold", basePrice=46, tags={"Container.General", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=20} },
    { item="Base.KeyRing_Forged_Silver", basePrice=46, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=20} },
    { item="Base.Wallet_Hide", basePrice=12, tags={"Container.General", "Rarity.Rare"}, stockRange={min=0, max=10} },


}

return DT_Organizer.items
