-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Bottom] [Rarity.Rare] (117 items)
    { item="Base.Dungarees", basePrice=18, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Dungarees_HuntingCamo", basePrice=18, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Ghillie_Trousers", basePrice=7, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.LongJohns_Bottoms", basePrice=10, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.LongJohns_Bottoms_Crafted_Burlap", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.LongJohns_Bottoms_Crafted_Cotton", basePrice=10, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_BoxingBlue", basePrice=4, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_BoxingRed", basePrice=4, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_CamoDesertNewLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_CamoGreenLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_CamoMiliusLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_CamoTigerStripeLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_CamoUrbanLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_FootballPants", basePrice=139, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_FootballPants_Black", basePrice=139, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_FootballPants_Gold", basePrice=139, tags={"Clothing.Bottom", "Rarity.Rare", "Quality.Luxury", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_FootballPants_White", basePrice=139, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_HockeyPants", basePrice=191, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_HockeyPants_Black", basePrice=191, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_HockeyPants_Red", basePrice=191, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_HockeyPants_UniBlue", basePrice=191, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_HockeyPants_White", basePrice=191, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_LongDenim", basePrice=83, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_LongDenim_Punk", basePrice=83, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_LongSport", basePrice=8, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_LongSport_Red", basePrice=8, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_OliveDrabLong", basePrice=17, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_ShortDenim", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_ShortFormal", basePrice=5, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shorts_ShortSport", basePrice=5, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Crafted_Burlap", basePrice=9, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Crafted_Cotton", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Crafted_Denim", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Crafted_DenimBlack", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Crafted_DenimLight", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_DeerHide", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Garbage", basePrice=9, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Hide", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Knees_Tarp", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Crafted_Burlap", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Crafted_Cotton", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Crafted_Denim", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Crafted_DenimBlack", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Crafted_DenimLight", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Garbage", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Hide", basePrice=4, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Long_Tarp", basePrice=4, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Mini", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Normal", basePrice=1, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Normal_Garbage", basePrice=2, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Normal_Hide", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Normal_Tarp", basePrice=3, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Short", basePrice=1, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Short_FaunHide", basePrice=14, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Short_Garbage", basePrice=8, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Short_Hide", basePrice=14, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Skirt_Short_Tarp", basePrice=14, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Socks_LegWarmers", basePrice=24, tags={"Clothing.Bottom", "Rarity.Rare", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=10} },
    { item="Base.Trousers", basePrice=18, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_ArmyService", basePrice=37, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Militia", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Black", basePrice=33, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoDesert", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoDesertNew", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoGreen", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoMilius", basePrice=85, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoTigerStripe", basePrice=85, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_CamoUrban", basePrice=85, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Chef", basePrice=12, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_Burlap", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_Cotton", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_Denim", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_DenimBlack", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_DenimLight", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Crafted_DenimRandom", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_DeerHide", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_DefaultTEXTURE", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_DefaultTEXTURE_HUE", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_DefaultTEXTURE_TINT", basePrice=16, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Denim", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Denim_Punk", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_FaunHide", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Hide", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_HuntingCamo", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_JeanBaggy", basePrice=35, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_JeanBaggy_Punk", basePrice=35, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_LeatherBlack", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_LeatherCrafted", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_NavyBlue", basePrice=29, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_OliveDrab", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Padded", basePrice=22, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Padded_HuntingCamo", basePrice=22, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Police", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_PoliceGrey", basePrice=33, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_PrisonGuard", basePrice=33, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Ranger", basePrice=42, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Santa", basePrice=44, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_SantaGreen", basePrice=44, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Scrubs", basePrice=7, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_SheepSkin", basePrice=18, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Trousers_Shellsuit_Black", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Shellsuit_Blue", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Shellsuit_Green", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Shellsuit_Pink", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Shellsuit_Teal", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Shellsuit_TINT", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Sheriff", basePrice=20, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Sport", basePrice=10, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_Suit", basePrice=26, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_SuitTEXTURE", basePrice=27, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_SuitWhite", basePrice=29, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_SuitWhite_White", basePrice=29, tags={"Clothing.Bottom", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_WhiteTEXTURE", basePrice=31, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Trousers_WhiteTINT", basePrice=31, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.TrousersMesh_DenimLight", basePrice=36, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.TrousersMesh_Leather", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Bottom Registry Complete")
