-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Bottom] [Rarity.Rare] (117 items)
    { item="Base.Dungarees", basePrice=79, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Dungarees_HuntingCamo", basePrice=79, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Ghillie_Trousers", basePrice=79, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.LongJohns_Bottoms", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.LongJohns_Bottoms_Crafted_Burlap", basePrice=59, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.LongJohns_Bottoms_Crafted_Cotton", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_BoxingBlue", basePrice=53, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_BoxingRed", basePrice=53, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_CamoDesertNewLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_CamoGreenLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_CamoMiliusLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_CamoTigerStripeLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_CamoUrbanLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_FootballPants", basePrice=112, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_FootballPants_Black", basePrice=112, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_FootballPants_Gold", basePrice=273, tags={"Clothing.Bottom", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=8} },
    { item="Base.Shorts_FootballPants_White", basePrice=112, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_HockeyPants", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_HockeyPants_Black", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_HockeyPants_Red", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_HockeyPants_UniBlue", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_HockeyPants_White", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_LongDenim", basePrice=77, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_LongDenim_Punk", basePrice=77, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_LongSport", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_LongSport_Red", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_OliveDrabLong", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_ShortDenim", basePrice=71, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_ShortFormal", basePrice=54, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shorts_ShortSport", basePrice=53, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Crafted_Burlap", basePrice=54, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Crafted_Cotton", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Crafted_Denim", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Crafted_DenimBlack", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Crafted_DenimLight", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_DeerHide", basePrice=56, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Garbage", basePrice=54, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Hide", basePrice=56, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Knees_Tarp", basePrice=56, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Crafted_Burlap", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Crafted_Cotton", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Crafted_Denim", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Crafted_DenimBlack", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Crafted_DenimLight", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Garbage", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Hide", basePrice=59, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Long_Tarp", basePrice=59, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Mini", basePrice=52, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Normal", basePrice=53, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Normal_Garbage", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Normal_Hide", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Normal_Tarp", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Short", basePrice=51, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Short_FaunHide", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Short_Garbage", basePrice=53, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Short_Hide", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Skirt_Short_Tarp", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Socks_LegWarmers", basePrice=90, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_ArmyService", basePrice=141, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=9} },
    { item="Base.Trousers_Black", basePrice=68, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoDesert", basePrice=71, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoDesertNew", basePrice=71, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoGreen", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoMilius", basePrice=78, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoTigerStripe", basePrice=78, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_CamoUrban", basePrice=78, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Chef", basePrice=58, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_Burlap", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_Cotton", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_Denim", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_DenimBlack", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_DenimLight", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Crafted_DenimRandom", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_DeerHide", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_DefaultTEXTURE", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_DefaultTEXTURE_HUE", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_DefaultTEXTURE_TINT", basePrice=61, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Denim", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Denim_Punk", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_FaunHide", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Hide", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_HuntingCamo", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_JeanBaggy", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_JeanBaggy_Punk", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_LeatherBlack", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_LeatherCrafted", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_NavyBlue", basePrice=66, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_OliveDrab", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Padded", basePrice=90, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Padded_HuntingCamo", basePrice=90, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Police", basePrice=118, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Trousers_PoliceGrey", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Trousers_PrisonGuard", basePrice=68, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Ranger", basePrice=74, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Santa", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_SantaGreen", basePrice=75, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Scrubs", basePrice=55, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_SheepSkin", basePrice=130, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Trousers_Shellsuit_Black", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Shellsuit_Blue", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Shellsuit_Green", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Shellsuit_Pink", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Shellsuit_Teal", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Shellsuit_TINT", basePrice=62, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Sheriff", basePrice=118, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Trousers_Sport", basePrice=57, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_Suit", basePrice=63, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_SuitTEXTURE", basePrice=64, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_SuitWhite", basePrice=66, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_SuitWhite_White", basePrice=66, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_WhiteTEXTURE", basePrice=66, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Trousers_WhiteTINT", basePrice=66, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.TrousersMesh_DenimLight", basePrice=81, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.TrousersMesh_Leather", basePrice=123, tags={"Clothing.Bottom", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
})

print("[DynamicTrading] Bottom Registry Complete")
