-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Head] [Rarity.Common] (137 items)
    { item="Base.Hat_Bandana", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Bandana_Green", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTied", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTied_Green", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTiedTINT", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BandanaTINT", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_BaseballCap", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_3N", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_3N_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanEats", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanEats_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanTire", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmericanTire_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BodyChisel", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BodyChisel_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_FireDept", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_FireDept_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil02", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil02_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Fossoil_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Gas2Go", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Gas2Go_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_HuntingCamo", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_HuntingCamo_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_JaysChicken", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_JaysChicken_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KnoxDistillery", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KnoxDistillery_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KYTransit", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_KYTransit_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LBMW", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LBMW_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LSU", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_LSU_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_MassGenfac", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_MassGenfac_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_PizzaWhirled", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_PizzaWhirled_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Sheriff", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=11} },
    { item="Base.Hat_BaseballCap_Sheriff_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=11} },
    { item="Base.Hat_BaseballCap_Spiffos", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Spiffos_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SpiffosLogo", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SpiffosLogo_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SWAT", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_SWAT_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_USL", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_USL_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapBlue", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapBlue_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapGreen", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapGreen_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Red", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Red_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapKY_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapRed", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapRed_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapTINT", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCapTINT_Reverse", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Beany", basePrice=12, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Beret", basePrice=7, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_CamoGreen", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_DesertCamo", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_DesertCamoNew", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_MiliusCamo", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_OliveDrab", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BonnieHat_TigerStripeCamo", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BucketHat", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BucketHatFishing", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_ChefHat", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Cowboy", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Angus", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Black", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_CowHide", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Holstein", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Plastic", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_Simmental", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Cowboy_White", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_EarMuff_Protectors", basePrice=10, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_EarMuffs", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood_IceCream", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FastFood_Spiffo", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Fedora", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Fedora_Delmonte", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_FishermanRainHat", basePrice=17, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_GolfHat", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_GolfHatTINT", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HeadMirrorDOWN", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HeadMirrorUP", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_HideHat", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Jay", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_LeatherStripTied", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_NewspaperHat", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PartyHat_Stars", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PartyHat_TINT", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_PeakedCapYacht", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Pilgrim", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Pirate", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Raccoon", basePrice=17, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=4} },
    { item="Base.Hat_RagBandana", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_RagBandanaTied", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Ranger", basePrice=12, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SantaHat", basePrice=14, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_SantaHatGreen", basePrice=14, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Sheriff", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=3, max=18} },
    { item="Base.Hat_ShowerCap", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Spiffo", basePrice=17, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe_Black", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Stovepipe_UncleSam", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_StrawHat", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SummerFlowerHat", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SummerHat", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_SurgicalCap", basePrice=4, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Clinical"}, stockRange={min=3, max=17} },
    { item="Base.Hat_Sweatband", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_TarpHat", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_TinFoilHat", basePrice=5, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=2, max=14} },
    { item="Base.Hat_WinterHat", basePrice=22, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_WinterHat_SheepSkin", basePrice=22, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },
    { item="Base.Hat_Witch", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_Wizard", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla"}, stockRange={min=4, max=23} },
    { item="Base.Hat_WoolyHat", basePrice=20, tags={"Clothing.Head", "Rarity.Common", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=2, max=14} },

    -- [Clothing.Head] [Rarity.Rare] (34 items)
    { item="Base.Animal_BowtieGold", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=4} },
    { item="Base.Animal_BowtieGreen", basePrice=20, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Animal_BowtieRed", basePrice=20, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Hat_Antlers", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_BunnyEarsBlack", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_BunnyEarsWhite", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_DeerHeadress", basePrice=10, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_FurryEars", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_GoldStar", basePrice=9, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Hat_HeadSack_Burlap", basePrice=29, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Cotton", basePrice=27, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Garbage", basePrice=27, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Hide", basePrice=29, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_HeadSack_Tarp", basePrice=29, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hat_JokeArrow", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_JokeKnife", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.Hat_SantaHatDebug", basePrice=20, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Burlap", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Cotton", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFace_Green", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Burlap", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Cotton", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_ShemaghFull_Green", basePrice=33, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=7} },
    { item="Base.Hat_WeddingVeil", basePrice=5, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=7} },
    { item="Base.HazmatSuit", basePrice=28, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Hoodie_Hide_UP", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_UP", basePrice=20, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.HoodieUP_WhiteTINT", basePrice=20, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGarbageBag", basePrice=15, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGreen", basePrice=17, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoTarp", basePrice=17, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoYellow", basePrice=17, tags={"Clothing.Head", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },

    -- [Clothing.Head] [Rarity.Uncommon] (9 items)
    { item="Base.Hat_ArmyWWII", basePrice=82, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=2, max=14} },
    { item="Base.Hat_BaseballCap_Police", basePrice=6, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCap_Police_Reverse", basePrice=6, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCapArmy", basePrice=6, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BaseballCapArmy_Reverse", basePrice=6, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_BeretArmy", basePrice=9, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_PeakedCapArmy", basePrice=8, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=1, max=8} },
    { item="Base.Hat_Police", basePrice=5, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=2, max=15} },
    { item="Base.Hat_Police_Grey", basePrice=5, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=2, max=15} },
})

print("[DynamicTrading] Head Registry Complete")
