-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Head] [Rarity.Common] (137 items)
    { item="Base.Hat_Bandana", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_Bandana_Green", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_BandanaTied", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_BandanaTied_Green", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_BandanaTiedTINT", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_BandanaTINT", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_BaseballCap", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_3N", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_3N_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmericanEats", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmericanEats_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmericanTire", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmericanTire_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_AmeriglobeCom_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_BodyChisel", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_BodyChisel_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_BoxpopBrewery_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_FireDept", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_FireDept_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Fossoil", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Fossoil02", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Fossoil02_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Fossoil_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Gas2Go", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Gas2Go_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_HuntingCamo", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_HuntingCamo_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_JaysChicken", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_JaysChicken_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_KnoxDistillery", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_KnoxDistillery_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_KYTransit", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_KYTransit_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LBMW", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LBMW_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LouisvilleBruiser_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LSU", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_LSU_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_MassGenfac", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_MassGenfac_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_PizzaWhirled", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_PizzaWhirled_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_ScarletOakDistillery_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Sheriff", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Sheriff_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Spiffos", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Spiffos_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_SpiffosLogo", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_SpiffosLogo_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_SWAT", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_SWAT_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_USL", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_USL_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_WestMapleCountryClub_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapBlue", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapBlue_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapGreen", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapGreen_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapKY", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapKY_Red", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapKY_Red_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapKY_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapRed", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapRed_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapTINT", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapTINT_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Beany", basePrice=6, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Beret", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_CamoGreen", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_DesertCamo", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_DesertCamoNew", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_MiliusCamo", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_OliveDrab", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BonnieHat_TigerStripeCamo", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BucketHat", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BucketHatFishing", basePrice=5, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_ChefHat", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_Angus", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_Black", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_CowHide", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_Holstein", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_Plastic", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_Simmental", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Cowboy_White", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_EarMuff_Protectors", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_EarMuffs", basePrice=6, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_FastFood", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_FastFood_IceCream", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_FastFood_Spiffo", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Fedora", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Fedora_Delmonte", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_FishermanRainHat", basePrice=9, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=3, max=15} },
    { item="Base.Hat_GolfHat", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_GolfHatTINT", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_HeadMirrorDOWN", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_HeadMirrorUP", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_HideHat", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Jay", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_LeatherStripTied", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_NewspaperHat", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_PartyHat_Stars", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_PartyHat_TINT", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_PeakedCapYacht", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Pilgrim", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Pirate", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Raccoon", basePrice=3, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=1, max=5} },
    { item="Base.Hat_RagBandana", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_RagBandanaTied", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_Ranger", basePrice=10, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_SantaHat", basePrice=7, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated"}, stockRange={min=3, max=15} },
    { item="Base.Hat_SantaHatGreen", basePrice=7, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Sheriff", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_ShowerCap", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_Spiffo", basePrice=17, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Stovepipe", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Stovepipe_Black", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Stovepipe_UncleSam", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_StrawHat", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_SummerFlowerHat", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_SummerHat", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_SurgicalCap", basePrice=1, tags={"Clothing.Head", "Rarity.Common", "Origin.Clinical"}, stockRange={min=5, max=25} },
    { item="Base.Hat_Sweatband", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=5, max=25} },
    { item="Base.Hat_TarpHat", basePrice=2, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_TinFoilHat", basePrice=1, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_WinterHat", basePrice=12, tags={"Clothing.Head", "Rarity.Common", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=3, max=15} },
    { item="Base.Hat_WinterHat_SheepSkin", basePrice=12, tags={"Clothing.Head", "Rarity.Common", "Theme.Winter", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Witch", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Wizard", basePrice=3, tags={"Clothing.Head", "Rarity.Common"}, stockRange={min=3, max=15} },
    { item="Base.Hat_WoolyHat", basePrice=11, tags={"Clothing.Head", "Rarity.Common", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=3, max=15} },

    -- [Clothing.Head] [Rarity.Rare] (34 items)
    { item="Base.Animal_BowtieGold", basePrice=13, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Animal_BowtieGreen", basePrice=13, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Animal_BowtieRed", basePrice=13, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Hat_Antlers", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_BunnyEarsBlack", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_BunnyEarsWhite", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_DeerHeadress", basePrice=4, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_FurryEars", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_GoldStar", basePrice=1, tags={"Clothing.Head", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.Hat_HeadSack_Burlap", basePrice=42, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_HeadSack_Cotton", basePrice=36, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_HeadSack_Garbage", basePrice=36, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_HeadSack_Hide", basePrice=42, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_HeadSack_Tarp", basePrice=42, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_JokeArrow", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_JokeKnife", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Hat_SantaHatDebug", basePrice=13, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFace", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFace_Burlap", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFace_Cotton", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFace_Green", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFull", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFull_Burlap", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFull_Cotton", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_ShemaghFull_Green", basePrice=32, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hat_WeddingVeil", basePrice=1, tags={"Clothing.Head", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.HazmatSuit", basePrice=3, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Hoodie_Hide_UP", basePrice=16, tags={"Clothing.Head", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_UP", basePrice=30, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.HoodieUP_WhiteTINT", basePrice=30, tags={"Clothing.Head", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.PonchoGarbageBag", basePrice=2, tags={"Clothing.Head", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoGreen", basePrice=3, tags={"Clothing.Head", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoTarp", basePrice=3, tags={"Clothing.Head", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoYellow", basePrice=3, tags={"Clothing.Head", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },

    -- [Clothing.Head] [Rarity.Uncommon] (9 items)
    { item="Base.Hat_ArmyWWII", basePrice=295, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Police", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCap_Police_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapArmy", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Militia", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BaseballCapArmy_Reverse", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Militia", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_BeretArmy", basePrice=3, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Militia", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_PeakedCapArmy", basePrice=3, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Militia", "Clothing.Tactical"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Police", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
    { item="Base.Hat_Police_Grey", basePrice=1, tags={"Clothing.Head", "Rarity.Uncommon", "Origin.Police", "Clothing.Authority"}, stockRange={min=3, max=15} },
})

print("[DynamicTrading] Head Registry Complete")
