-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Outerwear] [Rarity.Rare] (100 items)
    { item="Base.Apron_BBQ", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Black", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Garbage", basePrice=598, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Hide", basePrice=611, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_IceCream", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Jay", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Leather", basePrice=1156, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PileOCrepe", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PizzaWhirled", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Spiffos", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Tarp", basePrice=600, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_White", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Apron_WhiteTEXTURE", basePrice=596, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.BlackRobe", basePrice=600, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_AngusCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_AngusHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoDesert", basePrice=2528, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoDesertNew", basePrice=2528, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoGreen", basePrice=2532, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoMilius", basePrice=2528, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoTigerStripe", basePrice=2528, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoUrban", basePrice=2532, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyOliveDrab", basePrice=2532, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Black", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Chef", basePrice=599, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_CoatArmy", basePrice=2527, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_CowHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_DeerHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Hide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HuntingCamo", basePrice=1173, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather_Punk", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBarrelDogs", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBlack", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBrown", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherIronRodent", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherWildRacoons", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_NavyBlue", basePrice=1163, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded", basePrice=629, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamo", basePrice=629, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamoDOWN", basePrice=630, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_PaddedDOWN", basePrice=630, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Police", basePrice=2265, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Ranger", basePrice=1166, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SheepSkin", basePrice=1172, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Shellsuit_Black", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Blue", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Green", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Pink", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Teal", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_TINT", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Sheriff", basePrice=2265, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_SimmentalCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SimmentalHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Varsity", basePrice=625, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_WhiteTINT", basePrice=870, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Black", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_CowHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Doctor", basePrice=680, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Theme.Clinical", "Clothing.ScratchResistant", "Clothing.Medical"}, stockRange={min=0, max=1} },
    { item="Base.JacketLong_Hide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Random", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Santa", basePrice=875, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SantaGreen", basePrice=875, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SheepSkin", basePrice=626, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalCalfHide", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalHide", basePrice=1165, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.LongCoat_Bathrobe", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.LongCoat_Hide", basePrice=619, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGarbageBagDOWN", basePrice=606, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGreenDOWN", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoTarpDOWN", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoYellowDOWN", basePrice=608, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Suit_Jacket", basePrice=613, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_Jacket_White", basePrice=613, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_JacketTINT", basePrice=613, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Foreman", basePrice=620, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_HighViz", basePrice=602, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Camo", basePrice=623, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_CamoGreen", basePrice=623, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Grey", basePrice=626, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Khaki", basePrice=626, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Orange", basePrice=624, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_BarrelDogs", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Biker", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_IronRodents", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Veteran", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_WildRaccoons", basePrice=886, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_SheepSkin", basePrice=1180, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Trucker", basePrice=626, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat", basePrice=604, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat_GigaMart", basePrice=604, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_WaistcoatTINT", basePrice=604, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.WeddingJacket", basePrice=607, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
})

print("[DynamicTrading] Outerwear Registry Complete")
