-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Outerwear] [Rarity.Rare] (100 items)
    { item="Base.Apron_BBQ", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Black", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Garbage", basePrice=7, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Hide", basePrice=65, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Apron_IceCream", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Jay", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Leather", basePrice=131, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.Apron_PileOCrepe", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_PizzaWhirled", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Spiffos", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_Tarp", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_White", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Apron_WhiteTEXTURE", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.BlackRobe", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Jacket_AngusCalfHide", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_AngusHide", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoDesert", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoDesertNew", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoGreen", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoMilius", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoTigerStripe", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoUrban", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyOliveDrab", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Black", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Chef", basePrice=1, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_CoatArmy", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_CowHide", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_DeerHide", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Hide", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinCalfHide", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinHide", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HuntingCamo", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather_Punk", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBarrelDogs", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBlack", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBrown", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherIronRodent", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherWildRacoons", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_NavyBlue", basePrice=15, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamo", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamoDOWN", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_PaddedDOWN", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Police", basePrice=12, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Ranger", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SheepSkin", basePrice=15, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Shellsuit_Black", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Blue", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Green", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Pink", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Teal", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_TINT", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Sheriff", basePrice=12, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SimmentalCalfHide", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SimmentalHide", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Varsity", basePrice=88, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Jacket_WhiteTINT", basePrice=10, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusCalfHide", basePrice=7, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusHide", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Black", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_CowHide", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Doctor", basePrice=3, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Clinical", "Clothing.ScratchResistant", "Clothing.Medical"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Hide", basePrice=7, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinCalfHide", basePrice=7, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinHide", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Random", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Santa", basePrice=5, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SantaGreen", basePrice=5, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SheepSkin", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalCalfHide", basePrice=7, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalHide", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.LongCoat_Bathrobe", basePrice=4, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.LongCoat_Hide", basePrice=10, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoGarbageBagDOWN", basePrice=2, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoGreenDOWN", basePrice=3, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoTarpDOWN", basePrice=3, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.PonchoYellowDOWN", basePrice=3, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Suit_Jacket", basePrice=4, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_Jacket_White", basePrice=4, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_JacketTINT", basePrice=4, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Foreman", basePrice=52, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_HighViz", basePrice=16, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hunting_Camo", basePrice=56, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hunting_CamoGreen", basePrice=55, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hunting_Grey", basePrice=60, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hunting_Khaki", basePrice=60, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hunting_Orange", basePrice=56, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather_BarrelDogs", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather_Biker", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather_IronRodents", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather_Veteran", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Leather_WildRaccoons", basePrice=112, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_SheepSkin", basePrice=32, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Trucker", basePrice=60, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Waistcoat", basePrice=12, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Waistcoat_GigaMart", basePrice=13, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_WaistcoatTINT", basePrice=12, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.WeddingJacket", basePrice=3, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
})

print("[DynamicTrading] Outerwear Registry Complete")
