-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Outerwear] [Rarity.Rare] (100 items)
    { item="Base.Apron_BBQ", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Black", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Garbage", basePrice=8, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Hide", basePrice=20, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_IceCream", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Jay", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Leather", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PileOCrepe", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_PizzaWhirled", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Spiffos", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_Tarp", basePrice=10, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_White", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Apron_WhiteTEXTURE", basePrice=6, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.BlackRobe", basePrice=9, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_AngusCalfHide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_AngusHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_ArmyCamoDesert", basePrice=55, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoDesertNew", basePrice=55, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoGreen", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoMilius", basePrice=55, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoTigerStripe", basePrice=55, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyCamoUrban", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_ArmyOliveDrab", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Black", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Chef", basePrice=9, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_CoatArmy", basePrice=54, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Militia", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Tactical"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_CowHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_DeerHide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Hide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinCalfHide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HolsteinHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_HuntingCamo", basePrice=52, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Leather_Punk", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBarrelDogs", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBlack", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherBrown", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherIronRodent", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_LeatherWildRacoons", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_NavyBlue", basePrice=42, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded", basePrice=38, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamo", basePrice=38, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Padded_HuntingCamoDOWN", basePrice=40, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_PaddedDOWN", basePrice=40, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Police", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_Ranger", basePrice=45, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SheepSkin", basePrice=51, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Shellsuit_Black", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Blue", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Green", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Pink", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_Teal", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Shellsuit_TINT", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=4} },
    { item="Base.Jacket_Sheriff", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Police", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.Authority"}, stockRange={min=0, max=1} },
    { item="Base.Jacket_SimmentalCalfHide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_SimmentalHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Jacket_Varsity", basePrice=35, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Jacket_WhiteTINT", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusCalfHide", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_AngusHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Black", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_CowHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Doctor", basePrice=19, tags={"Clothing.Outerwear", "Rarity.Rare", "Origin.Clinical", "Clothing.ScratchResistant", "Clothing.Medical"}, stockRange={min=0, max=1} },
    { item="Base.JacketLong_Hide", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinCalfHide", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_HolsteinHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Random", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_Santa", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SantaGreen", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SheepSkin", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalCalfHide", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.JacketLong_SimmentalHide", basePrice=44, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.LongCoat_Bathrobe", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.LongCoat_Hide", basePrice=29, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGarbageBagDOWN", basePrice=16, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoGreenDOWN", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoTarpDOWN", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.PonchoYellowDOWN", basePrice=18, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Suit_Jacket", basePrice=23, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_Jacket_White", basePrice=23, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Suit_JacketTINT", basePrice=23, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Foreman", basePrice=30, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_HighViz", basePrice=12, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Camo", basePrice=33, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_CamoGreen", basePrice=33, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Grey", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Khaki", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hunting_Orange", basePrice=33, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_BarrelDogs", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Biker", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_IronRodents", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_Veteran", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Leather_WildRaccoons", basePrice=47, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_SheepSkin", basePrice=59, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.Protective", "Clothing.BiteResistant", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=2} },
    { item="Base.Vest_Trucker", basePrice=36, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Waistcoat_GigaMart", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.Vest_WaistcoatTINT", basePrice=14, tags={"Clothing.Outerwear", "Rarity.Rare"}, stockRange={min=0, max=12} },
    { item="Base.WeddingJacket", basePrice=17, tags={"Clothing.Outerwear", "Rarity.Rare", "Clothing.ScratchResistant"}, stockRange={min=0, max=2} },
})

print("[DynamicTrading] Outerwear Registry Complete")
