-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Top] [Rarity.Rare] (146 items)
    { item="Base.Bandeau_Burlap", basePrice=10, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_Denim", basePrice=10, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_FaunHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_Garbage", basePrice=17, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_Hide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_Rag", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Bandeau_Tarp", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Football_Jersey_Black", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Football_Jersey_Blue", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Football_Jersey_White", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Ghillie_Top", basePrice=27, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_Hide_DOWN", basePrice=33, tags={"Clothing.Top", "Rarity.Rare", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_DOWN", basePrice=21, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.HoodieDOWN_WhiteTINT", basePrice=21, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Ice_Hockey_Jersey_Black", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Ice_Hockey_Jersey_BlueUni", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Ice_Hockey_Jersey_Red", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Ice_Hockey_Jersey_White", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_DiamondPatternTINT", basePrice=37, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_PoloNeck", basePrice=24, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_RoundNeck", basePrice=20, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_TankTopDiamondTINT", basePrice=29, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_TankTopTINT", basePrice=18, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Jumper_VNeck", basePrice=18, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Baseball_KY", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Baseball_Rangers", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Baseball_Z", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_Blue", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_Brown", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_Green", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_LimeGreen", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_Pink", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Bowling_White", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoDesert", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoDesertNew", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoGreen", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoMilius", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoTigerStripe", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CamoUrban", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_Burlap", basePrice=13, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_Cotton", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_Denim", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_DenimBlack", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_DenimLight", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Crafted_DenimRandom", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CropTopNoArmTINT", basePrice=6, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_CropTopTINT", basePrice=6, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Denim", basePrice=29, tags={"Clothing.Top", "Rarity.Rare", "Clothing.WindResistant"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_FormalTINT", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_FormalWhite", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_FormalWhite_ShortSleeve", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_FormalWhite_ShortSleeveTINT", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_HawaiianRed", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_HawaiianTINT", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey01", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey02", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey03", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey04", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey05", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Jockey06", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Lumberjack", basePrice=23, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Lumberjack_Green", basePrice=23, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Lumberjack_TINT", basePrice=23, tags={"Clothing.Top", "Rarity.Rare", "Clothing.Insulated"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_NoSleeves_Crafted_Burlap", basePrice=10, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_NoSleeves_Crafted_Cotton", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_NoSleeves_Crafted_Denim", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimBlack", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimLight", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_OfficerWhite", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_OliveDrab", basePrice=11, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_PoliceBlue", basePrice=12, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_PoliceGrey", basePrice=13, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Priest", basePrice=10, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_PrisonGuard", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Ranger", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Scrubs", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Sheriff", basePrice=12, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Shirt_Workman", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_ArmyGreen", basePrice=18, tags={"Clothing.Top", "Rarity.Rare", "Origin.Militia", "Clothing.Tactical"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_BluesCountry", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_BusinessSpiffo", basePrice=10, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoDesert", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoDesertNew", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoGreen", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoMilius", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoTigerStripe", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_CamoUrban", basePrice=13, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_DefaultDECAL", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_DefaultDECAL_TINT", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_DefaultTEXTURE", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_DefaultTEXTURE_TINT", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_EMD", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Fossoil", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Gas2Go", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_HipHop", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_HuntingCamo", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Indie", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_IndieStoneDECAL", basePrice=13, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_LongSleeve_HuntingCamo", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_LongSleeve_SuperColor", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_McCoys", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Metal", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_OliveDrab", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PileOCrepe", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PizzaWhirled", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PoliceBlue", basePrice=11, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PoliceGrey", basePrice=12, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PoloStripedTINT", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_PoloTINT", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_FiremanBlue", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_FiremanRed", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_FiremanRed02", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_FiremanWhite", basePrice=16, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_PoliceBlue", basePrice=11, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_PoliceWhite", basePrice=11, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_RangerBrown", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_RangerGreen", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_VeterenGreen", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Profession_VeterenRed", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Punk", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Ranger", basePrice=14, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Rock", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Rock2", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Scrubs", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Sheriff", basePrice=11, tags={"Clothing.Top", "Rarity.Rare", "Origin.Police", "Clothing.Authority"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_SpiffoDECAL", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Sport", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_SportDECAL", basePrice=8, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_SuperColor", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_ThunderGas", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_TieDye", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_Tuxedo", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_ValleyStation", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_WhiteLongSleeve", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_WhiteLongSleeveTINT", basePrice=12, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Tshirt_WhiteTINT", basePrice=9, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_AngusHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_DeerHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_DefaultTEXTURE", basePrice=15, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_DefaultTEXTURE_TINT", basePrice=15, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_FawnHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Garbage", basePrice=17, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Hide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_HolsteinHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_SimmentalHide", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
    { item="Base.Vest_Tarp", basePrice=19, tags={"Clothing.Top", "Rarity.Rare"}, stockRange={min=0, max=6} },
})

print("[DynamicTrading] Top Registry Complete")
