-- ============================================================================
-- Clothing Items Registry for Dynamic Trading
-- If you want some suggestions or have balancing issues, please report them to
-- my discussion page. Happy to adjust prices and stock based on your feedback! :)
-- https://steamcommunity.com/sharedfiles/filedetails/?id=3635333613
-- ============================================================================

require "DT/Common/Config"
if not DynamicTrading then return end

DynamicTrading.RegisterBatch({
    -- The items are grouped by Primary tag and Rarity

    -- [Clothing.Top] [Rarity.Rare] (146 items)
    { item="Base.Bandeau_Burlap", basePrice=600, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Denim", basePrice=600, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_FaunHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Garbage", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Hide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Rag", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Bandeau_Tarp", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_Black", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_Blue", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Football_Jersey_White", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ghillie_Top", basePrice=867, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Protective", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_Hide_DOWN", basePrice=623, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.ScratchResistant", "Clothing.Insulated"}, stockRange={min=0, max=2} },
    { item="Base.Hoodie_HuntingCamo_DOWN", basePrice=612, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.HoodieDOWN_WhiteTINT", basePrice=612, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_Black", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_BlueUni", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_Red", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Ice_Hockey_Jersey_White", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_DiamondPatternTINT", basePrice=2837, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=8} },
    { item="Base.Jumper_PoloNeck", basePrice=614, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_RoundNeck", basePrice=610, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_TankTopDiamondTINT", basePrice=2829, tags={"Clothing.Top", "Rarity.Rare", "Quality.Luxury", "Origin.Vanilla"}, stockRange={min=0, max=8} },
    { item="Base.Jumper_TankTopTINT", basePrice=608, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Jumper_VNeck", basePrice=608, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_KY", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_Rangers", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Baseball_Z", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Blue", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Brown", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Green", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_LimeGreen", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_Pink", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Bowling_White", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoDesert", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoDesertNew", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoGreen", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoMilius", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoTigerStripe", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CamoUrban", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Burlap", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Cotton", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_Denim", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimBlack", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimLight", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Crafted_DenimRandom", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CropTopNoArmTINT", basePrice=596, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_CropTopTINT", basePrice=596, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Denim", basePrice=619, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.WindResistant"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalTINT", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite_ShortSleeve", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_FormalWhite_ShortSleeveTINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_HawaiianRed", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_HawaiianTINT", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey01", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey02", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey03", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey04", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey05", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Jockey06", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack", basePrice=613, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack_Green", basePrice=613, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Lumberjack_TINT", basePrice=613, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Clothing.Insulated"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Burlap", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Cotton", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_Denim", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimBlack", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_NoSleeves_Crafted_DenimLight", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_OfficerWhite", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_OliveDrab", basePrice=601, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_PoliceBlue", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_PoliceGrey", basePrice=1660, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_Priest", basePrice=600, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_PrisonGuard", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Ranger", basePrice=606, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Scrubs", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Shirt_Sheriff", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Shirt_Workman", basePrice=606, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ArmyGreen", basePrice=1880, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Militia", "Clothing.Tactical"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_BluesCountry", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_BusinessSpiffo", basePrice=600, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoDesert", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoDesertNew", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoGreen", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoMilius", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoTigerStripe", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_CamoUrban", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultDECAL", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultDECAL_TINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultTEXTURE", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_DefaultTEXTURE_TINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_EMD", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Fossoil", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Gas2Go", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_HipHop", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_HuntingCamo", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Indie", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_IndieStoneDECAL", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_LongSleeve_HuntingCamo", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_LongSleeve_SuperColor", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_McCoys", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Metal", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_OliveDrab", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PileOCrepe", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PizzaWhirled", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PoliceBlue", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_PoliceGrey", basePrice=1660, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_PoloStripedTINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_PoloTINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanBlue", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanRed", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanRed02", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_FiremanWhite", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_PoliceBlue", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_Profession_PoliceWhite", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_Profession_RangerBrown", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_RangerGreen", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_VeterenGreen", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Profession_VeterenRed", basePrice=603, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Punk", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Ranger", basePrice=604, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Rock", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Rock2", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Scrubs", basePrice=598, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Sheriff", basePrice=1659, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla", "Theme.Police", "Clothing.Authority"}, stockRange={min=0, max=9} },
    { item="Base.Tshirt_SpiffoDECAL", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Sport", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_SportDECAL", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_SuperColor", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ThunderGas", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_TieDye", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_Tuxedo", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_ValleyStation", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteLongSleeve", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteLongSleeveTINT", basePrice=602, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Tshirt_WhiteTINT", basePrice=599, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_AngusHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DeerHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DefaultTEXTURE", basePrice=605, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_DefaultTEXTURE_TINT", basePrice=605, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_FawnHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Garbage", basePrice=607, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Hide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_HolsteinHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_SimmentalHide", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
    { item="Base.Vest_Tarp", basePrice=609, tags={"Clothing.Top", "Rarity.Rare", "Origin.Vanilla"}, stockRange={min=0, max=12} },
})

print("[DynamicTrading] Top Registry Complete")
