if isClient() and not isServer() then return end

require "DT/V2/Faction/TradingSys/DynamicTrading_Factions"
require "DT/V2/Faction/TradingSys/DynamicTrading_Roster"
require "DT/V2/Config"
require "DT/Common/Trading/DT_Economy_Common"

DynamicTrading = DynamicTrading or {}
DynamicTrading.Economy = DynamicTrading.Economy or {}
DynamicTrading.Economy.V2 = {}

local Common = DynamicTrading.Economy.Common

-- =============================================================================
-- 1. V2 STOCK GENERATOR (Wrapper)
-- =============================================================================
function DynamicTrading.Economy.V2.GenerateStock(traderUUID)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    if not soul then return {} end
    
    local faction = DynamicTrading_Factions.GetFaction(soul.factionID)
    local archetype = DynamicTrading.Archetypes[soul.archetypeID] or DynamicTrading.Archetypes["General"]
    
    local masterList = DynamicTrading.Config.MasterList
    if not masterList then return {} end

    -- Difficulty (V2 might need its own or use Common)
    local diff = DynamicTrading.Config.GetDifficultyData()

    -- Modifiers (V2 specific)
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        globalStockMult = 1.0
    }
    
    -- Future: Add V2 specific modifiers here (e.g., Faction Stockpile level)

    -- Delegate to Common
    local rawStock = Common.GenerateStock(archetype, masterList, diff, modifiers)

    -- Adapt to V2 Format { [item] = {qty=..., basePrice=..., dynamicMod=..., customData=...} }
    local finalItems = {}
    for itemKey, entry in pairs(rawStock) do
        local itemData = masterList[itemKey]
        if itemData then
            finalItems[itemKey] = {
                qty = entry.qty,
                basePrice = itemData.basePrice,
                dynamicMod = 1.0, -- Placeholder for dynamic pricing variations
                customData = entry.customData -- Already generated by Common!
            }
        end
    end
    
    return finalItems
end

-- =============================================================================
-- 2. V2 PRICING LOGIC (Wrapper)
-- =============================================================================

function DynamicTrading.Economy.V2.GetBuyPrice(traderUUID, itemFullType)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 99999 end
    
    -- Fetch customData from stock if available
    local customData = nil
    if soul.stocks and soul.stocks[itemFullType] then
        customData = soul.stocks[itemFullType].customData
    end

    local diff = DynamicTrading.Config.GetDifficultyData()
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
        customData = customData
    }
    
    local price = Common.GetBuyPrice(itemFullType, itemData, diff, modifiers)
    
    return price
end

function DynamicTrading.Economy.V2.GetSellPrice(traderUUID, itemObj, itemFullType)
    local soul = DynamicTrading_Roster.GetSoulRegistry(traderUUID)
    local itemData = DynamicTrading.Config.MasterList[itemFullType]
    if not itemData or not soul then return 0 end
    
    local diff = DynamicTrading.Config.GetDifficultyData()
    local archetype = DynamicTrading.Archetypes[soul.archetypeID]
    local modifiers = {
        tagsConfig = DynamicTrading.Config.Tags,
    }
    
    local price = Common.GetSellPrice(itemFullType, itemData, itemObj, diff, archetype, modifiers)
    
    return price
end
